{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.18-rc.116/flow-wrapper-kmp-0.5.18-rc.116.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.18-rc.116",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.18-rc.116.aar",
          "size": 212299,
          "sha512": "8c84b752ec79cabcd720340564c60ad2ec31b9c36a4c847d00ac52d9fdf4c5b164b95955d7bcf140af683f65895764cb75a7ee2ae59cabc947773a8d60526a18",
          "sha256": "9392ed4cdeb9a13527f8b32509156690b83653f614825131f19fc5786fca9195",
          "sha1": "b17f8a10bf7d26944904d03c49d8f3af98f7bb09",
          "md5": "7d2f62ed7d16e25c2c7d8bff63d2454e"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.18-rc.116"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.18-rc.116"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.18-rc.116.aar",
          "size": 212299,
          "sha512": "8c84b752ec79cabcd720340564c60ad2ec31b9c36a4c847d00ac52d9fdf4c5b164b95955d7bcf140af683f65895764cb75a7ee2ae59cabc947773a8d60526a18",
          "sha256": "9392ed4cdeb9a13527f8b32509156690b83653f614825131f19fc5786fca9195",
          "sha1": "b17f8a10bf7d26944904d03c49d8f3af98f7bb09",
          "md5": "7d2f62ed7d16e25c2c7d8bff63d2454e"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-android-0.5.18-rc.116-sources.jar",
          "url": "flow-wrapper-kmp-android-0.5.18-rc.116-sources.jar",
          "size": 41956,
          "sha512": "e84ae8b8eb5dfd7a0979749f46994a25548f46923b3ae195f0e6dc70268b176d90f174a79e077598b26d6580ca37f3bde043c80f1b07b309996debf715e45b9f",
          "sha256": "6c75b01dc67785ae2a60a3f273504c80bd10bf7475ef641dc72eb5934af0bd78",
          "sha1": "3c42ce263bd3d573e75dc7cc1e742204bd853575",
          "md5": "f3ab734036f8501004a69df06a06cc37"
        }
      ]
    }
  ]
}
