{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.20-SNAPSHOT.4/flow-wrapper-kmp-0.5.20-SNAPSHOT.4.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.20-SNAPSHOT.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.4"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.20-SNAPSHOT.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosX64Main-0.5.20-SNAPSHOT.4.klib",
          "url": "flow-wrapper-kmp-iosx64-0.5.20-SNAPSHOT.4.klib",
          "size": 245495,
          "sha512": "0d424a875d04fcbd13081a0ffa02db749509113fd925fd3dfb382e5d3105a4d818a8ecfeffc908c7d534a9e6d8bfa30730b34cc020ad046225ac1a56ff9766b9",
          "sha256": "5761b379ec02c2581da565114acfeeffb848fef57842c05bd024179042c8e35f",
          "sha1": "442cf254eaa622c9bafa5864443436e988416152",
          "md5": "26d1d1a448e50368ea9e49e101a73fa8"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.20-SNAPSHOT.4-sources.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.20-SNAPSHOT.4-sources.jar",
          "size": 42618,
          "sha512": "845be6750fbd29d26a19ea5968c1c810480143fe5ee6a8c2f501027ddec4022343fee7f80c8df622d237fbdd64fdcda92de0051938bf75963e83980d8d52f3b5",
          "sha256": "b87626435f4ee9c85093ae74c3909e716094c1d5f6985fcee48cd44fc028b520",
          "sha1": "30c1009481ba1c4c81a73e8be7f7da2917e77324",
          "md5": "32210d1d224fe2734b8321591aeccf44"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.4"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.20-SNAPSHOT.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.20-SNAPSHOT.4.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosx64-0.5.20-SNAPSHOT.4-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "2af3e7ff7328055d87bdbd9e1201790f2e7de98a4c27c17fe1e5cf6099293ae9ed1dec97ca66aff113ade18e2c7abf97422d7f84b4667cc200175eb8480d86e2",
          "sha256": "0705bf8d3a003bb654129012e92949b93f078bc353237637f0fdece63c16401e",
          "sha1": "71e4935ffe8907f8af43d4f5952a18e37cde4de4",
          "md5": "7364963d1f19ba68548d226a1aba5e3a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.4"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.20-SNAPSHOT.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.20-SNAPSHOT.4-metadata.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.20-SNAPSHOT.4-metadata.jar",
          "size": 3747,
          "sha512": "891115e1362e6e1093c57f55331bacf1a466c882ebb4d8cf8dec95f4ff938319fc4b85e596ed836f6442751fd2712fa3912af32b747066ff10c4a37ae7a154a8",
          "sha256": "0af7e9a29aadbc44aa29d6d876489147fd66038c9f40c2a76b2f45d125a3668d",
          "sha1": "4ada954711b83947b6c4fc813430d2fcfcb3b75c",
          "md5": "6f742ff20d5a2902585dcbab829ba9db"
        }
      ]
    }
  ]
}
