{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.6.0-SNAPSHOT.22/composeblocks-0.6.0-SNAPSHOT.22.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.6.0-SNAPSHOT.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.22"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.22"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosSimulatorArm64Main-0.6.0-SNAPSHOT.22.klib",
          "url": "composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.22.klib",
          "size": 226436,
          "sha512": "7f4517aa160d4bd213ca25e5647b2f144d5a5b2ce80755a4224ace35ee56773108ac07c6d095147e5b8b03d9fdbe817a709cd0bc0d2dd7d4bd0fb14a8f78ca1d",
          "sha256": "bdaa8a9ce1ae79cc5a64dcb80a3e624dd990d56cb7a2bff5454ef4701fc32373",
          "sha1": "7a39a5ebd646b3f016bf64273ac297f72424ee3d",
          "md5": "00e6dbf06a484680eb388637f376e5ea"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.22-sources.jar",
          "url": "composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.22-sources.jar",
          "size": 36238,
          "sha512": "fdddd7a07414879297ac73d4d1f42aa786402b0bfcd45c52996d4203149d15768a5ddf17af1b7c6ebb0a1d781c9a2c0bd0f7ec8e03c834e82e44356c2493fdaa",
          "sha256": "fb1002d7086daf0f4dbbb3e08759878d68f00339df9c92c94c9dd1aa30f952de",
          "sha1": "f922fb0632d02d535bc99eabbdaa2b1ebd0adce0",
          "md5": "c2b07c9ab6101b593271548f70e3d0f0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.22"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.22"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.6.0-SNAPSHOT.22.kotlin_resources.zip",
          "url": "composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.22-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "0f7be11b16b60a762ca8483e5565a4d5a22926928d86e1296549464041d851a694f4ce63fe120e89d52a989561c8d0612fcd6566c5f73ef585f86a424a08be10",
          "sha256": "3ce2e2aa5b7dae90b1833251bef0c41b1d0346b91d8b56db1f7672534db056d6",
          "sha1": "77425f7a714d7d6fff59642e67532d41f04208c7",
          "md5": "b77565a5efa00b8631ac4bf739d4dfd8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.22"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.22"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.22-metadata.jar",
          "url": "composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.22-metadata.jar",
          "size": 261,
          "sha512": "6e182063ee2858952ef8fe7ac71ad8b094c5afb227d22a9640b1ee86d127848ac22fbdf9e1f256c5dc28fcea6e8acf2264cb5ca368c18db6eda69654a6203b94",
          "sha256": "c17aeea5dd12c1d3998ef10dcf40495ff538978d374804b95da07347871397ce",
          "sha1": "3c5a9e05e5a06f6ca8e3d7e4efd463d87e02f97c",
          "md5": "d9f049489e7c229c63c021f06062e482"
        }
      ]
    }
  ]
}
