{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.15-SNAPSHOT/flow-wrapper-kmp-0.5.15-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.15-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.15-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosSimulatorArm64Main-0.5.15-SNAPSHOT.klib",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.15-SNAPSHOT.klib",
          "size": 211781,
          "sha512": "a5355154c9279deabb437fde22bb5586ea92c2463cd6a648594279941400e152e9d96769d278c24da8b90da165e881ec29fe8a4f6e160636629954896e4625c0",
          "sha256": "87dd32c9a7757d71efe90bf3ba5c08bd8589690b44ccf8f2fc3a5d3408ba3136",
          "sha1": "539479e81a5b92229f5e6d4f5f5e2991b3a66ec9",
          "md5": "85e9394ec58ee88731d2a3a1502cc992"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iossimulatorarm64-0.5.15-SNAPSHOT-sources.jar",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.15-SNAPSHOT-sources.jar",
          "size": 36690,
          "sha512": "7115a780eea57f9d0d67f974907d4278ce0063b7542a68fc8f8e4d4bbc6bf55ff0ba48dfeb02ddd4f8f6efa4dd5a98c435989ff79e629bbc61e3d4b58408dd78",
          "sha256": "9410461b2f8aabdf62d8fcfae47f9ea6ceb826c8b3336046f6cd457f53428929",
          "sha1": "e86b031de379e064d66e936225504c2c2378ed56",
          "md5": "4a9a9a548db88db4b949198a9e25817e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.15-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.15-SNAPSHOT.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.15-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "1a97a2a99c0763e34c55a644ef0745f717bdfbaf40f607d8279d54153132bfb8344309efff19150c7148c25d272b70007e08ac4fa5a0c317a0f2610c7d0bdab9",
          "sha256": "79e97d72949501cc886bf1506b9f58f5bbceb5a69bf70d8506b49c277ddd7490",
          "sha1": "2923701a8894ce8e2a21cc77a2bf0085a07283ef",
          "md5": "95c5d3a62fd0f07c997fe65f6e475fb9"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.15-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iossimulatorarm64-0.5.15-SNAPSHOT-metadata.jar",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.15-SNAPSHOT-metadata.jar",
          "size": 3747,
          "sha512": "348041b8752d62a805884a94d3843f49c1ad6f3e7c679b8c0b71637b0df52836dc6959c54a205776aaff6dfe8a780b9a1c64d6312b4d33ef751e808eb3e474a4",
          "sha256": "0cf705c551b771c1ca97401361ab961f7efba4b560455261fc4321835c10a05e",
          "sha1": "c3dabf2fc6e389f9026b9bb7af5b660e45d05f69",
          "md5": "8c2d720eb3f405266418f11500b98fa6"
        }
      ]
    }
  ]
}
