{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.8.1-SNAPSHOT.1/runtime-0.8.1-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.8.1-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.aar",
          "url": "runtime-android-0.8.1-SNAPSHOT.1.aar",
          "size": 694312,
          "sha512": "12796981b6d21611f01a407c3dd4a28590fce54d85c073d9c2226148e973606bee598b7b9de0fe34129d1ddcafa0cc8c089a149efecc20d14bbb3250ab003e0e",
          "sha256": "61a2d1f76323fc765a6d4a2a2700396b203a2241126ed7d60d4409cdafd8b09a",
          "sha1": "87a1f3b449afd4a41b624a680b6f30f962dc27ee",
          "md5": "6e8a2a43890a682163963808656b74fe"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.aar",
          "url": "runtime-android-0.8.1-SNAPSHOT.1.aar",
          "size": 694312,
          "sha512": "12796981b6d21611f01a407c3dd4a28590fce54d85c073d9c2226148e973606bee598b7b9de0fe34129d1ddcafa0cc8c089a149efecc20d14bbb3250ab003e0e",
          "sha256": "61a2d1f76323fc765a6d4a2a2700396b203a2241126ed7d60d4409cdafd8b09a",
          "sha1": "87a1f3b449afd4a41b624a680b6f30f962dc27ee",
          "md5": "6e8a2a43890a682163963808656b74fe"
        }
      ]
    }
  ]
}
