{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.6.1-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-metadata-0.6.1-SNAPSHOT.2.jar",
          "url": "runtime-0.6.1-SNAPSHOT.2.jar",
          "size": 49769,
          "sha512": "a9e24ada0ce2fbac814807a128834c164ba3e2ea1c55b2f0a790948391c3bd6149386513273979a03fa5dbf8a6861dceecaf6e98029ff8df75b9221ef0c62d45",
          "sha256": "0a1c3814454915d7819125a0b985f3be00133b8dc3392d4940f3f80539931679",
          "sha1": "f70ebb357ba6490efefe57dd58b98a83f8258f4b",
          "md5": "6d8848a6b88750aa15f2fc6491eb5182"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-kotlin-0.6.1-SNAPSHOT.2-sources.jar",
          "url": "runtime-0.6.1-SNAPSHOT.2-sources.jar",
          "size": 56234,
          "sha512": "1c065967947a46c13533f9d4141bdfb51c151777bba0bda7ff5ad9677bcca8fca11a8eec2ddc24d76847797f47b624e8db40e5e8406fb0aeb708b9cdf933d7ae",
          "sha256": "7ed7954d9a0ed8d267409c104fa758bae7f75763d6f03cc192b4f8ed9214c7ca",
          "sha1": "8ea0804344ee1abe4d5969c6ab839ccfbac6e14f",
          "md5": "41ad4e495cd61b9d40bd649c825d56bf"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-android/0.6.1-SNAPSHOT.2/runtime-android-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-android",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-android/0.6.1-SNAPSHOT.2/runtime-android-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-android",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-android/0.6.1-SNAPSHOT.2/runtime-android-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-android",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.6.1-SNAPSHOT.2/runtime-iosarm64-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-iosarm64",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.6.1-SNAPSHOT.2/runtime-iosarm64-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-iosarm64",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.6.1-SNAPSHOT.2/runtime-iosarm64-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-iosarm64",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.6.1-SNAPSHOT.2/runtime-iossimulatorarm64-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-iossimulatorarm64",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.6.1-SNAPSHOT.2/runtime-iossimulatorarm64-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-iossimulatorarm64",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.6.1-SNAPSHOT.2/runtime-iossimulatorarm64-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-iossimulatorarm64",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosx64/0.6.1-SNAPSHOT.2/runtime-iosx64-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-iosx64",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosx64/0.6.1-SNAPSHOT.2/runtime-iosx64-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-iosx64",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosx64/0.6.1-SNAPSHOT.2/runtime-iosx64-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-iosx64",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.6.1-SNAPSHOT.2/runtime-jvm-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-jvm",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.6.1-SNAPSHOT.2/runtime-jvm-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-jvm",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.6.1-SNAPSHOT.2/runtime-jvm-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-jvm",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-linuxx64/0.6.1-SNAPSHOT.2/runtime-linuxx64-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-linuxx64",
        "version": "0.6.1-SNAPSHOT.2"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-linuxx64/0.6.1-SNAPSHOT.2/runtime-linuxx64-0.6.1-SNAPSHOT.2.module",
        "group": "br.com.wave",
        "module": "runtime-linuxx64",
        "version": "0.6.1-SNAPSHOT.2"
      }
    }
  ]
}
