{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.6.1-SNAPSHOT.2/flow-wrapper-kmp-0.6.1-SNAPSHOT.2.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.6.1-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.6.1-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosSimulatorArm64Main-0.6.1-SNAPSHOT.2.klib",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.6.1-SNAPSHOT.2.klib",
          "size": 281631,
          "sha512": "adf4f1a48af07f714f89783873801b6c6918469951a6d554bb26eba9bfd9e885387cc31ea17a4df5d031d2cbcc4fe8758cfcfeaae8e34d7f28a87323d4d6f5bb",
          "sha256": "1f44e32f3c39c6fe6da5698cbb8df26eebb429207fb7c5621de995c45a4bcbf3",
          "sha1": "b7831301d8305c21e2ba06137e0232d0e86c9221",
          "md5": "6f9cfd66cd00f5c07c4b677b635f3757"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iossimulatorarm64-0.6.1-SNAPSHOT.2-sources.jar",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.6.1-SNAPSHOT.2-sources.jar",
          "size": 59318,
          "sha512": "99cbe00a4ec75ef99413eff6e2bb16590c94c330948ec3afd3fd5394e8943c230e337117b832901896a1b0110057a69d118e6b3a4b76390e97df88fbf93e8727",
          "sha256": "005e7c312f21105c6bae9b029ad48e6973f04a9b016ea32af7ba36358713b782",
          "sha1": "ea8f7c78d801eaea4623158369b4d5372311c34f",
          "md5": "ae611ad3974ec40445e0ab513047314a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.6.1-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.6.1-SNAPSHOT.2.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.6.1-SNAPSHOT.2-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "16ca3ac0684731bbcfeb05c0f60abcba6bb8089d60c4681d91333c7b55eef65e7550b7f1a081e78af3da5565745415e54c2790de821dbf8d7e01842150207c8b",
          "sha256": "090cefd4042a431f7de5112df792b8399932d9c6637bd8359907801517210671",
          "sha1": "0aedb98d46db21620fde5d3207e17d63c59b9ad2",
          "md5": "80f8f5fcf8f0eec78397631c0e2f6b97"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.6.1-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iossimulatorarm64-0.6.1-SNAPSHOT.2-metadata.jar",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.6.1-SNAPSHOT.2-metadata.jar",
          "size": 3852,
          "sha512": "6ba123f555a3b79f8d8ae6d76514a252ad69e43e93e5a046ef8b52bcb53d9a9075b5bf2829d6e345bd10da98498e85bdff5d22d401f52e48a6f7a524410d9ba6",
          "sha256": "aac320332d050ffb929956a8ca3a67cc7303b399e148365f684922913fe60578",
          "sha1": "1aa372c1f567240dc7a1181b5e3f12b7a1c31c2a",
          "md5": "928660aa214d359d38772450b1ec465e"
        }
      ]
    }
  ]
}
