{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.6.0-SNAPSHOT.14/composeblocks-0.6.0-SNAPSHOT.14.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.6.0-SNAPSHOT.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.14"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.14"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.6.0-SNAPSHOT.14.klib",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.14.klib",
          "size": 231011,
          "sha512": "d103c511769945ae6a1de877ed81c8b54ac795b03c2d6b5edda8693bf955c399ee8c46cbc7c14de9f2c5fe738ec98f9dbb86540fb794c8427a9f0c1632d01faa",
          "sha256": "524952c194e7b1ee571028cb8adca3fcd5f301445ac3292899a9507fa4c1696d",
          "sha1": "a8a4fa456fcb3005bdd45f1f81910b17a4e05aae",
          "md5": "bd48ca68f798b796d92707fca6476317"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosx64-0.6.0-SNAPSHOT.14-sources.jar",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.14-sources.jar",
          "size": 36532,
          "sha512": "d678317680711090148338b172ef4093173e89d54aa18ec2588a254af7edc687d7137dc4ea753a4c46568b04a364a8975bdfe439313bbeaabf1b893530ade59f",
          "sha256": "cc96acb7d639737935b2f1309fec489fca83fdf6c0d5cb0d7bf0a29090f8c99c",
          "sha1": "90f356abf60297ed29a8b795793db277d8951938",
          "md5": "4343ae271f05ecded0475fbd032c1973"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.14"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.14"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.6.0-SNAPSHOT.14.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.14-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "14cfd93b584d83620a09b2da47b31c8965f7dde0e5796bae14d3578bcdbd4566fd7678848b0396241ae8db8a1d6e2b832ed4d62a0388eac0f9d4262b188e0ada",
          "sha256": "cb0c2d256842f3e9edef1a1a727a52a1455bfa329d737d07a583c482038c2650",
          "sha1": "d3b31d3b9bc037612e61e2f588598e72df83c34f",
          "md5": "40220afd03c2292ee2ab8c2e5f72d55d"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.14"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.14"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.6.0-SNAPSHOT.14-metadata.jar",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.14-metadata.jar",
          "size": 261,
          "sha512": "0b11afaa14542d93e6400ecd55a40a69ca9d0731a0276cb54283006ae1d6221b5da96e43dd41943408d60028d3d8dd06c30d4c6802b639ba531ef14b63840f59",
          "sha256": "879578b6961bfb2adb93f1c4fd203379780ca10b78141b99e5235bf3c747525f",
          "sha1": "a41dc6b23b5cb6364920bd1f3e2eb226a236a69b",
          "md5": "08b54c7fd4798da64c001733c226440e"
        }
      ]
    }
  ]
}
