{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.16-rc.94/composeblocks-0.5.16-rc.94.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.16-rc.94",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks.aar",
          "url": "composeblocks-android-0.5.16-rc.94.aar",
          "size": 194402,
          "sha512": "b73602ff9bce00a05ed6e20122e5541bfd39bd40767189084a28f20740c9ddc9c0bc9deb49a7c2b1587f22e6aad36561f7aff68faf178931dd1760c3ba3654c2",
          "sha256": "0d269e4e55e7b3d206fcf998566cf9b217374051ddd1b7c0bfbe25a9c2ac4aca",
          "sha1": "ef91f6dbe074b3426da46e94bc80599c7082e45f",
          "md5": "845485c8596676520b758a712d906bdd"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16-rc.94"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.16-rc.94"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks.aar",
          "url": "composeblocks-android-0.5.16-rc.94.aar",
          "size": 194402,
          "sha512": "b73602ff9bce00a05ed6e20122e5541bfd39bd40767189084a28f20740c9ddc9c0bc9deb49a7c2b1587f22e6aad36561f7aff68faf178931dd1760c3ba3654c2",
          "sha256": "0d269e4e55e7b3d206fcf998566cf9b217374051ddd1b7c0bfbe25a9c2ac4aca",
          "sha1": "ef91f6dbe074b3426da46e94bc80599c7082e45f",
          "md5": "845485c8596676520b758a712d906bdd"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "composeblocks-android-0.5.16-rc.94-sources.jar",
          "url": "composeblocks-android-0.5.16-rc.94-sources.jar",
          "size": 59511,
          "sha512": "9b215b4340d859f9bc19bcf8130f1ac340b58131f7c69825b2e0ac4afeb42e631a4a7f37b2b3c0a72a5b01c6366385395df28c5b7fc3e628eb8214a2e63e021f",
          "sha256": "5766c9ff09d578df821c1208f6bcf99afcfb80442ad1fb07333e14f240719a0c",
          "sha1": "de739a9fd5fe49eded6be087c00f311a5d69622f",
          "md5": "31b882d9765633f46be7c5c7d77e8031"
        }
      ]
    }
  ]
}
