{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.3/flow-wrapper-kmp-0.5.3.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosSimulatorArm64Main-0.5.3.klib",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.3.klib",
          "size": 78895,
          "sha512": "04351b613aa1957506f1200eb4dee771659687481bb80260bb15ace8c4960367d4445850e0ece8ff6e7a3cec577f7b0c8a20c850845f0bde32b4c33e6b0d92e1",
          "sha256": "eabb15d0f753bca792acaaafb049da5634f51932aa1b4b1f176f206096171768",
          "sha1": "580b92fe2991f7345ae92b151e821376b69b9621",
          "md5": "a8a46c3b7339de1fc4a6cee66290cf19"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iossimulatorarm64-0.5.3-sources.jar",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.3-sources.jar",
          "size": 13504,
          "sha512": "b2cab1965d11b2275b9cf0b562c1552fdbef45fe747ce960f48de0515ee8108dfb75e23e461a6dbf0e296930b815c8975047193aa1361481c0fed69f47db99cb",
          "sha256": "816b206d0126a1fe2e16e44c8caa01188afd390de142138f9edda5ec5a1405c6",
          "sha1": "bf9f8a53779acfe4cbcbdc24e4479117f583a006",
          "md5": "4a6bf2eebb2bc3fdc826e5eaa0ed6e3f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.3.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.3-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "c98549722de635dfb45ca7de41276b0191e587539ac0aa8e6b48aa57235d24ab6680e67c128e22d1b5926cf6b6d23789bf97907e4125834a2dc7a5d398916806",
          "sha256": "3dd48c8f22aeefa8354e382c14086dd3e78a4e3206ce606c483fabf24d04416b",
          "sha1": "727acbe12853e5e9b91179ececb3c6053991a30c",
          "md5": "eafd6cbbf5652b815b2ac9dce20aa4c4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iossimulatorarm64-0.5.3-metadata.jar",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.3-metadata.jar",
          "size": 3010,
          "sha512": "554ae7447c1d4298bf1d870011a4f5b05c456f79b12a24ba9f6d159a377f1c91794b8d86d3cd1c16e0ff51edff85132351fa6406c04540c06364c2efba2ef3f7",
          "sha256": "e0c5e56e73407d38f47d8bdbf72d8eb49d1f20e2384cf248a7820758285e4498",
          "sha1": "ece4aa7bdfb2ed1df8832285a612ef01ebcb3a93",
          "md5": "2c57115b09f378bf96dddb7c392bc661"
        }
      ]
    }
  ]
}
