{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.7.2-SNAPSHOT.1/runtime-0.7.2-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.7.2-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosSimulatorArm64Main-0.7.2-SNAPSHOT.1.klib",
          "url": "runtime-iossimulatorarm64-0.7.2-SNAPSHOT.1.klib",
          "size": 858731,
          "sha512": "8fc2a6b0bb5c02dea8668fb354f7c9a98799c9279b64eb1be9cb72af7eb887607827d1bb9ec37df00580b010eb708a446befb100952e048eba19fbcd5a911ae8",
          "sha256": "8d4bde55f8fae58ec4a538695e9ebed81ae59d3bc04d780fdf7910d9e926bc3a",
          "sha1": "efe3d6b8714eed6b77fdbb95d06c749f45b84102",
          "md5": "6325d5c8d2821d19072a4ce38a25def0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.7.2-SNAPSHOT.1-metadata.jar",
          "url": "runtime-iossimulatorarm64-0.7.2-SNAPSHOT.1-metadata.jar",
          "size": 2428,
          "sha512": "a877d4124ba526677f6e72721d8a8571d25ff5358faea2f98ce15633455201a7e5ec04b4e087546dee4b859c11d4f0f0a7b6a17b39d43239fc266e47d4ce3ee0",
          "sha256": "98a0f0ccc984034437003853c163d1199f8ab91e53c6bba99e30068595cb8515",
          "sha1": "330b2b6db6b41ac6ba103a25edb0051afb32267c",
          "md5": "51ad6a5e166ba703a09105ee53a49edd"
        }
      ]
    }
  ]
}
