{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.5.19-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-metadata-0.5.19-SNAPSHOT.jar",
          "url": "runtime-0.5.19-SNAPSHOT.jar",
          "size": 47037,
          "sha512": "0bb18809b95567b98f018271b2d23d3f51959fdffaea14850c7bccc04b254c82c7b2ae9777b8f0ea4a02214e0882ae6ccc60ca2ae225bdd682f134b5c0da5ec6",
          "sha256": "650250e605f97ef4c7de8fce610d9e85c94451aa38c4084a66fc1e16060187d0",
          "sha1": "17dcb46c69e3b80ef7ea9a3a445dfc2c37839a56",
          "md5": "abfa5efd7706d044b2d2ea02c6bcf3aa"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-kotlin-0.5.19-SNAPSHOT-sources.jar",
          "url": "runtime-0.5.19-SNAPSHOT-sources.jar",
          "size": 50503,
          "sha512": "b741e2c3899f9e65577e8080a418b870dd2315ac2e09441f6db739962e68c329ccb0313181227b1214f5bfb9f651dddfd4cf91d323956305992dfd7849fcdb15",
          "sha256": "8c5d995be759a74a4b4e033bf48636c8433ac2db997ec32a1cbe9ac74b93e0a3",
          "sha1": "290d6a491a5a41051248e5939456733712c31992",
          "md5": "81970411045461e6c6dc21af10b14a42"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-android/0.5.19-SNAPSHOT/runtime-android-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-android",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-android/0.5.19-SNAPSHOT/runtime-android-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-android",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-android/0.5.19-SNAPSHOT/runtime-android-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-android",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.5.19-SNAPSHOT/runtime-iosarm64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-iosarm64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.5.19-SNAPSHOT/runtime-iosarm64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-iosarm64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.5.19-SNAPSHOT/runtime-iosarm64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-iosarm64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.5.19-SNAPSHOT/runtime-iossimulatorarm64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-iossimulatorarm64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.5.19-SNAPSHOT/runtime-iossimulatorarm64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-iossimulatorarm64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.5.19-SNAPSHOT/runtime-iossimulatorarm64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-iossimulatorarm64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosx64/0.5.19-SNAPSHOT/runtime-iosx64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-iosx64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosx64/0.5.19-SNAPSHOT/runtime-iosx64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-iosx64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosx64/0.5.19-SNAPSHOT/runtime-iosx64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-iosx64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.5.19-SNAPSHOT/runtime-jvm-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-jvm",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.5.19-SNAPSHOT/runtime-jvm-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-jvm",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.5.19-SNAPSHOT/runtime-jvm-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-jvm",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-linuxx64/0.5.19-SNAPSHOT/runtime-linuxx64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-linuxx64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-linuxx64/0.5.19-SNAPSHOT/runtime-linuxx64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "runtime-linuxx64",
        "version": "0.5.19-SNAPSHOT"
      }
    }
  ]
}
