{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.5.20-SNAPSHOT.3/core-0.5.20-SNAPSHOT.3.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.5.20-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosSimulatorArm64Main-0.5.20-SNAPSHOT.3.klib",
          "url": "core-iossimulatorarm64-0.5.20-SNAPSHOT.3.klib",
          "size": 139283,
          "sha512": "aed690262a7124e298f905390510d670d77ae05e79c90363f1fa007aa237a9ac95d6935b1de9ede3417aab5019299c9c32d8f9ab6425b4ab46cdc19e108f39b9",
          "sha256": "f90ac2e592c4696e767603cb5820e59392726e08d5d09021dc762c4d3e247ce5",
          "sha1": "b63717d6c24ac600ed2319ee1754d6bb019d3e56",
          "md5": "81787398274b3975624b396feb9292e3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iossimulatorarm64-0.5.20-SNAPSHOT.3-sources.jar",
          "url": "core-iossimulatorarm64-0.5.20-SNAPSHOT.3-sources.jar",
          "size": 21237,
          "sha512": "6defbf474015ff1c5cb27250467c9076137faf32cf0215814b5424a1dcf6ac6d86dab4740cdb3ef60743966569e3280189e8656c32d09594a19c3a2cde9723f0",
          "sha256": "7fcb4b8742a2cd2bcef410a76db70c4c78c0a586e6d8ae25fcebec87e3cc3f11",
          "sha1": "6f4996116706a63834328b580fe7113520080310",
          "md5": "b423da40e6f7185f5c8899bc20e554cb"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.5.20-SNAPSHOT.3-metadata.jar",
          "url": "core-iossimulatorarm64-0.5.20-SNAPSHOT.3-metadata.jar",
          "size": 261,
          "sha512": "6d2d9a29706941b7dd036f21ab3fdd4ad51cb46aaafccd26f94bdefa143579c1c8dcbbeac8c400d6f25ad58cba02cafcc44d16802f87c911019969abe4c12763",
          "sha256": "00b396548193c682da728f05f386f1e1c9025175a64be2adf519ca0d68b3ee94",
          "sha1": "5e57207787ba7365c8cf19252658669fc279c4f4",
          "md5": "46227589ebda5bcd24af75cf03b52e43"
        }
      ]
    }
  ]
}
