{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.5.16-rc.72/core-0.5.16-rc.72.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.5.16-rc.72",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-linuxX64Main-0.5.16-rc.72.klib",
          "url": "core-linuxx64-0.5.16-rc.72.klib",
          "size": 124615,
          "sha512": "8171db239013c090092b8d30e83ef387676dceb98fec28811c7a8ef0ecfa5975c06aad6c9576d0c14f5226b90e891e3d6335b6b9f373ef7fb53ea77131f3c178",
          "sha256": "4e837ab1bde314584dfd917aea6366a4ea0b3cc0da075ada848d6d2f12fc4b5a",
          "sha1": "8963bafaa25d1b55f0b1866ccc8da1af7c3702e6",
          "md5": "0fd78d8e5a411ffbd7aeaec339deb522"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-linuxx64-0.5.16-rc.72-sources.jar",
          "url": "core-linuxx64-0.5.16-rc.72-sources.jar",
          "size": 18863,
          "sha512": "ded54edc3537f24fe476e51d9056dca914e79ce3b58b7743e6fdb11a49538bd4c1a388886b453d13bc2e50203511de7e4fdf1ccbbf274a58327ce9cfbde0576d",
          "sha256": "10c5bdb54159f4b9ea2ec1dc4ebd0b04ebdfec005ffed134fa81331a1aece645",
          "sha1": "f3239595bf931b02c4c326e40546fcc2079a98d6",
          "md5": "578b41ad0729d7ed72ab49695b5805f0"
        }
      ]
    }
  ]
}
