{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.16-SNAPSHOT/composeblocks-0.5.16-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.16-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.16-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.5.16-SNAPSHOT.klib",
          "url": "composeblocks-iosx64-0.5.16-SNAPSHOT.klib",
          "size": 289398,
          "sha512": "84f6943aa940274a3ce464ebd140c9cce1df89ab6f4a89cf30960009b835ea7998b745975d52d622c4bded43011e855f96fc9917f130f5a41c1ba3813c94c19f",
          "sha256": "ba6bcca269278757c6ebda27b1618dd9678eb2c7699960968c8a64ee70a535ef",
          "sha1": "1c3308bce5641b9cce4b164f1b19bc14b199ffa3",
          "md5": "9e62f06209325b504708f9a56d8e581a"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosx64-0.5.16-SNAPSHOT-sources.jar",
          "url": "composeblocks-iosx64-0.5.16-SNAPSHOT-sources.jar",
          "size": 50081,
          "sha512": "b60a2a9c8304fc3ecbd7d2f49e895c5e20e4a74c768cf0042e5119cf0b5e08f66f008bd6fc09d50733532b8b7938f77dec33ce52691cc9449915384ca40ff33a",
          "sha256": "2af9a587ffe1a63c4277b186a78c3e302e593feea472ede909dccd6da6cbc30c",
          "sha1": "d8d746660b6af9546a490cc78b37a4ab3de741c7",
          "md5": "21b1da1f823f65926e930b93509889bf"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.16-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.16-SNAPSHOT.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.5.16-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "a4a4649ccbcef383ac03e265869354c2e1cda81a6d78e3724772153e16ace509b990233d3b2748dcfd83d66448d53faf7edf63ce49e431c65742facbc9cacf83",
          "sha256": "4782c32f60c4271ef7853bebbd0df2d7b8df064b1cace72d37e174a1be3db5b6",
          "sha1": "985dee0082dacab841e8b521d78bead7d42c9316",
          "md5": "afe3a97abd6de04c2b6fb46c01323e6f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.16-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.5.16-SNAPSHOT-metadata.jar",
          "url": "composeblocks-iosx64-0.5.16-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "88881c7fcbdd3ca3f13bd26f783c4c2cedd7174542193468d096fa9fead1b6468c4e4cb43a900629b4b31002dd542e2cee51a3846d87ae3f51e4e4cbec8d89a4",
          "sha256": "4c7ab2425c9666994b7bf7c2de714f3938455dde470c55733b0336ca6709fd5a",
          "sha1": "464fe2b6c27ad35019de8f04c8770b1f96d04c2d",
          "md5": "af7d3d9b97157a5f3c21e2586763e4d9"
        }
      ]
    }
  ]
}
