{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.4/flow-wrapper-kmp-0.5.4.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosSimulatorArm64Main-0.5.4.klib",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.4.klib",
          "size": 78895,
          "sha512": "04351b613aa1957506f1200eb4dee771659687481bb80260bb15ace8c4960367d4445850e0ece8ff6e7a3cec577f7b0c8a20c850845f0bde32b4c33e6b0d92e1",
          "sha256": "eabb15d0f753bca792acaaafb049da5634f51932aa1b4b1f176f206096171768",
          "sha1": "580b92fe2991f7345ae92b151e821376b69b9621",
          "md5": "a8a46c3b7339de1fc4a6cee66290cf19"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iossimulatorarm64-0.5.4-sources.jar",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.4-sources.jar",
          "size": 13504,
          "sha512": "b2cab1965d11b2275b9cf0b562c1552fdbef45fe747ce960f48de0515ee8108dfb75e23e461a6dbf0e296930b815c8975047193aa1361481c0fed69f47db99cb",
          "sha256": "816b206d0126a1fe2e16e44c8caa01188afd390de142138f9edda5ec5a1405c6",
          "sha1": "bf9f8a53779acfe4cbcbdc24e4479117f583a006",
          "md5": "4a6bf2eebb2bc3fdc826e5eaa0ed6e3f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.4.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.4-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "559975474de85b8e170ccd81919eb71c76a837baaeeea53dd3b44fa1768f2747a04668f545dcdd5791ab32f1afa33f37ada92219ac7cd55e3288abf8f233adbb",
          "sha256": "4f6cb93485d19e7003b8970bcb16393441c7249f2cb1ae5d8124e95b14a08d96",
          "sha1": "7646871c2e15fccb3fafb964d8444f027230ea97",
          "md5": "31ac45af533bb601e0ecffcc59ef309a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iossimulatorarm64-0.5.4-metadata.jar",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.4-metadata.jar",
          "size": 3010,
          "sha512": "24b802de80c45234f212bb7a0851f65663b5246ff9b82b25bab6a54d449661dddd5cc3d8704ed94efd9a2b5ec7f44191bd81135cd33c731cb57e56518bd417ff",
          "sha256": "5c0d00a7766721940a5a9ac65358c5449b9860b53a2915b4ed2bddcda3c59abd",
          "sha1": "6e92d5c0a91d6a6c38797475adb353a0f9c05af2",
          "md5": "4b6c17bb348e6556ff2dff4be62110ae"
        }
      ]
    }
  ]
}
