{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.8.0/runtime-0.8.0.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.aar",
          "url": "runtime-android-0.8.0.aar",
          "size": 694312,
          "sha512": "eababc4a0978c9b126e8a4ed81d5109f10f35b3a977dcc8a1b44a24160b0fb383d17c33bed49d0933b099f4bb644f24b61821b7fde4b6a8cba461e712250ca31",
          "sha256": "604c5fc6b9636ec07df014a26fef0af1969cd8ed9ec3bf286c45a7fea9a00e93",
          "sha1": "4c5cb1c5ae7fbc82fcc76654908e7af2acff2606",
          "md5": "67d566e6e7c8a0f466df798b79a47a29"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.aar",
          "url": "runtime-android-0.8.0.aar",
          "size": 694312,
          "sha512": "eababc4a0978c9b126e8a4ed81d5109f10f35b3a977dcc8a1b44a24160b0fb383d17c33bed49d0933b099f4bb644f24b61821b7fde4b6a8cba461e712250ca31",
          "sha256": "604c5fc6b9636ec07df014a26fef0af1969cd8ed9ec3bf286c45a7fea9a00e93",
          "sha1": "4c5cb1c5ae7fbc82fcc76654908e7af2acff2606",
          "md5": "67d566e6e7c8a0f466df798b79a47a29"
        }
      ]
    }
  ]
}
