{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.6.0/flow-wrapper-kmp-0.6.0.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.6.0.aar",
          "size": 222467,
          "sha512": "39abf0a6fdfcdc2f93b340fb5a3a0767da48e787ed4e8dac8598cba8884c92c99533c4e1c4d411f69fe4ee0a562f118da8a297a1c08271775343c09e454c0741",
          "sha256": "65b1224c51e3eaf0716b3f3be29fee3de2d0376aa8fd0cec069ff247f9a6dcdd",
          "sha1": "fba081a9c0fc5fc8d5e3b23a169cae1df1f85c11",
          "md5": "e6786a65e17bd6e939c3e098232281aa"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.6.0.aar",
          "size": 222467,
          "sha512": "39abf0a6fdfcdc2f93b340fb5a3a0767da48e787ed4e8dac8598cba8884c92c99533c4e1c4d411f69fe4ee0a562f118da8a297a1c08271775343c09e454c0741",
          "sha256": "65b1224c51e3eaf0716b3f3be29fee3de2d0376aa8fd0cec069ff247f9a6dcdd",
          "sha1": "fba081a9c0fc5fc8d5e3b23a169cae1df1f85c11",
          "md5": "e6786a65e17bd6e939c3e098232281aa"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-android-0.6.0-sources.jar",
          "url": "flow-wrapper-kmp-android-0.6.0-sources.jar",
          "size": 50962,
          "sha512": "631572b71b02c4ceb46624abeba158497d05278e06c30bbeb97feacae8d1f4845cef74081d5aa88896c6188f5f20433f873ed25479a0248b1b59ec1211449340",
          "sha256": "ed09c2779c2dac0b4bfac7cef5a6018fd802e972b623caed52932303ee7a8283",
          "sha1": "7d9663f4c0d3bcc5cbbf20f644232789d6650074",
          "md5": "2b42dbde7f8718e6c0a17229d28d893b"
        }
      ]
    }
  ]
}
