{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.5.20-SNAPSHOT.5/runtime-0.5.20-SNAPSHOT.5.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.5.20-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosSimulatorArm64Main-0.5.20-SNAPSHOT.5.klib",
          "url": "runtime-iossimulatorarm64-0.5.20-SNAPSHOT.5.klib",
          "size": 641427,
          "sha512": "463068b01041e25049a8118abdec7cfe7f1e31af2bfd660ed296ea0e6a3f5f973cf25f9369c0437932ff77dbe5349040ea3e0f1309e9d3e134bd1fcbe681370d",
          "sha256": "255bbc5d4fcebd9c97ae7b0b0b1927b857552f98114636e1169d2fe46e30927a",
          "sha1": "c825f5824e5315db9158c0a1fb76608a36f29e06",
          "md5": "49f80f15e618514b8b9c3bb35f639583"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.5.20-SNAPSHOT.5-sources.jar",
          "url": "runtime-iossimulatorarm64-0.5.20-SNAPSHOT.5-sources.jar",
          "size": 50503,
          "sha512": "6e13220ecf9b1eaaaa4404b9b701d85f153edb4ae46f373d74543b267d55b6cab63801b1b0837cbd473f49e1e299b82da514d34eaaa3d461172ff8b019ea4a92",
          "sha256": "76e05607b8d54c60a6ab9f50794e1cf5f8a26031325413ebf1c27d8037895042",
          "sha1": "7849b4c038f026627e0a67c0b2edc624be1477c6",
          "md5": "b62ea369711befb0a346e316df9cd0f5"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.5.20-SNAPSHOT.5-metadata.jar",
          "url": "runtime-iossimulatorarm64-0.5.20-SNAPSHOT.5-metadata.jar",
          "size": 2428,
          "sha512": "57f1fa976ec3d52f17d170443cda760c815537686e32f25f4d31b119381a50cd5da876f1cd56e8e756a9206fab62981334f351d06ea30457e72b42b11f0a5633",
          "sha256": "61c357e6d8a4f87922e8df3d8b3d94952b9490c3a9f8a70cb694d01e8a041367",
          "sha1": "9a1791c6232c460b97be5a0ee23d5ee270e44ca0",
          "md5": "4e794b302a8c85242618c747171c5d25"
        }
      ]
    }
  ]
}
