{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.7.1-rc.239/runtime-0.7.1-rc.239.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.7.1-rc.239",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.239"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosArm64Main-0.7.1-rc.239.klib",
          "url": "runtime-iosarm64-0.7.1-rc.239.klib",
          "size": 858666,
          "sha512": "871073aaf9b4e8bfa614b15fa98b739bbf685a4cd00699b72aa8a9cf6cf307d209e7d115ae65950b8d4617dfa02487ce7c2e22362c33c5d9c7af3e75c3b294dc",
          "sha256": "489d02906a303c587a0bbaa78dae50b059a93c4a394c53ff184f39d592fa9450",
          "sha1": "74683701e0afd7393cc36fdd654641c85361f90c",
          "md5": "fd1891acccb143a845b894d3f7cc47d5"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.239"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosarm64-0.7.1-rc.239-metadata.jar",
          "url": "runtime-iosarm64-0.7.1-rc.239-metadata.jar",
          "size": 2428,
          "sha512": "2e2ef9b500b973c612ba59f62889eb806aa6146b301ce456283e169471635c86977adb0e51a0f12bfbf21a0655cc9362dfb077bfb72d2ac194547462ef2221b1",
          "sha256": "1867b8502467046bd9c4c8d5c0f548a8a00ef8ba7059a51d3ef912882b7e80b7",
          "sha1": "370cc5705040ff4230840fc8e7704ec27bd51136",
          "md5": "c8e49aa79868688cc7cd728547b9ac85"
        }
      ]
    }
  ]
}
