{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "viewblocks",
    "version": "0.7.1-rc.240",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        }
      ],
      "files": [
        {
          "name": "viewblocks-0.7.1-rc.240.aar",
          "url": "viewblocks-0.7.1-rc.240.aar",
          "size": 107999,
          "sha512": "acaba6c3abbdcbb43a4c07490c21fcd185d415b61957e321cc298522729b9628702be4081b0ca9d2848df28aefc08328dcd8474bcc5d9d7c6ac5fc4a9469a0b4",
          "sha256": "a740204b65a27fb2611f6e60a89e592a277b5a3fbaba43ff81aa01b428b1d236",
          "sha1": "ad352bf393bde645be6de0fbda36c3326c87ee74",
          "md5": "aeef010d441f263e8dcb3bfc1f4cccae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        }
      ],
      "files": [
        {
          "name": "viewblocks-0.7.1-rc.240.aar",
          "url": "viewblocks-0.7.1-rc.240.aar",
          "size": 107999,
          "sha512": "acaba6c3abbdcbb43a4c07490c21fcd185d415b61957e321cc298522729b9628702be4081b0ca9d2848df28aefc08328dcd8474bcc5d9d7c6ac5fc4a9469a0b4",
          "sha256": "a740204b65a27fb2611f6e60a89e592a277b5a3fbaba43ff81aa01b428b1d236",
          "sha1": "ad352bf393bde645be6de0fbda36c3326c87ee74",
          "md5": "aeef010d441f263e8dcb3bfc1f4cccae"
        }
      ]
    }
  ]
}
