{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.7.0.2/core-0.7.0.2.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosArm64Main-0.7.0.2.klib",
          "url": "core-iosarm64-0.7.0.2.klib",
          "size": 144154,
          "sha512": "cad8dbcda1052ccd69a3754bbb44b10e54f54d9fece5f8e058e7fb0ead5d40a612909df9f0efe254966829a99d0a1127ba2798b7de123e3adfff0e1c1ba34e36",
          "sha256": "c4dbd93120a682dc88820ed5d0f52650af8427b58d5d5bd01cb8d2b671716f46",
          "sha1": "eda3055ed9fef987b2c2a46b6ed2218c5b13a4a7",
          "md5": "e2b59f06b544a12a99e8343e2ccb221c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.7.0.2-metadata.jar",
          "url": "core-iosarm64-0.7.0.2-metadata.jar",
          "size": 261,
          "sha512": "caa2cc2457f761eff31bddcadd7a20593a598057fb569d99cce48c99b6398f3aab13c0627c946a0d9f43ec8ade63ca238852217513f3f912e4c77706fa2d91e4",
          "sha256": "d2f14d45ecc9f2c68f9879a36841e8447aeb96b66eaf92011dd638a803908977",
          "sha1": "c0163e82f3b38d7479cb88b6b2e54f3cc0884bec",
          "md5": "1fe8424a8263dc969fe7354c70b4f30e"
        }
      ]
    }
  ]
}
