{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.20.2-rc.158/flow-wrapper-kmp-0.5.20.2-rc.158.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.20.2-rc.158",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.20.2-rc.158.aar",
          "size": 221741,
          "sha512": "3514e19bbe8eccce4d0bb9460fc1049e1e6c3750550b418575cd8c46a88e8329fec2628e560c9cb06dfcaa10b919c98744404fb9e49b9d42a1ec4891095a23e9",
          "sha256": "2be2267d3d85a092199ce7137ef9d7b40cdbbe6242bf8e97f6279fe58a3139a5",
          "sha1": "42f3aa4986e29182682359fe0d58ea04f568786b",
          "md5": "580101f3d1818d4f6ae3804c3a7f16d3"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20.2-rc.158"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.20.2-rc.158"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.20.2-rc.158.aar",
          "size": 221741,
          "sha512": "3514e19bbe8eccce4d0bb9460fc1049e1e6c3750550b418575cd8c46a88e8329fec2628e560c9cb06dfcaa10b919c98744404fb9e49b9d42a1ec4891095a23e9",
          "sha256": "2be2267d3d85a092199ce7137ef9d7b40cdbbe6242bf8e97f6279fe58a3139a5",
          "sha1": "42f3aa4986e29182682359fe0d58ea04f568786b",
          "md5": "580101f3d1818d4f6ae3804c3a7f16d3"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-android-0.5.20.2-rc.158-sources.jar",
          "url": "flow-wrapper-kmp-android-0.5.20.2-rc.158-sources.jar",
          "size": 46542,
          "sha512": "216ef3cc161075987a7f39523ad23023b7feb56f81393879d1a8a6558c158273f0c1c957ff217ae28bcb94f96b25e1cd35b4973a7cad37243f0e34265429ba49",
          "sha256": "0bc86f60ee5664d759b477adce64c8be9ce40a4a51fc66fbe8fa620244556ebf",
          "sha1": "30b93b022d850b3eef28b8023ba127a0dfceb7f3",
          "md5": "c214d36805e55f8ac46d48a8b4a17014"
        }
      ]
    }
  ]
}
