{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.5.15-SNAPSHOT.2/core-0.5.15-SNAPSHOT.2.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.5.15-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosSimulatorArm64Main-0.5.15-SNAPSHOT.2.klib",
          "url": "core-iossimulatorarm64-0.5.15-SNAPSHOT.2.klib",
          "size": 121273,
          "sha512": "82981eb2ff2ddad4c23a4a6147277069189a48da52e9dfbbb57cd5f47e736d890f3ff756bec95e53e10366524d63dbb494844fce744c08a7c88ff1465e86ab0e",
          "sha256": "995c49c6fa03080b82bd665b63f8bea1abfa6ed230f8eddeb800bcc9cc23fbc4",
          "sha1": "ceb3616fe6410e6ecbce10b47cd4a33681440740",
          "md5": "5cdefbac6f9347b9c95ae46d48e47401"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iossimulatorarm64-0.5.15-SNAPSHOT.2-sources.jar",
          "url": "core-iossimulatorarm64-0.5.15-SNAPSHOT.2-sources.jar",
          "size": 18169,
          "sha512": "f8335fc9598e964a6ad61d5a562f5f49a9a4ce89ead746c9ec3d13d2b9567ee18775e22ce47a4fa2ddf0fc50f73e835f99560a109a7ead9f679fef87895ae5b4",
          "sha256": "ef43d06e0850a567869b1f021d174c2f21b122579a07a1ca04445d4c2ba8a084",
          "sha1": "a23c78c369e3ed09ffcec4b159e75b5b0b9d53a1",
          "md5": "1781c02ee9f043240940dcaffbf6e679"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.5.15-SNAPSHOT.2-metadata.jar",
          "url": "core-iossimulatorarm64-0.5.15-SNAPSHOT.2-metadata.jar",
          "size": 261,
          "sha512": "aa63037aa8da452421e3cbb9329c9e4db210f184e014c6f74361514d26bb61cfeecde828831f063d3ab832caec12284c459b86592132479371c739bf8cc02145",
          "sha256": "cf87f3bc66a378342118ecb5aa7058548d893c67fd8d390a0929c48655489fb3",
          "sha1": "4e2534e38de07dd0f14b390136d096b174a5d7c0",
          "md5": "718b15781a1128f36fe99b77bbdd3f19"
        }
      ]
    }
  ]
}
