{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.5.20-rc.140/flows-sdk-0.5.20-rc.140.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.20-rc.140",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-rc.140"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.20-rc.140.aar",
          "size": 194612,
          "sha512": "9a60e36381a5406527010f94a908080771c1af7ea267747807ab15e86d3634cf4e26c2305ff0564352a6a9d056658621a36958793658ecc934a90ebe2e1b9fd4",
          "sha256": "8e1f6d85260856f279b0d5679f5dc2f776a375c5b048383d74bf252291cf04d3",
          "sha1": "8f1c38b164edf25f3cea819d48a8ba913f349cf4",
          "md5": "2294b98fb9f352d7b04e0143d03ecc08"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-rc.140"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-jdk",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-rc.140"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.20-rc.140"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-optimal",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.20-rc.140.aar",
          "size": 194612,
          "sha512": "9a60e36381a5406527010f94a908080771c1af7ea267747807ab15e86d3634cf4e26c2305ff0564352a6a9d056658621a36958793658ecc934a90ebe2e1b9fd4",
          "sha256": "8e1f6d85260856f279b0d5679f5dc2f776a375c5b048383d74bf252291cf04d3",
          "sha1": "8f1c38b164edf25f3cea819d48a8ba913f349cf4",
          "md5": "2294b98fb9f352d7b04e0143d03ecc08"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flows-sdk-android-0.5.20-rc.140-sources.jar",
          "url": "flows-sdk-android-0.5.20-rc.140-sources.jar",
          "size": 32045,
          "sha512": "4ef2e84a48ee655db1d3b87d1d9e2bd86630b05c75e47d4707b007b22f80818f3d6a9cbfa4ab22e933a065f39bc7992c79be5a50effbd80e7cc61ec45a55a67f",
          "sha256": "ca53ee3c2884405d287fc6ad3aabb53469e92244d91c5c8d5ba7188ceb8d7003",
          "sha1": "9b987b2475a1c75ba91ecf282023ee8aaaa0dc68",
          "md5": "3308dc75dfe5e16cfbe0dc632fe7efde"
        }
      ]
    }
  ]
}
