{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.5.15/runtime-0.5.15.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.5.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosX64Main-0.5.15.klib",
          "url": "runtime-iosx64-0.5.15.klib",
          "size": 611865,
          "sha512": "7fe20a14fba34facfe1e6b3bb148f4823b7453296a86d32a047f495dbd32143b35cf51e22af142bad75fcd128ecaf4aadbce7110402261b9a1f4e2eacd638cfc",
          "sha256": "06c1a9cbfae68dba12cc0831e53703b67c91e51a9468af1c4dd482fe56a57445",
          "sha1": "cccf5895fd84fcd25b393bd21fd2c673002167b6",
          "md5": "c45aff50d97c7b57113051d64eebb1c1"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-iosx64-0.5.15-sources.jar",
          "url": "runtime-iosx64-0.5.15-sources.jar",
          "size": 47799,
          "sha512": "cb100860d8ec6bc80257bdae06c133361d687cb8063858d313fe74c88688f8358c8519ad7342281f6e94629a9d8c126260e51153e2655f85daea22a7057d7e80",
          "sha256": "f7411582376d70363b1bb45cc4831b4f145bea73283b3793ef0ae3a05e059a0b",
          "sha1": "3aa30f288162f368895810cba40d5d6853e42ea8",
          "md5": "39c253acf971bd770df12e104511d2b2"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosx64-0.5.15-metadata.jar",
          "url": "runtime-iosx64-0.5.15-metadata.jar",
          "size": 2428,
          "sha512": "b6c7cdc630a594727d67133eb32195cc9c0571ade091242850b4474c33e8abd87d647264b6966aa82915ca7825ebacf0265c89cb87bddb46d37995375ca2809d",
          "sha256": "c8c6808e34b76ddbda0cce93e9932636f31cc689587123b17c461dd7e20d641d",
          "sha1": "81650b1639c75b224caa9ccac1d4e2acc817eb00",
          "md5": "3cdf3e997736ca3d5125312a2a62b505"
        }
      ]
    }
  ]
}
