{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.20.2-rc.158/flow-wrapper-kmp-0.5.20.2-rc.158.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.20.2-rc.158",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20.2-rc.158"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.20.2-rc.158"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosArm64Main-0.5.20.2-rc.158.klib",
          "url": "flow-wrapper-kmp-iosarm64-0.5.20.2-rc.158.klib",
          "size": 256230,
          "sha512": "86a8718e5c771b68f2ee48875052edf23e43d39db55c79c5cc9bfe92e390c4fdb187f3b4f3f9f5f3b9207556781625aecb43006803a4f6b9ec7a180d2137a347",
          "sha256": "682eadfc00c9f1d61512bd6da53f2c55724d51cf62a2cfc9b3c43498398e8b02",
          "sha1": "5732ef56719af81361060629c1852c00797f6bae",
          "md5": "f2d654cee819c308949e5aab5ac52296"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosarm64-0.5.20.2-rc.158-sources.jar",
          "url": "flow-wrapper-kmp-iosarm64-0.5.20.2-rc.158-sources.jar",
          "size": 46015,
          "sha512": "0bd8f8ddbb2b42d6b2b99b2b84a0195578b01823ab294d598e9fa6b152f0381361b34617d33c3cf2e80c4590cf4e3ac19f67034e149cd0d4d200faa4ee57febb",
          "sha256": "94e02580ecab9288f73c4ea759d031037f6d6fbcafeed644c53ce8b67faa2bdd",
          "sha1": "ccd41f380d89e6ccf26a375b94bdc5f08f2f3c75",
          "md5": "0907b84047fe1e6d28b64b8c9152be1a"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20.2-rc.158"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.20.2-rc.158"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.20.2-rc.158.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosarm64-0.5.20.2-rc.158-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "755c3e83ef172b082cdb00a34ca577be2dc1b170f4dc4385f193fb88a8351d4b5b0c63afcbbf2fb6c7091d1ebb171a356de5d12c8a53b9898bf2fb03d1fe5492",
          "sha256": "c3cdf71040ee53c01ca0d12636d2536eec222f19428a265fb2fb508fbf747f79",
          "sha1": "a671fb3062fb03585d75d8838fa05443d83b287a",
          "md5": "b48d4adac7a32aa1c366a9c7d3262f12"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20.2-rc.158"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.20.2-rc.158"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosarm64-0.5.20.2-rc.158-metadata.jar",
          "url": "flow-wrapper-kmp-iosarm64-0.5.20.2-rc.158-metadata.jar",
          "size": 3786,
          "sha512": "559342dcce773d1c62e93d9cdb143d717f5d42f3bf89519319afd926b0792c203e6dd89898960b4752ffecb0e75ae327bcab543f8127c510121bf14791cb54a5",
          "sha256": "9a1a1f417985100bae6b0deffc8957ee10ebe5399fc18ead0007a79c387f4548",
          "sha1": "81ed83ca35c2f8bb46ab2e1939a628ff975006f4",
          "md5": "d78600b6e1873211d61042b480b35ee1"
        }
      ]
    }
  ]
}
