{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.5.20-rc.139/flows-sdk-0.5.20-rc.139.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.20-rc.139",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-rc.139"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.20-rc.139.aar",
          "size": 193650,
          "sha512": "bcd989d95dd22a2f5423d0550b7cfc1cb7cb7fdebb25f7061856065f4ff9dc31b48f3f62f7a8026d8fcac5f52bbf190fd9156878075f6baef426b016e626ce11",
          "sha256": "a002b4858e54ff51fd6c276f1bd38e3415adb3f630711eb84db651f5b834f74f",
          "sha1": "fff782942ac73ffc2dfee040646825609d1cc4b5",
          "md5": "3cf6b59868fc05ab8ca7a2655f8c5189"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-rc.139"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-jdk",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-rc.139"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.20-rc.139"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-optimal",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.20-rc.139.aar",
          "size": 193650,
          "sha512": "bcd989d95dd22a2f5423d0550b7cfc1cb7cb7fdebb25f7061856065f4ff9dc31b48f3f62f7a8026d8fcac5f52bbf190fd9156878075f6baef426b016e626ce11",
          "sha256": "a002b4858e54ff51fd6c276f1bd38e3415adb3f630711eb84db651f5b834f74f",
          "sha1": "fff782942ac73ffc2dfee040646825609d1cc4b5",
          "md5": "3cf6b59868fc05ab8ca7a2655f8c5189"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flows-sdk-android-0.5.20-rc.139-sources.jar",
          "url": "flows-sdk-android-0.5.20-rc.139-sources.jar",
          "size": 31517,
          "sha512": "f8cf8a3d8119ef0ea2aa2e905aa39cc1b445841e1ed35e6ac773ab51c46da25600c1818b062082a7505ebc72bd7ab8a95bb725875078e8a9432c09ce2d2a574e",
          "sha256": "e55aff0d26f19e3a7d761fa97e2b67f10ada4b77694ef076f52478367c6580b4",
          "sha1": "fb4ceee7b05632cb113cf2c441cd8217dcacf260",
          "md5": "33a872f68d44dea6e5da312c6b1e0385"
        }
      ]
    }
  ]
}
