{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.6.0-SNAPSHOT.25/core-0.6.0-SNAPSHOT.25.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.6.0-SNAPSHOT.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosArm64Main-0.6.0-SNAPSHOT.25.klib",
          "url": "core-iosarm64-0.6.0-SNAPSHOT.25.klib",
          "size": 101570,
          "sha512": "2d557eb26b83d8643d0531a51368526da11680968874c91516b5950805ee02687c51ce44023b78d41a9e7e616bd169914e248d43377359ff895367cb01a6cfa4",
          "sha256": "16445b9ec5c81d19d0a4b52775345c94c0a3d61a85fa94e74240827e883a5d08",
          "sha1": "1fbc109c91d97236bd4b63829a144a12308f5068",
          "md5": "05b1ec743bb6ed602600c0f551303b97"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iosarm64-0.6.0-SNAPSHOT.25-sources.jar",
          "url": "core-iosarm64-0.6.0-SNAPSHOT.25-sources.jar",
          "size": 12871,
          "sha512": "9384b55817f88f910ec57688f568f23c7334e431ee50978b193d247dc6dc8604297381b30757d73c8c22a3ea4f3da34334acfaf4bfa1121de726f0027e0f3235",
          "sha256": "cbafd42c100bb7358370dc203cd61d4041cd683b48d69db2eda1e6514b18e617",
          "sha1": "20061d10ddcd97c4bb4a9c49602da7d79000e539",
          "md5": "337280c1de2570f705980fc4fe7f6037"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.6.0-SNAPSHOT.25-metadata.jar",
          "url": "core-iosarm64-0.6.0-SNAPSHOT.25-metadata.jar",
          "size": 261,
          "sha512": "8e2a79e42b2558cc7da9c03eafe9014ca3fac710399b09e75daec9968a26d05af91ca9def20a020e18a86dd708636feb10b45355fe42e5e5666e8d58fa274cac",
          "sha256": "ada3ebc93a72bf13df3fa2ebc1cb313fe28e810365052b3233382ee024d2c252",
          "sha1": "4e492a4fcad7cccb908fdf7cb0052502893495db",
          "md5": "6a30657a81d2b897686f5d11d7ee485c"
        }
      ]
    }
  ]
}
