{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.8.1-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-metadata-0.8.1-SNAPSHOT.1.jar",
          "url": "composeblocks-0.8.1-SNAPSHOT.1.jar",
          "size": 37856,
          "sha512": "c7182a3029b639aaa73626a79a1969423a9794df34b4499280e8eee63f6e0420e8b62e832e8c4cd95628e69a021fc03a194655d58b3d4c7665b15df0026e42ae",
          "sha256": "10feb9100362b9267ae50d982eaec2dbc2fc80d2a5e9a17b7c6909143b926e53",
          "sha1": "31ff16e27b8c09efa1236f87777204d3f554360f",
          "md5": "311924f7623b3250eebda79c88c86bbd"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.8.1-SNAPSHOT.1/composeblocks-android-0.8.1-SNAPSHOT.1.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.8.1-SNAPSHOT.1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.8.1-SNAPSHOT.1/composeblocks-android-0.8.1-SNAPSHOT.1.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.8.1-SNAPSHOT.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.8.1-SNAPSHOT.1/composeblocks-iosarm64-0.8.1-SNAPSHOT.1.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.8.1-SNAPSHOT.1"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.8.1-SNAPSHOT.1/composeblocks-iosarm64-0.8.1-SNAPSHOT.1.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.8.1-SNAPSHOT.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.8.1-SNAPSHOT.1/composeblocks-iosarm64-0.8.1-SNAPSHOT.1.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.8.1-SNAPSHOT.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.8.1-SNAPSHOT.1/composeblocks-iossimulatorarm64-0.8.1-SNAPSHOT.1.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.8.1-SNAPSHOT.1"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.8.1-SNAPSHOT.1/composeblocks-iossimulatorarm64-0.8.1-SNAPSHOT.1.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.8.1-SNAPSHOT.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.8.1-SNAPSHOT.1/composeblocks-iossimulatorarm64-0.8.1-SNAPSHOT.1.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.8.1-SNAPSHOT.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.8.1-SNAPSHOT.1/composeblocks-iosx64-0.8.1-SNAPSHOT.1.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.8.1-SNAPSHOT.1"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.8.1-SNAPSHOT.1/composeblocks-iosx64-0.8.1-SNAPSHOT.1.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.8.1-SNAPSHOT.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.8.1-SNAPSHOT.1/composeblocks-iosx64-0.8.1-SNAPSHOT.1.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.8.1-SNAPSHOT.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-jvm/0.8.1-SNAPSHOT.1/composeblocks-jvm-0.8.1-SNAPSHOT.1.module",
        "group": "br.com.wave",
        "module": "composeblocks-jvm",
        "version": "0.8.1-SNAPSHOT.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-jvm/0.8.1-SNAPSHOT.1/composeblocks-jvm-0.8.1-SNAPSHOT.1.module",
        "group": "br.com.wave",
        "module": "composeblocks-jvm",
        "version": "0.8.1-SNAPSHOT.1"
      }
    }
  ]
}
