{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.6.0-SNAPSHOT.15/composeblocks-0.6.0-SNAPSHOT.15.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.6.0-SNAPSHOT.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks.aar",
          "url": "composeblocks-android-0.6.0-SNAPSHOT.15.aar",
          "size": 134611,
          "sha512": "e5a3b1f6e182c39e3bb682c6ea79ef24768fe91d48ec26a261dfb0ddd717b0b66927c556e7b4018741c415ecece929210ea9db5d2a36fafeda2879d4eb74fa2e",
          "sha256": "eb2bb2c07560a522f52dcc92aa601a8a22e44109c6ff8fa486903fdacc1e5eb6",
          "sha1": "498088ef4909648798af7c03eee80c5467145289",
          "md5": "cefbc0b71006c726277ed9b89bb6a85e"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.15"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.15"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks.aar",
          "url": "composeblocks-android-0.6.0-SNAPSHOT.15.aar",
          "size": 134611,
          "sha512": "e5a3b1f6e182c39e3bb682c6ea79ef24768fe91d48ec26a261dfb0ddd717b0b66927c556e7b4018741c415ecece929210ea9db5d2a36fafeda2879d4eb74fa2e",
          "sha256": "eb2bb2c07560a522f52dcc92aa601a8a22e44109c6ff8fa486903fdacc1e5eb6",
          "sha1": "498088ef4909648798af7c03eee80c5467145289",
          "md5": "cefbc0b71006c726277ed9b89bb6a85e"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "composeblocks-android-0.6.0-SNAPSHOT.15-sources.jar",
          "url": "composeblocks-android-0.6.0-SNAPSHOT.15-sources.jar",
          "size": 36198,
          "sha512": "1efb00bb7841cb013d49d59bc98b77483cc32f0cb699782934cbfa66309fa9857f33cff027a27a49233a7f06202677900cfcc84d05a3e58930a000ef58c09475",
          "sha256": "c143fa3e329bf3ee8084e33434d670c3d11e1419dede1b439ce189859a6b72f4",
          "sha1": "cbbed2cf4f7acbc10d8b06ef143d15d551f6bfb3",
          "md5": "3588824e4914a64fa247866a0242de9b"
        }
      ]
    }
  ]
}
