{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.7.1-rc.237/core-0.7.1-rc.237.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.7.1-rc.237",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosX64Main-0.7.1-rc.237.klib",
          "url": "core-iosx64-0.7.1-rc.237.klib",
          "size": 235778,
          "sha512": "1c678b4a7d1aa1505124412c2b4b85f27eb9a82a8097c2c298ccd9c3a6342a38d998a4e590fc0c50ff090ef05e72680410c561f07971fc55a39d807a3982c9c7",
          "sha256": "0f93b141072e2a924d4432efb3d0ce203b1096fa2edb96fe6a443a505c316054",
          "sha1": "35c74ac91bbdbe78dae2cbb74bfc103ae11af596",
          "md5": "0105305b1bc3dd169668c98308f2b58c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.7.1-rc.237-metadata.jar",
          "url": "core-iosx64-0.7.1-rc.237-metadata.jar",
          "size": 261,
          "sha512": "9b7f5468df88fa48a150d4200578608f0ecee2721d1d85d7ae0f37dda874ab212f50dac6f1066d0f49e396aa4aa708002f8eefb8a1281c1dd592a8b1e71bceec",
          "sha256": "b33ddc16e569513730c5cb4c7f41a6645b4d0b2fda2f788413e54e19a88449f4",
          "sha1": "26f681207143ce0519b275b8dff58b91f5e9daf7",
          "md5": "a4b94defad3afdd37764a13d07c9ae90"
        }
      ]
    }
  ]
}
