{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.15-SNAPSHOT.2/flow-wrapper-kmp-0.5.15-SNAPSHOT.2.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.15-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.15-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosArm64Main-0.5.15-SNAPSHOT.2.klib",
          "url": "flow-wrapper-kmp-iosarm64-0.5.15-SNAPSHOT.2.klib",
          "size": 238155,
          "sha512": "49914ad632caa7fe90babcaa3e50690b1ea793fafd3acb55d6cf9296c8d01ab4974f6c4d85e479e469c24fe747414b9fe9a5458b2d66c2e3f23d956876975da1",
          "sha256": "4458863a9dd88e9d51ec452ee6343cabb54344519b3d6f2d67f8dc67d3ee0a56",
          "sha1": "f167266501c9d85b601f36b1fecffe19e250cfb5",
          "md5": "4609783b1e2ece2b8934f60f7262b8b4"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosarm64-0.5.15-SNAPSHOT.2-sources.jar",
          "url": "flow-wrapper-kmp-iosarm64-0.5.15-SNAPSHOT.2-sources.jar",
          "size": 41223,
          "sha512": "4ae3602ddeb0fe12aefed436646d10422621976901b28f3ec57df61c975de6978fa81138c6a76468a3e76c705cfc1a390dd351d28e3d30340a0fa7a58b9adb56",
          "sha256": "9a5a34ae9c27f561e985a3529252e2cdd379cb5a0d6ea650e71383713e2cff9f",
          "sha1": "da86fd5b1d5783c761029cb09710d5755b60b80f",
          "md5": "cd4722712ceb9f610142f2c2f66f12fa"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.15-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.15-SNAPSHOT.2.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosarm64-0.5.15-SNAPSHOT.2-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "4723e69c17278151463a0d9628747993eaea2728ac7988f34e9ccf3c4c25275d28a3ba480923fcc43f5c1b1e4e8f8b448f424f7b029858427ffa08c49a77657f",
          "sha256": "c99c235dbdc4fcdf07df4d20f69c379234eba95de2e45cb6795a1688ef3abd1b",
          "sha1": "bd7ff1d9b526e4670a5ec53766e52d31bfb1b661",
          "md5": "abb4cd4a855ad80c8f5cd16ce375b091"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.15-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosarm64-0.5.15-SNAPSHOT.2-metadata.jar",
          "url": "flow-wrapper-kmp-iosarm64-0.5.15-SNAPSHOT.2-metadata.jar",
          "size": 3747,
          "sha512": "4971be44ed77ca90d1aad0de700fff7114c34948c7bfd561be8584cb3af3d583986a19cfafb03889c65868c0a844ab5fab28647acc924b120dc4035db06f10bb",
          "sha256": "ef242a7d15f6a6b397b2df02a1b0386924d49fc71755afdbe050e322afa5296b",
          "sha1": "a762504907e69db8fe67e7b31b2383f02b83be6e",
          "md5": "f22b02682eaadf78fee7a223e846e439"
        }
      ]
    }
  ]
}
