{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.5.16-rc.94/runtime-0.5.16-rc.94.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.5.16-rc.94",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16-rc.94"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosArm64Main-0.5.16-rc.94.klib",
          "url": "runtime-iosarm64-0.5.16-rc.94.klib",
          "size": 640344,
          "sha512": "c296aba9f85cc0efbf84d3398a15c4a427063d463cb1d740d9363632a6c6c48c71186eee4d192536ab12971b3c2402a896fd657054c6d1b19eade546abad9b46",
          "sha256": "721034ba10e25be5f67cc95c789bf028d5dae8ae95021abc435bc0ab3b604172",
          "sha1": "9a5453415edacab91969d290e0723135f48d5d65",
          "md5": "cb1a9b3a896b9b0232e364fa52d82d63"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-iosarm64-0.5.16-rc.94-sources.jar",
          "url": "runtime-iosarm64-0.5.16-rc.94-sources.jar",
          "size": 50432,
          "sha512": "963e702e635d69f3f30b2eec29532cd072ae1656c985a3b66942b99934b0bfebbaf51c9615d942146b537ab3398746881a7e14285a73773e84fa09b9e6ee85d5",
          "sha256": "abf8aff6002dc43e767fdd5a9359a51dcd7cf45cb634b5c32a3bff8695d9f7a7",
          "sha1": "6beffa84d84efad812de920582dac6e1657ee6ac",
          "md5": "a8a2686a4d636d22ae565704e2824741"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16-rc.94"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosarm64-0.5.16-rc.94-metadata.jar",
          "url": "runtime-iosarm64-0.5.16-rc.94-metadata.jar",
          "size": 2428,
          "sha512": "d01e34b25fa65a502825110e8f31aa78c3c2c6886265715f6d3b27680da09f9bc41b1d6621c03a9ab6d956c16d6de0bd6a5795e17a028e0306309a95fea9658d",
          "sha256": "e37903795b8d8c4ad7a7e718610bb20ad1efb0d3b66dddf91028d2056ee93943",
          "sha1": "6c2adb1dfa3beb2e6d99bcfca8483509187b5430",
          "md5": "3b61e268682ad10317d954f8942c7e54"
        }
      ]
    }
  ]
}
