{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.5.14/flows-sdk-0.5.14.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.14.aar",
          "size": 125929,
          "sha512": "503c34843ea06a3ae90f3cc3fec30ee22b19676637ba4dfd7cd79b5adeeca08d1a1cb30f4aa138a9f1465f2c3f552ba30b991cb65811687fbba17aaab9fde43d",
          "sha256": "7d11c45b6df108f3a6557cf85d420fea448f94207ce040cef0874ebf6ba7b50a",
          "sha1": "2f2f1e72506203202ab40766e3682df1ac813117",
          "md5": "40ca7d604a17b22e69129927b0b40f9d"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.14"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.14"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.14"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.14.aar",
          "size": 125929,
          "sha512": "503c34843ea06a3ae90f3cc3fec30ee22b19676637ba4dfd7cd79b5adeeca08d1a1cb30f4aa138a9f1465f2c3f552ba30b991cb65811687fbba17aaab9fde43d",
          "sha256": "7d11c45b6df108f3a6557cf85d420fea448f94207ce040cef0874ebf6ba7b50a",
          "sha1": "2f2f1e72506203202ab40766e3682df1ac813117",
          "md5": "40ca7d604a17b22e69129927b0b40f9d"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flows-sdk-android-0.5.14-sources.jar",
          "url": "flows-sdk-android-0.5.14-sources.jar",
          "size": 14369,
          "sha512": "dad6576bcceca6369bafedbc9c366784fa44a47f183de7d723084d2f387e9795385be68273e8d1078cc1feabc91decd918211e0d0697f9fa09ac55ac56e052b6",
          "sha256": "91908552d65dc748db460083c6176dcc3881d16d8268edae75e440e3bcb25bf7",
          "sha1": "8049e44b853aa7425a56a1b997c0100ac410d2d4",
          "md5": "d7444cc023b6e2f52bcb1dd40af1746b"
        }
      ]
    }
  ]
}
