{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.12-rc.30/composeblocks-0.5.12-rc.30.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.12-rc.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12-rc.30"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.12-rc.30"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosArm64Main-0.5.12-rc.30.klib",
          "url": "composeblocks-iosarm64-0.5.12-rc.30.klib",
          "size": 224297,
          "sha512": "f88370249404aaa3d1950e3d53efbc80093687d9150d64a5778a984af12596c7b9df3cf220655fab62b1ad96104757df7ba2889b07bc005f0f253bac3f417ddd",
          "sha256": "7f395fcb6b4b96471c31e5b7bf33ddd96f18278225c1616860c9d38b0bb19812",
          "sha1": "382c3f709b87d7b4824369cc1a453bfa61d97311",
          "md5": "5bf76d450fde515242b64c15540548dd"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.12-rc.30-sources.jar",
          "url": "composeblocks-iosarm64-0.5.12-rc.30-sources.jar",
          "size": 36171,
          "sha512": "23c4853c4c5ee3e6ac70f0d156f7edca210d60c462afc04368f907794a7dd2bb486270d34bbf5a74f3b285ae3096689a8043dbeac4e6731b501f0447b4c97010",
          "sha256": "27d5e6dbc67211882f5e0804adf3872f8687745226d6a4874e42cce92a4b2e3f",
          "sha1": "5993f83f60b0d937068cf7414394a0621ef03b5d",
          "md5": "f7e8a769e83320cad5d567a321b1c829"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12-rc.30"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.12-rc.30"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.12-rc.30.kotlin_resources.zip",
          "url": "composeblocks-iosarm64-0.5.12-rc.30-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "3959fdfe7779c470fb96c72c8ac7c838965d106b4f3d4dbc075ccf186164155cd17d91522d36f67f79a474c3fe6b9046b3fb5f2de5ced81921224cc155685399",
          "sha256": "3a973466f9131b555f89cd0751b9b8ae0158e8e95bab44b8915d02edb5fdd956",
          "sha1": "41c0e4f263e464460405370a0b115aecbf1480ff",
          "md5": "c39a2a96e14ccc0cec4b5e2ac6fa4195"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12-rc.30"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.12-rc.30"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.12-rc.30-metadata.jar",
          "url": "composeblocks-iosarm64-0.5.12-rc.30-metadata.jar",
          "size": 261,
          "sha512": "e8dffede53d18b0b583981aede924368a92baae4bc4a61390c06230b3b3d7b2c01b9047191a7bbfa116d9fa5f094fc3e868f8fad17077bd5505f667e3b78c33f",
          "sha256": "6f23d884927f933491258f4b85dcf1ffd9e5930d6258ba9f9b8ccf22ca674daf",
          "sha1": "38d6feb2d5e55da81137cc1e32c261d14ff52919",
          "md5": "638f31503da267d6910d1a905863d348"
        }
      ]
    }
  ]
}
