{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.13/flow-wrapper-kmp-0.5.13.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosSimulatorArm64Main-0.5.13.klib",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.13.klib",
          "size": 144429,
          "sha512": "9b67a262352e6c74d47dbc10edc4925cb162f19ed808ca11ffbaebf9be208d3975b0eec34673173e68de55f3b012fa3c36cfe0456145e1111df40880305a09f0",
          "sha256": "77194c7f44bf196f184f325d8b9aeda24b29ef6fb5a283d92b1294672a47b6b2",
          "sha1": "fbea5efd96b59035c3083387c4e0a1ad7d39b316",
          "md5": "e566315c2066bcdb83ddf7acc3ef7f88"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iossimulatorarm64-0.5.13-sources.jar",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.13-sources.jar",
          "size": 25954,
          "sha512": "5c235fd22ca0d98861526a9d96ca33448d146d609e40ea0bb177aa5ecf44ae155d80ab8903587bba8bd995fd6269bff102cb8d19c89ee74ce355610ba431a696",
          "sha256": "9b0476b54abba699bd3ce18f77b08798daab723f2e7db295322b6c5856bc84ae",
          "sha1": "5dd45b1e757225ad9d55c6c5b334e5c7d4bdcc34",
          "md5": "ad53dbdde5b7cbd9aa0dc2def82e1413"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.13.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.13-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "865298b35136adb92bc4fbb83e9879300df40fbfaf090a836716774750de2005eaded3e87cd7ed6c640f2c56af81d63ccfaf1dbf24069401a28473d43d4c11f8",
          "sha256": "4f9f7d5eb0d84b9759af4fa3b5a5455f85656307b94205e54f9c8f2521772d78",
          "sha1": "c62cca3753d9dfc85b98f7e8ce375b6d6e26d8a7",
          "md5": "1d0a1d708c60bdf444d69f4e85201f28"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iossimulatorarm64-0.5.13-metadata.jar",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.13-metadata.jar",
          "size": 3747,
          "sha512": "c64a1fffb9f83de0b6daefc3558a48d96524a5c6e807ccff869c894ddf78d3a3121f2c91195a1feb3bba3f8a9496dbadb6ff7c206928622d41f6ce36a6e4822e",
          "sha256": "d27515975f70b0442eac2aeba118e3dde13301aa70f0be6fd3250403be910a11",
          "sha1": "3d21af223b9cf2a36b028a88370b3e17c87d4856",
          "md5": "9c058524e2fcb1263d5eb36c365d1a93"
        }
      ]
    }
  ]
}
