{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.8.0-rc.261/runtime-0.8.0-rc.261.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.8.0-rc.261",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosX64Main-0.8.0-rc.261.klib",
          "url": "runtime-iosx64-0.8.0-rc.261.klib",
          "size": 871199,
          "sha512": "b205bec8f10ca3dd10a2f611cdd12e4f7ca1f28c38dfb65bd03ad4d069d07d66fd13d0d5c6e3a69b9e0930027c894d61187b459eac74ccbdf9bd2973be97f2e0",
          "sha256": "b7fac440353e1e09e565199ce7159779cd55f925f66328f9a5cfb7415c9d0a5e",
          "sha1": "cfd4ca45214149c6fe7c6c4ae9e685b12dcfe5ad",
          "md5": "f8c35671fb0660abeecbbda91518b12c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosx64-0.8.0-rc.261-metadata.jar",
          "url": "runtime-iosx64-0.8.0-rc.261-metadata.jar",
          "size": 2428,
          "sha512": "bca426eb2ab694788922952eac3b8eec158d353b863d090c3457a5f108f7ea801d8cb96c28f30776d735b81eed7ee85ac06468d3d6666ed077f4cce269b9ae20",
          "sha256": "c98a1c63803340b472d69f4167c3862a6f84aece12b3a9ce1152673249df8405",
          "sha1": "db283c56eb4608fa96fe45f557a4a8d1828d2171",
          "md5": "4da61199977b7f75622ccc4a142cab37"
        }
      ]
    }
  ]
}
