{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.5.15-rc.67/flows-sdk-0.5.15-rc.67.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.15-rc.67",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-iosX64Main-0.5.15-rc.67.klib",
          "url": "flows-sdk-iosx64-0.5.15-rc.67.klib",
          "size": 100335,
          "sha512": "8015bfd43e67dbf5f26510a4d992d16d44e65adf997edae37e7ce6ba65599e5223cc4947e9d33320ac57fdf5f87bbc2d85825553fa1532a4e13408aa52055384",
          "sha256": "69afabc86b9d60748b4465cd25fef46c861a3c9224202e4b7b7ffaabb6826707",
          "sha1": "9601f66e8ec5a10279caa79e33391638787f2e1c",
          "md5": "328b07fc3f354139217a2794bb0d8b1e"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flows-sdk-iosx64-0.5.15-rc.67-sources.jar",
          "url": "flows-sdk-iosx64-0.5.15-rc.67-sources.jar",
          "size": 23136,
          "sha512": "be462d9c0d96a869cf97e56d4e240958b3e30e85dd92a6c7576d93eb6fe2c25b0222deb381a9493181920024375877fd2f1435f0a57e5a8d4e9a013c9dc44fc6",
          "sha256": "8fc06cc991257b0ce3d815b39f5b850e05d55124e5fa6e4fdbfffe3c825060f2",
          "sha1": "8e9960c05d62cee76d49967033917b03135abb9f",
          "md5": "237004cb39b0938dc5505e6bb8a9978e"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-0.5.15-rc.67.kotlin_resources.zip",
          "url": "flows-sdk-iosx64-0.5.15-rc.67-kotlin_resources.kotlin_resources.zip",
          "size": 61888,
          "sha512": "49fbc54346d19dbfc46b07e3d5683e0e54e7a817050c66915515fadcde060062a442fefa1f55a608d9377c01adf827efd4d56efa3d68d68f6b913e47b1318791",
          "sha256": "73a70f4f2f0479866e635b682c9c6be54454b2af8f171980cd65faf415402bf3",
          "sha1": "2083096bf651a4708edf2247296bf70fcc77bed0",
          "md5": "59d716aedd0d322e2c4a60e8d5cf76a1"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-iosx64-0.5.15-rc.67-metadata.jar",
          "url": "flows-sdk-iosx64-0.5.15-rc.67-metadata.jar",
          "size": 4019,
          "sha512": "12f8e3eaca2730a99f3e7e102e6dae66595c126ba953dea92aba0b39b2a71d09f20c20afb21d963f29ff8ffe2d92adee4f840af0e7a5fac1c257c6539ec9ff21",
          "sha256": "dda5801c2edeba330a3f9ad7d429a186a347ead09b93213ad81ed0f015882770",
          "sha1": "f4e82132e8b959cd2cc5f76dac0919efff692b24",
          "md5": "ef348147a3357f09d3de50c577af113f"
        }
      ]
    }
  ]
}
