{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.15-SNAPSHOT.3/flow-wrapper-kmp-0.5.15-SNAPSHOT.3.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.15-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.15-SNAPSHOT.3.aar",
          "size": 208267,
          "sha512": "20f11adf29bf125be2f7164ed1212c5768f21cb4f04a6c869a86c974b6db53c5e474ddc3820d1c4da965bef19c8842057a899205eec68b812b8019840818cf2c",
          "sha256": "728ec0a1cf0e8a9d1f51506bf8431c0edc7c598075e7d7c6e3053d7e61162ca4",
          "sha1": "3104a58d090dda8ab5df08ba8e7fae6fece2b358",
          "md5": "48110c558027fb8a3cb55cd14a5b7d6e"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.15-SNAPSHOT.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.15-SNAPSHOT.3.aar",
          "size": 208267,
          "sha512": "20f11adf29bf125be2f7164ed1212c5768f21cb4f04a6c869a86c974b6db53c5e474ddc3820d1c4da965bef19c8842057a899205eec68b812b8019840818cf2c",
          "sha256": "728ec0a1cf0e8a9d1f51506bf8431c0edc7c598075e7d7c6e3053d7e61162ca4",
          "sha1": "3104a58d090dda8ab5df08ba8e7fae6fece2b358",
          "md5": "48110c558027fb8a3cb55cd14a5b7d6e"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-android-0.5.15-SNAPSHOT.3-sources.jar",
          "url": "flow-wrapper-kmp-android-0.5.15-SNAPSHOT.3-sources.jar",
          "size": 40754,
          "sha512": "4faa81a0414c0b6fea71fb2129de1cfcdd12a0513d16820e5e45e6c01f16366c86e95e7e5182f138b7d2f0f646b5c47e390b7757fbcc2bb3b6a29e65c134221d",
          "sha256": "566ac40eb7806b1cc90e058e2a883502a8e82491477b22f1a3a75a552f4a13b3",
          "sha1": "18618468c9dc29c481ff6d7afe0cb071d5ab662f",
          "md5": "f2c79e9136f04742a4cd0a5bae558de4"
        }
      ]
    }
  ]
}
