{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.15-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-SNAPSHOT.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.15-SNAPSHOT.3"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.15-SNAPSHOT.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-metadata-0.5.15-SNAPSHOT.3.jar",
          "url": "flows-sdk-0.5.15-SNAPSHOT.3.jar",
          "size": 16145,
          "sha512": "1658d527acfff364029b7c8e1ac89a2fd0ac10168c5774ac4f57c4ed44210d4c0cbcb1d923e1538f63c79881b1bc8bbb50b106c24eeb5bb25d9d5c00897a0766",
          "sha256": "ae3b924bba74d482cc5ffb06b28e5b456ae100bed0c1cadfd62025336997ade1",
          "sha1": "76e06d2e348e371180e290e3463a94467b7b4efc",
          "md5": "9058e78ed9093d6a83faebb1ebef77c0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "flows-sdk-kotlin-0.5.15-SNAPSHOT.3-sources.jar",
          "url": "flows-sdk-0.5.15-SNAPSHOT.3-sources.jar",
          "size": 21637,
          "sha512": "c4f59a487ad50ec5381b88ece40cecfe7b4625de4a5b8ed4ddb046cac6b31f08b34eb7d54360b7706f6b6fe9d84763a1a61fc3d3189818fb90ad5d3aac3a0412",
          "sha256": "af0ec8b7713a604e93b705bbd1ecc43b8883a87377c76f6cb99846b9cb1887b5",
          "sha1": "15220c098447c3004c1201e1167f8bdeb06d97c3",
          "md5": "93eb707029b1506574cc06c3b9b7a20d"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flows-sdk-android/0.5.15-SNAPSHOT.3/flows-sdk-android-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flows-sdk-android",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flows-sdk-android/0.5.15-SNAPSHOT.3/flows-sdk-android-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flows-sdk-android",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flows-sdk-android/0.5.15-SNAPSHOT.3/flows-sdk-android-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flows-sdk-android",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosarm64/0.5.15-SNAPSHOT.3/flows-sdk-iosarm64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosarm64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosarm64/0.5.15-SNAPSHOT.3/flows-sdk-iosarm64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosarm64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosarm64/0.5.15-SNAPSHOT.3/flows-sdk-iosarm64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosarm64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosarm64/0.5.15-SNAPSHOT.3/flows-sdk-iosarm64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosarm64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iossimulatorarm64/0.5.15-SNAPSHOT.3/flows-sdk-iossimulatorarm64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iossimulatorarm64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iossimulatorarm64/0.5.15-SNAPSHOT.3/flows-sdk-iossimulatorarm64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iossimulatorarm64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iossimulatorarm64/0.5.15-SNAPSHOT.3/flows-sdk-iossimulatorarm64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iossimulatorarm64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iossimulatorarm64/0.5.15-SNAPSHOT.3/flows-sdk-iossimulatorarm64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iossimulatorarm64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosx64/0.5.15-SNAPSHOT.3/flows-sdk-iosx64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosx64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosx64/0.5.15-SNAPSHOT.3/flows-sdk-iosx64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosx64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosx64/0.5.15-SNAPSHOT.3/flows-sdk-iosx64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosx64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosx64/0.5.15-SNAPSHOT.3/flows-sdk-iosx64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosx64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    }
  ]
}
