{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.20-SNAPSHOT.3/composeblocks-0.5.20-SNAPSHOT.3.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.20-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.5.20-SNAPSHOT.3.klib",
          "url": "composeblocks-iosx64-0.5.20-SNAPSHOT.3.klib",
          "size": 348256,
          "sha512": "50eebfd10315a9e0644a18798624f1b82a97a1611beada213be162e2387ac4d9832b177bd3ccf8cd37a3cd72f37f659e5ac8948a00eff4411bed5ef02d894793",
          "sha256": "8a2deec24740eabfee9b7006e54e36ac8ed89c4cd57d96f89c013cb5b78e6b26",
          "sha1": "60c24c57c0103b0d8b4ee58214d26cb1ed79cacc",
          "md5": "4baa2d37f9c1b7e76c4149eff06d0838"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosx64-0.5.20-SNAPSHOT.3-sources.jar",
          "url": "composeblocks-iosx64-0.5.20-SNAPSHOT.3-sources.jar",
          "size": 62890,
          "sha512": "4a59e27f2a29435e1ef668a3f80f54b5579a027454fa3563ccbac9ebc4c20fea52d6a9c9b1073a4eea216c777bd6f08d9104dc1622d14a962c7a0f6555a52602",
          "sha256": "38494ba44d71f81e028eb09b8af0ae27a8b8ece1e6c8a7a7e9656f507a53fe71",
          "sha1": "e6e5c5547420fa3ae406d945fd6226ba56b60f9f",
          "md5": "e71bf7ca299e303fb36f875345bdde51"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.20-SNAPSHOT.3.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.5.20-SNAPSHOT.3-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "4a4a29918ef52c49095200ac2dd7210f9def516a3f79a3f9ff816c29fa4d6d1a4132d65ae474caa024eb091431de497b5690ab0b77b89d4e25b037825fa50b03",
          "sha256": "f3e5ee0c3a05cf5600a5ea97fedc8750dccf9924a73d7720f3e3373471285aae",
          "sha1": "82606f59c924dc385ebe7a992882582a72ca765d",
          "md5": "180879cc7597d4cc6deac4226d3a90bc"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.5.20-SNAPSHOT.3-metadata.jar",
          "url": "composeblocks-iosx64-0.5.20-SNAPSHOT.3-metadata.jar",
          "size": 261,
          "sha512": "5fc7f3c021c20889df7e1626f764c3898343bbd57c2fed9f53f81097cfc2228996cbfe51c2d21e3665bf5965e4199f431f192b7f9a75a9829b8b412777b348d7",
          "sha256": "70061e649996f6f938bd750fc81f4a04161358ba1e39c104154c7cbdd806bde1",
          "sha1": "de10114a0f6d319246dac8aca6da03c62888a08a",
          "md5": "714012f46ae8302b6b63423c142c28b7"
        }
      ]
    }
  ]
}
