{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-metadata-0.5.9.jar",
          "url": "flow-wrapper-kmp-0.5.9.jar",
          "size": 12297,
          "sha512": "488eca13010b682e18e8cd538f0dbcc263326b89e8137c268b2e9f8dd7435606addf0d31e5565f37a50d7d3f25e3a763306418e1f5726bdab8520078d36c0cba",
          "sha256": "c0f36a2c28378a547a2a0ac55837998c4bb3a9e90c6b1edc02ee075a5e98f107",
          "sha1": "ea66267f2c31c967f957d08312f95f3e1011b5f4",
          "md5": "76d179957fc6d418b1d03f645a2fdc7f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-kotlin-0.5.9-sources.jar",
          "url": "flow-wrapper-kmp-0.5.9-sources.jar",
          "size": 14147,
          "sha512": "ad0ae7b1eb33dd6e79d2b4818aa7f09ee6415b57f8b85d93483af6e86aa881c4c30d9378099e3e6edc4f054394c8ebcf9c01a502cdccbf60128a1bcff944c720",
          "sha256": "22083cb0d4d219a5875f053d863f6acfae925371c368bced7d903c4ce818013e",
          "sha1": "a0f68d569eee99e62132ce5b2e8c6d79e5098f28",
          "md5": "534d8605597fcab8a983f0fd3f6730c3"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-android/0.5.9/flow-wrapper-kmp-android-0.5.9.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-android",
        "version": "0.5.9"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-android/0.5.9/flow-wrapper-kmp-android-0.5.9.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-android",
        "version": "0.5.9"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-android/0.5.9/flow-wrapper-kmp-android-0.5.9.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-android",
        "version": "0.5.9"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.9/flow-wrapper-kmp-iosarm64-0.5.9.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.9"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.9/flow-wrapper-kmp-iosarm64-0.5.9.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.9"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.9/flow-wrapper-kmp-iosarm64-0.5.9.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.9"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.9/flow-wrapper-kmp-iosarm64-0.5.9.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.9"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.9/flow-wrapper-kmp-iossimulatorarm64-0.5.9.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.9"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.9/flow-wrapper-kmp-iossimulatorarm64-0.5.9.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.9"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.9/flow-wrapper-kmp-iossimulatorarm64-0.5.9.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.9"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.9/flow-wrapper-kmp-iossimulatorarm64-0.5.9.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.9"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.9/flow-wrapper-kmp-iosx64-0.5.9.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.9"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.9/flow-wrapper-kmp-iosx64-0.5.9.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.9"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.9/flow-wrapper-kmp-iosx64-0.5.9.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.9"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.9/flow-wrapper-kmp-iosx64-0.5.9.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.9"
      }
    }
  ]
}
