{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.7.2-SNAPSHOT.1/composeblocks-0.7.2-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.7.2-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.7.2-SNAPSHOT.1.klib",
          "url": "composeblocks-iosx64-0.7.2-SNAPSHOT.1.klib",
          "size": 456656,
          "sha512": "afb615b738ec67516b6078676bf74773fb9390afa1a5ad83652a2ae685047f13a6fec310903fb98487c76c909d7433d760b6d39c64225a47a4c341dc46b407da",
          "sha256": "91b34e8145020ce26477813043207e2c02f52265c81055d27472aa286435d3b8",
          "sha1": "218acdb00b7ed3e3d8814b7fe5d34de1192c6d3f",
          "md5": "207260a4643f6cc206d42a138f372a9e"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.7.2-SNAPSHOT.1.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.7.2-SNAPSHOT.1-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "edf6904c36a34471dff8d9c1a4b2fdf51bf8294a1277b47359eda1f58be3666cd963b9bb022deba5582c71c414bbe0925a11c8cd33cae46283e35b9ecd329840",
          "sha256": "756b6fc83d8230df769b77a9e4c02e6177322e783acda8c8ef56da375612514e",
          "sha1": "e4517e85618deaf17c747dde226c8e1b50d45e4b",
          "md5": "0f9ecb59d2f2c2ab52ec18704b89cf53"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.7.2-SNAPSHOT.1-metadata.jar",
          "url": "composeblocks-iosx64-0.7.2-SNAPSHOT.1-metadata.jar",
          "size": 261,
          "sha512": "46c1598e053055d834ae9fc329a9d7e562ecaa59758af5822970854e7ee3711b2869945d75e820a35c118c6da4527e2190984f30e71dbfaff2d8415e9f3ea55d",
          "sha256": "7036b1f6a8c11aba981451d7ad926d7edfd0801fb8f12af582feab8da96eb494",
          "sha1": "4e17234c7c0fee16baf4fbd0dae8c63e5b212f77",
          "md5": "707749f9162e2fea4fca7dbe7bda05a9"
        }
      ]
    }
  ]
}
