{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.7.1-rc.241/core-0.7.1-rc.241.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.7.1-rc.241",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosSimulatorArm64Main-0.7.1-rc.241.klib",
          "url": "core-iossimulatorarm64-0.7.1-rc.241.klib",
          "size": 235855,
          "sha512": "8a84c52bc45606a8a0d9a37fba040c942c63ecb0b61842f0372be0ad3506d715fb158df0bb407fb381e67f68a916b510b377246ee261a7f9889e6a4d7cd9ee35",
          "sha256": "e08aabd9fec76b1e463695e95c47e2c4d66fa450120a66e8737d9170f6391ac4",
          "sha1": "8322b4ce1d93693397412a2430f5aee9b6a73947",
          "md5": "5a1c0c98e641937f1ba0d0de74678987"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.7.1-rc.241-metadata.jar",
          "url": "core-iossimulatorarm64-0.7.1-rc.241-metadata.jar",
          "size": 261,
          "sha512": "f148cbaa2a2d69a60245861a3d9bdd002865e2c1ff1265887477af2a647fbda63d46db3c0764c905d4a4e08c67d445d5e29c4517dd9a93ee213a85c3f6dbdfd1",
          "sha256": "552a2432ef3a3e0b52445776b9bf3bbdfd5d60904edd557d6d868f27edbda708",
          "sha1": "8ac7f49fa76b521baa9b9765ec0ab0a24e19246a",
          "md5": "515ba24e0111ce32e7b3aa45db35f6ea"
        }
      ]
    }
  ]
}
