{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.15-SNAPSHOT.1/flow-wrapper-kmp-0.5.15-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.15-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.15-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosSimulatorArm64Main-0.5.15-SNAPSHOT.1.klib",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.15-SNAPSHOT.1.klib",
          "size": 238224,
          "sha512": "9e36faa95b4a7d8b7bbe6b3c5ccf6590fe160bd679979261bffeb68b1d4ff03e145dc12c55f9c890ca5c0a3b7f0c1893940443d7964c5bbe5fa1aaad96cae57c",
          "sha256": "4fface705f1c0ec9b719f2e7bbd6f7c0501596858ea9fee2d02b893d48f24d51",
          "sha1": "9f005c7b097348ad4333511b4cebbf3d377b99b5",
          "md5": "84bdcc6e653d8f9719277bc8025d9475"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iossimulatorarm64-0.5.15-SNAPSHOT.1-sources.jar",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.15-SNAPSHOT.1-sources.jar",
          "size": 41370,
          "sha512": "17ddcb32d2cd62337ff5e5fe42bed78504de4171cb0a1141ef8b71eda6c84e8d069b7f5995c5762d85e0e61f699d518fa24c6cf9d0439d9f64226caad52af17a",
          "sha256": "f1aacf7f83cda37f1712d653c2d804d77d47a82f3305cce73fab18d7b2e710cc",
          "sha1": "e9fee77b4c008dee4ad816e9613bacb0c7dc2537",
          "md5": "9923d7191b79dea98c7100e28a77386c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.15-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.15-SNAPSHOT.1.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.15-SNAPSHOT.1-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "31df754762598e4a7588b0c89795c1bba358599b454b0186c4703ed4b2457faa1fe93f04dd2545c771ab863b803fdd4e6f2eed1a5c9a65875db9a1a74a7830bb",
          "sha256": "6b86c1378af199ed3930237a963e381dea17ca83df7afdec7e7946df9ec6c107",
          "sha1": "bd49bc2af9cbf58170fb8a6f179fa5cbbd35748e",
          "md5": "d8cba7aa74684194eff22ff71582ab4c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.15-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iossimulatorarm64-0.5.15-SNAPSHOT.1-metadata.jar",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.5.15-SNAPSHOT.1-metadata.jar",
          "size": 3747,
          "sha512": "282bd03cc3d7c01e4c64753dfb28845d2ec04a95b7b5bedacdb774b019c7c167ec72fc9d8d6b732e25fbfe25fce1bd351a8d62cd28491c332f0b993a8dd21067",
          "sha256": "eac1d088e817f5c610796123e9b1ef27a9128b51308aefda8e4c666c18370799",
          "sha1": "2e42b2fd5db557897bc1cf5e8d44eeac8c7747c3",
          "md5": "049c6a21119a537015a86a727ad5953d"
        }
      ]
    }
  ]
}
