{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.8.0/composeblocks-0.8.0.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks.aar",
          "url": "composeblocks-android-0.8.0.aar",
          "size": 272970,
          "sha512": "0a63e9e7e6a227c1c63bec38eccb8e9709847c298ebeed3434493b3be08eb3b85fb13f9e511e8d90eb0c174bf55a3cf83fc66e248bc6f024d9d697b9d998e406",
          "sha256": "16a415f1a90e29a723116ad9531bfb63beff44bf391be3d4db2bbe3d285b9255",
          "sha1": "95d5359a700f2fa8dc51ff4ed9cbd1428a3e261d",
          "md5": "690cf84221d21c02328f47c8bc81024e"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks.aar",
          "url": "composeblocks-android-0.8.0.aar",
          "size": 272970,
          "sha512": "0a63e9e7e6a227c1c63bec38eccb8e9709847c298ebeed3434493b3be08eb3b85fb13f9e511e8d90eb0c174bf55a3cf83fc66e248bc6f024d9d697b9d998e406",
          "sha256": "16a415f1a90e29a723116ad9531bfb63beff44bf391be3d4db2bbe3d285b9255",
          "sha1": "95d5359a700f2fa8dc51ff4ed9cbd1428a3e261d",
          "md5": "690cf84221d21c02328f47c8bc81024e"
        }
      ]
    }
  ]
}
