{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.6.0-rc.170/core-0.6.0-rc.170.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.6.0-rc.170",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosSimulatorArm64Main-0.6.0-rc.170.klib",
          "url": "core-iossimulatorarm64-0.6.0-rc.170.klib",
          "size": 139283,
          "sha512": "aed690262a7124e298f905390510d670d77ae05e79c90363f1fa007aa237a9ac95d6935b1de9ede3417aab5019299c9c32d8f9ab6425b4ab46cdc19e108f39b9",
          "sha256": "f90ac2e592c4696e767603cb5820e59392726e08d5d09021dc762c4d3e247ce5",
          "sha1": "b63717d6c24ac600ed2319ee1754d6bb019d3e56",
          "md5": "81787398274b3975624b396feb9292e3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iossimulatorarm64-0.6.0-rc.170-sources.jar",
          "url": "core-iossimulatorarm64-0.6.0-rc.170-sources.jar",
          "size": 21237,
          "sha512": "6defbf474015ff1c5cb27250467c9076137faf32cf0215814b5424a1dcf6ac6d86dab4740cdb3ef60743966569e3280189e8656c32d09594a19c3a2cde9723f0",
          "sha256": "7fcb4b8742a2cd2bcef410a76db70c4c78c0a586e6d8ae25fcebec87e3cc3f11",
          "sha1": "6f4996116706a63834328b580fe7113520080310",
          "md5": "b423da40e6f7185f5c8899bc20e554cb"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.6.0-rc.170-metadata.jar",
          "url": "core-iossimulatorarm64-0.6.0-rc.170-metadata.jar",
          "size": 261,
          "sha512": "e51cc65b1ffd069fa2a449e449ed9e05a778a5f5b6c12e256b30047e3fd19ab8ea483661f66664c156577c39479842db7c8bfb3ea1979ddc4dafe2fc928ef27e",
          "sha256": "7b10b66f12bbce996d7373754523679e6cc0ca7772c0d0230cd00b3ad23789a3",
          "sha1": "755227eeede1a31cb379ed9958b18048942d4a21",
          "md5": "16922454e171b46acd5f5dc21eb93c73"
        }
      ]
    }
  ]
}
