{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.8.1-SNAPSHOT.1/core-0.8.1-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.8.1-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosSimulatorArm64Main-0.8.1-SNAPSHOT.1.klib",
          "url": "core-iossimulatorarm64-0.8.1-SNAPSHOT.1.klib",
          "size": 244457,
          "sha512": "2ab75e4ce440a614486957affb671e35b4be553d3f3f615b0c8406a18e914e2a4576f51a77cf8778ba50754b4b38635564a7a515daa9e10f895fb489aa0b2153",
          "sha256": "0759bc00286d59f61a76ab579759d228e7480db6aac12f3b5ae47b1b0753bd17",
          "sha1": "b6a40848526445b8fd38855849af9fe9176cc2b6",
          "md5": "051165e9e82ff4065bdcaff042db10d4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.8.1-SNAPSHOT.1-metadata.jar",
          "url": "core-iossimulatorarm64-0.8.1-SNAPSHOT.1-metadata.jar",
          "size": 261,
          "sha512": "fc72f2b204cbaf8f304cb54ad227c77593af6b57bc2bd0727b6e815de56b4059273dced140c685fd44595f40f0b9279bda546045d0ce9f66797ae1e346569bf7",
          "sha256": "af8255211d44a38067dee3f438976d45933c02a212341f8b860a084584a78f8e",
          "sha1": "82b5dd24e09896945a509772cdd2efabd1ec9eae",
          "md5": "a8a8de2c3527f50bbbc5d2764a0a2018"
        }
      ]
    }
  ]
}
