{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.12-rc.30/flow-wrapper-kmp-0.5.12-rc.30.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.12-rc.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.12-rc.30"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosArm64Main-0.5.12-rc.30.klib",
          "url": "flow-wrapper-kmp-iosarm64-0.5.12-rc.30.klib",
          "size": 144406,
          "sha512": "e9846aee3fc19e34e0ab6b7030d64c8c865d97e98c88349aa0a8d99d0c23afddbe46395a8d8e6d579aae1d8f975dad58f277aba1010827e67fe45cdb58521717",
          "sha256": "8ac497a4f3220233c7f5cebbef401abf574ee8212341a184ff074b2e8e628067",
          "sha1": "2154b0e81c5b680204d3135fb810290826e90b17",
          "md5": "4b247a27ae01d7eeff00c329218f9393"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosarm64-0.5.12-rc.30-sources.jar",
          "url": "flow-wrapper-kmp-iosarm64-0.5.12-rc.30-sources.jar",
          "size": 25765,
          "sha512": "bd1c2988293d1400594e5b02772862bf5c66262d6d8828dd9bab8ae8727d18a20a7029f42ae761ef6e024eaef10944f2fa8133dc7a5b283d9a05633fa18773dd",
          "sha256": "8ef4fcdd8d2310764c28caa3b930af4ba31530dbaa0ade7b53eec6e3ee35296d",
          "sha1": "22c657fbb4c551e0e27fae4db868c70f5390ea28",
          "md5": "67a9574f910fc8ee0ce15327c964e5af"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.12-rc.30"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.12-rc.30.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosarm64-0.5.12-rc.30-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "06839980960871ce85ec7ebd37328a71123a24713bd9c768f6caf09f12c5c63df0638abf7d5835cad59dc2ae4ddd5d8abce2fa959b560dd1cc7d55333dcd8acc",
          "sha256": "70de54b75f7bf2e08a5e2f36ef3702c18272dfeb3814ac1f0d3ff2197c9ae1ac",
          "sha1": "91928f04d950783b5e630c57e99164d500693af3",
          "md5": "b0cca7aaa688e3489480e4bdf329e681"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.12-rc.30"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosarm64-0.5.12-rc.30-metadata.jar",
          "url": "flow-wrapper-kmp-iosarm64-0.5.12-rc.30-metadata.jar",
          "size": 3747,
          "sha512": "c7ee32e0c414aa48865b04d1bfcfaafbe818c2c62ff47ee177ec3206e708aa0c1637b05ac5ccf736a780b530c61a818e8706c0bf2f38f8c15332149ff089fe77",
          "sha256": "f589c180efb72227d4ad83fa22dc7a4f2802845f6e1ca7f79494e54f7f58c58e",
          "sha1": "4c9d0a4d088975856eabb9ba31a10cbbe3d7b009",
          "md5": "5a86fa3cb72a9da45d3c92b8864f4312"
        }
      ]
    }
  ]
}
