{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.6.0-SNAPSHOT.17/core-0.6.0-SNAPSHOT.17.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.6.0-SNAPSHOT.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosSimulatorArm64Main-0.6.0-SNAPSHOT.17.klib",
          "url": "core-iossimulatorarm64-0.6.0-SNAPSHOT.17.klib",
          "size": 101634,
          "sha512": "9c400a1c7128bc02011d5d29d2e0bc097bc71c03989bbaca5a7af2d860d27c2e3e15b0d65c4094b27b67ad5f18121428e7ba1ffd56a4e02673b2baa105274ec9",
          "sha256": "023be5334a14dfd2da73a221dcb514a699a878e3d87e04c085f72fb500de0972",
          "sha1": "190100a606c72e9c95671160849e0af9f5f28772",
          "md5": "de39d466ebd26b6349e2784ba26980cc"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iossimulatorarm64-0.6.0-SNAPSHOT.17-sources.jar",
          "url": "core-iossimulatorarm64-0.6.0-SNAPSHOT.17-sources.jar",
          "size": 12871,
          "sha512": "9384b55817f88f910ec57688f568f23c7334e431ee50978b193d247dc6dc8604297381b30757d73c8c22a3ea4f3da34334acfaf4bfa1121de726f0027e0f3235",
          "sha256": "cbafd42c100bb7358370dc203cd61d4041cd683b48d69db2eda1e6514b18e617",
          "sha1": "20061d10ddcd97c4bb4a9c49602da7d79000e539",
          "md5": "337280c1de2570f705980fc4fe7f6037"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.6.0-SNAPSHOT.17-metadata.jar",
          "url": "core-iossimulatorarm64-0.6.0-SNAPSHOT.17-metadata.jar",
          "size": 261,
          "sha512": "129e16cc2ff8a0acf12b29585bd3db77bededd72eecb1d1f405f55f037cd5a92562689dd7f0dad30d47ee56ad79815962c6f266776f42e968111d76fcbf0eb31",
          "sha256": "a820cb9da1b8b9a88d883dd0775e8b8bda0e2196f991f6a2acafe6bad82c86c2",
          "sha1": "37d140f8aa26761ca9bd7104c2940f5455d9485b",
          "md5": "32633ccbe3c5093ae44bb309b564662f"
        }
      ]
    }
  ]
}
