{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.7/flow-wrapper-kmp-0.5.7.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosArm64Main-0.5.7.klib",
          "url": "flow-wrapper-kmp-iosarm64-0.5.7.klib",
          "size": 78869,
          "sha512": "abf47bfea385cc6017c5ed89c621f16c3c1ecff8d6e17935dcb8b69353fc4c425964adae349d93c2b13223d8ea510355698d3bbf786b7b1f0740311787956004",
          "sha256": "3bb7c27137f50c99730b3c62d5ba4e412d153bfff186db3415b310a5f346e2f4",
          "sha1": "4008f1b3d630e901c9bc6874b4e6288a3d2d2090",
          "md5": "3db496cafb0a1ff0b2370c046f5d1752"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosarm64-0.5.7-sources.jar",
          "url": "flow-wrapper-kmp-iosarm64-0.5.7-sources.jar",
          "size": 13343,
          "sha512": "faf15bafb088e5adf4bf600bdcb832981f429239e86b357c75a03732b2ef230ad1b6edc9ab83f860756cdd8dd207cb94bb39e67340a9e99c1ecf17762b09d381",
          "sha256": "6c817fe1c0f685032e08004078f365103bb0fc7b50e7296ac2e156b87cd7769e",
          "sha1": "abcb6dc491a27e2ca6c563f43cc30d90e050bd40",
          "md5": "545d4a6a976dd33fe0dec26e3e1af158"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.7.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosarm64-0.5.7-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "f1d315fc4c3e93b9b90acefb48110c3ae947f19c749dd353f6d0cb049d91cfbb1c32abcfacc58c3e0dd3e5fce34d139de92d82bef765d400c73851beb380ca9b",
          "sha256": "b66de999f2cadb190ebcbbf987a08a35c9959af24396afd89a8d22caaa307b4a",
          "sha1": "bd4f29577fa1b56bd5bce73841d69d42b12e6664",
          "md5": "1b5c84d33aafb5ddd391079411a684f8"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosarm64-0.5.7-metadata.jar",
          "url": "flow-wrapper-kmp-iosarm64-0.5.7-metadata.jar",
          "size": 3010,
          "sha512": "739e25c8d414569dcb31f0fb78b3bce9617ad976fd759eaebe710761e8356857edf669c462ca53c21ee6f107178c49dc9f6adfb1305899c8d5581db0d32aa961",
          "sha256": "85b683c9214a05c12866b3a07b8df680d78aedbf3f31baa844a1ca34aea06f5f",
          "sha1": "e8afb10f78e777edc6f0abe1b7e65c23116ffdec",
          "md5": "54d6e80ef174900c2c931d944f36335e"
        }
      ]
    }
  ]
}
