{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.5.18-SNAPSHOT/flows-sdk-0.5.18-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.18-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-iosSimulatorArm64Main-0.5.18-SNAPSHOT.klib",
          "url": "flows-sdk-iossimulatorarm64-0.5.18-SNAPSHOT.klib",
          "size": 107608,
          "sha512": "492fa195e18c836655777e89aa7f48377522c5e2733b8214434bc3d6bf95f7dfd48144642faa24f5971fd9d4eab35798314f873d908270df146e161eb5a2df65",
          "sha256": "9a5f8608c2ab405082f9cd9a01a522ac40f1defed014125ca0c43992df68375c",
          "sha1": "a2147c0ad8148841b9e18a63e025bdac2bc6b364",
          "md5": "d0745541942cadbd276364d9a7657d64"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flows-sdk-iossimulatorarm64-0.5.18-SNAPSHOT-sources.jar",
          "url": "flows-sdk-iossimulatorarm64-0.5.18-SNAPSHOT-sources.jar",
          "size": 24494,
          "sha512": "fb6375bceb411f1ef0408a1007d60f5f10dba846f9ab990dc0bb502935542ef718449a312cba4fefb6a04d8f2931a9aad11fdf3dadaef2e214808b54b19f548b",
          "sha256": "959df4fd6a4f3c8f840896d147a399eec49297b2dfd60ce0ed506c5e52f25528",
          "sha1": "8045936d9a88aa76012af781b3b9b5c8bb7949b3",
          "md5": "d77c94dfebd8052333a68b86ef0a05e1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-0.5.18-SNAPSHOT.kotlin_resources.zip",
          "url": "flows-sdk-iossimulatorarm64-0.5.18-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 61888,
          "sha512": "0a428caf687aa059fd2ecedabb6b9cc1af55c8aaca7e642df8731292839482d51c6fbbb39f6279c1dc86ce799f545ebc49d47925331656734d78ac6e104018db",
          "sha256": "aebbc46a1cebbe5ca05a44887e2dc8a2c224c1186b62330221f6abeb0725b1b0",
          "sha1": "8f762e031a128e6d4cedac8fc2b118c582b98505",
          "md5": "ed2a08ba46a6b585a4fae11592852093"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-iossimulatorarm64-0.5.18-SNAPSHOT-metadata.jar",
          "url": "flows-sdk-iossimulatorarm64-0.5.18-SNAPSHOT-metadata.jar",
          "size": 4019,
          "sha512": "5fa8203662aa2f6d4ff63c3ecccc424d7e709a79cc61917f9e67ca9c34a463fa7363be2032c38e3d8abf49a231cd37ab7514f617d6e8a384db2561989d1a8f46",
          "sha256": "8c39be46ec3f4ef3ec1f27b3be6c17b852877f03413947f4b444d56342b40fe3",
          "sha1": "071739a68d1ca5c7c11e09100fb78dad36f16e5f",
          "md5": "f75eb47cf3456ac589ac01e08a496818"
        }
      ]
    }
  ]
}
