{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.15-rc.67/composeblocks-0.5.15-rc.67.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.15-rc.67",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosSimulatorArm64Main-0.5.15-rc.67.klib",
          "url": "composeblocks-iossimulatorarm64-0.5.15-rc.67.klib",
          "size": 289477,
          "sha512": "83e43eb3df22eed25b591f97505a08c6cb20f2ad83a827725d93fde6e28ff7c0e24455af7f4cdf03501ae8ad5e0f0ed9649993138291474878e1843c5ac468f8",
          "sha256": "8b3a86bfe5c3735649a70a86d39f7c730e845911bbcfbc9fb45aa278ea7147ca",
          "sha1": "ced3921b88c87bd24a2b2957dca4aef4655442b3",
          "md5": "5012e42db957ecab005de282cd5e66c6"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.15-rc.67-sources.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.15-rc.67-sources.jar",
          "size": 50081,
          "sha512": "b60a2a9c8304fc3ecbd7d2f49e895c5e20e4a74c768cf0042e5119cf0b5e08f66f008bd6fc09d50733532b8b7938f77dec33ce52691cc9449915384ca40ff33a",
          "sha256": "2af9a587ffe1a63c4277b186a78c3e302e593feea472ede909dccd6da6cbc30c",
          "sha1": "d8d746660b6af9546a490cc78b37a4ab3de741c7",
          "md5": "21b1da1f823f65926e930b93509889bf"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.15-rc.67.kotlin_resources.zip",
          "url": "composeblocks-iossimulatorarm64-0.5.15-rc.67-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "d085b47fb293d28ee42c6ab4a3b1ac879e126ae80c9a26477d760087950be1aa09a0af3ca0e2fabbdba1bd9eab8676eb31ea23c2ebfa559c15fafaf5bf216aa7",
          "sha256": "e6f64f7e20309319e7eb3c64c0b5679b85d73962eeba18c67c739b1b4d52c010",
          "sha1": "19a987b8def5d320fdf77a9e00b0b0f702145f37",
          "md5": "80ee28e5f432fbc05f0d29cc16820d89"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.15-rc.67-metadata.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.15-rc.67-metadata.jar",
          "size": 261,
          "sha512": "7f6a6bb0885e647c55142fdf1fe28a99fba7a4d1cd4d2be5ee5956c5eb495d78f3e1e54857de2693111c569efa318307a5ab744b03873a3b40688815db21ba9d",
          "sha256": "a9f9a0b7d0c05e35e7ea037c926540a89441d546b0d4fc297b300ca985a7081d",
          "sha1": "ff64ba5ff4d343e3bf3388eaa9fee44b46c63c1c",
          "md5": "4ac3426a916a7ca0d0b8daadd31e4cb6"
        }
      ]
    }
  ]
}
