{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.5.17-rc.109/core-0.5.17-rc.109.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.5.17-rc.109",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.5.17-rc.109.jar",
          "url": "core-jvm-0.5.17-rc.109.jar",
          "size": 160857,
          "sha512": "16ce40a769b83397ff7c1072cbe1fc00407f6291e123b761ac1461bfe2650e4b5af5c693c12f0bf364e4c77634833aa769fddce070d3b49a04fe0ed4291e851b",
          "sha256": "b9158f6e1d867186359393cf5c2a32dba93e51c58658a1694e82f4a876058e62",
          "sha1": "bba6fb28918814f8d20ca865c6151db99870582a",
          "md5": "590f8260cd73290b38f0af62a58631c6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.5.17-rc.109.jar",
          "url": "core-jvm-0.5.17-rc.109.jar",
          "size": 160857,
          "sha512": "16ce40a769b83397ff7c1072cbe1fc00407f6291e123b761ac1461bfe2650e4b5af5c693c12f0bf364e4c77634833aa769fddce070d3b49a04fe0ed4291e851b",
          "sha256": "b9158f6e1d867186359393cf5c2a32dba93e51c58658a1694e82f4a876058e62",
          "sha1": "bba6fb28918814f8d20ca865c6151db99870582a",
          "md5": "590f8260cd73290b38f0af62a58631c6"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-0.5.17-rc.109-sources.jar",
          "url": "core-jvm-0.5.17-rc.109-sources.jar",
          "size": 19168,
          "sha512": "fd197d938de534a7e41f8395587df54772e10d2f8875d12969b2dd0d7425d4ed7377caf17a1fc04775d9de6b2c02837252e82757498d401437e0eba129c67251",
          "sha256": "101df60d3d5497a6ca9b4c4aceb098b2c32c45306d0f3efd03838bd093c7c1fa",
          "sha1": "d16fc10cfadec7e60926a0fba06accd218f78c66",
          "md5": "d0fa1b1c212201641c53528a18d6d2ea"
        }
      ]
    }
  ]
}
