{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.5.15-SNAPSHOT.2/core-0.5.15-SNAPSHOT.2.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.5.15-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosX64Main-0.5.15-SNAPSHOT.2.klib",
          "url": "core-iosx64-0.5.15-SNAPSHOT.2.klib",
          "size": 121196,
          "sha512": "9962e9119fa5bc6f743c44ca64a6a59a9eae13020d11412427fbe9b5a0394f029f2822ebff125a5421caa31ef271f5e6e923b2e8065d94c36d81c2da9da0f21d",
          "sha256": "7609920b3f5ca8c25e6d137e741042340f1dc385bd04790a6573c4ad5cdc210b",
          "sha1": "d81671194c0d8e2252bcb4e903b49e8584069023",
          "md5": "b6c627d6a589600a28464477dddf5d5c"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iosx64-0.5.15-SNAPSHOT.2-sources.jar",
          "url": "core-iosx64-0.5.15-SNAPSHOT.2-sources.jar",
          "size": 18169,
          "sha512": "f8335fc9598e964a6ad61d5a562f5f49a9a4ce89ead746c9ec3d13d2b9567ee18775e22ce47a4fa2ddf0fc50f73e835f99560a109a7ead9f679fef87895ae5b4",
          "sha256": "ef43d06e0850a567869b1f021d174c2f21b122579a07a1ca04445d4c2ba8a084",
          "sha1": "a23c78c369e3ed09ffcec4b159e75b5b0b9d53a1",
          "md5": "1781c02ee9f043240940dcaffbf6e679"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.5.15-SNAPSHOT.2-metadata.jar",
          "url": "core-iosx64-0.5.15-SNAPSHOT.2-metadata.jar",
          "size": 261,
          "sha512": "21f83f601d813cb6411c5c2be65e97b957698dfb486feb163d0dcde12f4c62f3b51d1dd2ea31b860781ea09ab1afdcfe21ead36d282f1984e2fcf8d18c9f19a4",
          "sha256": "7a2eb4307850e0de258955a6b28ae602c8ec6847e6d44df624890eef587cc09f",
          "sha1": "d2b8c808151b456b18caa24cbe49d8b01a12225f",
          "md5": "42d4aa7d486fdf0eef6857d4f9779704"
        }
      ]
    }
  ]
}
