{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.5.20-rc.141/flows-sdk-0.5.20-rc.141.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.20-rc.141",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-rc.141"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.20-rc.141.aar",
          "size": 194606,
          "sha512": "fd22c2c02fd4e130fdfe8514ec15fd7f050fe94df416eae1bb6ba476c638687dd342a8aa7d2055e95cc840463ec46cea2d38ce55dedc773878dc38ad436d6b42",
          "sha256": "9a57720211ab5999b929ba5caf90ab9cd9c9912b1f5bdb774002cadf6cfb2a35",
          "sha1": "9eb54a2c365b9f1caf3c19247021a71fbecf94e0",
          "md5": "df7aaa45649a6b6b21243f89781e4ce8"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-rc.141"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-jdk",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-rc.141"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.20-rc.141"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-optimal",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.20-rc.141.aar",
          "size": 194606,
          "sha512": "fd22c2c02fd4e130fdfe8514ec15fd7f050fe94df416eae1bb6ba476c638687dd342a8aa7d2055e95cc840463ec46cea2d38ce55dedc773878dc38ad436d6b42",
          "sha256": "9a57720211ab5999b929ba5caf90ab9cd9c9912b1f5bdb774002cadf6cfb2a35",
          "sha1": "9eb54a2c365b9f1caf3c19247021a71fbecf94e0",
          "md5": "df7aaa45649a6b6b21243f89781e4ce8"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flows-sdk-android-0.5.20-rc.141-sources.jar",
          "url": "flows-sdk-android-0.5.20-rc.141-sources.jar",
          "size": 32044,
          "sha512": "96bf883a1fa13961d20901bce5f1c2b7c66bfa627bb1cfa30ee3f215517e4ddafeebff1d610b163405974ec626814598bf9fe45e07b61efa9871e143d2f70a78",
          "sha256": "7f61c3e6797cacf40576d1401a84615419757c0e0b524367d9c150309ca75b0a",
          "sha1": "4b89a36a974f1436f3e2210e4c929e699ab8c410",
          "md5": "b930374bed7f6e013a8b1612ef967d6f"
        }
      ]
    }
  ]
}
