{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.5.17-noscroll-SNAPSHOT.1/core-0.5.17-noscroll-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.5.17-noscroll-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosSimulatorArm64Main-0.5.17-noscroll-SNAPSHOT.1.klib",
          "url": "core-iossimulatorarm64-0.5.17-noscroll-SNAPSHOT.1.klib",
          "size": 127470,
          "sha512": "c8ecfefc6eb010f9a2710df8f32e5fed97d304a94e993c1a9ebf4d4380a0e3b525226e23930de2027d1c35938d8f7ee49eef12be52070cba0c6691b6078dba93",
          "sha256": "17a96ae407866d4cbec00f112787212e2f51205872d817cdff7a34e7a926e3f2",
          "sha1": "a1983bd554c96863044474cfa0eb8564e3609bbc",
          "md5": "373e960a8b1e368ab7970439c93b1b9d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iossimulatorarm64-0.5.17-noscroll-SNAPSHOT.1-sources.jar",
          "url": "core-iossimulatorarm64-0.5.17-noscroll-SNAPSHOT.1-sources.jar",
          "size": 19168,
          "sha512": "fd197d938de534a7e41f8395587df54772e10d2f8875d12969b2dd0d7425d4ed7377caf17a1fc04775d9de6b2c02837252e82757498d401437e0eba129c67251",
          "sha256": "101df60d3d5497a6ca9b4c4aceb098b2c32c45306d0f3efd03838bd093c7c1fa",
          "sha1": "d16fc10cfadec7e60926a0fba06accd218f78c66",
          "md5": "d0fa1b1c212201641c53528a18d6d2ea"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.5.17-noscroll-SNAPSHOT.1-metadata.jar",
          "url": "core-iossimulatorarm64-0.5.17-noscroll-SNAPSHOT.1-metadata.jar",
          "size": 261,
          "sha512": "75525f368f4a78ab866494716355c95db63beb63a954af96a05333068729a0d60d392f7b916d42fd687a28a9b7bbead56c06dc06753fc7f82f0092962c6a01f5",
          "sha256": "4f9124ef26d1fb1e0e0d3279672202f6bdf1ff140399acc6027ea50961c2793d",
          "sha1": "c2e148287c1e0f0d8de70f0c879c8c867cd5ddca",
          "md5": "28c7e7ed108317a4932fbf26ee4e600c"
        }
      ]
    }
  ]
}
