{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.8.0/core-0.8.0.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosSimulatorArm64Main-0.8.0.klib",
          "url": "core-iossimulatorarm64-0.8.0.klib",
          "size": 244457,
          "sha512": "2ab75e4ce440a614486957affb671e35b4be553d3f3f615b0c8406a18e914e2a4576f51a77cf8778ba50754b4b38635564a7a515daa9e10f895fb489aa0b2153",
          "sha256": "0759bc00286d59f61a76ab579759d228e7480db6aac12f3b5ae47b1b0753bd17",
          "sha1": "b6a40848526445b8fd38855849af9fe9176cc2b6",
          "md5": "051165e9e82ff4065bdcaff042db10d4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "core-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "737b39981a5d7d6e5a801a9faa7086948e25bea2f5a69c5458ea289c373bbc44a83c5690bc8d178efb7b097b9abf376cc3be75be4f439f9798d1443e8d85a0b6",
          "sha256": "d7a87d98a4958b2711ee2012187cf126dfb97c583c2b4f457f61a277119c0524",
          "sha1": "bb6c86062b29eb9e7dcbbb93501da9118d85e13d",
          "md5": "47c0cd38fe93c43b57f2f257886d3757"
        }
      ]
    }
  ]
}
