{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.6.0-SNAPSHOT.16/runtime-0.6.0-SNAPSHOT.16.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.6.0-SNAPSHOT.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-linuxX64Main-0.6.0-SNAPSHOT.16.klib",
          "url": "runtime-linuxx64-0.6.0-SNAPSHOT.16.klib",
          "size": 573924,
          "sha512": "fdd139f3e50f2e1496e838825fafe4f4657346e90571f5abf9b21e4f6b5441ac88b970fd8655cf2b0c7440c65256c60dd5915eaf27632c7ddb056c1df9afc57d",
          "sha256": "b5190ba7e496e72ed93c3d203ee3e685c8845fb2f6280e1f5b5206674b6b51a1",
          "sha1": "00ffd8f1fc30497b17c1dc27d28848cd24b3e812",
          "md5": "400a4c867576c8569b62163fc2831462"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-linuxx64-0.6.0-SNAPSHOT.16-sources.jar",
          "url": "runtime-linuxx64-0.6.0-SNAPSHOT.16-sources.jar",
          "size": 43187,
          "sha512": "44ec7122805db3e51651062986179bb1f65b8730566a95859de4aae3d61ea6bf5b982eb803241509729cef655e2a9b233e479419e40cc9be7dd04617967b9f5b",
          "sha256": "3bfe48980278c57164ee0f03677327a524aeb277235447ccd4182776703b9008",
          "sha1": "d9303d93a234d4501c6a269e2a632f59d3af020d",
          "md5": "d08efece3809d2fe03dd23dcd68037c7"
        }
      ]
    }
  ]
}
