{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.7.1-rc.241/composeblocks-0.7.1-rc.241.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.7.1-rc.241",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.241"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.1-rc.241"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosSimulatorArm64Main-0.7.1-rc.241.klib",
          "url": "composeblocks-iossimulatorarm64-0.7.1-rc.241.klib",
          "size": 456735,
          "sha512": "3cfca3b95329ad82a6c9df800b5969b46d59b62b9d31c099eded6f6be8c6508611921ebb27550f3d067c0929c8a528ff03722a41c1d6f10c8606ae78b6fbf58d",
          "sha256": "efe19eb1c86a11be1ca857e3c029d7403ac527201680fee51e9c9a300bc4d91a",
          "sha1": "c005f6c1b9e114c7272fc3676bd3e7017e5a61c7",
          "md5": "d0c1c3316e6739bb0a72dc545688969a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.241"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.1-rc.241"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.7.1-rc.241.kotlin_resources.zip",
          "url": "composeblocks-iossimulatorarm64-0.7.1-rc.241-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "6ba86fe86614c3b9fbbe32dbf15289a5624b4c9052261a0ed95fba276f2d74c6fd2139c26796ebbaa498099cdbb88fb206a6a0f9d083ac73412a2c219d6ffc02",
          "sha256": "38551a9ca250729f748b9cd5e2080caf44627e737583419d4edba80b850a2a70",
          "sha1": "53080b390ef063b6a83cbe803f99305028a18e7b",
          "md5": "9956c78cf51fe640694914cfef667383"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.241"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.1-rc.241"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.7.1-rc.241-metadata.jar",
          "url": "composeblocks-iossimulatorarm64-0.7.1-rc.241-metadata.jar",
          "size": 261,
          "sha512": "84ce73aa9fbe10903da3e5dbe5201cf7b13521df6bedcffc892fab6c0b562b3dadf24f97cbc30ea84c2ee0bda65cd4413226b26348a0bb6b3860d288d7e72c18",
          "sha256": "2882073e63f65cd784a9f8c30e6b5eb4d761c14001b74faa467d37e70d0fd9a7",
          "sha1": "1086fc75192a198e6cfd385e764f6b94342ac5fb",
          "md5": "cddbd24f24ec50400f82cd16daf3bf9d"
        }
      ]
    }
  ]
}
