{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.7.0.1/composeblocks-0.7.0.1.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.7.0.1.klib",
          "url": "composeblocks-iosx64-0.7.0.1.klib",
          "size": 391297,
          "sha512": "9dc1b8de98486ddd849dbd346fb2d8ed70ca73332fcb9b55b1992fdc04fb58ef83db1b3eddd59b8e701f4b1fec1f5253eeaaa30cfd0842a9f61dd81ae16907e5",
          "sha256": "8d1326e36a7ca1ce07a242b71ae9c051be900c534aa55a9e2eadf073b0d20e79",
          "sha1": "f9c16d85151a52cd5afd4b0211c61c51e228d9e3",
          "md5": "6483c34f3f962b754d61ebc0815f8c05"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.7.0.1.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.7.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "15f1f8e8ed4eda107e55433955f0fa924e4c6689cda45f7f195e645b0005aeae7eca886c00fca6e521739e1310918a6b8e448a476c4d2e3d31f2b785b94a8e53",
          "sha256": "3252b1eeff612dc1f986b915a394dc05f261fb2af8f8618344e45349223bd1ef",
          "sha1": "298d24afe2151f9b275f5ebe72a9eee9bcc6a769",
          "md5": "f453ec8864ead46894513788e1ed41d3"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.7.0.1-metadata.jar",
          "url": "composeblocks-iosx64-0.7.0.1-metadata.jar",
          "size": 261,
          "sha512": "c5e4a37ed1908cbcfb7881acdaca4face5dfef7bf62c8f054d24eee1062e55d19d5ee6474bb9f57cbceab17f12adbebc69e7a1f6ee406883064411be2e9356ac",
          "sha256": "6dff3daae10ffadc05c356d813f83b3e9eb0348566604e9b2de82bbdab74845b",
          "sha1": "1e1c9cfcba3bc4a2f39dd802ce16876b8c3b95bd",
          "md5": "37b19fd399af5c20067eb8bd2b18491c"
        }
      ]
    }
  ]
}
