{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.7.0-rc.186/flow-wrapper-kmp-0.7.0-rc.186.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.7.0-rc.186",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.7.0-rc.186",
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.0-rc.186",
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.0-rc.186",
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.0-rc.186",
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.0-rc.186",
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.0-rc.186",
            "requires": "0.7.0-rc.186"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.7.0-rc.186.aar",
          "size": 160475,
          "sha512": "0359b60776cfce0316b48f6002ea6f0797c57ace27a4b43a78b487d649473546fac1b1ff93d8b3027c9978c8c6ab8ff7a167ea2a76b62e68d6b2b79597a348dd",
          "sha256": "95de765556d033fe0e1ff6a84c4eba7e3e9d043b9d483015b7c005f679fc11df",
          "sha1": "ae5d1631fbcad970be03e31337af32105d1ce426",
          "md5": "5eeb8007266cd98f34ad43fbb3367586"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.7.0-rc.186",
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.0-rc.186",
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.0-rc.186",
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.0-rc.186",
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.0-rc.186",
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.0-rc.186",
            "requires": "0.7.0-rc.186"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.7.0-rc.186.aar",
          "size": 160475,
          "sha512": "0359b60776cfce0316b48f6002ea6f0797c57ace27a4b43a78b487d649473546fac1b1ff93d8b3027c9978c8c6ab8ff7a167ea2a76b62e68d6b2b79597a348dd",
          "sha256": "95de765556d033fe0e1ff6a84c4eba7e3e9d043b9d483015b7c005f679fc11df",
          "sha1": "ae5d1631fbcad970be03e31337af32105d1ce426",
          "md5": "5eeb8007266cd98f34ad43fbb3367586"
        }
      ]
    }
  ]
}
