{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "core",
    "version": "0.5.20-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.5.20-SNAPSHOT.3.jar",
          "url": "core-0.5.20-SNAPSHOT.3.jar",
          "size": 25702,
          "sha512": "d3ddc2ed1b7134986f15f6e68109543200eeda36970e05a6db4e603e7af0c577d3f8c5b1162923ac4470b8771f5dc5a2e4f3896c777fac5fbec0a407bdaac1de",
          "sha256": "a4c4dd502690ba9af89957aff743b3dad222a2382916e10178483594eb7492e9",
          "sha1": "86fc1e741545543db7efe5c0330df0bcf6b6d4c8",
          "md5": "902c79c1227ce332b75dbcd7f7fbb0e8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-kotlin-0.5.20-SNAPSHOT.3-sources.jar",
          "url": "core-0.5.20-SNAPSHOT.3-sources.jar",
          "size": 21237,
          "sha512": "6defbf474015ff1c5cb27250467c9076137faf32cf0215814b5424a1dcf6ac6d86dab4740cdb3ef60743966569e3280189e8656c32d09594a19c3a2cde9723f0",
          "sha256": "7fcb4b8742a2cd2bcef410a76db70c4c78c0a586e6d8ae25fcebec87e3cc3f11",
          "sha1": "6f4996116706a63834328b580fe7113520080310",
          "md5": "b423da40e6f7185f5c8899bc20e554cb"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-android/0.5.20-SNAPSHOT.3/core-android-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-android",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-android/0.5.20-SNAPSHOT.3/core-android-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-android",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-android/0.5.20-SNAPSHOT.3/core-android-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-android",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.5.20-SNAPSHOT.3/core-iosarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-iosarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.5.20-SNAPSHOT.3/core-iosarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-iosarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/0.5.20-SNAPSHOT.3/core-iosarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-iosarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.5.20-SNAPSHOT.3/core-iossimulatorarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-iossimulatorarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.5.20-SNAPSHOT.3/core-iossimulatorarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-iossimulatorarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iossimulatorarm64/0.5.20-SNAPSHOT.3/core-iossimulatorarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-iossimulatorarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.5.20-SNAPSHOT.3/core-iosx64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-iosx64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.5.20-SNAPSHOT.3/core-iosx64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-iosx64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/0.5.20-SNAPSHOT.3/core-iosx64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-iosx64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.5.20-SNAPSHOT.3/core-jvm-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-jvm",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.5.20-SNAPSHOT.3/core-jvm-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-jvm",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.5.20-SNAPSHOT.3/core-jvm-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-jvm",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-linuxx64/0.5.20-SNAPSHOT.3/core-linuxx64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-linuxx64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-linuxx64/0.5.20-SNAPSHOT.3/core-linuxx64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "core-linuxx64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    }
  ]
}
