{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-metadata-0.7.0.jar",
          "url": "composeblocks-0.7.0.jar",
          "size": 30924,
          "sha512": "91a1950df6a447f607ee6a8cc1fb0240460cec70a65e7a50a199084a848e49cbdd97acdcf7bd19a098f3d3f78f934599cf0c50bc7888c62188187239118d2b75",
          "sha256": "3b13579fb9c83fc317d0b305cab96e88aa801230d5f3b560e8739ba50a835b47",
          "sha1": "2674fcf97ae19db3905d4fdcfa8d19788e641472",
          "md5": "42262c18e160ecfc1cc70b2927ca605a"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.7.0/composeblocks-android-0.7.0.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.7.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.7.0/composeblocks-android-0.7.0.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.7.0/composeblocks-iosarm64-0.7.0.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.7.0/composeblocks-iosarm64-0.7.0.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.7.0/composeblocks-iosarm64-0.7.0.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.7.0/composeblocks-iossimulatorarm64-0.7.0.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.7.0/composeblocks-iossimulatorarm64-0.7.0.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.7.0/composeblocks-iossimulatorarm64-0.7.0.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.7.0/composeblocks-iosx64-0.7.0.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.7.0/composeblocks-iosx64-0.7.0.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.7.0/composeblocks-iosx64-0.7.0.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.7.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-jvm/0.7.0/composeblocks-jvm-0.7.0.module",
        "group": "br.com.wave",
        "module": "composeblocks-jvm",
        "version": "0.7.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-jvm/0.7.0/composeblocks-jvm-0.7.0.module",
        "group": "br.com.wave",
        "module": "composeblocks-jvm",
        "version": "0.7.0"
      }
    }
  ]
}
