{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.8.0-rc.261/runtime-0.8.0-rc.261.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.8.0-rc.261",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.aar",
          "url": "runtime-android-0.8.0-rc.261.aar",
          "size": 694312,
          "sha512": "76f39c72308e1ad69ce0083ae1febed9baa44cc0aa21dff28e6d461c16ec732de9cb48f79a5ff21b03469ecfe514e093abf2612d9b7c6256f26c839a9dde8b40",
          "sha256": "a7f3e6d065515f5d4a8ff9408d0ea97a7496fd57abe9f5ded19ff86e367d5473",
          "sha1": "5de1ee54269e633b0d686e9d83a435b1af813232",
          "md5": "135be610e76e6ae77e213caf1fbd7fc6"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.aar",
          "url": "runtime-android-0.8.0-rc.261.aar",
          "size": 694312,
          "sha512": "76f39c72308e1ad69ce0083ae1febed9baa44cc0aa21dff28e6d461c16ec732de9cb48f79a5ff21b03469ecfe514e093abf2612d9b7c6256f26c839a9dde8b40",
          "sha256": "a7f3e6d065515f5d4a8ff9408d0ea97a7496fd57abe9f5ded19ff86e367d5473",
          "sha1": "5de1ee54269e633b0d686e9d83a435b1af813232",
          "md5": "135be610e76e6ae77e213caf1fbd7fc6"
        }
      ]
    }
  ]
}
