{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.20.1/composeblocks-0.5.20.1.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosSimulatorArm64Main-0.5.20.1.klib",
          "url": "composeblocks-iossimulatorarm64-0.5.20.1.klib",
          "size": 347074,
          "sha512": "184fa8791de4502b7c8597a7b5a59038457e1e06fa352d3314f16287e35b4796644f7b92189c1a932b96358433e8d46801e3fa703ac0cf62bfcbc3c349715d61",
          "sha256": "716b8fb0f70603781d7fe9d35790b2575bba611ed511004a155706f73c07697c",
          "sha1": "edb5de83445ab5c489edf9cb7146a88306f9e64f",
          "md5": "4a05e8e01bee626387ad28321697530c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.20.1-sources.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.20.1-sources.jar",
          "size": 62929,
          "sha512": "a1b6fc6d924260f33998241e03ec24748d5c5dfd0113774ba6737d13cf12976f05d7730d8a31102924f3f379dc14469fbbbc54a33812c1b3466749ccc47684d1",
          "sha256": "c060c74601af62602de4fce2f88037ef006540f40ab0fc07a70a191070214b78",
          "sha1": "16aca03e0bca1374655d6244d13d0ebffcd27f34",
          "md5": "18983dc3d325a95705ebeb14c1ac28aa"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.20.1.kotlin_resources.zip",
          "url": "composeblocks-iossimulatorarm64-0.5.20.1-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "831c849370b5434b9d888ec089de1382a43ba7ec3b385ed52ea5437e3131b676132558e5a32c6fbedcaae353cdd4754cd56658a3bbb0dac0fd69c2b2c9fede29",
          "sha256": "24e887510ad3f1fa8fcc6012e16377de407ba7bc77d8c268f17007da85c027aa",
          "sha1": "15c1881a17a6f0dff49830f6dbd90a98f90f8444",
          "md5": "f2f311658b7dfba108915261043e8bd1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.20.1-metadata.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.20.1-metadata.jar",
          "size": 261,
          "sha512": "f16ba0a92ca4f9e009fc18b3c28f78d532b1e0d2c4a1c66e7cc36a06ac6b745d1975ec2c18e26098fbe913744c582373793b8d16e58a7999572eebfcc028f45f",
          "sha256": "170473b04a0643dad876d1db9859c17d7b3e6804b9bd1dfd9cf8f5eb281e0e32",
          "sha1": "309088e2829faf7db82e170a3169f6e74b3d29a4",
          "md5": "9aea28d128a54c42df5fd312af5550fb"
        }
      ]
    }
  ]
}
