{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.10/flow-wrapper-kmp-0.5.10.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosX64Main-0.5.10.klib",
          "url": "flow-wrapper-kmp-iosx64-0.5.10.klib",
          "size": 104009,
          "sha512": "6e5394873684d7dda902e33e23ade91796407f489a09557e22bdfb64467fd75f3cf4818646a15a1983391b7b6645d7fc6ca6141379e1fec0d57dda055901c566",
          "sha256": "4d95e76a42ca34c416647e9d02019499e91cf7b16ade4fe7a356f7b7ce4261a6",
          "sha1": "f796c69d873a74dd1ea87cff55d80fd6870505e2",
          "md5": "349046576404cff6faf1e738713486a8"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.10-sources.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.10-sources.jar",
          "size": 16682,
          "sha512": "02b75d00c0410f7a74407efb0a8a536a752ce5071bb4e6dc92535e8f4606943dc2e2ebbef7231a16698841096869be71de806f951e677be1a46836403e41392c",
          "sha256": "95c0c455e66c64d4e373023f2b02fb26d39ba0a2d6671bdb9cd42a4a545e87c9",
          "sha1": "d73573d7d9c929857407809f8d7096674ac9892a",
          "md5": "ce2b1d2209908b3e8b451e826167f0d8"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.10.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosx64-0.5.10-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "279ee29e6718c1658b2bf97e43dfdd5d46fb3e3a1cad0e7ecae3fb0e63b941f4f226b55946a78eda82a2bab0d8425239159e97181bee523a82b6b3ff9957e285",
          "sha256": "b86d07ff1edd5c8f00e52bae677570a66f0fe42b9e00b60ef009b7f951b2f86a",
          "sha1": "b2df91adaf2c01b23027b84969135a2f531109e9",
          "md5": "17deaa7ec6fab9ef9d422b9b66b4d8f7"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.10-metadata.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.10-metadata.jar",
          "size": 3469,
          "sha512": "6a15d442a63e370721fe376fa799b1fc27cacf6ac9c307e603ef52224e03e913e3d274664890e580fc8ec67080e784e859b65422bcebc3dd797c4ded4cc09d6a",
          "sha256": "96ffc190e9a10e7c42e525251d03acfebf6c8feffdee35b7fa8471a90d1e24ca",
          "sha1": "5f864046a1b9ef17cc9f8564212bcd3327348982",
          "md5": "2027c46f39a6064cdaccaf90dc165d3f"
        }
      ]
    }
  ]
}
