{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.5.20-SNAPSHOT/core-0.5.20-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.5.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosArm64Main-0.5.20-SNAPSHOT.klib",
          "url": "core-iosarm64-0.5.20-SNAPSHOT.klib",
          "size": 127618,
          "sha512": "59fbd589c3ae50af24f503b3638ad717a1e67760dffe55a195adb9067ea4b4c391979b93526835dc29483047d2765ad6449723740387c3bf1747dc1a0aa2fef6",
          "sha256": "214f156f4e5456284b88598ee148ef13e89ac91339fa1bac28778324215b2ee8",
          "sha1": "464c9215b953d8035f5ee45613553394c6315807",
          "md5": "b4c535d63b0fc5dbb4dfe845b9065f8d"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iosarm64-0.5.20-SNAPSHOT-sources.jar",
          "url": "core-iosarm64-0.5.20-SNAPSHOT-sources.jar",
          "size": 19241,
          "sha512": "9a5393b3bb0307aa6931eb24e76bb3cbd6385fb2e1dba4c14e1a6d1864435fb6fd9ffef6aaf0d386dfc1a3d497e459f26c09cdac9f556b235a16802af7ac8b75",
          "sha256": "1c7a9aa3464ab76183efb0ae36a0ca75a3cdd21378c8e962848aca7556096d4e",
          "sha1": "43eed877c7528a7ce139b1643e585998031a97b3",
          "md5": "f3b49f1808e86065dcb78b9e223f0537"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.5.20-SNAPSHOT-metadata.jar",
          "url": "core-iosarm64-0.5.20-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c842f4ba92721f39b4f1f78d402cfa22f81a887756b9a8b141d470d4d27559891ca893748b767deb2c142d436035f63cee91dc28ef98bd042a5d0d914a0daf36",
          "sha256": "39bcafd42d14fd0871a00fb0a67ed4128a78ffc56f1c327f6b03abd398d1941f",
          "sha1": "b66d3f7ab32cd0e280956a5c4cef51d88d341e03",
          "md5": "b576ea97fd1770c823873a361b7379a2"
        }
      ]
    }
  ]
}
