{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.8.1-SNAPSHOT.1/runtime-0.8.1-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.8.1-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosArm64Main-0.8.1-SNAPSHOT.1.klib",
          "url": "runtime-iosarm64-0.8.1-SNAPSHOT.1.klib",
          "size": 871212,
          "sha512": "59060cdb32b8fe180a7f2057b283b18a8bc708a1442493588a03013e18b75e8d200a424218ae2d047a995519de536a7de4260624a905155b1d62eacfc9746852",
          "sha256": "650799ac4b640e939e7d253a106239a185b54d62a7f36ac624bb2f0b8f9ac3a0",
          "sha1": "7eec9d08d44f449f3d96008f8529bd3df34cae50",
          "md5": "3ed37e7d525be09d1bc3564ab9d1c038"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosarm64-0.8.1-SNAPSHOT.1-metadata.jar",
          "url": "runtime-iosarm64-0.8.1-SNAPSHOT.1-metadata.jar",
          "size": 2428,
          "sha512": "f1066df2565de1ee279ec6fb255f3c8d6216ff6da2eed499e492de2ae7ed090067029ee69e89d74881de434e4e7a7a545ccfd088f8b076c3dc0e050775232274",
          "sha256": "ab3f54bc279d1ec0553db27187ba71f1de508cbe13fb71434e8732ab2f39422d",
          "sha1": "a975462e1a628cc3300f003a43ccda331468e7fd",
          "md5": "f9aa279718ab94ff6267322930ce4e14"
        }
      ]
    }
  ]
}
