{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.6.0-SNAPSHOT.13/flows-sdk-0.6.0-SNAPSHOT.13.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.6.0-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.6.0-SNAPSHOT.13.aar",
          "size": 51891,
          "sha512": "7a2e2abde31b981d1eb5cc07bd57d2751c358103945003f212aa6c77f0f88ba1fc07e7e93ac3a2fd784753308204e992ed0e74b2d77027ab9200d5a67ae9a3b8",
          "sha256": "728ce696a2feb064ba81b0bf64dedecc575aea3775718fe848109c2228c61802",
          "sha1": "41bb1c49069c99172e776194c0fede36569b8594",
          "md5": "ae214291aae2a8174c428bbf801ffc27"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.13"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.13"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.6.0-SNAPSHOT.13"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.6.0-SNAPSHOT.13.aar",
          "size": 51891,
          "sha512": "7a2e2abde31b981d1eb5cc07bd57d2751c358103945003f212aa6c77f0f88ba1fc07e7e93ac3a2fd784753308204e992ed0e74b2d77027ab9200d5a67ae9a3b8",
          "sha256": "728ce696a2feb064ba81b0bf64dedecc575aea3775718fe848109c2228c61802",
          "sha1": "41bb1c49069c99172e776194c0fede36569b8594",
          "md5": "ae214291aae2a8174c428bbf801ffc27"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flows-sdk-android-0.6.0-SNAPSHOT.13-sources.jar",
          "url": "flows-sdk-android-0.6.0-SNAPSHOT.13-sources.jar",
          "size": 12833,
          "sha512": "f483970fc8016677e37b99fe829f313b619cc2fcaf70fb8ed7ed7cb5476d09aaee933e72b0b36449cebfca856e5cafd190aeb5aaad14cefed73ad554d55bd7b6",
          "sha256": "12eafd8698e74989ceeb44f7369023086bc79c8f24fb0ff35f250114699d9f5d",
          "sha1": "c2f37a7c25a961cf3547650f78489d299c654205",
          "md5": "c46e78aeccd56f81ad698e65b2d184a7"
        }
      ]
    }
  ]
}
