{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.15-SNAPSHOT.1/composeblocks-0.5.15-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.15-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.15-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosArm64Main-0.5.15-SNAPSHOT.1.klib",
          "url": "composeblocks-iosarm64-0.5.15-SNAPSHOT.1.klib",
          "size": 288707,
          "sha512": "8498685ea85a4d3dadd0a682f9f11907080bac398db0801944abdf8c63cb320a6b0fc10f865829ff34ff156d529fbdb13d7015a9e3ea527b2c4fe892b2c945fd",
          "sha256": "d5aab759972e803fb2a5504e7122f1af629b0200dbba36b13797387b3e0a5f22",
          "sha1": "d21ec682b07326a6d74bf0fc57a6b9f61b886fcb",
          "md5": "5c7f8c23428b5a4cfc28519332628059"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.15-SNAPSHOT.1-sources.jar",
          "url": "composeblocks-iosarm64-0.5.15-SNAPSHOT.1-sources.jar",
          "size": 50047,
          "sha512": "73aefc09413371b7c1627ba11b2287d9524b52a8c594d6c62778e1b1757568b5a1d9b6dbb657b07242cc457d41a3491eabd307b598f27ae8544c082eefe49018",
          "sha256": "1462b2e7d16af0f30e535e9e99fe6cf859cede99cbbaf0ec4039acbad447604f",
          "sha1": "a2d4ac93c14b90434a52ecec9070e65ab9e996ee",
          "md5": "71ef8e9e038de35a3f4136149f32fbbe"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.15-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.15-SNAPSHOT.1.kotlin_resources.zip",
          "url": "composeblocks-iosarm64-0.5.15-SNAPSHOT.1-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "62cd96830b13be54b4acf2ab2493bdf5e34f6196ab9808e57f6c3b40f891a81b64b69a63046e522955e88e83f718f93b9afe8d08bfcb796983475cfe5bd5c91f",
          "sha256": "0ce2ba991c9efa2f0e52b15d984fa1821a55f95ffc0cd638511dc86f3ff7974d",
          "sha1": "5f832769a8a00b74dd87ddaef10aca69e81c64ce",
          "md5": "40642ccb4ffdb7f833d686d1b4aa6793"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.15-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.15-SNAPSHOT.1-metadata.jar",
          "url": "composeblocks-iosarm64-0.5.15-SNAPSHOT.1-metadata.jar",
          "size": 261,
          "sha512": "42f29738301496404205586b1e7247cba59fbfb80ecc2c1cb7e42952021efdd321c7b5be5f6e9ea2c8f870b94b45b7d7b7018ead6d38294a222ceb741246e38b",
          "sha256": "5efb1b0b09d362f0e1dc60eecc2718d75d25b0076a39a29279f0760f15a42fd1",
          "sha1": "429a3932d2b935d3228ef6e1cd100cca44ea48a8",
          "md5": "2f912f9e9a3ff1a4a02b531ad1bb7df5"
        }
      ]
    }
  ]
}
