{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.19-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.19-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.19-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-optimal",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-apple",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-metadata-0.5.19-SNAPSHOT.jar",
          "url": "flows-sdk-0.5.19-SNAPSHOT.jar",
          "size": 21000,
          "sha512": "c1439d478fe92f71eb8b45494ddc511d99785b289b2527076c8375f269d77a834babe30887abe21a85ebce12ea03e7761f03dd550ca0cb08f75a45545af410b2",
          "sha256": "497d53c9868b6b5aa2e07f744601d460d97c56a4d75ce89010f6e3033e1c8151",
          "sha1": "c28d6ba5181cbd04c1347cb0bb7ed5ebf2deb143",
          "md5": "c8c45c3b372259a98c0d7b32d4c604ff"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "flows-sdk-kotlin-0.5.19-SNAPSHOT-sources.jar",
          "url": "flows-sdk-0.5.19-SNAPSHOT-sources.jar",
          "size": 27482,
          "sha512": "6160ecb8c9450680038de61b50c6f04f937d2f2ed76b071c60b7cd8ebf98048d1e13780b9bfc1711c413dcebe22c97ff177283cd1fa38040b8fa135b3d561f5f",
          "sha256": "80b31ed4ce51355afec82be6dbd393fba96a37724f603fa210de0e55ca34905c",
          "sha1": "e5a46abc6d36a825b4be0aff381cfafa4178916b",
          "md5": "986debfa9968a5483704f55a54b2e6ce"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flows-sdk-android/0.5.19-SNAPSHOT/flows-sdk-android-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "flows-sdk-android",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flows-sdk-android/0.5.19-SNAPSHOT/flows-sdk-android-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "flows-sdk-android",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flows-sdk-android/0.5.19-SNAPSHOT/flows-sdk-android-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "flows-sdk-android",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosarm64/0.5.19-SNAPSHOT/flows-sdk-iosarm64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosarm64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosarm64/0.5.19-SNAPSHOT/flows-sdk-iosarm64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosarm64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosarm64/0.5.19-SNAPSHOT/flows-sdk-iosarm64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosarm64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosarm64/0.5.19-SNAPSHOT/flows-sdk-iosarm64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosarm64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iossimulatorarm64/0.5.19-SNAPSHOT/flows-sdk-iossimulatorarm64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iossimulatorarm64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iossimulatorarm64/0.5.19-SNAPSHOT/flows-sdk-iossimulatorarm64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iossimulatorarm64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iossimulatorarm64/0.5.19-SNAPSHOT/flows-sdk-iossimulatorarm64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iossimulatorarm64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iossimulatorarm64/0.5.19-SNAPSHOT/flows-sdk-iossimulatorarm64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iossimulatorarm64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosx64/0.5.19-SNAPSHOT/flows-sdk-iosx64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosx64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosx64/0.5.19-SNAPSHOT/flows-sdk-iosx64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosx64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosx64/0.5.19-SNAPSHOT/flows-sdk-iosx64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosx64",
        "version": "0.5.19-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosx64/0.5.19-SNAPSHOT/flows-sdk-iosx64-0.5.19-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosx64",
        "version": "0.5.19-SNAPSHOT"
      }
    }
  ]
}
