{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.7.0.1/core-0.7.0.1.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosArm64Main-0.7.0.1.klib",
          "url": "core-iosarm64-0.7.0.1.klib",
          "size": 144154,
          "sha512": "cad8dbcda1052ccd69a3754bbb44b10e54f54d9fece5f8e058e7fb0ead5d40a612909df9f0efe254966829a99d0a1127ba2798b7de123e3adfff0e1c1ba34e36",
          "sha256": "c4dbd93120a682dc88820ed5d0f52650af8427b58d5d5bd01cb8d2b671716f46",
          "sha1": "eda3055ed9fef987b2c2a46b6ed2218c5b13a4a7",
          "md5": "e2b59f06b544a12a99e8343e2ccb221c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.7.0.1-metadata.jar",
          "url": "core-iosarm64-0.7.0.1-metadata.jar",
          "size": 261,
          "sha512": "f4aab473584c359cfa2ab6536f583b5e326b1fec03fb8c31ecc3185578498bed55a464828cd1ed3ce66c6c6f87671b45b6c2933e5258e44a70c0db2379e27522",
          "sha256": "6cca5b97f1f2d5f7e895d622a9e8cdcb77809b4936e1c746809d176049d82504",
          "sha1": "5a08f1a7b1d2d9db43bae56b78539e2df0b911e6",
          "md5": "580323e3acdbfe78a8c826f191a68c10"
        }
      ]
    }
  ]
}
