{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.6.0-SNAPSHOT.22/core-0.6.0-SNAPSHOT.22.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.6.0-SNAPSHOT.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosSimulatorArm64Main-0.6.0-SNAPSHOT.22.klib",
          "url": "core-iossimulatorarm64-0.6.0-SNAPSHOT.22.klib",
          "size": 101634,
          "sha512": "9c400a1c7128bc02011d5d29d2e0bc097bc71c03989bbaca5a7af2d860d27c2e3e15b0d65c4094b27b67ad5f18121428e7ba1ffd56a4e02673b2baa105274ec9",
          "sha256": "023be5334a14dfd2da73a221dcb514a699a878e3d87e04c085f72fb500de0972",
          "sha1": "190100a606c72e9c95671160849e0af9f5f28772",
          "md5": "de39d466ebd26b6349e2784ba26980cc"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iossimulatorarm64-0.6.0-SNAPSHOT.22-sources.jar",
          "url": "core-iossimulatorarm64-0.6.0-SNAPSHOT.22-sources.jar",
          "size": 12871,
          "sha512": "9384b55817f88f910ec57688f568f23c7334e431ee50978b193d247dc6dc8604297381b30757d73c8c22a3ea4f3da34334acfaf4bfa1121de726f0027e0f3235",
          "sha256": "cbafd42c100bb7358370dc203cd61d4041cd683b48d69db2eda1e6514b18e617",
          "sha1": "20061d10ddcd97c4bb4a9c49602da7d79000e539",
          "md5": "337280c1de2570f705980fc4fe7f6037"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.6.0-SNAPSHOT.22-metadata.jar",
          "url": "core-iossimulatorarm64-0.6.0-SNAPSHOT.22-metadata.jar",
          "size": 261,
          "sha512": "db3f4a4a77390b38cf38dd9930c6c24bfed1c5ae09227e972749a404af9aeee19f1d5907aed08345dec9d618a78ae4bf6d401855b78c30f59629ae74f5fa52fc",
          "sha256": "b2e66a28d31a454eca21034b50213f9f5cb6cd148078975c13f6593c7f9fdcd8",
          "sha1": "c305428c98814b83d488fde8384bb138430ec4dc",
          "md5": "680d23a8639998d5969c542274b6c5be"
        }
      ]
    }
  ]
}
