{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.5.15-SNAPSHOT/flows-sdk-0.5.15-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.15-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.15-SNAPSHOT.aar",
          "size": 146896,
          "sha512": "0ce94f79807fdb8e58c3c328d31cd3fb443245237adb1a69da73c637e160eb938f3ae2030610449595dab281fc84f9ddf74887c638b96e9ddd1eb731fb9b8f5f",
          "sha256": "9002756b55cc5910553b7124083dfea536e0f5fdbcfb6884b87448ac9ed3d01a",
          "sha1": "3c15f17107628ae6fd28b83aacb4f278b8ffbec2",
          "md5": "b54a02c42ccf045856f632dbe70a17a0"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.15-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.15-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.15-SNAPSHOT.aar",
          "size": 146896,
          "sha512": "0ce94f79807fdb8e58c3c328d31cd3fb443245237adb1a69da73c637e160eb938f3ae2030610449595dab281fc84f9ddf74887c638b96e9ddd1eb731fb9b8f5f",
          "sha256": "9002756b55cc5910553b7124083dfea536e0f5fdbcfb6884b87448ac9ed3d01a",
          "sha1": "3c15f17107628ae6fd28b83aacb4f278b8ffbec2",
          "md5": "b54a02c42ccf045856f632dbe70a17a0"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flows-sdk-android-0.5.15-SNAPSHOT-sources.jar",
          "url": "flows-sdk-android-0.5.15-SNAPSHOT-sources.jar",
          "size": 22297,
          "sha512": "01511bd2bc81747792fbf45dfc6f4d5bd3f95816bc20c8397655ad68790f9705d2051eb991196a36d0c01ce1e74687825b9ab92f8763d44ffd54f2b8d54d3136",
          "sha256": "431a634db387d50b7176290f4c1c96d4fee815f0dbf0d4d015e7fd766048b40a",
          "sha1": "5d39f7bce57c265060d286fdfc7b8502a44ac63b",
          "md5": "b5d3f6b62158e3595db21772ec1eba49"
        }
      ]
    }
  ]
}
