{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.12-SNAPSHOT.2/composeblocks-0.5.12-SNAPSHOT.2.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.12-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12-SNAPSHOT.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.12-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosSimulatorArm64Main-0.5.12-SNAPSHOT.2.klib",
          "url": "composeblocks-iossimulatorarm64-0.5.12-SNAPSHOT.2.klib",
          "size": 224363,
          "sha512": "56882b901f156ebf4a67bcfa3bc44a2ca796196feb125023b53cde29d5ae134fb57a8911cb4da27c6f3289e949c2d359b9da007f42c00044d10fef21da1bf549",
          "sha256": "54d0fdfee8959177283c6d62934da72be3f828e58dc77e4cc5bd472ef41f7a94",
          "sha1": "f2fc8b0271efa28c544834e08ebc89eb6e1f4431",
          "md5": "1e8a81d31f400592a786a9ca4ec5df43"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.12-SNAPSHOT.2-sources.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.12-SNAPSHOT.2-sources.jar",
          "size": 36171,
          "sha512": "23c4853c4c5ee3e6ac70f0d156f7edca210d60c462afc04368f907794a7dd2bb486270d34bbf5a74f3b285ae3096689a8043dbeac4e6731b501f0447b4c97010",
          "sha256": "27d5e6dbc67211882f5e0804adf3872f8687745226d6a4874e42cce92a4b2e3f",
          "sha1": "5993f83f60b0d937068cf7414394a0621ef03b5d",
          "md5": "f7e8a769e83320cad5d567a321b1c829"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12-SNAPSHOT.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.12-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.12-SNAPSHOT.2.kotlin_resources.zip",
          "url": "composeblocks-iossimulatorarm64-0.5.12-SNAPSHOT.2-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "c13c5ab266c2e366df9257f4887641603e6f79827b52c0276b356d1339acaf5b9c90dd684f249200fc5b3112e6325e827f3c34c3b9fdb31e1bd164a075d90324",
          "sha256": "aa04e5fe6e43807df0c770dfcc9a600478294a73ae8892f68b55f976800cdb72",
          "sha1": "d406cab3bd5b1ebd05af72590608be022fe2c5e1",
          "md5": "915d94dee878744c314c30defec2556f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12-SNAPSHOT.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.12-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.12-SNAPSHOT.2-metadata.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.12-SNAPSHOT.2-metadata.jar",
          "size": 261,
          "sha512": "b01fb2437a5b2c8cbf3b57ec34ce3e42d23748b4d4a68416a6107253cef1fff2868f0ac60f1486a8b5f9a6d0a504ba973dfe2c44401a2f448d0aede752dce291",
          "sha256": "49474a0c9bd249c7248600751f86fa80ba72e1a5ddd48e1b81af7ee4601ddf88",
          "sha1": "7891a7863545e2a47a0045cc88ae801f1151b19d",
          "md5": "3808374841b9f8c4d202ee2c9330dd64"
        }
      ]
    }
  ]
}
