{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.5.19/flows-sdk-0.5.19.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-apple",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-optimal",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-iosX64Main-0.5.19.klib",
          "url": "flows-sdk-iosx64-0.5.19.klib",
          "size": 139023,
          "sha512": "de9bd0e41340f30955a13ae137953735f559d15ce6a8fef631a45e38e5ac3bccf199a3274478586bc521a7d15cd34adbdd50f6aaf8ad8dc2aa931c5be75bad18",
          "sha256": "3c7705e8f0ef599ab2409aa37a252f9e767d27ed5b539b7da73e37dc9f6ac844",
          "sha1": "9e6ddf81eead3bb0ac2547a820e9fb936fbdb0de",
          "md5": "97fff62afb24e0e824c98dcd016ad53e"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flows-sdk-iosx64-0.5.19-sources.jar",
          "url": "flows-sdk-iosx64-0.5.19-sources.jar",
          "size": 28982,
          "sha512": "24cb053a78ee1189306593a845395cb1734762dd40a3d48a59771c463ae9b13c6f97ca42ad7750a08802627a79643df036ff052d76ab891e3a4b51f25d7eb5c0",
          "sha256": "1f49bdbd35099c4073c11cc1ce92dd0c3510f040f3e99664b7f16f40bd9a3c63",
          "sha1": "247ded51431a099a625f03722dde1535ff3d8b9c",
          "md5": "6c59b554305e8f79a491e2c7608278a9"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-apple",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-optimal",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-0.5.19.kotlin_resources.zip",
          "url": "flows-sdk-iosx64-0.5.19-kotlin_resources.kotlin_resources.zip",
          "size": 61888,
          "sha512": "acdb00386434020de2896209591896fc744ac38d49075877db7235493b31d6f1abcb259e807706c61a777a8c9f15658a4b5179436a36bf426cb1232311ce6f9e",
          "sha256": "4b48e7499c18029d6426f6312fe0585787d8958dbabe12cb8e0a02564c338f99",
          "sha1": "84eb32c0be7ce9960a36635fe1c9e7f5bf9e940e",
          "md5": "9583d0746648fd4cc5a746ada3e57b0a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-apple",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-optimal",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-iosx64-0.5.19-metadata.jar",
          "url": "flows-sdk-iosx64-0.5.19-metadata.jar",
          "size": 4019,
          "sha512": "8b1ef9548b0ed9cc23f36b2e6643fb2d6ff17736ffe5ccc454cfdb380b57296c288666c73aa73e80562d47a548eac5cc690405a77d82f5985443c7b6a86bd6c7",
          "sha256": "05645501a8561c5c5cf9216d0575847187e2d45de18d5bc2116b9d3afe61f498",
          "sha1": "1f8b10bc815be0ca17707cd547789ab0e9bb0a11",
          "md5": "28da00786760b63acc50589f135fb390"
        }
      ]
    }
  ]
}
