{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.7.1-rc.237/core-0.7.1-rc.237.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.7.1-rc.237",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosArm64Main-0.7.1-rc.237.klib",
          "url": "core-iosarm64-0.7.1-rc.237.klib",
          "size": 235791,
          "sha512": "f2e6ffb13a2aa1e204ede3af81bc8808993900b13c9d3faa3b344209acc7df67f4d1d906efe064e6737154eded92c43ed2a7cb6e5e5b72dc55f4344f79948f97",
          "sha256": "99c8616cb054cdfa9e672146364a1dab25946a0d9a09e9e03402572f79cda504",
          "sha1": "3c4840a1bbb735e452921137a9ed2909950478f9",
          "md5": "f3a607732b06ea9b76941d0ae0fb9da1"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.7.1-rc.237-metadata.jar",
          "url": "core-iosarm64-0.7.1-rc.237-metadata.jar",
          "size": 261,
          "sha512": "9b7f5468df88fa48a150d4200578608f0ecee2721d1d85d7ae0f37dda874ab212f50dac6f1066d0f49e396aa4aa708002f8eefb8a1281c1dd592a8b1e71bceec",
          "sha256": "b33ddc16e569513730c5cb4c7f41a6645b4d0b2fda2f788413e54e19a88449f4",
          "sha1": "26f681207143ce0519b275b8dff58b91f5e9daf7",
          "md5": "a4b94defad3afdd37764a13d07c9ae90"
        }
      ]
    }
  ]
}
