{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.6.1-SNAPSHOT.1/composeblocks-0.6.1-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.6.1-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosArm64Main-0.6.1-SNAPSHOT.1.klib",
          "url": "composeblocks-iosarm64-0.6.1-SNAPSHOT.1.klib",
          "size": 382142,
          "sha512": "c826e8536bfc74c12b0686a5cf1a26b8c4ea738981614347ab85fb7df92de9510797750ede785197bb8c5bc81f7b33e2bd365df01aba2016e0e130ca8f3f5dba",
          "sha256": "9a1f0172f73dfe699c5031aab49217cf859663aef4d28de7b9fe0d3a96ebd8fb",
          "sha1": "9a20eb0cd20e521b7b5a9064d21aeeb902edd1b9",
          "md5": "41eaf56182c16bebcc4400fcf99a546c"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosarm64-0.6.1-SNAPSHOT.1-sources.jar",
          "url": "composeblocks-iosarm64-0.6.1-SNAPSHOT.1-sources.jar",
          "size": 72079,
          "sha512": "283c8bf185bb3fb08a7a10c39263e177e68dcc4a6dec480b72a2e90b7f40ad33708f4a1f228a9dada854d0ffcef630bd9433d23ad83e3b01e922120cca22ff44",
          "sha256": "7f0efb93ed5e5ac093c13a78289c5c665858c83aa9f26aa6284765c2a105a713",
          "sha1": "3b413c4dba9d61a966597f0b2c5fc61baedfeb5b",
          "md5": "43b60d69962c649ab93691e209be7b5b"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.6.1-SNAPSHOT.1.kotlin_resources.zip",
          "url": "composeblocks-iosarm64-0.6.1-SNAPSHOT.1-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "e7ec01cee093bd6c61db7081b8954c9704e9eea9c447ffa8c7a03168a02d2ffa4a2f789a59f27f327aa4997c153a18210878790e8c0a8dde2125ddd97715e33b",
          "sha256": "e6ee9fe5cb51d2c216ef6abcb4ffe4960042ce161cf74f71d4e63ad7f3bfe366",
          "sha1": "911df19e1bdbb6593a7f96be5ef2d6c85c3ea26d",
          "md5": "cb51b9fc9caa8da209c8cc412e7ef066"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosarm64-0.6.1-SNAPSHOT.1-metadata.jar",
          "url": "composeblocks-iosarm64-0.6.1-SNAPSHOT.1-metadata.jar",
          "size": 261,
          "sha512": "7fd1cd65afc7427ce4766ea973ef1802112c10a20ffe5932aab60698abee66673122bd50b56c020fb6b75d5226394732ede1bcf32b2b58d902026a228636a0f9",
          "sha256": "d9b916a8f047dae70cb3a8d8b85a8d9f7813c37a0046790fa76662fc8eff9d6c",
          "sha1": "5ac887460e241a99b14e52b87f7e8c71eb649fd0",
          "md5": "61f214878173ef433406736471d02f90"
        }
      ]
    }
  ]
}
