{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.5.16/flows-sdk-0.5.16.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.16.aar",
          "size": 161233,
          "sha512": "d8fab6a44559b1686dd023859cfffac6b02556b501819c1db6c48df248c6be6652f44deb2f8b9008128b41687a2406fdec248880c254bce747a3164573b07d86",
          "sha256": "9b6a2a0af6d53510e83b81490a0f37feed81bd040b0eb0e203fafc4f244dc59b",
          "sha1": "123e4041062aa07626146ce3737746a211422658",
          "md5": "f28849e3eb732fbc505638a8d7052652"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.16.aar",
          "size": 161233,
          "sha512": "d8fab6a44559b1686dd023859cfffac6b02556b501819c1db6c48df248c6be6652f44deb2f8b9008128b41687a2406fdec248880c254bce747a3164573b07d86",
          "sha256": "9b6a2a0af6d53510e83b81490a0f37feed81bd040b0eb0e203fafc4f244dc59b",
          "sha1": "123e4041062aa07626146ce3737746a211422658",
          "md5": "f28849e3eb732fbc505638a8d7052652"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flows-sdk-android-0.5.16-sources.jar",
          "url": "flows-sdk-android-0.5.16-sources.jar",
          "size": 24407,
          "sha512": "b35a1e6db1169fd08b291a5327832c5784a4566ef55526e43c1a32f74ad093cbf12ed31a2e8a9e66776c9a2867d21f5e440a98ee667180f13092be9af95be7b3",
          "sha256": "00a806556a8094bbea5035cb31e3b9403d5fcd9bff088a2810ba5e8ec723fb81",
          "sha1": "810dfedbeb0512d07aeaea6885859595623f83ae",
          "md5": "38a3faf48dc035ea9e843d3ca7f9b1ae"
        }
      ]
    }
  ]
}
