{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.7.1/core-0.7.1.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosSimulatorArm64Main-0.7.1.klib",
          "url": "core-iossimulatorarm64-0.7.1.klib",
          "size": 235855,
          "sha512": "8a84c52bc45606a8a0d9a37fba040c942c63ecb0b61842f0372be0ad3506d715fb158df0bb407fb381e67f68a916b510b377246ee261a7f9889e6a4d7cd9ee35",
          "sha256": "e08aabd9fec76b1e463695e95c47e2c4d66fa450120a66e8737d9170f6391ac4",
          "sha1": "8322b4ce1d93693397412a2430f5aee9b6a73947",
          "md5": "5a1c0c98e641937f1ba0d0de74678987"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.7.1-metadata.jar",
          "url": "core-iossimulatorarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "eea6c6d3f5f5249d58ecf41b2ef4fc6fc3d4177c396db13251de633d7c56e4319dc58b4797f1228401ccc811d3158dde41cebeb389f45cb557c22f3fd3354556",
          "sha256": "aa6608cc14111b7aa713183d2a671f091e057512da13b8e3d096444fec705f23",
          "sha1": "55dbf3e964dbdcded2b1fb1e02b256f8516b870b",
          "md5": "e8a6f468c5d46aad257073e02c4c2a22"
        }
      ]
    }
  ]
}
