{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.8.0/core-0.8.0.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "core-android-0.8.0.aar",
          "size": 131707,
          "sha512": "2903d392eee51341cab7ba276d7f2a2bab58e34074d3a94aee82c1b2cc7c3ed41fe8dc2025c8cff09fddbc4a1b6564cb2dbf28707b24b371c15dcd05cca55b22",
          "sha256": "d9ff8ba7502b993bfcef28d40c582d80f45c9cf43f4e7d0e2c91ee26b35c758e",
          "sha1": "857492bd4e8738e0f6c626621304750b78d88c89",
          "md5": "16d7ec5389a04adf134f36685f602c9e"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.8.0",
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "core-android-0.8.0.aar",
          "size": 131707,
          "sha512": "2903d392eee51341cab7ba276d7f2a2bab58e34074d3a94aee82c1b2cc7c3ed41fe8dc2025c8cff09fddbc4a1b6564cb2dbf28707b24b371c15dcd05cca55b22",
          "sha256": "d9ff8ba7502b993bfcef28d40c582d80f45c9cf43f4e7d0e2c91ee26b35c758e",
          "sha1": "857492bd4e8738e0f6c626621304750b78d88c89",
          "md5": "16d7ec5389a04adf134f36685f602c9e"
        }
      ]
    }
  ]
}
