{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.6.0/runtime-0.6.0.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosSimulatorArm64Main-0.6.0.klib",
          "url": "runtime-iossimulatorarm64-0.6.0.klib",
          "size": 642308,
          "sha512": "d79e0cb69ac293d4494032de7c4f150a144e67331ffb4e004b8e5730518ac095f836e1f136e7fe8094770f7906971f571827c005c59e284d1ffe96646ae1ca4f",
          "sha256": "0ecab6b2999be57702623fd10cd1b0b44420897c10068b24b10b6e67e4c469a6",
          "sha1": "478e75c437d0f398c78c47c38c4f25e766ad770a",
          "md5": "e2766919d13a2e32b6728c9efe424ba1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.6.0-sources.jar",
          "url": "runtime-iossimulatorarm64-0.6.0-sources.jar",
          "size": 50861,
          "sha512": "3c67581834b2cf1e1356cfa3c27c3af7db07353c34fbb53ed816e7582b67f07f85949c4afabf1f811024bda0eed5f8b0f7fc00735a76c4dd00a994fc18b3e498",
          "sha256": "f9b4e25e066d710713ef37c3c09f45896f39f7986728047ee07b711a9130509d",
          "sha1": "02a952931a8f52748cb21dbc280a54d360cffe4d",
          "md5": "5d1fc380b5b0f7bc652bdffba7bf735b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.6.0-metadata.jar",
          "url": "runtime-iossimulatorarm64-0.6.0-metadata.jar",
          "size": 2428,
          "sha512": "9ac90ca7ed93688e1bd172fc14f78d74646fdf4123a1f7e19b707c8c43664822545f34a4a75e63f935434a20f6a1e77312d0647e22670eb872e5363202a480ba",
          "sha256": "a92191fbfc2a5990bbf23204133d37146098ecbaac556e1257f4a418324f9fbb",
          "sha1": "73c3dd6bbab407784d677f85e02278a03a1f32dd",
          "md5": "aaf2abc09ceb45ad54b3dfe30227f832"
        }
      ]
    }
  ]
}
