{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.6.1-SNAPSHOT.1/runtime-0.6.1-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.6.1-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosArm64Main-0.6.1-SNAPSHOT.1.klib",
          "url": "runtime-iosarm64-0.6.1-SNAPSHOT.1.klib",
          "size": 657208,
          "sha512": "859930d09a9095af78bfbf26699b2a54107cb1e021e0cfce5ff5f38cd3e7baaaf59f2f42cc62331aecdda8def72192da8d92e751c90c622af0c7a8ec59a860ea",
          "sha256": "dd3b24e72cf53d157cb4559f394fae3e307b41ec6a126bb3b0ff15b17d16eba8",
          "sha1": "8eef0c1583171bf592d6ec6ab211e08ab7c2de2b",
          "md5": "fdc36477ef6047b685d3a7fe620385a8"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-iosarm64-0.6.1-SNAPSHOT.1-sources.jar",
          "url": "runtime-iosarm64-0.6.1-SNAPSHOT.1-sources.jar",
          "size": 53701,
          "sha512": "936748c434872cc4dcc491c270bf92db7d44159e470bf1c3627ab7e7ecee67fc9b259e7adf79109a0802e06d0437e6938e87a54c1d646e9bacfd2f51b31b7752",
          "sha256": "0d08aa47701f00ae4715f2f911ccb57fe32198fa0428db0be52df1c17e367e17",
          "sha1": "9fb24cd643b4dcd8bed9d86a800bca609c298f64",
          "md5": "4edda202bffaed60297276c528a8aace"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosarm64-0.6.1-SNAPSHOT.1-metadata.jar",
          "url": "runtime-iosarm64-0.6.1-SNAPSHOT.1-metadata.jar",
          "size": 2428,
          "sha512": "1fc155bcc60df5e62e26051104f5e9e88893dde18d55ed3b4ac0ee865d6a5711d076cb336557f081fc8a749e66c40136fb7b5ba9c4c4a732707abcae9f799de2",
          "sha256": "524727f15e73d569562201a1df9bd8917e131b23d9008d352413a6367b1bdd37",
          "sha1": "3c7c3829abd890d12f745382d2b018aa3321a665",
          "md5": "9e23401d4b6e8da0ad4827f99e028eff"
        }
      ]
    }
  ]
}
