{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.7/flow-wrapper-kmp-0.5.7.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosX64Main-0.5.7.klib",
          "url": "flow-wrapper-kmp-iosx64-0.5.7.klib",
          "size": 78857,
          "sha512": "8b1bb3bbd0c0df62d7e06ca72a90962b4b994b1032b0f71c3214de66677b5d7c350a3474a7dfb72b2f7080b8e46a85c4be83e67214a3f2a5deb358fdf894daf9",
          "sha256": "335291c7c654cbd25a0622cd30bdc3d2d04583190b4e9daac43e13bcef46ccef",
          "sha1": "9a2c6ec8d03b1d8ba7a0efaeb4214dcbf18f3f79",
          "md5": "011343396b00681b2c82a078f94e18c0"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.7-sources.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.7-sources.jar",
          "size": 13311,
          "sha512": "781190e2e87705b8a0946d34f21053d724aa2f94ea5db3e17bdad23d3d6f672d97681f4c81428aa300889c90c6f4d33353b301b3a463059d0e969124ee4bfed8",
          "sha256": "e8efcc13970736a458183f946016770be8fbeb5c73289084057ac32b6f1114f0",
          "sha1": "935384d72c77a9a76f5eeedd06eabe6279455002",
          "md5": "227a2f28f95eb7935de489fdf4591818"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.7.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosx64-0.5.7-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "060da01ea2a2646bbaa07c373ec134f33843617a69ab61c6e065f85addf9daf1c35d49bc228d11a160ea6a8bf86117c210553db33b8cb4ca13ccf03dcf73a143",
          "sha256": "aac1d8899440d2a124a0b51047bbdd5fa60dcca20c6b5f2177d5012ac78025f1",
          "sha1": "ebb916f0bd420544126b8dd0a0c865b97f977d0d",
          "md5": "e73f3976d383b08d212fa76b639d16eb"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.7-metadata.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.7-metadata.jar",
          "size": 3010,
          "sha512": "202776993a97ffacfec545429f2cccf9956de45bdebe3f8a439b80b54980b583a1b390710f1f882d4e9a0cfd98fd46e846208a963e3e6b747fb1a5d1ea1f2913",
          "sha256": "25528df50e2c5199f7235200020f90aff5dbd4eb2a9b575a4bd42a7864ac22e0",
          "sha1": "29c6f839556456fb7753665899dc5ee319177ddb",
          "md5": "5297dd334ea55f209a25b12b18507a1c"
        }
      ]
    }
  ]
}
