{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.7.0.2/runtime-0.7.0.2.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosSimulatorArm64Main-0.7.0.2.klib",
          "url": "runtime-iossimulatorarm64-0.7.0.2.klib",
          "size": 684949,
          "sha512": "80bd629234038c1fc72f59ac6dbdf6d24db834e62aa620276202258597797a8faea684d5099d0b82274eb0124a98b884eb6a83ba447a9a017f93ad777f127699",
          "sha256": "06ce5f22d6cbf81ddd82c114e5dcddde63935b2cdb8d55d7d65dcbde52080b17",
          "sha1": "9ee2fdbe0156287382179101e5ee4b0ead7e45ec",
          "md5": "5bd70e11d706479a414d081fee54f08a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.7.0.2-metadata.jar",
          "url": "runtime-iossimulatorarm64-0.7.0.2-metadata.jar",
          "size": 2428,
          "sha512": "711f5ca390159d612573ec2a8e522168173e93be398d36b7969d8e0ec22c70bf5d358f189b5a97d83f38d2d2691a2f37e465e316b1667806f8016bfe3f0efb09",
          "sha256": "2e5aa2ac7649a28f381b43b1425634674a0b3c42afc217b1a39a706ec0785b3d",
          "sha1": "a55724604203d6fc21eea21424e2023cd2cb327a",
          "md5": "bda22afd6ed477cc134fff109d4cd9e3"
        }
      ]
    }
  ]
}
