{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.7.1-rc.238/flow-wrapper-kmp-0.7.1-rc.238.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.7.1-rc.238",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosSimulatorArm64Main-0.7.1-rc.238.klib",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.7.1-rc.238.klib",
          "size": 302534,
          "sha512": "ca7b0b3d6f44095557bc058a803d60461b84bc342e30e0d1c9fc39ba71a39298d96964c65e54c57f333280b9b32fc7e47f239bd01e089d0c06d82e715bcee8af",
          "sha256": "a33896d3e9f73334e33a949b6f5550cf57801231d18bd3d43ab83c180eecfcf1",
          "sha1": "80597e2a1da7ff2e85145acd915a494617225024",
          "md5": "5b341b5cc769388f2ddbbca27d12ff91"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.7.1-rc.238.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.7.1-rc.238-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "7e9e8a1ee675215f3eeb9e50e073124f1d766bc753b3a849e6c6c0e04d4caa8d43f18a242eb292403a52c4d7c27f987fdfa809d768f0d71c080c5a86ceefce75",
          "sha256": "dc3822e3e1d741d40f07a4f247c0eb2db51f6d359d1828b15d146d420643c7a0",
          "sha1": "eb7274acc7a24b8ffe17848ca7b0a19383ff3704",
          "md5": "2dcc4c56ec95b5728edf7448ceb0c4c6"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iossimulatorarm64-0.7.1-rc.238-metadata.jar",
          "url": "flow-wrapper-kmp-iossimulatorarm64-0.7.1-rc.238-metadata.jar",
          "size": 4576,
          "sha512": "6cf294c11a4c791f126911e126b2cc87fa7cac0bc9e01d7208c0d5a98b77ce6ff6c2674e9c1db949692899d9f1e190280a2b397e9f3b374fbd6b019850e1cddf",
          "sha256": "3799f8a318029c6594598782c48c6128c119ab756e9afbd2d4b332c884fe5a98",
          "sha1": "d7fad665526c34e61e9d0b83ff5e2e680bdcae6b",
          "md5": "49251c9b8c060788b01e1f6fbf5ccb48"
        }
      ]
    }
  ]
}
