{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.7.0.2/composeblocks-0.7.0.2.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.7.0.2.klib",
          "url": "composeblocks-iosx64-0.7.0.2.klib",
          "size": 393340,
          "sha512": "9a2d8829f4e8c2236ae365915049d14b74b30a8159fe080a981baf6bc90dd7021477618aa55fc6addfb18ffad796ead19244f9539df02af74c96d2a3251b73ca",
          "sha256": "8388d2cacb2e347e4743ecdee53de226f28615f74b76dc348e96137d9c724328",
          "sha1": "879714687e33f7a03425375fabccf0ffcbb37ec0",
          "md5": "c0b959b4c32ab9520e16efac66fe964a"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.7.0.2.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.7.0.2-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "008f822e7fd08b2d0f7a2396c783fd4d921a2a0f1859d54dfbea0974a0567634a854e499444c6c6bd390e4e43d3dca1b430c93930ae24f569a6fe77148aa32ef",
          "sha256": "18a9e51fd1f0d474498247e4266e7cf788fde4b39512e19abfd6bf9d4b2dfb4e",
          "sha1": "6bbf32074f0175d311cc571a366fe6fad158f152",
          "md5": "b600347529a2cc6622c3e54c2877054a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.7.0.2-metadata.jar",
          "url": "composeblocks-iosx64-0.7.0.2-metadata.jar",
          "size": 261,
          "sha512": "d9472052d7bf9384219aef1aaf638c800fa590948db971ab5e3b2243d4dcdb48c7c8e29396a990c983b8c57b92a7ba049c82b2127de5c673e7316b2eafda847c",
          "sha256": "f56a5c853f4b57ea31563cb0d02ed71b167b58efab248ba08119c0a01fbdfc4f",
          "sha1": "2cb83e51136a75b450212c4e884c618294e4937b",
          "md5": "7d4489e5dc3f40a279870cfc8bca632f"
        }
      ]
    }
  ]
}
