{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.6.0-SNAPSHOT.26/core-0.6.0-SNAPSHOT.26.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.6.0-SNAPSHOT.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosX64Main-0.6.0-SNAPSHOT.26.klib",
          "url": "core-iosx64-0.6.0-SNAPSHOT.26.klib",
          "size": 101557,
          "sha512": "dd30cc5428330ca805dabccb224465779c22a913d7a7c83e2ab54f139762b39afd6462a926f604101567100120b9f3cb90ed2ed572e0274a8899c9f3207ffd3a",
          "sha256": "7f3d9cde978d7e1bc0affbe24ff8ca1b03eccf4ef5002cff687eb5a5bd649d98",
          "sha1": "dd862715eaf51db488cc5ca889a80ac3377c46ec",
          "md5": "913b0ac160a5f627f17d69ffb35c3a44"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iosx64-0.6.0-SNAPSHOT.26-sources.jar",
          "url": "core-iosx64-0.6.0-SNAPSHOT.26-sources.jar",
          "size": 12871,
          "sha512": "9384b55817f88f910ec57688f568f23c7334e431ee50978b193d247dc6dc8604297381b30757d73c8c22a3ea4f3da34334acfaf4bfa1121de726f0027e0f3235",
          "sha256": "cbafd42c100bb7358370dc203cd61d4041cd683b48d69db2eda1e6514b18e617",
          "sha1": "20061d10ddcd97c4bb4a9c49602da7d79000e539",
          "md5": "337280c1de2570f705980fc4fe7f6037"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.6.0-SNAPSHOT.26-metadata.jar",
          "url": "core-iosx64-0.6.0-SNAPSHOT.26-metadata.jar",
          "size": 261,
          "sha512": "1fea074d13abb19e4c93283d5bacbd5a97ef9a798fa7c04b406961160deba4f72bf57475b09202656da1078fab65f4baa40dbd2ad46c5efd64afa3c13be79db7",
          "sha256": "7a15f9419b26021dcc3dddbf4e88cdeb9c02919723eec09febbc974fd83e6792",
          "sha1": "5c43948adbc3ac04cbe7db30e644fcf95d90d37a",
          "md5": "2479a6b23050945e2f7ace9bb30d0909"
        }
      ]
    }
  ]
}
