{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.7.1-rc.241/runtime-0.7.1-rc.241.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.7.1-rc.241",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.241"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosX64Main-0.7.1-rc.241.klib",
          "url": "runtime-iosx64-0.7.1-rc.241.klib",
          "size": 858653,
          "sha512": "b51ec3269115cc4a9490beb94afb248a47fac997da188a03eab9a249d70a9ca112c98c16be1b3bae1413d7a5081ee13b3b8defecd8bbd220c7b2265ac8cb7b1f",
          "sha256": "a89091cc0b2ed3a4a0ad927f764031e2bcc0d7f15c886402cec47ec7130e552a",
          "sha1": "85c5757513bcfdc60ed35d1ab62ae2218adc941d",
          "md5": "cef8831aff317a975ec36ffee3254b26"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.241"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosx64-0.7.1-rc.241-metadata.jar",
          "url": "runtime-iosx64-0.7.1-rc.241-metadata.jar",
          "size": 2428,
          "sha512": "5dfbb34f217cd39818f466d41bdb7335ce7759e8ba5070e1c77e688f55d29f5b07c8604eef153dd3478d936e15c9162a0f53ef3bc13916bc69d0d20e21f0b718",
          "sha256": "240f30c03e269c13fe495c13dff46ed857906d76d7c562435e613a27a890eefa",
          "sha1": "59077b294efd4d4db992f0e64db6e41bdc02ae91",
          "md5": "41005794482f72f1c0b8a1d2198ecaa7"
        }
      ]
    }
  ]
}
