{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.8.0-rc.261/composeblocks-0.8.0-rc.261.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.8.0-rc.261",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.8.0-rc.261.klib",
          "url": "composeblocks-iosx64-0.8.0-rc.261.klib",
          "size": 465672,
          "sha512": "980b1e51dff7f6a25502d2a97abd8ee7115a75a65c794c46fc5cb518919c4f0f68eb71ec2d42f556ab6e48c38220e40e7cfdf4f29ec8c157e65009f92b54a09c",
          "sha256": "a83cab25641e2ddcff00cdd0420f3c8566b18f84d16c2a160615421138cc7cb7",
          "sha1": "a96be6a7607900926165d7b4564c1fc953339f8c",
          "md5": "9b0b32faa29fd152616dee04114123e8"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.8.0-rc.261.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.8.0-rc.261-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "ec7159440060702dd68d9a446683f878a0c257aa576ea2fb119625c7a9d0ee0fa42da39104db1fcea8989459934fe73fb3378c7dce448a9c8eda8768a2ca2625",
          "sha256": "95c5473111bf32cade651665a19a5141834a0081a92f5dbeb2132ed9abf3dd8b",
          "sha1": "7e530bab43ccc42977a3543ed5fa125d318090c1",
          "md5": "fea63138de9156493c62a42718d3e7af"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.8.0-rc.261-metadata.jar",
          "url": "composeblocks-iosx64-0.8.0-rc.261-metadata.jar",
          "size": 261,
          "sha512": "daad830ec680f4003476dfd3283548eb5609ea5712f81c388918b4736364792db762289669d01189e430b89d5418f07e421eeb1fbaf4093830bd7b42937c69ac",
          "sha256": "fa0092acd8dbe8c501822ecb37a023657eba529bfc74489a40b4ee9c4f22762b",
          "sha1": "aa139a98538d89ce774070af1ecd060a9ad2b1f8",
          "md5": "8000a3550e1f8f5e32f8fb798dc4f639"
        }
      ]
    }
  ]
}
