{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.20/composeblocks-0.5.20.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosArm64Main-0.5.20.klib",
          "url": "composeblocks-iosarm64-0.5.20.klib",
          "size": 347008,
          "sha512": "521d2016e352fd5d4300256af33294babdc35bb78a110ca0bea4af22d16d35e1f818f2cc8201d56184c5c4239032a11547eba3485b4572257ce1906c9b12069f",
          "sha256": "e38d8d8b69c2fe312aebd4fba62b2bda11fc6cb94b7d03779ca36402be65f7bd",
          "sha1": "7d4c78b49f3d8d12217f420546ab2b1600f2c455",
          "md5": "f76e22f535f586e9454fdaba50f4b356"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.20-sources.jar",
          "url": "composeblocks-iosarm64-0.5.20-sources.jar",
          "size": 62929,
          "sha512": "a1b6fc6d924260f33998241e03ec24748d5c5dfd0113774ba6737d13cf12976f05d7730d8a31102924f3f379dc14469fbbbc54a33812c1b3466749ccc47684d1",
          "sha256": "c060c74601af62602de4fce2f88037ef006540f40ab0fc07a70a191070214b78",
          "sha1": "16aca03e0bca1374655d6244d13d0ebffcd27f34",
          "md5": "18983dc3d325a95705ebeb14c1ac28aa"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.20.kotlin_resources.zip",
          "url": "composeblocks-iosarm64-0.5.20-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "d6d170b08657c5a176717b2946e7f7450c298daeda3fdf082b08643abddce60d4b588413256239f6e42803a60b48b3f4971206b88f7f8bbf84ce882b671a82e9",
          "sha256": "a2fa0dd4a35fea649073279cf692e6ca4503ae9bfa3adcaed5a00c38f74f2d6e",
          "sha1": "99a6eba16a5ebf43a7079c2f29da7a253b0d1b9e",
          "md5": "44de22ff248b4e0f491a3e902f178cc8"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.20-metadata.jar",
          "url": "composeblocks-iosarm64-0.5.20-metadata.jar",
          "size": 261,
          "sha512": "026a2610e9215c43385da0e29bf29d589d0f4547706b11b4b3476e79d446ab79f00ad51553aa0ea4b245e7129b0b6a68a781cf4007a78309c431b97385e92fa1",
          "sha256": "6bb9926131860f80f16b82e73668980039d0ee507074b5e075b4eaf3d68f5f5d",
          "sha1": "b5b1eb12335fdecec5f7980f165b80dd5ccf0969",
          "md5": "c7166c1c6a2f4d3c002bc865a6ce2914"
        }
      ]
    }
  ]
}
