{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.9/flow-wrapper-kmp-0.5.9.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosX64Main-0.5.9.klib",
          "url": "flow-wrapper-kmp-iosx64-0.5.9.klib",
          "size": 94251,
          "sha512": "10bf4843c9e4fd0d3fe3a9343f534ae3d1e13974f24c6dd6521bb12139ecfa62114cfcc1446d3e983e49f9021bb12aec3b69527134755cb6324abf1abcf64ba0",
          "sha256": "b9eeef71b5c7dfc92d66a1f11cea00fc212d26272804fa25fe1950cd3d2e0be7",
          "sha1": "1fd21ce41bbfa8cc5da1568c6e627c19b507c04a",
          "md5": "1dabf8324dd75082bce14fc465b8a719"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.9-sources.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.9-sources.jar",
          "size": 15704,
          "sha512": "24edb05ab070e43fe55d302e997d472a1ad165b5191d901833bf8f940972747706497a30b9117684ca1b57a3eb34d17a459d427d77c5ad4ba5adc605bc762129",
          "sha256": "67d78c87dfa1b6541ac7fecda17a10132e3767f92af554b5bedc2c2f299d9cac",
          "sha1": "d5ca871bb4e4f5753c7577f58b2558f7666e63c4",
          "md5": "76a98f529710562bd7b7d616c5bf59d2"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.9.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosx64-0.5.9-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "744fd7d4ca682d9aa56cbb5187c6382a781ab2b4d7b716651c1d122cc415a106e53df40b62b0f48c862bdcede11573ff9f579628136848e9b7cb3276aba39940",
          "sha256": "80ba8dd3c234f743e04f028d2d59aa3a4e6229b7d8bc32de9e1b0a62817a644c",
          "sha1": "411aa0e43827eb8285f49a56d1f5b3d450105b65",
          "md5": "97694b8fef9a58f315b5b906c64b1187"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.9-metadata.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.9-metadata.jar",
          "size": 3352,
          "sha512": "d67ac847ffd1c55c828f3287ab6763a934e754c05b180597171f0f97cc22ade748ce9152701d8a89c8a9e6a730c6bbfbb2e2c5e2d505c69bb8d79797e7bc3c2f",
          "sha256": "c4c624b631e4ca465c780d674452ee218fca74eca19a44910e6cbf2abba55ff4",
          "sha1": "acbaef3e618aa79783f734fbabd48a636d549b17",
          "md5": "f31b9fac5ffac2251521710646575989"
        }
      ]
    }
  ]
}
