{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.7.1-rc.239/core-0.7.1-rc.239.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.7.1-rc.239",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosX64Main-0.7.1-rc.239.klib",
          "url": "core-iosx64-0.7.1-rc.239.klib",
          "size": 235778,
          "sha512": "1c678b4a7d1aa1505124412c2b4b85f27eb9a82a8097c2c298ccd9c3a6342a38d998a4e590fc0c50ff090ef05e72680410c561f07971fc55a39d807a3982c9c7",
          "sha256": "0f93b141072e2a924d4432efb3d0ce203b1096fa2edb96fe6a443a505c316054",
          "sha1": "35c74ac91bbdbe78dae2cbb74bfc103ae11af596",
          "md5": "0105305b1bc3dd169668c98308f2b58c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.7.1-rc.239-metadata.jar",
          "url": "core-iosx64-0.7.1-rc.239-metadata.jar",
          "size": 261,
          "sha512": "c56b43eff4ba1a00ed1a50fb1647db992908a24043d7d7571a081a138e21766ec7d04fd36bba6b4ee9358ef73b74e235004f7ccee9cfb19f8200a02230a1ac8d",
          "sha256": "1f30154435faefefc2948383a1821a3444aef4456c6be0c8631e14348f663b19",
          "sha1": "253f929fa0e35c4ffe3c87c89ddcf73e88ccd68c",
          "md5": "5a850dc9affa01f7e083c06507e09097"
        }
      ]
    }
  ]
}
