{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.5.15-SNAPSHOT.1/core-0.5.15-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.5.15-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosArm64Main-0.5.15-SNAPSHOT.1.klib",
          "url": "core-iosarm64-0.5.15-SNAPSHOT.1.klib",
          "size": 121209,
          "sha512": "c6e1aff4723b6ff432f6776bf408d78ae23554ee8b0a5d254ae87b7a0ad50f5b52cbe465b758ae8ddc53685aae2558f0f7e219ed2f3cfacadbac19a3fc780d19",
          "sha256": "71ecbf3ce8d2ce24ae329b6549e94911c86870e8b5127d3581149ef701b7763b",
          "sha1": "f51986a73c220dff71ec9f0e1becb08aa3b0d8f4",
          "md5": "614c6ab801d67d6a177db401db16cec6"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iosarm64-0.5.15-SNAPSHOT.1-sources.jar",
          "url": "core-iosarm64-0.5.15-SNAPSHOT.1-sources.jar",
          "size": 18169,
          "sha512": "f8335fc9598e964a6ad61d5a562f5f49a9a4ce89ead746c9ec3d13d2b9567ee18775e22ce47a4fa2ddf0fc50f73e835f99560a109a7ead9f679fef87895ae5b4",
          "sha256": "ef43d06e0850a567869b1f021d174c2f21b122579a07a1ca04445d4c2ba8a084",
          "sha1": "a23c78c369e3ed09ffcec4b159e75b5b0b9d53a1",
          "md5": "1781c02ee9f043240940dcaffbf6e679"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.5.15-SNAPSHOT.1-metadata.jar",
          "url": "core-iosarm64-0.5.15-SNAPSHOT.1-metadata.jar",
          "size": 261,
          "sha512": "e93a427f575dca384727378049ab32195522e5e63701947b21e0e2df9f664eba68d217fe015c80a0421836acc0d7d4ffa561509142684563e80b410537f9f43a",
          "sha256": "8da42f1bf16dc0469e8e72672052fd492cda73eb38ab15da513b4d65fb3b68b3",
          "sha1": "29bd4e1d25812e0729ac52a5e21378771e52cfee",
          "md5": "aab8bebcf16e95505cd64b41837131c3"
        }
      ]
    }
  ]
}
