{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.18-rc.116/composeblocks-0.5.18-rc.116.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.18-rc.116",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.18-rc.116"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.18-rc.116"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosArm64Main-0.5.18-rc.116.klib",
          "url": "composeblocks-iosarm64-0.5.18-rc.116.klib",
          "size": 346287,
          "sha512": "fb8fb5feac7b0aa8fcff26b8c8225562dc85df05efc9954a31342a40ffedeec5d7dbb6562394da7c7b22d54061a7893dbc7f607231c75937cccc00e7ec50a543",
          "sha256": "2651745d2a14cc6cdc5f7fa060da5ea1af735bc537275ed429f85c27b9e86519",
          "sha1": "726477a0372392a79d741629c536bb232a17675d",
          "md5": "f8b904c73f5940f86a3f59f97e95b310"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.18-rc.116-sources.jar",
          "url": "composeblocks-iosarm64-0.5.18-rc.116-sources.jar",
          "size": 62231,
          "sha512": "cfbfe2bf7b7416f7af8f97aa075f8b57d3969a5017052c4d671bd69718e963d7ff1dcd1cfed19a311f81a9103a224fc48ab4283f6c5a8c83c59b7f7f89fe6172",
          "sha256": "e761524c5ac32c9653ead0e6a1f263738e0d2182ff6f9a0ca8e79de42d779531",
          "sha1": "0b235e3d8c927ad8b3eddb08fad6a492a7394142",
          "md5": "182b7e2476de6a929ce1da2235eea64c"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.18-rc.116"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.18-rc.116"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.18-rc.116.kotlin_resources.zip",
          "url": "composeblocks-iosarm64-0.5.18-rc.116-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "a61ca86e4af8adf982b28920cc9a80e0f86118ef3165e4c5101635f0976e8adc15ab208a8b8350c62e0c3268e85acedddb5ba789c535e76043307bfd8dc0a27c",
          "sha256": "91a49fc612d2916d5b69b0fc9f4d3bb5e758172a4db3f3464d67c0cf2d4d7af2",
          "sha1": "39a08130f59237ef206dc2496c56f49be1c32e14",
          "md5": "c65277e9b2100b416679b3c48df3e6d9"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.18-rc.116"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.18-rc.116"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.18-rc.116-metadata.jar",
          "url": "composeblocks-iosarm64-0.5.18-rc.116-metadata.jar",
          "size": 261,
          "sha512": "acf95004645a50747315da01139e29daac822dba273b1a82e9250ca477dd925a8bbc757f2350781ec90a45ad9ab0b36d77d0a7111e96ed860379ddd7f2389675",
          "sha256": "9e826e671dec49840661cebf02efb7eaf4a4a491e0c11ef9a4759c8086b5390c",
          "sha1": "40bc615b4281ae0d4f8e32bfccd2a91a60a6753b",
          "md5": "bde661bd108b127ce26ea9f5c6ec5d0b"
        }
      ]
    }
  ]
}
