{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.12-SNAPSHOT.2/composeblocks-0.5.12-SNAPSHOT.2.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.12-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12-SNAPSHOT.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.12-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.5.12-SNAPSHOT.2.klib",
          "url": "composeblocks-iosx64-0.5.12-SNAPSHOT.2.klib",
          "size": 224284,
          "sha512": "ed461d51c1a11762041aa82a139852aa54ee2277d40582b1dd79bb5e383eb0c2f98d9d550de916aadb2eb2cf1f9e8ba9bc0aa711a41c9c09474757a38875a4d8",
          "sha256": "3cc65df49b7e71b896b4cb8471e4f2ab76420883a2c2f30ca1b96caa101d4f9c",
          "sha1": "457d05f3131ea8abce554dcf991f8c226c948244",
          "md5": "1331d1a7e614b206040e75f3ab63c7a5"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosx64-0.5.12-SNAPSHOT.2-sources.jar",
          "url": "composeblocks-iosx64-0.5.12-SNAPSHOT.2-sources.jar",
          "size": 36171,
          "sha512": "23c4853c4c5ee3e6ac70f0d156f7edca210d60c462afc04368f907794a7dd2bb486270d34bbf5a74f3b285ae3096689a8043dbeac4e6731b501f0447b4c97010",
          "sha256": "27d5e6dbc67211882f5e0804adf3872f8687745226d6a4874e42cce92a4b2e3f",
          "sha1": "5993f83f60b0d937068cf7414394a0621ef03b5d",
          "md5": "f7e8a769e83320cad5d567a321b1c829"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12-SNAPSHOT.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.12-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.12-SNAPSHOT.2.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.5.12-SNAPSHOT.2-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "9b132bc4247daa0cfedea0b8b1e0b15f9676c8d50e646587936542b2a01b9652410e39aabdbd16fb8cf1e07592007708700dd7e67d9e0835aa2758a092860082",
          "sha256": "278fcbe4453c5e20173c790711cbea1b722f528fd61ae52b4ee145bc4a195a2d",
          "sha1": "f0923fbd131cec231c3bfa918022c33e2f15d4f1",
          "md5": "d6e4f1319b8fb6d5817952e6d46b2192"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12-SNAPSHOT.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.12-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.5.12-SNAPSHOT.2-metadata.jar",
          "url": "composeblocks-iosx64-0.5.12-SNAPSHOT.2-metadata.jar",
          "size": 261,
          "sha512": "f7a9c779059ef0ffcd425eb7a88efa4b247f995242e38b9c415ff611d348709feb84164a920b2da4776fff732cbbfd6876863f43e7a445d688bda87351048264",
          "sha256": "93715b97962a8b7b549da691b9b792a627c655acdfbb3cee5250a9e1fb5fb92e",
          "sha1": "38be0db2d6ce71e9dcabf431d691ce414440f1b2",
          "md5": "c24724fed6e29723515378d3d55ebd7a"
        }
      ]
    }
  ]
}
