{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.8.1-SNAPSHOT.1/flows-sdk-0.8.1-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.8.1-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.8.1-SNAPSHOT.1.aar",
          "size": 170690,
          "sha512": "2769cc567710858caf82718b2da0c9f74da58f5da0cd46d95386c19ebca0f0b1891d7b265b0bdf09d911f6a6e9a94b89b841219967d7ddcb9078246d4d827670",
          "sha256": "5a4087a718e603a53d62a6e084c81953707dc2ac64b58b0d56f113750d47eb35",
          "sha1": "792e546e17b4a630c1b7e80866035cc019d4e473",
          "md5": "803667dfead5ffba2e621b0ae4526f79"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.8.1-SNAPSHOT.1",
            "requires": "0.8.1-SNAPSHOT.1"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.8.1-SNAPSHOT.1.aar",
          "size": 170690,
          "sha512": "2769cc567710858caf82718b2da0c9f74da58f5da0cd46d95386c19ebca0f0b1891d7b265b0bdf09d911f6a6e9a94b89b841219967d7ddcb9078246d4d827670",
          "sha256": "5a4087a718e603a53d62a6e084c81953707dc2ac64b58b0d56f113750d47eb35",
          "sha1": "792e546e17b4a630c1b7e80866035cc019d4e473",
          "md5": "803667dfead5ffba2e621b0ae4526f79"
        }
      ]
    }
  ]
}
