{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.12-SNAPSHOT/flow-wrapper-kmp-0.5.12-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosX64Main-0.5.12-SNAPSHOT.klib",
          "url": "flow-wrapper-kmp-iosx64-0.5.12-SNAPSHOT.klib",
          "size": 122606,
          "sha512": "efe9d542f6d46640e55462f4b221618fb7e5911369e3095aab4d83c5a8beb9bccc748b4faab190160c29c0b5f88d74c0476dd1deba6db0890e9a4ebaea784187",
          "sha256": "a60f487e20758429159cce3b462c2dc2a018c1f1b38e41c8eeffe76d7f98f0d7",
          "sha1": "2b405e9524a2da46c13574938c6da9debef256d0",
          "md5": "5cab011366013483946fd1e8e04e6cd4"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.12-SNAPSHOT-sources.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.12-SNAPSHOT-sources.jar",
          "size": 21589,
          "sha512": "6014506976bbd10c06ee063808430e25547bfe61988d8996fd85655e37b962414a93a2c6540a50e3bf2b57504bb92d58530e07d3e14b95ba5d7d4873a68692d0",
          "sha256": "4566722e780b7e23a164f7ddcb46da20573ddb68276fe04c34a98a9b62c305e3",
          "sha1": "54287e065d51ddbedb628742a9299504309ca093",
          "md5": "1b87968741570bd51fcdd1ab1b7b20dd"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.12-SNAPSHOT.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosx64-0.5.12-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "d65bf6c7efdd37e3515a994b805d6638c8fda566ece278c36780b42d69f5be9846eaa52edb5a07d2bf1244f77a804dabfd1f7ca38d59be100ff68b90e9fcf30f",
          "sha256": "a2b497f22236b5bd08a4908086dca509dfc7d132b47fea47497569340b62315d",
          "sha1": "8fd017432969d0139886ac8c619fadef976e833c",
          "md5": "2bb63fa5843864a99e900fd0fe1fcee2"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.12-SNAPSHOT-metadata.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.12-SNAPSHOT-metadata.jar",
          "size": 3469,
          "sha512": "4988dccde408ac5e04f26a6dbc8383edb1655b42f849e7c6ca7d7a715082644299a7dd5ce6506adac2468e0131fa924c7b753f889ddd90c04c29dc24ba46967f",
          "sha256": "821664e195ce18361eb958e61f8dd0ee414c5985c5dbaeac6a2207c554bcdca5",
          "sha1": "41bf852ddd109980b54c0e4c8d66140050bf467c",
          "md5": "eda3985105637edac2c103601ac39af1"
        }
      ]
    }
  ]
}
