{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.16/flow-wrapper-kmp-0.5.16.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.16.aar",
          "size": 212376,
          "sha512": "f1fc7421156b179a59e07b0dd28c5de1b29d9de35c3b9e52906408039e1caf39841807aeba0fa717f3247f80edf5d7773eeea3f6c4f6d3d55731d11906ef71e0",
          "sha256": "0952e7d7f05091409bde4e21ea2eca282d9853266d24fb8f852a21d915c78aaf",
          "sha1": "ef6c790a8a618a9fddce17d6f4b1491db45091c7",
          "md5": "02a9d936cf192a82c22352900bd8ff6a"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.16.aar",
          "size": 212376,
          "sha512": "f1fc7421156b179a59e07b0dd28c5de1b29d9de35c3b9e52906408039e1caf39841807aeba0fa717f3247f80edf5d7773eeea3f6c4f6d3d55731d11906ef71e0",
          "sha256": "0952e7d7f05091409bde4e21ea2eca282d9853266d24fb8f852a21d915c78aaf",
          "sha1": "ef6c790a8a618a9fddce17d6f4b1491db45091c7",
          "md5": "02a9d936cf192a82c22352900bd8ff6a"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-android-0.5.16-sources.jar",
          "url": "flow-wrapper-kmp-android-0.5.16-sources.jar",
          "size": 41882,
          "sha512": "8f5e3a875e77db40142bb381b1009a5043e1be2a4efb134508730dedf7ff75c08e200744dd5d2d78d8df33b333d2b2d988d4603bef9a71b49ce12003dde2a909",
          "sha256": "0a9b23eeb9fa9e784fd1be95203c3ed6b2254b0d58778e7ba542874ee9bb708f",
          "sha1": "aa5e0eaf9ca5fbd897cc4d6d13c47104b69ef444",
          "md5": "5c2007b50cf046c4cee0bcc755fc7d49"
        }
      ]
    }
  ]
}
