{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.18-SNAPSHOT/composeblocks-0.5.18-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.18-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosSimulatorArm64Main-0.5.18-SNAPSHOT.klib",
          "url": "composeblocks-iossimulatorarm64-0.5.18-SNAPSHOT.klib",
          "size": 344668,
          "sha512": "03c1e553290f80039dc5de2343b0c89e8d7bfa7999cc888c7c2d7adebd3fad3d0bbe3d2010c22eb6cd4e2f8e72264f53a5ff0fff1908b27b70f68624cda9f872",
          "sha256": "d9bfa7547cab0ddc4ea1d2be59658004ef670f6e5ae2edb4a9ca45aa897aea90",
          "sha1": "2e9ade820d13981fcc3f6bfb02e55145b294d933",
          "md5": "455d3a3497991d4040ea5237cdbcb04c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.18-SNAPSHOT-sources.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.18-SNAPSHOT-sources.jar",
          "size": 61722,
          "sha512": "a82fdd47d7da96a81aaed8005a4b941247647218ea9a2627d23b72f664c7a8e238c3487104200057043a82cf69d3ae685cab9f7bf60d01d21e624abefb12764b",
          "sha256": "c08a32ed59f8283e6f8eaf4a51e9dffb804eb86bd14f8c78ff5a9721c2e36866",
          "sha1": "d691f285cd7214d60faf1d3a6646ae63791df966",
          "md5": "05c64f60a31443a21663cabadb1d5ea5"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.18-SNAPSHOT.kotlin_resources.zip",
          "url": "composeblocks-iossimulatorarm64-0.5.18-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "406ed4038475bcfbfcdd412a37e75d359393be3cddc99cec8341fe0a36d95a6ae9330d0fcdf2db35cabe47fc1a6c24571a864a4a6e23544fc8a31b90910b64ce",
          "sha256": "1052042c3b3eb6ab652906a3d215985c1ea863f3051749f430cd005b143b4122",
          "sha1": "0458728a10cb7932176c9ebe0c9ebda27f3810a9",
          "md5": "0c601982f0b5aeaa64ceb69642d502b1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.18-SNAPSHOT-metadata.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.18-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6b099e98f4ad5f0be4890e15e2da9958af82e1892221e639d8144ef6b4c1687134f45a88b5efd6bc2b24ae142743d189996c03a1522661c371af11032a6a265c",
          "sha256": "ca0ca538c88b74a1a747b65ee6a8163ac4f2687fe562ac2c4977c17354b86223",
          "sha1": "88def4fac291c5a773251e57d8760c366ef5dcd3",
          "md5": "93dbf4ae6b1c7813f16f183b33b7fbf0"
        }
      ]
    }
  ]
}
