{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.6.0-SNAPSHOT.26/flows-sdk-0.6.0-SNAPSHOT.26.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.6.0-SNAPSHOT.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.6.0-SNAPSHOT.26.aar",
          "size": 53185,
          "sha512": "801f4f5fc727dc5b1d9c92c32829fe607db59b49193463922a64ae518944ead0d70709c44c118129754c45cd71c39e1c9e3c85e22764cb8e20378822903ef3a7",
          "sha256": "3b37f5ee8b12eded32e9a6378c8edc1d58b5155ac85de7efef47d4f31e987739",
          "sha1": "604ae09cf764d87403ff8bf0f74136f401f541c4",
          "md5": "a1fe1b312d737315bf59afff582aea72"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.26"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.26"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.6.0-SNAPSHOT.26"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.6.0-SNAPSHOT.26.aar",
          "size": 53185,
          "sha512": "801f4f5fc727dc5b1d9c92c32829fe607db59b49193463922a64ae518944ead0d70709c44c118129754c45cd71c39e1c9e3c85e22764cb8e20378822903ef3a7",
          "sha256": "3b37f5ee8b12eded32e9a6378c8edc1d58b5155ac85de7efef47d4f31e987739",
          "sha1": "604ae09cf764d87403ff8bf0f74136f401f541c4",
          "md5": "a1fe1b312d737315bf59afff582aea72"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flows-sdk-android-0.6.0-SNAPSHOT.26-sources.jar",
          "url": "flows-sdk-android-0.6.0-SNAPSHOT.26-sources.jar",
          "size": 13680,
          "sha512": "fdd79064a580d9d69f2eaf78d4b16ab5fc59f364c502c16f585b335d95f61b3afd68c6e65d43064f80bc91fb4063d76d0ba6ba97e7cfbfaf6438c0e66f03e4f8",
          "sha256": "64f02ecdd9bcd7a482449a4c61f6cef2a3229929e50d6c2ba906468fa4107f23",
          "sha1": "95f5aaa35d171e71b7a221f4ff7bf9a791cf3973",
          "md5": "bb2af172359e6e18f20332086e2e90ab"
        }
      ]
    }
  ]
}
