{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.5.20.2/runtime-0.5.20.2.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.5.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-jvm-0.5.20.2.jar",
          "url": "runtime-jvm-0.5.20.2.jar",
          "size": 856793,
          "sha512": "ea401b2e789889d8888eaac4478d97b016eb2afb7c0f957e1fca50105b79226484210283c91208cfc2172cfe1dbeb79594908bc71893888b38c72e8c2a1b59f9",
          "sha256": "39453b1d21e50c4b4db3283bd71daf4703b6deed278ac18a341dbac8989166ed",
          "sha1": "f545a9655b90966c722c313fe92653ec05677ddf",
          "md5": "6e4eb088ec981f3b79c2c887a39cdd69"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-jvm-0.5.20.2.jar",
          "url": "runtime-jvm-0.5.20.2.jar",
          "size": 856793,
          "sha512": "ea401b2e789889d8888eaac4478d97b016eb2afb7c0f957e1fca50105b79226484210283c91208cfc2172cfe1dbeb79594908bc71893888b38c72e8c2a1b59f9",
          "sha256": "39453b1d21e50c4b4db3283bd71daf4703b6deed278ac18a341dbac8989166ed",
          "sha1": "f545a9655b90966c722c313fe92653ec05677ddf",
          "md5": "6e4eb088ec981f3b79c2c887a39cdd69"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "runtime-jvm-0.5.20.2-sources.jar",
          "url": "runtime-jvm-0.5.20.2-sources.jar",
          "size": 50636,
          "sha512": "daafdc147c3f34e35a8d43f967ec13abf76313face5b780e070f793f40c93f8628ee57bf2091803b8b1e60a5e3efb38c03337ac4a35ebbce16edb0f5ebd39ba8",
          "sha256": "59faa38ac6f8f4e6abb4209325f65838bcfad2206ce5b87815d93428d10cb1de",
          "sha1": "aea8e1f0049f00881e66e2d61d0da614980a5ec1",
          "md5": "9a1d85b3ccd35930ff1d54a93948b0c8"
        }
      ]
    }
  ]
}
