{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.5.12/core-0.5.12.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.5.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosX64Main-0.5.12.klib",
          "url": "core-iosx64-0.5.12.klib",
          "size": 101557,
          "sha512": "dd30cc5428330ca805dabccb224465779c22a913d7a7c83e2ab54f139762b39afd6462a926f604101567100120b9f3cb90ed2ed572e0274a8899c9f3207ffd3a",
          "sha256": "7f3d9cde978d7e1bc0affbe24ff8ca1b03eccf4ef5002cff687eb5a5bd649d98",
          "sha1": "dd862715eaf51db488cc5ca889a80ac3377c46ec",
          "md5": "913b0ac160a5f627f17d69ffb35c3a44"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iosx64-0.5.12-sources.jar",
          "url": "core-iosx64-0.5.12-sources.jar",
          "size": 12871,
          "sha512": "9384b55817f88f910ec57688f568f23c7334e431ee50978b193d247dc6dc8604297381b30757d73c8c22a3ea4f3da34334acfaf4bfa1121de726f0027e0f3235",
          "sha256": "cbafd42c100bb7358370dc203cd61d4041cd683b48d69db2eda1e6514b18e617",
          "sha1": "20061d10ddcd97c4bb4a9c49602da7d79000e539",
          "md5": "337280c1de2570f705980fc4fe7f6037"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.5.12-metadata.jar",
          "url": "core-iosx64-0.5.12-metadata.jar",
          "size": 261,
          "sha512": "201a58106839935f05726273692b7956fd6de2ca1d1db9d2f507de0964a2dd057e0a2fa4e3be809844a0e8585dddbd667cf9a4a1a3108ca90bc0f713ec9bc8b0",
          "sha256": "df5d84eb47845e79ea3bd5a5069c10dd78d3abd0ceb51e1d1b8fdefa4c0ab1c7",
          "sha1": "69c717f2d9baba74a82634baaabbccfd09ad4807",
          "md5": "a627980078803c80baa83415a46a0d27"
        }
      ]
    }
  ]
}
