{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.5.17-noscroll-SNAPSHOT.1/flows-sdk-0.5.17-noscroll-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.17-noscroll-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17-noscroll-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.17-noscroll-SNAPSHOT.1.aar",
          "size": 161178,
          "sha512": "bb677df11008885a54957bb7cedd425263f4eed0d6406ba9db84f01abc836585af3b9ba18e62f6536b023d96e3e942755a93bb8830f40b304b83427fc1d9d3ed",
          "sha256": "42e1df303404b9e0e7dcfbc1431fbe5d48855c7d20bf22399fa543d8bb626e29",
          "sha1": "dadffd0404a880c62bb4bfd5148938224de74f6f",
          "md5": "bc495f38116902d3f10e1f8908ff2bd3"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17-noscroll-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.17-noscroll-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.17-noscroll-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.17-noscroll-SNAPSHOT.1.aar",
          "size": 161178,
          "sha512": "bb677df11008885a54957bb7cedd425263f4eed0d6406ba9db84f01abc836585af3b9ba18e62f6536b023d96e3e942755a93bb8830f40b304b83427fc1d9d3ed",
          "sha256": "42e1df303404b9e0e7dcfbc1431fbe5d48855c7d20bf22399fa543d8bb626e29",
          "sha1": "dadffd0404a880c62bb4bfd5148938224de74f6f",
          "md5": "bc495f38116902d3f10e1f8908ff2bd3"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flows-sdk-android-0.5.17-noscroll-SNAPSHOT.1-sources.jar",
          "url": "flows-sdk-android-0.5.17-noscroll-SNAPSHOT.1-sources.jar",
          "size": 24428,
          "sha512": "35ed903ba04e0132e769927cd415e0b88e71085de07dbc746d906233053751c62fdf85d8f2d607679aef337161d36728e11e59a70f3706b78189880d62749b81",
          "sha256": "3e8ba23d519ac5ebdc95381d3a7cfc6397cd361d46bdd1d160e3b4f047150f12",
          "sha1": "92541baedb2ae19bdd5622159e9940dc54a7736f",
          "md5": "8e063407a02fe5aa8b8fa7406675d91e"
        }
      ]
    }
  ]
}
