{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.7.1-rc.239/composeblocks-0.7.1-rc.239.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.7.1-rc.239",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.239"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.1-rc.239"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.7.1-rc.239.klib",
          "url": "composeblocks-iosx64-0.7.1-rc.239.klib",
          "size": 456656,
          "sha512": "afb615b738ec67516b6078676bf74773fb9390afa1a5ad83652a2ae685047f13a6fec310903fb98487c76c909d7433d760b6d39c64225a47a4c341dc46b407da",
          "sha256": "91b34e8145020ce26477813043207e2c02f52265c81055d27472aa286435d3b8",
          "sha1": "218acdb00b7ed3e3d8814b7fe5d34de1192c6d3f",
          "md5": "207260a4643f6cc206d42a138f372a9e"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.239"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.1-rc.239"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.7.1-rc.239.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.7.1-rc.239-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "8e27a5363a695edb697446ec3db2c41a9aba84af205b58fe0a76adad00e1972fdc27a1cb700bfb90e156bcf287e140790fb45c077b33d70d1fc3df3a0efa80fc",
          "sha256": "2337d78b158f6bd80a6f772a772d28c843ea46d343e7b7853b31ae36fcb51c53",
          "sha1": "7eb3d26e3587f15f0315e2f736bdc233c7da571d",
          "md5": "a93276f2f029320d4b7ff35c5e5717ff"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.239"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.1-rc.239"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.7.1-rc.239-metadata.jar",
          "url": "composeblocks-iosx64-0.7.1-rc.239-metadata.jar",
          "size": 261,
          "sha512": "80c7a7bb771861f87af4fb0ed17ac71fdf5a28914ec243725b28da516321a0cea46d7d1a2904202b1d1f064f3ce76d6192c8c07b589dde877c7f33a91ad89221",
          "sha256": "e36410317789307e0820257577333b633d83687cbb7f7b055acae0741f6aa1c0",
          "sha1": "a918906191423c6ca294a6e85baa735d6a9c2152",
          "md5": "bc7a7a9a1d824f23e5438d0d9315f4f6"
        }
      ]
    }
  ]
}
