{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.7.0.1/runtime-0.7.0.1.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosSimulatorArm64Main-0.7.0.1.klib",
          "url": "runtime-iossimulatorarm64-0.7.0.1.klib",
          "size": 682230,
          "sha512": "b19946eec3013586ed194eb2ea71b121422d2881ca87a174b34372372e518169e3f784b65f32534fbf2455c6828da7930254592e8cd063894548b4ba4d09db87",
          "sha256": "6aed8661ee46c59092b299935c40d521ede611bfeb6bd5ee7a98217dc5673685",
          "sha1": "5cb95304ec6e963bf39044d3e6d1a558dc20edb0",
          "md5": "f0850f93f7018318d11114baf5031527"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.7.0.1-metadata.jar",
          "url": "runtime-iossimulatorarm64-0.7.0.1-metadata.jar",
          "size": 2428,
          "sha512": "88decab416018ef2326f9211184afb4590c5f2d6e1717c61bff7ae81aec683631360aef2a4691d4a9a9522ec24c6829f59e2ec19d632fd1297c5868f8960d303",
          "sha256": "f2370ad573d4aec4408ee03205f004385a1f1e9571cc7123ca2fea675ad8779f",
          "sha1": "fcbf9f627dc936565ed2b7ee8d19a2aff615a33f",
          "md5": "97f7616d6ea8f3290062c92b216fa15a"
        }
      ]
    }
  ]
}
