{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.18-SNAPSHOT/flow-wrapper-kmp-0.5.18-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.18-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.18-SNAPSHOT.aar",
          "size": 212388,
          "sha512": "59ef965969cdc48bb3c12427003b65233b7e8c212708bc9af7047967d024ae4cb7754f4f5836cd630238b6d6e94f08f92cfa1317e1fac6edcae307681f5f8259",
          "sha256": "bd6cf4de2f638f0a79f66f8ab08a32bf4169bf9bfe993f45841f0e0987c38238",
          "sha1": "8b10932bee1bf213d56296f87feb32270d9ea964",
          "md5": "5d17ac3dffcdb7569ee3bad7b2da45e8"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.18-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.18-SNAPSHOT.aar",
          "size": 212388,
          "sha512": "59ef965969cdc48bb3c12427003b65233b7e8c212708bc9af7047967d024ae4cb7754f4f5836cd630238b6d6e94f08f92cfa1317e1fac6edcae307681f5f8259",
          "sha256": "bd6cf4de2f638f0a79f66f8ab08a32bf4169bf9bfe993f45841f0e0987c38238",
          "sha1": "8b10932bee1bf213d56296f87feb32270d9ea964",
          "md5": "5d17ac3dffcdb7569ee3bad7b2da45e8"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-android-0.5.18-SNAPSHOT-sources.jar",
          "url": "flow-wrapper-kmp-android-0.5.18-SNAPSHOT-sources.jar",
          "size": 41893,
          "sha512": "083eda27015704501ff69041337c18e699b7f36fb83b2537f9559790221d1d72567bf1c50b3040b8ea20196915483daa04a0ca71546ca69b50116112f51ad515",
          "sha256": "927a29ab230b331b8652794d4c4128c38efad0142dee42462a7c99e74f52746c",
          "sha1": "bbc685b61c5c637578c43df72035895e06da58b1",
          "md5": "0c766c9c596dde79f44424421546d2fe"
        }
      ]
    }
  ]
}
