{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.5.16-rc.72/runtime-0.5.16-rc.72.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.5.16-rc.72",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16-rc.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosSimulatorArm64Main-0.5.16-rc.72.klib",
          "url": "runtime-iossimulatorarm64-0.5.16-rc.72.klib",
          "size": 615243,
          "sha512": "5d1841a7ceca59601d3134da6411d586c5c780367ddb67ca49abc8881e57e5c32e5c709382b81b863f3b2aa161000aa1b1cca1b82ae8c121efb8918df40f42dc",
          "sha256": "6da72c233ce6bec74a449aaafbd0ee01d7dff0c2786cb9200c83d35a46ef5c3d",
          "sha1": "8b68339629be816b1147e46d9e17bf43872f6a77",
          "md5": "63271da9f0a2e38b428ed6d0a2993617"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.5.16-rc.72-sources.jar",
          "url": "runtime-iossimulatorarm64-0.5.16-rc.72-sources.jar",
          "size": 48102,
          "sha512": "db93a7c131e6d1f68c67d15f9dd031b7a6012365759389ec26ad5b6959dc349c1770661fe1613e81a2ecc8e4a3088956565ceb5a86c005e651de5000624e1210",
          "sha256": "0856e8ef678d016aeebca73711df42045a3608f8876fac42eb536d98af7cb759",
          "sha1": "99c814f5c15e5030fe59c9e1985e921cd5566cc4",
          "md5": "c90720ce17aabd807b4aecf44ed21455"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16-rc.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.5.16-rc.72-metadata.jar",
          "url": "runtime-iossimulatorarm64-0.5.16-rc.72-metadata.jar",
          "size": 2428,
          "sha512": "35dcc7463f4d949983e10db22df3e20260bc7c2113aba07066eacbe3d9bd36de4c94332356f30bb52fae4391c808d7f5008e098368c541d008ad5e4e7c289a93",
          "sha256": "29b2ffd5b8d896d1a218782ec8e99d34954ba11c4e25518f0f40c59397ec1591",
          "sha1": "a6000b2632d3fe1c26b4250ea9eed45dcd7f8eaa",
          "md5": "06f9c45aa66131ac2a83d726d034cdd3"
        }
      ]
    }
  ]
}
