{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.5.16-SNAPSHOT/flows-sdk-0.5.16-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.16-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.16-SNAPSHOT.aar",
          "size": 153767,
          "sha512": "c72cea660efbacb6a0747a63d60748667565a21ec5823ee9f9b3c07abc778936382ad3065a0665edf4d8011ed41519632af83f9c8d708c65763727974d089c22",
          "sha256": "51112741460537a42b7abcd36221f543f33eac45515b4120e233a8f9d3697f84",
          "sha1": "d425240a3a060fac96f600058726ab2c8797965a",
          "md5": "2657b37b96046bd94308d930a0c9fbd0"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.16-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.16-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.16-SNAPSHOT.aar",
          "size": 153767,
          "sha512": "c72cea660efbacb6a0747a63d60748667565a21ec5823ee9f9b3c07abc778936382ad3065a0665edf4d8011ed41519632af83f9c8d708c65763727974d089c22",
          "sha256": "51112741460537a42b7abcd36221f543f33eac45515b4120e233a8f9d3697f84",
          "sha1": "d425240a3a060fac96f600058726ab2c8797965a",
          "md5": "2657b37b96046bd94308d930a0c9fbd0"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flows-sdk-android-0.5.16-SNAPSHOT-sources.jar",
          "url": "flows-sdk-android-0.5.16-SNAPSHOT-sources.jar",
          "size": 23212,
          "sha512": "a48ad46be3234be84df5ec306dc31cf050e78f444cdac39dc7fc135187d662cf16c8d393660461f72fc523fa1d97e0abdafdaaa35e68774c13ee0793f04b3463",
          "sha256": "4ab7894d740666d3719fd366d8ae34e8e0000666e887876fa8570ce968d8773e",
          "sha1": "cdcc3d25ce559ce98ab80ac1187f6131d779a5eb",
          "md5": "6d1a27b5ac793f8faeb00feaf61668ca"
        }
      ]
    }
  ]
}
