{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.5.18/flows-sdk-0.5.18.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.18"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-apple",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.18"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.18"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-optimal",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-iosX64Main-0.5.18.klib",
          "url": "flows-sdk-iosx64-0.5.18.klib",
          "size": 139021,
          "sha512": "fb8056584d5f0d64ba974737f3903b1294c49e45916144e80d12765f067b6871de9926adf01023c72a6d7e88a75d4141115ff8657ffd756247b130cfac6aa087",
          "sha256": "f7545b64122ae31ddaf57ad82dc90de0a7b967c5f917509426e2f117fc9a01e2",
          "sha1": "8bd08aab2b95b32ac7c9e4e0f666a78a289525b6",
          "md5": "36b49f7b8e1135178019d15571ac9379"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flows-sdk-iosx64-0.5.18-sources.jar",
          "url": "flows-sdk-iosx64-0.5.18-sources.jar",
          "size": 28981,
          "sha512": "0f3ffa6fb2f15b7b31f93fe788bf4cd25466bffa3a5c3191376aa38ead902b99be502c9d781de3df92571c5c789ffa639cd74e5fb10e8e122e2c5371630f24f1",
          "sha256": "97bc9769215381027bbb286479ee52b77d271e3a14ce3d8435f9b0acad50e50c",
          "sha1": "02b1e64077b63d53add6c8c8c97a73e29b6d3015",
          "md5": "52b7f942f448c7a907389d4de6c4ed79"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.18"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-apple",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.18"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.18"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-optimal",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-0.5.18.kotlin_resources.zip",
          "url": "flows-sdk-iosx64-0.5.18-kotlin_resources.kotlin_resources.zip",
          "size": 61888,
          "sha512": "09393d49caca67c088693bf5f603ab4ecae8a10ab8098350878d8f45863d63e7b5e59bbd3c12186f2ee006621c5bb42cb9aff0e22795853f5ecd94a78f8c863a",
          "sha256": "50ddca36fb7d2d1f8c43a77d8d0a3be096caa1d2efd3253096fd7a4a4babf47f",
          "sha1": "fd72bc6b521901ca74543792a8aa355710ca8045",
          "md5": "3090e073a13090ab8df488e3782ce20f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.18"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-apple",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.18"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.18"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-optimal",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-iosx64-0.5.18-metadata.jar",
          "url": "flows-sdk-iosx64-0.5.18-metadata.jar",
          "size": 4019,
          "sha512": "62f3fd9da2334afb06ea9395d3a900c5824f864b28c16925bd3a9844d693446c0f0d885c961622562cc25155368b5ab0d445f46dea642f05488d39c1d9ba8b99",
          "sha256": "e3fb1a3478aa1982e71f109722f9f92b12a1b935cd464f6c06415eb754560610",
          "sha1": "4757539f51b94d9f8e48cdc7da11fce96716b652",
          "md5": "7daa6b98480d5c00441da45807bb30d2"
        }
      ]
    }
  ]
}
