{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.6.0-SNAPSHOT.16/composeblocks-0.6.0-SNAPSHOT.16.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.6.0-SNAPSHOT.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.16"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.16"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosArm64Main-0.6.0-SNAPSHOT.16.klib",
          "url": "composeblocks-iosarm64-0.6.0-SNAPSHOT.16.klib",
          "size": 226370,
          "sha512": "4feb58995705254788e6b6a9ac6cd5d7dd30def00bb7a9143fddd47b600e61923df61e488a9d08c3f553af37bf5819bdafcad67f19e8412db7a78c6e9503b1a1",
          "sha256": "e36bba966189d108e7276f64a93e18f540d277a74ce0578a866910dc2fd43652",
          "sha1": "6ee56691113678019eddae9c7ccb1c3e96a7e874",
          "md5": "cf42b1882946cc9d7e48cd9f65077bbf"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosarm64-0.6.0-SNAPSHOT.16-sources.jar",
          "url": "composeblocks-iosarm64-0.6.0-SNAPSHOT.16-sources.jar",
          "size": 36238,
          "sha512": "fdddd7a07414879297ac73d4d1f42aa786402b0bfcd45c52996d4203149d15768a5ddf17af1b7c6ebb0a1d781c9a2c0bd0f7ec8e03c834e82e44356c2493fdaa",
          "sha256": "fb1002d7086daf0f4dbbb3e08759878d68f00339df9c92c94c9dd1aa30f952de",
          "sha1": "f922fb0632d02d535bc99eabbdaa2b1ebd0adce0",
          "md5": "c2b07c9ab6101b593271548f70e3d0f0"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.16"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.16"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.6.0-SNAPSHOT.16.kotlin_resources.zip",
          "url": "composeblocks-iosarm64-0.6.0-SNAPSHOT.16-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "e2dd2eba61d53d495d0f568d76a0b3f274f087673c702a51754c00fb77bc987e16713e26b1ef70337a68ba8a2d8d48e45fa7aac1c363c11eb70991a1292f4464",
          "sha256": "176928e5840468465a7a35fb01093ad98f4f7eee0135a3d249904e3e12df84e0",
          "sha1": "d4493ddbd75644dbf94a724d81d7f12287c0153e",
          "md5": "d58afbd59d321e37539905865b18d889"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.16"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.16"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosarm64-0.6.0-SNAPSHOT.16-metadata.jar",
          "url": "composeblocks-iosarm64-0.6.0-SNAPSHOT.16-metadata.jar",
          "size": 261,
          "sha512": "88c0df4b1c02601b70bd8e740f55c9d47f17322de2c241a58323ee1f97897ca5596376e8030f9392b95403903b2ef51c4eb520715b084997e74a93a82f42c068",
          "sha256": "b4e020a6c0b6465b5e3c1ad74e082528099a8f4af5d44ac74d29004fa6a2c9c0",
          "sha1": "7aea7162ab7b88abdd6d830311428ba40c2a93eb",
          "md5": "2b544ecfc422e7096e15a5eaf4d8c397"
        }
      ]
    }
  ]
}
