{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.5.12-SNAPSHOT.1/runtime-0.5.12-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.5.12-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosX64Main-0.5.12-SNAPSHOT.1.klib",
          "url": "runtime-iosx64-0.5.12-SNAPSHOT.1.klib",
          "size": 576229,
          "sha512": "ace531d2ba04bceb06a44be14e8938278edd1bd6440419ee990ae43262f7522d572c0396dc91920d97e02be75dd6fb89b4db151cc5f97f4e74364836f82facd1",
          "sha256": "d7805bb70a8182c23346dcb6ddaef3b4e0f9477a8684b7ecd5fbc1a1f21266d0",
          "sha1": "7a8fc28de02fb66bc64a736aaff9bb63f01ac204",
          "md5": "2b6d5cf495f2f71bc31fe8692f24efa2"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-iosx64-0.5.12-SNAPSHOT.1-sources.jar",
          "url": "runtime-iosx64-0.5.12-SNAPSHOT.1-sources.jar",
          "size": 43264,
          "sha512": "7181e822faba84fb7bde74fd0f90c4e390939287d9b8836c221acd15bf0c80d2e2cba78ee4cf07da15d3d384ce815092ffdd670bd9eecfe5185b7fed794bdbb0",
          "sha256": "c08c746a03c2d40cb6675263b6d010f960c903a8ec5c30970089f6fd7677df48",
          "sha1": "5893eb8f9308c87025fdd293195f3d17d13f5b83",
          "md5": "a1a34e2ac7535d628e343852bee7ec09"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosx64-0.5.12-SNAPSHOT.1-metadata.jar",
          "url": "runtime-iosx64-0.5.12-SNAPSHOT.1-metadata.jar",
          "size": 2428,
          "sha512": "89ccbfd7847b0bd1b1456201907e094528d1fd3775b6d2dfb16e311bc6af35e16fef671a12e7c9b55cc0937b3d17291fed011b1ea0b7d1ac779f8cf2e4404a4a",
          "sha256": "f0ddbba7b99264d5f9091285e5f377361627e5606f03bf62474d651f8b35f04f",
          "sha1": "9e520f20fa00727cb2474a9328e82518960a3dfd",
          "md5": "30cc228c036c84fa7565523f35537182"
        }
      ]
    }
  ]
}
