{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.20-rc.141",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-rc.141"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-rc.141"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.20-rc.141"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-optimal",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-apple",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-metadata-0.5.20-rc.141.jar",
          "url": "flows-sdk-0.5.20-rc.141.jar",
          "size": 22260,
          "sha512": "d8901cbb35ada880028d2a50204c942163e59c5421a0d46886fb06501d3d8fdcd52bcfdebe3f897ef663ae72c8af551ec373ddc7eb78e5c35bea19ef736a35d6",
          "sha256": "cc1de1cc731f590b39911de357b6539b725fa55b04f559bb8dfe9767717627a7",
          "sha1": "83669575cb3f6487cdc8767ca8ea5ef2c780e66f",
          "md5": "d6182de51977da96152353197f855ef1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "flows-sdk-kotlin-0.5.20-rc.141-sources.jar",
          "url": "flows-sdk-0.5.20-rc.141-sources.jar",
          "size": 30463,
          "sha512": "e861468b1e5a6d625e0fe7c9010e02ebfd564d62bba854a3f86a8f75fb366f180d6fdf258361719ed4f6c36683a77b6093b7a6d748d6ee62b2a0e128487c34ec",
          "sha256": "074229dd300a477f6c704b1a5914e862a82fd29581da831bce2ec64d71d96c1e",
          "sha1": "ccbff64154f4e78fdfe51c7c3cd8de8fa32c1344",
          "md5": "4652dfdfd3f57d30fc1b5ea8e78258ff"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flows-sdk-android/0.5.20-rc.141/flows-sdk-android-0.5.20-rc.141.module",
        "group": "br.com.wave",
        "module": "flows-sdk-android",
        "version": "0.5.20-rc.141"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flows-sdk-android/0.5.20-rc.141/flows-sdk-android-0.5.20-rc.141.module",
        "group": "br.com.wave",
        "module": "flows-sdk-android",
        "version": "0.5.20-rc.141"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flows-sdk-android/0.5.20-rc.141/flows-sdk-android-0.5.20-rc.141.module",
        "group": "br.com.wave",
        "module": "flows-sdk-android",
        "version": "0.5.20-rc.141"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosarm64/0.5.20-rc.141/flows-sdk-iosarm64-0.5.20-rc.141.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosarm64",
        "version": "0.5.20-rc.141"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosarm64/0.5.20-rc.141/flows-sdk-iosarm64-0.5.20-rc.141.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosarm64",
        "version": "0.5.20-rc.141"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosarm64/0.5.20-rc.141/flows-sdk-iosarm64-0.5.20-rc.141.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosarm64",
        "version": "0.5.20-rc.141"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosarm64/0.5.20-rc.141/flows-sdk-iosarm64-0.5.20-rc.141.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosarm64",
        "version": "0.5.20-rc.141"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iossimulatorarm64/0.5.20-rc.141/flows-sdk-iossimulatorarm64-0.5.20-rc.141.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iossimulatorarm64",
        "version": "0.5.20-rc.141"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iossimulatorarm64/0.5.20-rc.141/flows-sdk-iossimulatorarm64-0.5.20-rc.141.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iossimulatorarm64",
        "version": "0.5.20-rc.141"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iossimulatorarm64/0.5.20-rc.141/flows-sdk-iossimulatorarm64-0.5.20-rc.141.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iossimulatorarm64",
        "version": "0.5.20-rc.141"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iossimulatorarm64/0.5.20-rc.141/flows-sdk-iossimulatorarm64-0.5.20-rc.141.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iossimulatorarm64",
        "version": "0.5.20-rc.141"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosx64/0.5.20-rc.141/flows-sdk-iosx64-0.5.20-rc.141.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosx64",
        "version": "0.5.20-rc.141"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosx64/0.5.20-rc.141/flows-sdk-iosx64-0.5.20-rc.141.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosx64",
        "version": "0.5.20-rc.141"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosx64/0.5.20-rc.141/flows-sdk-iosx64-0.5.20-rc.141.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosx64",
        "version": "0.5.20-rc.141"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosx64/0.5.20-rc.141/flows-sdk-iosx64-0.5.20-rc.141.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosx64",
        "version": "0.5.20-rc.141"
      }
    }
  ]
}
