{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.7.0.1/composeblocks-0.7.0.1.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosSimulatorArm64Main-0.7.0.1.klib",
          "url": "composeblocks-iossimulatorarm64-0.7.0.1.klib",
          "size": 391376,
          "sha512": "193e0dc8e8af3a59c8885a614876958b0b8d24fd37e20d21325a5fc148afff70cc030d5eed1cd80a8e339098dbeff37c10376ae773bb2450e65adcd816cc6977",
          "sha256": "b2a11fc13ab9de635534b73a33937615749e31469cc5d4aabb26b6dad5656225",
          "sha1": "b03e64e1eb2ecb7a404169a9ad5725ae73470dc1",
          "md5": "60f622ee406399e4e4e33b385c5c6990"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.7.0.1.kotlin_resources.zip",
          "url": "composeblocks-iossimulatorarm64-0.7.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "c4f3f990b0503c8f6aa57893efe31a7a8c63384a57be6beec6ea7e8c9d1859926263203b1c93e8d66fdf43320b2586a823bb863184832d05803b1400eed490b1",
          "sha256": "ceeba332465e7181f0495cac99ab619a73475c688df25dd48b7b5f9737cff541",
          "sha1": "0b30a003f076f004fcbaed247a0516b5c51cd756",
          "md5": "b425986907a676acd70dad44722e31d6"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.7.0.1-metadata.jar",
          "url": "composeblocks-iossimulatorarm64-0.7.0.1-metadata.jar",
          "size": 261,
          "sha512": "932c6271646911309773b78496092d8197e6209a231df48707e794bcad1e566589bec59fee19d9a5ee8012600edbb3bd0df0c7d78f7c527037958e78dc87a0e6",
          "sha256": "df9523898c108030baa1276621b156dd4b5980bcce0cd5961aae3fb86cfcee27",
          "sha1": "41fa904414c6b761bab34862f3b04ad242386cd2",
          "md5": "b06468584c3e22a7572dcff84e7ed598"
        }
      ]
    }
  ]
}
