{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.6.0.2/flows-sdk-0.6.0.2.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.6.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.6.0.2.aar",
          "size": 189139,
          "sha512": "50c9f1e9cc7bcaf212a4908b27c152a8568829c3f55804a15877d1a0e600bbdec40d1369085e26139a4b79687baf54cefc0896cde0b113581db249610334c2b5",
          "sha256": "b2b29af51e12c90f7a7a64707cc5fd58ae7ebb55bb445beec74716ccef8ef544",
          "sha1": "98b02082fd98711a78726f4bc435364eb91f3c61",
          "md5": "f5423471b82f8b63e0c60f809c347dc1"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.6.0.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.6.0.2.aar",
          "size": 189139,
          "sha512": "50c9f1e9cc7bcaf212a4908b27c152a8568829c3f55804a15877d1a0e600bbdec40d1369085e26139a4b79687baf54cefc0896cde0b113581db249610334c2b5",
          "sha256": "b2b29af51e12c90f7a7a64707cc5fd58ae7ebb55bb445beec74716ccef8ef544",
          "sha1": "98b02082fd98711a78726f4bc435364eb91f3c61",
          "md5": "f5423471b82f8b63e0c60f809c347dc1"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flows-sdk-android-0.6.0.2-sources.jar",
          "url": "flows-sdk-android-0.6.0.2-sources.jar",
          "size": 35415,
          "sha512": "d19d1ba52c1dc19519d579e36dc46f2308e71cb8d6bf728e3887b2912aa556adc0ba01f88fc870cb3499cae7b93aa68ee44030f94a555130616f28c11be50f61",
          "sha256": "0a17b8f7e2bdff1599094cd9e7f892cdb505f76c6b93c806d05fa53e3891dcab",
          "sha1": "9e2bd9d13b0147a912ae9bcf25285dc667c0f2df",
          "md5": "a2e3a8d97feebd2a9c03b4d3400ace05"
        }
      ]
    }
  ]
}
