{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.6.0-SNAPSHOT.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-metadata-0.6.0-SNAPSHOT.14.jar",
          "url": "runtime-0.6.0-SNAPSHOT.14.jar",
          "size": 43713,
          "sha512": "5ac7790e8cd4002da8e57856ed7ad3408f0dcd672dd673d5713a4479189478b42e6a1e4a42608ff455189a61058435cf6b60a50c2e32c2acc5314c5e74326786",
          "sha256": "9ac8c3d2acea1eba1d149644a15655847734b0d19be0ecd07f25de17fe60d59f",
          "sha1": "fa530b5454e5b75f29959065cbfae41ad3593754",
          "md5": "54be1a8ce1f620ce6e7b2f50cd5bc484"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-kotlin-0.6.0-SNAPSHOT.14-sources.jar",
          "url": "runtime-0.6.0-SNAPSHOT.14-sources.jar",
          "size": 42972,
          "sha512": "dfb3d757357ca5d7adf56cec62414c7372451c713817a6ed24b1b4c8a7bf6c2a54d9a6b2e64271e79379b61866e5e28a52055a4a3e037a6bb20e37b7aa85178d",
          "sha256": "c5c2c2978ef22d02aed46e2766592365d092c0a4205df7bb3672d6ce7cce3254",
          "sha1": "d63cb1cc4213f502b9b47c1b5f9ace44fbd2eb83",
          "md5": "20351ade74ae979e61386521efbd8ef1"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-android/0.6.0-SNAPSHOT.14/runtime-android-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-android",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-android/0.6.0-SNAPSHOT.14/runtime-android-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-android",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-android/0.6.0-SNAPSHOT.14/runtime-android-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-android",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.6.0-SNAPSHOT.14/runtime-iosarm64-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-iosarm64",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.6.0-SNAPSHOT.14/runtime-iosarm64-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-iosarm64",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.6.0-SNAPSHOT.14/runtime-iosarm64-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-iosarm64",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.6.0-SNAPSHOT.14/runtime-iossimulatorarm64-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-iossimulatorarm64",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.6.0-SNAPSHOT.14/runtime-iossimulatorarm64-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-iossimulatorarm64",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.6.0-SNAPSHOT.14/runtime-iossimulatorarm64-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-iossimulatorarm64",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosx64/0.6.0-SNAPSHOT.14/runtime-iosx64-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-iosx64",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosx64/0.6.0-SNAPSHOT.14/runtime-iosx64-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-iosx64",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosx64/0.6.0-SNAPSHOT.14/runtime-iosx64-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-iosx64",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.6.0-SNAPSHOT.14/runtime-jvm-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-jvm",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.6.0-SNAPSHOT.14/runtime-jvm-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-jvm",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.6.0-SNAPSHOT.14/runtime-jvm-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-jvm",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-linuxx64/0.6.0-SNAPSHOT.14/runtime-linuxx64-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-linuxx64",
        "version": "0.6.0-SNAPSHOT.14"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-linuxx64/0.6.0-SNAPSHOT.14/runtime-linuxx64-0.6.0-SNAPSHOT.14.module",
        "group": "br.com.wave",
        "module": "runtime-linuxx64",
        "version": "0.6.0-SNAPSHOT.14"
      }
    }
  ]
}
