{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.8.0/composeblocks-0.8.0.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosSimulatorArm64Main-0.8.0.klib",
          "url": "composeblocks-iossimulatorarm64-0.8.0.klib",
          "size": 465751,
          "sha512": "132a97e459e5800678f9f999cae771a4822ab0ca8da51986aaacf000e62a194a4364c87d307c4510b02e19f1c60028292049117b21bd8aee907d514dc5f902ab",
          "sha256": "2a86b8d13694d6b609275cde4e5071c957e1ca8c09259074d411cd7cd60045cd",
          "sha1": "6cd1486c6327324fd78324409a85af828f7065a5",
          "md5": "7faa47a44153ff3276788b63c2c2d4dd"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.8.0.kotlin_resources.zip",
          "url": "composeblocks-iossimulatorarm64-0.8.0-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "a4f94326d8cc20d5d5f36b4ede5153e34a1be5dcae47a22d2fe981a33312aa170af7ed0ac3f4606cb9c6ae0e82453ad364362c5db2d534c8e88eb82cf23a141b",
          "sha256": "343255e69b06d8774e590678e8de17b87470e21da2bf8cc23b860917d2b60846",
          "sha1": "38e40023477a94f30286f401d9c273c5d4a2eab1",
          "md5": "d99de0e503aaa23c4c46a7e793e32e6b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "composeblocks-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "4e7dcae70a502061081c2488c8ba03ba19db4ced7105c25ecfa3f57267027271e0f2cb90b2d0d8080da1576701867d29898d6aab116f3237aba7d6ce64cfe28c",
          "sha256": "bee7a7491b86c0fae1bdda3a086f20822ae94b4b637ccc93ccfc9b637d40b19f",
          "sha1": "18c552a56cd27efc49aab1ef76d522f468f25ad7",
          "md5": "f9873ab3ac4b59b8b9ce1c0b2b87b365"
        }
      ]
    }
  ]
}
