{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-metadata-0.5.20.jar",
          "url": "composeblocks-0.5.20.jar",
          "size": 28427,
          "sha512": "ed7bcffcad5ec7c55d0d3781b172f684a7035a67d99706cb9d6b9e2ef2f86e5552fecaa72b2863282895550d77c9072d27e34706df8883e6b493e3ac08460647",
          "sha256": "9460b4db8b561181069444b15d71658a666ea779816dff27c6ce5926c6500a7f",
          "sha1": "8d836a5ed88c541f6b128d061b79e02ce2aac38c",
          "md5": "56c7668d27159a2231114e69ca1d5c4e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "composeblocks-kotlin-0.5.20-sources.jar",
          "url": "composeblocks-0.5.20-sources.jar",
          "size": 62929,
          "sha512": "a1b6fc6d924260f33998241e03ec24748d5c5dfd0113774ba6737d13cf12976f05d7730d8a31102924f3f379dc14469fbbbc54a33812c1b3466749ccc47684d1",
          "sha256": "c060c74601af62602de4fce2f88037ef006540f40ab0fc07a70a191070214b78",
          "sha1": "16aca03e0bca1374655d6244d13d0ebffcd27f34",
          "md5": "18983dc3d325a95705ebeb14c1ac28aa"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.5.20/composeblocks-android-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.5.20"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.5.20/composeblocks-android-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.5.20"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.5.20/composeblocks-android-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.5.20"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.5.20/composeblocks-iosarm64-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.5.20"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.5.20/composeblocks-iosarm64-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.5.20"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.5.20/composeblocks-iosarm64-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.5.20"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.5.20/composeblocks-iosarm64-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.5.20"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.5.20/composeblocks-iossimulatorarm64-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.5.20"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.5.20/composeblocks-iossimulatorarm64-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.5.20"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.5.20/composeblocks-iossimulatorarm64-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.5.20"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.5.20/composeblocks-iossimulatorarm64-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.5.20"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.5.20/composeblocks-iosx64-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.5.20"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.5.20/composeblocks-iosx64-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.5.20"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.5.20/composeblocks-iosx64-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.5.20"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.5.20/composeblocks-iosx64-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.5.20"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-jvm/0.5.20/composeblocks-jvm-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-jvm",
        "version": "0.5.20"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-jvm/0.5.20/composeblocks-jvm-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-jvm",
        "version": "0.5.20"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-jvm/0.5.20/composeblocks-jvm-0.5.20.module",
        "group": "br.com.wave",
        "module": "composeblocks-jvm",
        "version": "0.5.20"
      }
    }
  ]
}
