{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.5.18/core-0.5.18.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.5.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosSimulatorArm64Main-0.5.18.klib",
          "url": "core-iossimulatorarm64-0.5.18.klib",
          "size": 127682,
          "sha512": "a98a7128048ee203ddba83cd9bbac4ac342076389248a3b1d01224ea1d30e081c3bda9c96117a239f917106b614ed7a4e9a4bedb0fa096a972daba0517b7d35b",
          "sha256": "e0ddb583ce19ae7024a698f64d4ef3634e73c0ec89315071b6808ba068efa531",
          "sha1": "93ce093dec896ddaeb92bb93ec90b491ef3cc98b",
          "md5": "542a91c00bc4f5305aa30ca044df8736"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iossimulatorarm64-0.5.18-sources.jar",
          "url": "core-iossimulatorarm64-0.5.18-sources.jar",
          "size": 19241,
          "sha512": "9a5393b3bb0307aa6931eb24e76bb3cbd6385fb2e1dba4c14e1a6d1864435fb6fd9ffef6aaf0d386dfc1a3d497e459f26c09cdac9f556b235a16802af7ac8b75",
          "sha256": "1c7a9aa3464ab76183efb0ae36a0ca75a3cdd21378c8e962848aca7556096d4e",
          "sha1": "43eed877c7528a7ce139b1643e585998031a97b3",
          "md5": "f3b49f1808e86065dcb78b9e223f0537"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.5.18-metadata.jar",
          "url": "core-iossimulatorarm64-0.5.18-metadata.jar",
          "size": 261,
          "sha512": "f04ca478c6d1057aea708575b961faef4a94643d3cd680a209b0d959a256f883f3fbee1efebf030b590363a64bbb7b21057d8fd8167e71c45fc654aa08cd0afc",
          "sha256": "409bdc1b3bcd6d149e700a536aa85f555aa656f85789d32f2c8875bad1f1311c",
          "sha1": "be06b4c86d817f6c3d010f14de15dba3ce7164c9",
          "md5": "3794cbed1606170025ee0499bc7340f9"
        }
      ]
    }
  ]
}
