{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.7.1-rc.237/core-0.7.1-rc.237.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.7.1-rc.237",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "core-android-0.7.1-rc.237.aar",
          "size": 127707,
          "sha512": "8e6595363733715e050f79632503a962dd69596dcef86d1bcbfee51cdd2fb3fa10ddc4b1ab033f6a8f91a81024f62e350e5c5f4d22c172e29a29d4957b485df2",
          "sha256": "c7ca683eed19b1a7a2ad56ec989d0eff0810f11c268d2a5374dcd24ea6b6db8a",
          "sha1": "848a90ad5f8c068eec0d8c3d181ec3be0256d5f8",
          "md5": "494bea8ff14c84583b702928687412d6"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "core-android-0.7.1-rc.237.aar",
          "size": 127707,
          "sha512": "8e6595363733715e050f79632503a962dd69596dcef86d1bcbfee51cdd2fb3fa10ddc4b1ab033f6a8f91a81024f62e350e5c5f4d22c172e29a29d4957b485df2",
          "sha256": "c7ca683eed19b1a7a2ad56ec989d0eff0810f11c268d2a5374dcd24ea6b6db8a",
          "sha1": "848a90ad5f8c068eec0d8c3d181ec3be0256d5f8",
          "md5": "494bea8ff14c84583b702928687412d6"
        }
      ]
    }
  ]
}
