{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.6.1-SNAPSHOT.1/flows-sdk-0.6.1-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.6.1-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-iosX64Main-0.6.1-SNAPSHOT.1.klib",
          "url": "flows-sdk-iosx64-0.6.1-SNAPSHOT.1.klib",
          "size": 154635,
          "sha512": "6c5aaed5ac38ab8e28766e54c8a8b8917a740fcf434ffeec86a398365303e73fa44781b4391baa397eb6211f29516a2ae3b5be5e9b35eceacbb45a8aadf1d3fc",
          "sha256": "0b809f22f728041b7f23e6819b47108ae3eeeb70e10476c52447f0e6b6dbf1d5",
          "sha1": "fb4e77b63f75a8ff8341341dddeacc12eb4b6602",
          "md5": "f4ffdc4636e42937d38e61458dab4652"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flows-sdk-iosx64-0.6.1-SNAPSHOT.1-sources.jar",
          "url": "flows-sdk-iosx64-0.6.1-SNAPSHOT.1-sources.jar",
          "size": 37351,
          "sha512": "1e18c16858d64676331914babfa0ae957df06be846ca8cf410cf6ab3629ef54b03e789a07de078da834611a251b27a8913e2d7b9c02ddad40875a06e82614a5d",
          "sha256": "e0560c4875377c4446559ad81ca3c32b4e872a8f44ba1fbeddad6f241c3a34ed",
          "sha1": "4859c243a75e9499f3df2a967755f111ef9049b8",
          "md5": "d8d8397035c5aab623751974eb1832ad"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-0.6.1-SNAPSHOT.1.kotlin_resources.zip",
          "url": "flows-sdk-iosx64-0.6.1-SNAPSHOT.1-kotlin_resources.kotlin_resources.zip",
          "size": 61888,
          "sha512": "bedfd56aecd54a38cfbbe94323fcd0ac5af95fe1201a9d54c788223fa480df28eefb1dfcc4ca80fc945be47c4025e68ddf13e163a646205f4ea3bf53bf046eb9",
          "sha256": "ec2af7194693812fa56e4e320717fe62247c25a5ba330080f1a618ac877b039e",
          "sha1": "258d36f6c3927619c08fd1f2fda7c0a2337ee365",
          "md5": "38a0135bd3fc1602e71e27df28f58cdc"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-iosx64-0.6.1-SNAPSHOT.1-metadata.jar",
          "url": "flows-sdk-iosx64-0.6.1-SNAPSHOT.1-metadata.jar",
          "size": 5272,
          "sha512": "fe4bd5253a5186852931be53261bf644e7b5d6ae0b081a7eebc72c3f2805950f92c1bcbe6c11482a33c608694fa7503b8e7fcdea671cb078a43cd9542dff63e7",
          "sha256": "27513f90aa7e5629fe6f3cd17e043efa82add092ac81079ef1c3b9475b65f8e9",
          "sha1": "59daa480b3d4e6ab97858fd315d6291f1fe3fd5a",
          "md5": "f4d52c720041a22719daa5f65c604ae7"
        }
      ]
    }
  ]
}
