{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.7.0.2/core-0.7.0.2.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.0.2",
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.0.2",
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.0.2",
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.0.2",
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.0.2",
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.0.2",
            "requires": "0.7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "core-android-0.7.0.2.aar",
          "size": 81962,
          "sha512": "11c4332b9c8e055c000469613fcf2845f680509feee704d19e2431261f7fb2216568ae3197e7e2917b52e90fb932f3894afe8364bf3719f45d7c514ee579cca1",
          "sha256": "d536510a6eb8500fe9332ca5a3342b3702ec202c6f3debe686cbe4a7e3fd2ac1",
          "sha1": "c4388dd4c4eff9857dd9ccc9e31bb954e09c8165",
          "md5": "ed3b2b2bcec814c1e9f33cf58ced5896"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.0.2",
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.0.2",
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.0.2",
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.0.2",
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.0.2",
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.0.2",
            "requires": "0.7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "core-android-0.7.0.2.aar",
          "size": 81962,
          "sha512": "11c4332b9c8e055c000469613fcf2845f680509feee704d19e2431261f7fb2216568ae3197e7e2917b52e90fb932f3894afe8364bf3719f45d7c514ee579cca1",
          "sha256": "d536510a6eb8500fe9332ca5a3342b3702ec202c6f3debe686cbe4a7e3fd2ac1",
          "sha1": "c4388dd4c4eff9857dd9ccc9e31bb954e09c8165",
          "md5": "ed3b2b2bcec814c1e9f33cf58ced5896"
        }
      ]
    }
  ]
}
