{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.7.0.1/core-0.7.0.1.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "core-android-0.7.0.1.aar",
          "size": 82225,
          "sha512": "f2310a865a18005d3f63856f0861df4a66879b9b7ae8f8ea9d9294746c8cc92eb26a5c97796ce7d59f30f47c3a5be56c443efe2254d2cf76631a1a60c3d3f36e",
          "sha256": "e9c25bad1228b2c9f76234e4042fa2b84deb1df62e681daebe4bd2b491f27b05",
          "sha1": "04162a50bb38bae3c3cdf3cdfc009fae48167c38",
          "md5": "96f14481d7b41fc0d0595374b4b1f825"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "core-android-0.7.0.1.aar",
          "size": 82225,
          "sha512": "f2310a865a18005d3f63856f0861df4a66879b9b7ae8f8ea9d9294746c8cc92eb26a5c97796ce7d59f30f47c3a5be56c443efe2254d2cf76631a1a60c3d3f36e",
          "sha256": "e9c25bad1228b2c9f76234e4042fa2b84deb1df62e681daebe4bd2b491f27b05",
          "sha1": "04162a50bb38bae3c3cdf3cdfc009fae48167c38",
          "md5": "96f14481d7b41fc0d0595374b4b1f825"
        }
      ]
    }
  ]
}
