{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.6.0-SNAPSHOT.15/runtime-0.6.0-SNAPSHOT.15.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.6.0-SNAPSHOT.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.15"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosArm64Main-0.6.0-SNAPSHOT.15.klib",
          "url": "runtime-iosarm64-0.6.0-SNAPSHOT.15.klib",
          "size": 573911,
          "sha512": "4076649f31f3e5eaa7593b22e0957c3dc664abe10dc838271d99a753226ade543758438d6d5d38fd10d728b5b5a369830a78cb75bf21b895a52141bf09a7f510",
          "sha256": "79a4645a41d6ee592b44f129152ccd482ee94058447d91525c605c004bfcf45c",
          "sha1": "323ede48dd22b58112514297477ba36fb7fe636e",
          "md5": "8b57fcb24e15f2bbd73e213fad408350"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-iosarm64-0.6.0-SNAPSHOT.15-sources.jar",
          "url": "runtime-iosarm64-0.6.0-SNAPSHOT.15-sources.jar",
          "size": 43087,
          "sha512": "0fd848edd7ebdd9c62b5660e8daa95e2e143a9415f2ce411b442fdd8ec4fc8bdc0ceac8ec36bb2dc7d0421a059188c05113190b727eb291b9539b3f6636d7846",
          "sha256": "716957d01dbe2671f867ab86ff8a84f9ee415e43e6afc8ec3dc2b121732e36b2",
          "sha1": "4ca0163c442c33ab5734ea25b7f619acf8996ddd",
          "md5": "a91bddf80edce74f2270947c251e5879"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.15"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosarm64-0.6.0-SNAPSHOT.15-metadata.jar",
          "url": "runtime-iosarm64-0.6.0-SNAPSHOT.15-metadata.jar",
          "size": 2428,
          "sha512": "0eb004d9aeaf4d4735b99b82144eaaf333e20d9d4b47637f7b5eeacfd87cb0cb4165447355fbb37dfebf9a41cea99c84dd0bf3099fa35abf124c0930e4ce4fbb",
          "sha256": "ff41745728b65a3a642cc9390e87d86b54b60101a0ffc101947eaa657bdc0abe",
          "sha1": "8a31af494a749dc72abc8a04689e3be4a6ae6355",
          "md5": "5ed483fa9452f197b5e9f2de1219829f"
        }
      ]
    }
  ]
}
