{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.12/flow-wrapper-kmp-0.5.12.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.12"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosX64Main-0.5.12.klib",
          "url": "flow-wrapper-kmp-iosx64-0.5.12.klib",
          "size": 144393,
          "sha512": "16a2828428b682fdae618e9bc7dd42e89174c0b9ecaf4f021ed89c8e82b4ddc89e3b53b89358fbf42916974e17a09c47f873ea75271a8efa11ed067938e1fe56",
          "sha256": "73787bdd84845fac09907b94f4640e6b1d43976ebbd88793bb21042cc011530e",
          "sha1": "8a35e85269895cd2e99f739b53e3d655aa68bf0f",
          "md5": "b00ccd43a33d9b0891cccc23491efe3c"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.12-sources.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.12-sources.jar",
          "size": 25733,
          "sha512": "e69aaa8014388360dec0dfa21d5eab283bf314ede6f48e8f3c2ef3315861156a922e2bb4217740bf65c7afc9caa69985182642325a338db014ee1d9818c12d30",
          "sha256": "7bf8817dbe523ce96e9ba5a5e89ddfcc419c89377933ef652e55e5ef0591555f",
          "sha1": "6c9572de3f98ef75f5b2dea1dfe9b4e1e637e155",
          "md5": "63460b706b7e1a1ea4dc505443525d58"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.12"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.12.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosx64-0.5.12-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "abdc51555bb327b4a11f23d3a9bd3ff1a01ea9fa5d906569ec35ea8ce982fdb28a7d2fc594029ca4bc4d2981cf4592053d807ae1de6a510440adafe0180d17e5",
          "sha256": "0dee2336ada0d6f6d58fc1fac6a19ae0d8dae175820bfd8b959ed4b2ec27e447",
          "sha1": "f8f7863756b0f564321ce3a6424f998aa78dab5e",
          "md5": "7e50a276f483fdf036bb4c5b5808b31e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.12"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.12-metadata.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.12-metadata.jar",
          "size": 3747,
          "sha512": "342d65bd2157012fe492f186abd45e196a8b4f0c5e8fdd9948e0ca2c7f58b5a7c729b6af170484e286dd9ea2e8829ebd052bc92ca952c698f8f3ffc972c95fb9",
          "sha256": "691b22251d15997ed5c08c637874ac83a8742a2e356f4d158734125f584d13ec",
          "sha1": "09187b5889fbb08d386a937b6233a057277ef650",
          "md5": "75d67351bf91c56403ee8a14ecf51532"
        }
      ]
    }
  ]
}
