{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.6.0-rc.171/flow-wrapper-kmp-0.6.0-rc.171.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.6.0-rc.171",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-rc.171"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.6.0-rc.171"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosArm64Main-0.6.0-rc.171.klib",
          "url": "flow-wrapper-kmp-iosarm64-0.6.0-rc.171.klib",
          "size": 258102,
          "sha512": "e99612c4f551a62530109dec05aa7704b0bb2774baf1bf521a0f47348cf5b6e0dc971e379b5183ad4469cbb943c9622659217cd497482ec546e2585bbb6924d9",
          "sha256": "f9fa6a5f4ff6c1d8ab2341f7cfa19f55813a8b6ca29bd1dbc6cde5e5f681293e",
          "sha1": "e6c65d3fc66d5a14c6237979a8dc86b27a427f36",
          "md5": "060890c78eea6f690b89ecf8ef620a86"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosarm64-0.6.0-rc.171-sources.jar",
          "url": "flow-wrapper-kmp-iosarm64-0.6.0-rc.171-sources.jar",
          "size": 50391,
          "sha512": "0b2cdd8d68c97dac8cdea75cb463222caa4c4000ce6c44f9c4dcc499f16bb9fb85cd43c6a67497b62e681f4163c1d4b3213f1e35bf1ece9933ecc251bdd98a91",
          "sha256": "2f5962fa188850d7b6fd41423d90176df4a3a62673149f968225fc7910836f77",
          "sha1": "c92c71af80b11773ff77d69009af8e9443365c87",
          "md5": "1997e35b3c197aa4132b258f78f330d7"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-rc.171"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.6.0-rc.171"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.6.0-rc.171.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosarm64-0.6.0-rc.171-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "cf7e423afe35d7ff55e4676cb707b7e87b3e3a7c645e6129220eef7ff5236abe7544d68f198e7412136581bb62d6d9894dc94ec1b2a247f03f03b833e49e4111",
          "sha256": "42c72ca66137b2cde6a08861442c754b9419fdcf05257d520903dee47f44f336",
          "sha1": "9f5b8c1331934edb50a4a0b63b5f04a4bbd2e2ff",
          "md5": "8a8ea6684d82e59a64226e03ccce19ea"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-rc.171"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.6.0-rc.171"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosarm64-0.6.0-rc.171-metadata.jar",
          "url": "flow-wrapper-kmp-iosarm64-0.6.0-rc.171-metadata.jar",
          "size": 3852,
          "sha512": "9179a94f1fbc8d4bf60f7daf05ffb199d7280f7357a210ebc7c6784cb60aa2fe705e8ae93d14eeec4f58ee8e710951f426cd08a61f2800bb08be073e75752d17",
          "sha256": "12f485410ef65929fe5f3a2578c2524eff691a564ea8f520703060766a8d6813",
          "sha1": "fa79c8e703bda131be5ea2475aa35f039ed2a8b6",
          "md5": "b98ccf7f76625edb9014522038275ddb"
        }
      ]
    }
  ]
}
