{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.15-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.15-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-metadata-0.5.15-SNAPSHOT.jar",
          "url": "composeblocks-0.5.15-SNAPSHOT.jar",
          "size": 25750,
          "sha512": "3bf6a82c17542afa2db41f7df110a7229031a82e83636497ebd8ab17669fc4dff403f222df56cc37465df6ed58d1abf80bc03efef4f06c4887c9511607959982",
          "sha256": "fa42521cadb81f4915805b799e101432cd2a8bb9d95ea43b6d1a6486711b1bd5",
          "sha1": "7a059c22405071499927a4c00b1d4917989cc23e",
          "md5": "ee7f6c2e1ae03e38feba65042c7f0746"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "composeblocks-kotlin-0.5.15-SNAPSHOT-sources.jar",
          "url": "composeblocks-0.5.15-SNAPSHOT-sources.jar",
          "size": 49753,
          "sha512": "f1ca9dbe4aba1ce199469980de91d0aff310ac7bc2fd97d94f63963fc2024670238b09d6ff0c246e8deb9ff40079362229ebcce87baf7623cff9f1848eba1353",
          "sha256": "606e92cc853eb5db91b72d692c4e97452a52a86e90266a537da512c327feba87",
          "sha1": "b24766f213a6c6db982f52a4e5fbbd7c5f7a9c89",
          "md5": "ba8582f31cd9206ddf3f9a338071c1a9"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.5.15-SNAPSHOT/composeblocks-android-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.5.15-SNAPSHOT/composeblocks-android-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.5.15-SNAPSHOT/composeblocks-android-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.5.15-SNAPSHOT/composeblocks-iosarm64-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.5.15-SNAPSHOT/composeblocks-iosarm64-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.5.15-SNAPSHOT/composeblocks-iosarm64-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.5.15-SNAPSHOT/composeblocks-iosarm64-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.5.15-SNAPSHOT/composeblocks-iossimulatorarm64-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.5.15-SNAPSHOT/composeblocks-iossimulatorarm64-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.5.15-SNAPSHOT/composeblocks-iossimulatorarm64-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.5.15-SNAPSHOT/composeblocks-iossimulatorarm64-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.5.15-SNAPSHOT/composeblocks-iosx64-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.5.15-SNAPSHOT/composeblocks-iosx64-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.5.15-SNAPSHOT/composeblocks-iosx64-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.5.15-SNAPSHOT/composeblocks-iosx64-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-jvm/0.5.15-SNAPSHOT/composeblocks-jvm-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-jvm",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-jvm/0.5.15-SNAPSHOT/composeblocks-jvm-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-jvm",
        "version": "0.5.15-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-jvm/0.5.15-SNAPSHOT/composeblocks-jvm-0.5.15-SNAPSHOT.module",
        "group": "br.com.wave",
        "module": "composeblocks-jvm",
        "version": "0.5.15-SNAPSHOT"
      }
    }
  ]
}
