{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.19-SNAPSHOT/composeblocks-0.5.19-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.19-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.19-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.5.19-SNAPSHOT.klib",
          "url": "composeblocks-iosx64-0.5.19-SNAPSHOT.klib",
          "size": 346274,
          "sha512": "f6d8d65f6b16a0e644f1dde9b7954a29fe7b60275edee4df9f961ce0b370ee114aef727da7324e0988270737c9633f28d6043d7133acff536eb0556c0860dc7a",
          "sha256": "3d9c46319ac8877dac45d57c8bb491a6e3c7dd33add6430e8b7269f0a7c113a1",
          "sha1": "bcb2023b57e6194efa84a237092c5e9e6f6e0734",
          "md5": "1ce00441259311222d02969950ad44a3"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosx64-0.5.19-SNAPSHOT-sources.jar",
          "url": "composeblocks-iosx64-0.5.19-SNAPSHOT-sources.jar",
          "size": 62231,
          "sha512": "cfbfe2bf7b7416f7af8f97aa075f8b57d3969a5017052c4d671bd69718e963d7ff1dcd1cfed19a311f81a9103a224fc48ab4283f6c5a8c83c59b7f7f89fe6172",
          "sha256": "e761524c5ac32c9653ead0e6a1f263738e0d2182ff6f9a0ca8e79de42d779531",
          "sha1": "0b235e3d8c927ad8b3eddb08fad6a492a7394142",
          "md5": "182b7e2476de6a929ce1da2235eea64c"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.19-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.19-SNAPSHOT.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.5.19-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "630eefba12da42e2fdc5923788b27aa02e56801b6fb8a795cfc8d6caf0597d6ccbc66ff72b23f95e0d0c426b706f4c242732c96de94fce8c6efc783fce0e3a72",
          "sha256": "2357d4eefc1f15c4334abdb9286ba1d5e2ec9f2a250e39e7931924c484d707f5",
          "sha1": "822dc2b084e99fac72063b92cfeac96e4e349bca",
          "md5": "9d2eecbf58f3cac7101974dce9381609"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.19-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.5.19-SNAPSHOT-metadata.jar",
          "url": "composeblocks-iosx64-0.5.19-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "2a381b922d44f915ee0fea2c6f40cbc241d235a617998cfad71a39e98ca238537291478a3235197b7f40a411508b3e7a261663897c46a9c46fc98e047bbddcce",
          "sha256": "35d47dfc6c62e5fbb1838bf6cf034d75fb73f49aaf71dbc7ad3b6968cbc974ce",
          "sha1": "f1137350ee8541f644be5811f8c58a0b888012bb",
          "md5": "66466ecaadb6ffcfa44b2b4b8a71830e"
        }
      ]
    }
  ]
}
