{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.17/composeblocks-0.5.17.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.17"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosArm64Main-0.5.17.klib",
          "url": "composeblocks-iosarm64-0.5.17.klib",
          "size": 344602,
          "sha512": "fe199cd682719788636e5731e461fb8b72a53959a03b522a220fe2c80268c5b62fc12ecd5f99b6f9eb232634327e2463d13695c0b936c70e29dc10b81b645fc4",
          "sha256": "8d5b179ec17631f943f7a18682f65a4dfaf1541b14d46fe496e7e1f6d4496d4a",
          "sha1": "e0d2617eb2e867c2885aa16ae91501b692f0d67f",
          "md5": "3c0fb93d696a5222f27ad19bd893370b"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.17-sources.jar",
          "url": "composeblocks-iosarm64-0.5.17-sources.jar",
          "size": 61722,
          "sha512": "a82fdd47d7da96a81aaed8005a4b941247647218ea9a2627d23b72f664c7a8e238c3487104200057043a82cf69d3ae685cab9f7bf60d01d21e624abefb12764b",
          "sha256": "c08a32ed59f8283e6f8eaf4a51e9dffb804eb86bd14f8c78ff5a9721c2e36866",
          "sha1": "d691f285cd7214d60faf1d3a6646ae63791df966",
          "md5": "05c64f60a31443a21663cabadb1d5ea5"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.17"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.17.kotlin_resources.zip",
          "url": "composeblocks-iosarm64-0.5.17-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "20c4995173d415bab1f7dfda786f9986251fa159a17dbca6284a1c56096710c3d95864b2d118710e5ebfda3dd9bd60b71fba1e03668378ca281afd082fecc798",
          "sha256": "6b523cd29a8cb54923c33fd164d3a8ff7fe51253ba9b71bce20b1ffe7055919e",
          "sha1": "692c0895f368aab8ca362069f4b193fb5c672eba",
          "md5": "4494b762c90b0336c220a28f1328a061"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.17"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.17-metadata.jar",
          "url": "composeblocks-iosarm64-0.5.17-metadata.jar",
          "size": 261,
          "sha512": "ae528cb3febf977c2a16aaa255471ec06b381870fc771ffc5a94f7eeaac917e4f12edcf7d04d9f3f3a5c4f11fe866e808ba344adac9c070d94380686f017ab5a",
          "sha256": "981ca45e1e105de683a74853c7a695dea9b3fb9d13246f3135573ad0a8119c3a",
          "sha1": "90b27037787b8ce8bb24d7cd8a9467d2f3e52d37",
          "md5": "93eb20956b0e960d55011809a5a645f7"
        }
      ]
    }
  ]
}
