{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.13-rc.50/composeblocks-0.5.13-rc.50.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.13-rc.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks.aar",
          "url": "composeblocks-android-0.5.13-rc.50.aar",
          "size": 134217,
          "sha512": "2c50b08a37f1378ad5f5c3dcbcfd16b8cd997d07d57d4d2a3619454b3579c81a4395c8511f5fe14454d70f461de833211999e323bfbfbc9da516ae14c9a57f7d",
          "sha256": "768e884ad4f64aa4349650e9e38492705e0c10a0ed718807b9c647c437f0ab05",
          "sha1": "da31ac2cf5002a1676784de690b77539ae991ff3",
          "md5": "6b894de0f1e9f493b6c2e2150006b6ff"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.13-rc.50"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.13-rc.50"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks.aar",
          "url": "composeblocks-android-0.5.13-rc.50.aar",
          "size": 134217,
          "sha512": "2c50b08a37f1378ad5f5c3dcbcfd16b8cd997d07d57d4d2a3619454b3579c81a4395c8511f5fe14454d70f461de833211999e323bfbfbc9da516ae14c9a57f7d",
          "sha256": "768e884ad4f64aa4349650e9e38492705e0c10a0ed718807b9c647c437f0ab05",
          "sha1": "da31ac2cf5002a1676784de690b77539ae991ff3",
          "md5": "6b894de0f1e9f493b6c2e2150006b6ff"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "composeblocks-android-0.5.13-rc.50-sources.jar",
          "url": "composeblocks-android-0.5.13-rc.50-sources.jar",
          "size": 36171,
          "sha512": "23c4853c4c5ee3e6ac70f0d156f7edca210d60c462afc04368f907794a7dd2bb486270d34bbf5a74f3b285ae3096689a8043dbeac4e6731b501f0447b4c97010",
          "sha256": "27d5e6dbc67211882f5e0804adf3872f8687745226d6a4874e42cce92a4b2e3f",
          "sha1": "5993f83f60b0d937068cf7414394a0621ef03b5d",
          "md5": "f7e8a769e83320cad5d567a321b1c829"
        }
      ]
    }
  ]
}
