{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.6.0-SNAPSHOT.26/composeblocks-0.6.0-SNAPSHOT.26.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.6.0-SNAPSHOT.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.26"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.26"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.6.0-SNAPSHOT.26.klib",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.26.klib",
          "size": 224071,
          "sha512": "948afd36c2e3ee6b738d78a0207b05e5dfdc1ebbeaa30882f1f2368907f882ed5e548529b087566d5442cc6422e3439a0c60bbbb1ba8de669261dddfcc48a879",
          "sha256": "bea0e5b50621e69bc4578122d65ac862d822355ec4c345de033a7e9c5c2251ac",
          "sha1": "ee7d328345a6cb216806bd0d67de43faacc23535",
          "md5": "49392f03c6e84ca0e4521694bcf0c6be"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosx64-0.6.0-SNAPSHOT.26-sources.jar",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.26-sources.jar",
          "size": 36001,
          "sha512": "a06eae165039e1dbce80d1ab377809fb2ad27f0caf4672e34d468bdd4286a33897a422d7fc8bf7ebd0a52f42cc02d5a5c0c718918a6df9454c2982ec4b59c736",
          "sha256": "bca7eacd2963d7040e5e5b9373bbb3ff433d26fccadc3c9bb70bda49906b9493",
          "sha1": "27713da878c704a2da419c8ee1fbb57d345716e3",
          "md5": "bb9423db087a7fa0fad0bb98eeba094e"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.26"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.26"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.6.0-SNAPSHOT.26.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.26-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "b1e427479c3eae00b66399d44407e0e68f8b4d6500382d4b4877dd90f53407fc1c34a019e686559148468c0ee564c7388e7a212908ac8009a88bb83ed6910724",
          "sha256": "502288e3382d28c4720fe1f84a24e013958e3efa9df3ef46b7f39ea74c480678",
          "sha1": "73bce8d18df3bab76b3dcd1eb88949f43223225a",
          "md5": "379128df7cfc7685b204895adb25e76b"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.26"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.26"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.6.0-SNAPSHOT.26-metadata.jar",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.26-metadata.jar",
          "size": 261,
          "sha512": "4df542251141f4d91d7dd4f1a014df6972effe2d242bc97360b106c95a516c21bc5b9bbab949712f8f439e9bdad5eef030ce0a27f219286fab3a639522698f4b",
          "sha256": "9beba0060deb9d52801fe0d7569da92c005068507eb4611826da38f4b97fa419",
          "sha1": "43aeb4916cb3d2e0a543efabb44fccab0de12811",
          "md5": "c7f0e65dc49de89e5265fbce0ce93932"
        }
      ]
    }
  ]
}
