{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.19/composeblocks-0.5.19.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.5.19.klib",
          "url": "composeblocks-iosx64-0.5.19.klib",
          "size": 346623,
          "sha512": "454c09dbbd853fd6271e0041ca78cbe2088d9bd87c51c0c3bb7810057363d4dc67a57a47d869d60bf980b15f253377d96e430bda7a0a38fd64452b517ed71b7d",
          "sha256": "fa62a77dad9d43c7e6bc6fc62ad264f788f850eaa3c9aa7ffa216781746b399d",
          "sha1": "ee1d71ca903f1de63b9facac184b5cac33f16637",
          "md5": "a5dce53ff2fa273f42f8ea8e1d87b9b2"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosx64-0.5.19-sources.jar",
          "url": "composeblocks-iosx64-0.5.19-sources.jar",
          "size": 62439,
          "sha512": "d298077bddd9dd1a8a5e1872887446c920abb210d1dfdeed88e9d970fc0ffb1e3621620a71bec1c9125f09f9bda5cd9b2e16857511ee4a9746979231889089b3",
          "sha256": "fc541b5ec39cc4f025d6450782fa4ce92a66871b0ea12e2143e7d3907c97f61a",
          "sha1": "6bd12f366865d460c6c3a6906d1cf84d301959cf",
          "md5": "50b8a091984e6b08e0ed8c5465ada2e2"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.19.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.5.19-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "7d6a0ecae12a9b5f128e182b1397b743430d99f5a093eee1134ed56d14006ca8d503977c0e07fc68cd8ebcd13c7cf8772e4b97befb507ab8d85779f0f0710f3f",
          "sha256": "04a161218065c84edda85abf347c98b95ca760bbaafac2c9c8ada74e7e4795ff",
          "sha1": "1979749ec67a4ea8705fad9b697315b9c643321a",
          "md5": "7af1a7ae8ab36a7c1a665cf0475c36e3"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.5.19-metadata.jar",
          "url": "composeblocks-iosx64-0.5.19-metadata.jar",
          "size": 261,
          "sha512": "9d7b171369bac0990d31ec59242e119eeae096e958680ae39e0211ef03371eade3138738ebe9fd317a6d8685b6205a67d8b5540a675b2f5a65528a3d5e57ad95",
          "sha256": "d60745ff96b35f4296e815f3b54c9e9558cea2e63e881cbe38f7a55dd8b5227f",
          "sha1": "78da316fd3d39529daf0e9ac28ad536c745200ea",
          "md5": "51e9cf4319ecedb605a5c350c4ea3f6f"
        }
      ]
    }
  ]
}
