{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.7.0-rc.186",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk-metadata-0.7.0-rc.186.jar",
          "url": "flows-sdk-0.7.0-rc.186.jar",
          "size": 24767,
          "sha512": "7a5af63246dfb29d0f7a1c4a27625db238ae55ed508ec50617e18623b911781851d756b1bf5338936e70f2b058276e3effff2bb64d4e2199fdfca0b274840824",
          "sha256": "bc12cb9e0addc634e558fcd79981a04cfc297442a76789bdf6f4e0170d9db986",
          "sha1": "49add408cfc7f2a0b6ea748db231a284625ecffc",
          "md5": "bbade265803eb73f2a48dcc5331ee22e"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flows-sdk-android/0.7.0-rc.186/flows-sdk-android-0.7.0-rc.186.module",
        "group": "br.com.wave",
        "module": "flows-sdk-android",
        "version": "0.7.0-rc.186"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flows-sdk-android/0.7.0-rc.186/flows-sdk-android-0.7.0-rc.186.module",
        "group": "br.com.wave",
        "module": "flows-sdk-android",
        "version": "0.7.0-rc.186"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosarm64/0.7.0-rc.186/flows-sdk-iosarm64-0.7.0-rc.186.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosarm64",
        "version": "0.7.0-rc.186"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosarm64/0.7.0-rc.186/flows-sdk-iosarm64-0.7.0-rc.186.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosarm64",
        "version": "0.7.0-rc.186"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosarm64/0.7.0-rc.186/flows-sdk-iosarm64-0.7.0-rc.186.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosarm64",
        "version": "0.7.0-rc.186"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iossimulatorarm64/0.7.0-rc.186/flows-sdk-iossimulatorarm64-0.7.0-rc.186.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iossimulatorarm64",
        "version": "0.7.0-rc.186"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iossimulatorarm64/0.7.0-rc.186/flows-sdk-iossimulatorarm64-0.7.0-rc.186.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iossimulatorarm64",
        "version": "0.7.0-rc.186"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iossimulatorarm64/0.7.0-rc.186/flows-sdk-iossimulatorarm64-0.7.0-rc.186.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iossimulatorarm64",
        "version": "0.7.0-rc.186"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosx64/0.7.0-rc.186/flows-sdk-iosx64-0.7.0-rc.186.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosx64",
        "version": "0.7.0-rc.186"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosx64/0.7.0-rc.186/flows-sdk-iosx64-0.7.0-rc.186.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosx64",
        "version": "0.7.0-rc.186"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flows-sdk-iosx64/0.7.0-rc.186/flows-sdk-iosx64-0.7.0-rc.186.module",
        "group": "br.com.wave",
        "module": "flows-sdk-iosx64",
        "version": "0.7.0-rc.186"
      }
    }
  ]
}
