{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.20-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-metadata-0.5.20-SNAPSHOT.3.jar",
          "url": "composeblocks-0.5.20-SNAPSHOT.3.jar",
          "size": 28471,
          "sha512": "33631de15c71dda6a86a34bfca5b18ea2438832b8f4c5f407ec54caebc63596843bc0ce630e33f8141d3f64515c143a213fbe7686bc17b20036ef77e8a8f400e",
          "sha256": "c51ab46cb1865857070d293ac8346cf3e582ad61e8b11c58bfcc1225565b1ce7",
          "sha1": "e3a05d3fd0c62be24fc2fe9ceccf7ed951b8a7d1",
          "md5": "cc1668d8ff97d33fb52bc27380f7db77"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "composeblocks-kotlin-0.5.20-SNAPSHOT.3-sources.jar",
          "url": "composeblocks-0.5.20-SNAPSHOT.3-sources.jar",
          "size": 62890,
          "sha512": "4a59e27f2a29435e1ef668a3f80f54b5579a027454fa3563ccbac9ebc4c20fea52d6a9c9b1073a4eea216c777bd6f08d9104dc1622d14a962c7a0f6555a52602",
          "sha256": "38494ba44d71f81e028eb09b8af0ae27a8b8ece1e6c8a7a7e9656f507a53fe71",
          "sha1": "e6e5c5547420fa3ae406d945fd6226ba56b60f9f",
          "md5": "e71bf7ca299e303fb36f875345bdde51"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.5.20-SNAPSHOT.3/composeblocks-android-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.5.20-SNAPSHOT.3/composeblocks-android-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.5.20-SNAPSHOT.3/composeblocks-android-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.5.20-SNAPSHOT.3/composeblocks-iosarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.5.20-SNAPSHOT.3/composeblocks-iosarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.5.20-SNAPSHOT.3/composeblocks-iosarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.5.20-SNAPSHOT.3/composeblocks-iosarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.5.20-SNAPSHOT.3/composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.5.20-SNAPSHOT.3/composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.5.20-SNAPSHOT.3/composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.5.20-SNAPSHOT.3/composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.5.20-SNAPSHOT.3/composeblocks-iosx64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.5.20-SNAPSHOT.3/composeblocks-iosx64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.5.20-SNAPSHOT.3/composeblocks-iosx64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.5.20-SNAPSHOT.3/composeblocks-iosx64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-jvm/0.5.20-SNAPSHOT.3/composeblocks-jvm-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-jvm",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-jvm/0.5.20-SNAPSHOT.3/composeblocks-jvm-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-jvm",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-jvm/0.5.20-SNAPSHOT.3/composeblocks-jvm-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "composeblocks-jvm",
        "version": "0.5.20-SNAPSHOT.3"
      }
    }
  ]
}
