{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.18/flow-wrapper-kmp-0.5.18.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.18.aar",
          "size": 212290,
          "sha512": "fe1464c66b68342da6f2fe3a91d07fa4f79ae7bb3f5e3087de123c095d9b37fe73025f4cd18fa4ff5ee16875e21a320c84f57a5fe5b481ea30564a884d590fe7",
          "sha256": "5233fed84bc7cffe51aaea755a96050968a8e62fcafa8a7843d5a7a8b5d6cf1b",
          "sha1": "47d0a05135abaf28bb30a7495d3e960ea8fbe51b",
          "md5": "f1bf443b8a804334003c0d54cf023bdf"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.18"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.18"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.18.aar",
          "size": 212290,
          "sha512": "fe1464c66b68342da6f2fe3a91d07fa4f79ae7bb3f5e3087de123c095d9b37fe73025f4cd18fa4ff5ee16875e21a320c84f57a5fe5b481ea30564a884d590fe7",
          "sha256": "5233fed84bc7cffe51aaea755a96050968a8e62fcafa8a7843d5a7a8b5d6cf1b",
          "sha1": "47d0a05135abaf28bb30a7495d3e960ea8fbe51b",
          "md5": "f1bf443b8a804334003c0d54cf023bdf"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-android-0.5.18-sources.jar",
          "url": "flow-wrapper-kmp-android-0.5.18-sources.jar",
          "size": 41948,
          "sha512": "fe1852fcdb7845a74f2a9bc05b9666618d71eb2c68816e5d04d914a9ea33d9d37260f0211d10eea51d31c4435ec16aa980fa7d000ca9aa03fa2513f7913394e9",
          "sha256": "87e0fde2ebdec6ec5ff0567e3f7e2b823171f224b7497e5d1516b9d6c13f5f1a",
          "sha1": "d762845bee768838794fe5dac6ccb8c6b8a2aed0",
          "md5": "f922ae38d522d63e12b7cfa9f92a640d"
        }
      ]
    }
  ]
}
