{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.7.0.1/core-0.7.0.1.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosSimulatorArm64Main-0.7.0.1.klib",
          "url": "core-iossimulatorarm64-0.7.0.1.klib",
          "size": 144211,
          "sha512": "00781c2d5ef30a2f7896418c82a3e03bf5a923e7bc593de8e1034534627ba0d8dc87d74c6993058d33844076deb88bf499c29d6015f2cf0a404e13a0bea3ddce",
          "sha256": "1aade37a38efd99b88d35a05abe7f0b1de29b5c04b3e17f391919775d8d600d7",
          "sha1": "6b2bf7ba131eb4401aace7aaedda90406f45af61",
          "md5": "7cdb42cfa82788cd07808cafed802d80"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.7.0.1-metadata.jar",
          "url": "core-iossimulatorarm64-0.7.0.1-metadata.jar",
          "size": 261,
          "sha512": "82915f327053e7c63e5dc21f45ee69331bcb43c9714233fca0d9129eebbb47ef2c5427c40e9e911876f942925cb58d88bf1347c4398ab9d3b8c59bededa682d5",
          "sha256": "5edba5e6a29cbbdd564b2855c8a172db916a44ca3284fe09e861ec7678e9e654",
          "sha1": "af807036d3c0871f8739216ff9ad25e47dc08777",
          "md5": "8add0cf3bf2ff01485bf6df08498ea3f"
        }
      ]
    }
  ]
}
