{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.6.1-SNAPSHOT.2/flow-wrapper-kmp-0.6.1-SNAPSHOT.2.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.6.1-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.6.1-SNAPSHOT.2.aar",
          "size": 233914,
          "sha512": "8224c60b2d051f9272cd4c32b8c05dccddcf96119ac5330ef51fff2df313d5a69ca91046af228792941a16696052ee91376319ae137530ee18470c40180ba6f9",
          "sha256": "0af580f77fe3ef5e889cc71fac808b267b685c4badd67fbdde2cdebbf6ed0a1b",
          "sha1": "8505ba8d7df71058aa60ecfcfcd903a9de48dc00",
          "md5": "95cd278d4e5f6694077e6c9a71d94071"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.6.1-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.6.1-SNAPSHOT.2.aar",
          "size": 233914,
          "sha512": "8224c60b2d051f9272cd4c32b8c05dccddcf96119ac5330ef51fff2df313d5a69ca91046af228792941a16696052ee91376319ae137530ee18470c40180ba6f9",
          "sha256": "0af580f77fe3ef5e889cc71fac808b267b685c4badd67fbdde2cdebbf6ed0a1b",
          "sha1": "8505ba8d7df71058aa60ecfcfcd903a9de48dc00",
          "md5": "95cd278d4e5f6694077e6c9a71d94071"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-android-0.6.1-SNAPSHOT.2-sources.jar",
          "url": "flow-wrapper-kmp-android-0.6.1-SNAPSHOT.2-sources.jar",
          "size": 59732,
          "sha512": "17325b1e8cfa23ebccf4c79e9143e30fb956ee02ddba0e16f96208f62ff682f97c91ec187356ebcd7d5629299c0dbe5d1e61a5ba381d0e26d1c6e50a7508cbd4",
          "sha256": "c1e9c443e7ec79923a1b675cbdc3709651d49eec389d6aa8535cf4edc4053c0b",
          "sha1": "d38aada90edf748b05b377756680658efe729e5c",
          "md5": "b390576426ae2e5d2df788f234cc150f"
        }
      ]
    }
  ]
}
