{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.7.2-SNAPSHOT.1/runtime-0.7.2-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.7.2-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.7.2-SNAPSHOT.1",
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.2-SNAPSHOT.1",
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.2-SNAPSHOT.1",
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.2-SNAPSHOT.1",
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.2-SNAPSHOT.1",
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.2-SNAPSHOT.1",
            "requires": "0.7.2-SNAPSHOT.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.aar",
          "url": "runtime-android-0.7.2-SNAPSHOT.1.aar",
          "size": 686586,
          "sha512": "1f0f5fcb01fe421fb0a1d6f31be6a96947167a9a2c2fc3a71eb353cd5aa62cb9377563b4f45101730cdcf2483178ec868167100c4017fa173ed235413e43ce7b",
          "sha256": "1643dc5fbfefdc31037a19476426be4b42c0ac61dead307cb73f6f6438b38f4c",
          "sha1": "cd992521ce617bc413a06f08dce57df5481a010f",
          "md5": "bf433991c2704f2bff1b6f8104d74f27"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.7.2-SNAPSHOT.1",
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.2-SNAPSHOT.1",
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.2-SNAPSHOT.1",
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.2-SNAPSHOT.1",
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.2-SNAPSHOT.1",
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.2-SNAPSHOT.1",
            "requires": "0.7.2-SNAPSHOT.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.aar",
          "url": "runtime-android-0.7.2-SNAPSHOT.1.aar",
          "size": 686586,
          "sha512": "1f0f5fcb01fe421fb0a1d6f31be6a96947167a9a2c2fc3a71eb353cd5aa62cb9377563b4f45101730cdcf2483178ec868167100c4017fa173ed235413e43ce7b",
          "sha256": "1643dc5fbfefdc31037a19476426be4b42c0ac61dead307cb73f6f6438b38f4c",
          "sha1": "cd992521ce617bc413a06f08dce57df5481a010f",
          "md5": "bf433991c2704f2bff1b6f8104d74f27"
        }
      ]
    }
  ]
}
