{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.17-SNAPSHOT/composeblocks-0.5.17-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.17-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.17-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosArm64Main-0.5.17-SNAPSHOT.klib",
          "url": "composeblocks-iosarm64-0.5.17-SNAPSHOT.klib",
          "size": 342632,
          "sha512": "988c72478afa81da275ef6555452a47603447360038ebb0b4c0b6d267682de5dc31289d6f913b55cfa1111766ca762538a08536cc3778974386f0f411ac55673",
          "sha256": "38a6c38dd01dd4aee7e700994bcc54ee23b5b4b77910598cff4b4c9852b5ac30",
          "sha1": "e9f93863d609240e1ca9f4b1c84730d668f28aef",
          "md5": "08a3b4716c6bd924ddf1925e9f99028f"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.17-SNAPSHOT-sources.jar",
          "url": "composeblocks-iosarm64-0.5.17-SNAPSHOT-sources.jar",
          "size": 60646,
          "sha512": "72b321fce90019e028ba8e489e7bbe0e4863e35ac4b443749bdd4821e8bc2429294f29b8ae79c0e52ca87f5a8b36bc2093ef61815f4c51b76e935d10c5deb0e7",
          "sha256": "766c3bd150fce2a922f56071959613846680561526d6cf900be495e726708482",
          "sha1": "8db9966a7c740c7b8752b16761d5e3a48bf33a93",
          "md5": "0ee548675101f621f6b753e4b9feb248"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.17-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.17-SNAPSHOT.kotlin_resources.zip",
          "url": "composeblocks-iosarm64-0.5.17-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "fac8f49359abe673da379810da2267358b65ff58b16cfe169bec880be90f055f04ec44892b5c79a1d073b83a7e8db86914550719547b3c52ea46517a515f2d46",
          "sha256": "9b7f6feb97e575cdd55e1345b41d03f756312fdab70898de77a776c3ce2ecef4",
          "sha1": "aeeed3fb9b4c428bfd49332e32babff8637b6f5e",
          "md5": "82c206eede38d728ad243d9d6cc4b298"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.17-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.17-SNAPSHOT-metadata.jar",
          "url": "composeblocks-iosarm64-0.5.17-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "48d6bea427bd9cf557f1862326f1f36c59279148cfad972804fe3eb3665911d634da73a2b045537823c6dee57639fafc452f4f77dea81bdb2b7d39faa587ebfb",
          "sha256": "9e409bf58f6eb2f51f98ac65d1d9809c29c663962b7a4cf4ab3b3916d627610a",
          "sha1": "42730a35ee13871b680bde54cbeb6dc57ba37e31",
          "md5": "d777aaea6d204cfbcce19926abcc12c3"
        }
      ]
    }
  ]
}
