{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.7.1-rc.238/runtime-0.7.1-rc.238.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.7.1-rc.238",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.7.1-rc.238",
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.1-rc.238",
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.1-rc.238",
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.1-rc.238",
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.1-rc.238",
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.1-rc.238",
            "requires": "0.7.1-rc.238"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.aar",
          "url": "runtime-android-0.7.1-rc.238.aar",
          "size": 676568,
          "sha512": "ab9e38e0459502316eb81c2c4580255456a530385921012d9856551980b6b4c3f9b2eb7a4281ebf506144dc8317eceab2a4f3b8aa97c606041dd7a007091f2ad",
          "sha256": "68a4463be402ea92496c1602e7aff6e4719fd8bc432449bb43403f8782f5cb57",
          "sha1": "63458bc8c7eef4217f3bb1e87e136223b66cd04b",
          "md5": "1a3627950373ef7315228b7613a3c086"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.7.1-rc.238",
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.1-rc.238",
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.1-rc.238",
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.1-rc.238",
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.1-rc.238",
            "requires": "0.7.1-rc.238"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.1-rc.238",
            "requires": "0.7.1-rc.238"
          }
        }
      ],
      "files": [
        {
          "name": "runtime.aar",
          "url": "runtime-android-0.7.1-rc.238.aar",
          "size": 676568,
          "sha512": "ab9e38e0459502316eb81c2c4580255456a530385921012d9856551980b6b4c3f9b2eb7a4281ebf506144dc8317eceab2a4f3b8aa97c606041dd7a007091f2ad",
          "sha256": "68a4463be402ea92496c1602e7aff6e4719fd8bc432449bb43403f8782f5cb57",
          "sha1": "63458bc8c7eef4217f3bb1e87e136223b66cd04b",
          "md5": "1a3627950373ef7315228b7613a3c086"
        }
      ]
    }
  ]
}
