{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.8.0/runtime-0.8.0.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosArm64Main-0.8.0.klib",
          "url": "runtime-iosarm64-0.8.0.klib",
          "size": 871212,
          "sha512": "59060cdb32b8fe180a7f2057b283b18a8bc708a1442493588a03013e18b75e8d200a424218ae2d047a995519de536a7de4260624a905155b1d62eacfc9746852",
          "sha256": "650799ac4b640e939e7d253a106239a185b54d62a7f36ac624bb2f0b8f9ac3a0",
          "sha1": "7eec9d08d44f449f3d96008f8529bd3df34cae50",
          "md5": "3ed37e7d525be09d1bc3564ab9d1c038"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosarm64-0.8.0-metadata.jar",
          "url": "runtime-iosarm64-0.8.0-metadata.jar",
          "size": 2428,
          "sha512": "35e2188dff5bd9ac4aca8f6d6e06d672bc908f6e2d42b9591cf2009f960df4f05c6eeb6c440da6187e7ed680319984ba01c02d14a17af6ff41d3d7441a9e932f",
          "sha256": "d72d89468a627e3fa1c2e54bff91f824e1e2e31534e6a8d1d145e2a3be2b5633",
          "sha1": "639011bc45a3a1059b75970a14d8cb8e420ae739",
          "md5": "8ee441f8f06b12d7f7d46e22598016fb"
        }
      ]
    }
  ]
}
