{
  "formatVersion": "1.1",
  "component": {
    "url": "../../webblocks/0.7.1/webblocks-0.7.1.module",
    "group": "br.com.wave",
    "module": "webblocks",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.7.1",
            "requires": "0.7.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.1",
            "requires": "0.7.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.1",
            "requires": "0.7.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.1",
            "requires": "0.7.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.1",
            "requires": "0.7.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.1",
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "webblocks.aar",
          "url": "webblocks-android-0.7.1.aar",
          "size": 47652,
          "sha512": "63788497050038898ebd104eb0bcc922e0bdc752a5f3aee908efd0b91ec12b55d4d70864239dc4b0e9c0d5fa72c46eafe1b4338fd89557e4152d8d640c6c8db5",
          "sha256": "5ee445a947f553e6d71390ad2f7e3ece51157ae95c6004eb79f7f38abb14a9bd",
          "sha1": "f8f5c546fd21e661ae3ba36d66210e8bd7713658",
          "md5": "f09c3f003f6eab1790eb6674e8ec66f8"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.7.1",
            "requires": "0.7.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.1",
            "requires": "0.7.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.1",
            "requires": "0.7.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.1",
            "requires": "0.7.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.1",
            "requires": "0.7.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.1",
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "webblocks.aar",
          "url": "webblocks-android-0.7.1.aar",
          "size": 47652,
          "sha512": "63788497050038898ebd104eb0bcc922e0bdc752a5f3aee908efd0b91ec12b55d4d70864239dc4b0e9c0d5fa72c46eafe1b4338fd89557e4152d8d640c6c8db5",
          "sha256": "5ee445a947f553e6d71390ad2f7e3ece51157ae95c6004eb79f7f38abb14a9bd",
          "sha1": "f8f5c546fd21e661ae3ba36d66210e8bd7713658",
          "md5": "f09c3f003f6eab1790eb6674e8ec66f8"
        }
      ]
    }
  ]
}
