{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.7.0.1/runtime-0.7.0.1.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosX64Main-0.7.0.1.klib",
          "url": "runtime-iosx64-0.7.0.1.klib",
          "size": 684859,
          "sha512": "53342255345af67180d80eccddc8d1e96548df0f54ea3031a837efbb51d2804cf808f904a4d1e1c2a61ac5a511228f576a49e48e0375a8be9edc55ea7d3ad46c",
          "sha256": "674818b2236e77ed83f9baaede219a378e420d4dc9ced96c8d566c4b386f675f",
          "sha1": "a622269bfc02f0d9c142600350a16aa0e49c49fb",
          "md5": "b3f10374347695cd36c034c0f1b11b8c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosx64-0.7.0.1-metadata.jar",
          "url": "runtime-iosx64-0.7.0.1-metadata.jar",
          "size": 2428,
          "sha512": "ca60fddeedb6a9f30006dbcd1832439a0bf8794f64da5220b1ad3892d4b4180d2d449949d8b41083077cb1ec2ca5ec0879115446b56754bd00d253d6996ffd0b",
          "sha256": "082c883a1039f2e1ab720e7b5acfd2f5279fceff0847461a0d1f5453318aba85",
          "sha1": "6d6ec2ce69d70f15bb1981b730ca8e53f4744fb2",
          "md5": "b6dfba8007ee4a0ce60f1dd76dcd4771"
        }
      ]
    }
  ]
}
