{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.20-SNAPSHOT.3/composeblocks-0.5.20-SNAPSHOT.3.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.20-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosSimulatorArm64Main-0.5.20-SNAPSHOT.3.klib",
          "url": "composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.3.klib",
          "size": 348335,
          "sha512": "723d73406fa58cceee3d46aa58e56c35f5976741350cf9d844c02fbbb1144461d52b78289ccef6b9d3da98e40e42b720248268d0dab51e2aec01711401327de7",
          "sha256": "f46711bd396d234e4557f469ab2c96ceb1b725cbaeddff8ab90a275c4e9a256c",
          "sha1": "594a2a0f9f2dd0f57727a5f84ae18b1d29f128b1",
          "md5": "3569261d4c25373e22780274ea63060e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.3-sources.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.3-sources.jar",
          "size": 62890,
          "sha512": "4a59e27f2a29435e1ef668a3f80f54b5579a027454fa3563ccbac9ebc4c20fea52d6a9c9b1073a4eea216c777bd6f08d9104dc1622d14a962c7a0f6555a52602",
          "sha256": "38494ba44d71f81e028eb09b8af0ae27a8b8ece1e6c8a7a7e9656f507a53fe71",
          "sha1": "e6e5c5547420fa3ae406d945fd6226ba56b60f9f",
          "md5": "e71bf7ca299e303fb36f875345bdde51"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.20-SNAPSHOT.3.kotlin_resources.zip",
          "url": "composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.3-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "5565e0a83f3dd327d557bc9dae74ba6242482a86305d014472f7a2376841218d87239640e8516aa3e71029f15329cfcb3bf4e9840ca72a299adef0818e4d7edb",
          "sha256": "b70e82783d7e1706a95ca4f9dccbf1fc54c957f9cb79bfd0e66fedc801571447",
          "sha1": "db05a36a55990954a13189e3ecfa12c7ee573815",
          "md5": "816a8ea9d1c98efbee4083c649339652"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.3-metadata.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.3-metadata.jar",
          "size": 261,
          "sha512": "1e441f564c36cfdef0a421d3b7c4b69f5ba5230fcb867d18e04f3b547c09f5658bb86cfbec3e72f8991e2bcc6aa98efef3db4a018807feafff230485b49d5663",
          "sha256": "141c28a9c935f6c9df1cda97c044fc52a11002eefe7093f83705786c9c137342",
          "sha1": "de0186b422f40b72fe955ddc419bc78fc1a98573",
          "md5": "da352352761dc9cd3529174193395659"
        }
      ]
    }
  ]
}
