{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.5.12/runtime-0.5.12.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.5.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosArm64Main-0.5.12.klib",
          "url": "runtime-iosarm64-0.5.12.klib",
          "size": 576242,
          "sha512": "5e8656b453af1a09a3c62e1c0f5050233bb4a5120aa91c23ff3faac18d18f5bc00647a0cdf50bed850935a0439a5c1506e816d6f14ae1dc5216281ce074b1843",
          "sha256": "c7073a438dee0e64047c49fb2efad5124b92ad42c0bda76a619e2c1baba38bfe",
          "sha1": "837f0d27642de1b6b56169a59c2f3777bd277dfd",
          "md5": "08406f273b9264c4eff17bee824705ae"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-iosarm64-0.5.12-sources.jar",
          "url": "runtime-iosarm64-0.5.12-sources.jar",
          "size": 43264,
          "sha512": "7181e822faba84fb7bde74fd0f90c4e390939287d9b8836c221acd15bf0c80d2e2cba78ee4cf07da15d3d384ce815092ffdd670bd9eecfe5185b7fed794bdbb0",
          "sha256": "c08c746a03c2d40cb6675263b6d010f960c903a8ec5c30970089f6fd7677df48",
          "sha1": "5893eb8f9308c87025fdd293195f3d17d13f5b83",
          "md5": "a1a34e2ac7535d628e343852bee7ec09"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosarm64-0.5.12-metadata.jar",
          "url": "runtime-iosarm64-0.5.12-metadata.jar",
          "size": 2428,
          "sha512": "f2df5898a6e8be47ff0cfe93bc3e717666c4c46473b4225eb457ad053986a5e1f85d9ddce609aa89585a796ca0b34ecedf1aacb7425dbff477d879cf547486d5",
          "sha256": "8ea962f3d7c6b8f441adae0e65acfc98dee80d9e6f32634f74837a7e76d6ba8c",
          "sha1": "d6db9ff56371443eadd74bb114ca6ce30c276e54",
          "md5": "1ebe629def57fbc80ea00bb2e8ce06fb"
        }
      ]
    }
  ]
}
