{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.17-rc.109/composeblocks-0.5.17-rc.109.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.17-rc.109",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17-rc.109"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.17-rc.109"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.5.17-rc.109.klib",
          "url": "composeblocks-iosx64-0.5.17-rc.109.klib",
          "size": 344589,
          "sha512": "154399ddc3b7d39f67e66fb1ef0793e4d0e650fc2858c027079b1dd87942904d4d6eb17754f64a6f1d86a3d1d3a3c0d4553fd71bb4e5888942030fbc7266cd50",
          "sha256": "c7f6677a08b59b2a2bf6e0c77c40d9f2aebf2c8b294b8908266a7fae8c859e91",
          "sha1": "94b6396201dde3f45cb96aa76c8e7f8d499157a6",
          "md5": "57bde26c079dd02ca5527477ce5dff72"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosx64-0.5.17-rc.109-sources.jar",
          "url": "composeblocks-iosx64-0.5.17-rc.109-sources.jar",
          "size": 61722,
          "sha512": "a82fdd47d7da96a81aaed8005a4b941247647218ea9a2627d23b72f664c7a8e238c3487104200057043a82cf69d3ae685cab9f7bf60d01d21e624abefb12764b",
          "sha256": "c08a32ed59f8283e6f8eaf4a51e9dffb804eb86bd14f8c78ff5a9721c2e36866",
          "sha1": "d691f285cd7214d60faf1d3a6646ae63791df966",
          "md5": "05c64f60a31443a21663cabadb1d5ea5"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17-rc.109"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.17-rc.109"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.17-rc.109.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.5.17-rc.109-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "1bdc2e5b3fbc749318c3ee029dbf45bd98a9b509a29bde0bc50e264a2b85a7c321b20fe3098779b32874ec0d60614534adf37264391cb929c874fe5d7cab505e",
          "sha256": "b48cd50410db0dc248ca17026d6d74b375fa138773b0d0cf91f35aa653d7a77f",
          "sha1": "fadaf9be5245e3246b99da37b5f729338f2d3ad0",
          "md5": "b47fb8ef82c8277d75d13e569357b36b"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17-rc.109"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.17-rc.109"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.5.17-rc.109-metadata.jar",
          "url": "composeblocks-iosx64-0.5.17-rc.109-metadata.jar",
          "size": 261,
          "sha512": "c6732ffae4d146fe0141febd0bb207bb6ac699ccc41a21698eaa9946bc4c8d8b38b9747525f3cef8f79e3e5ff945929541467b372403c53e85cbb4ea36818a05",
          "sha256": "8c6debb3b6b6ba7cfde591e567f824f84ecaeec8671b3d8c047d75080dfe987d",
          "sha1": "87b861bef2dc1231788f62fbdcdea0eeaf5bcc62",
          "md5": "1610742d5bdba0c72e008b9b11978079"
        }
      ]
    }
  ]
}
