{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.20.3-rc.160/composeblocks-0.5.20.3-rc.160.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.20.3-rc.160",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-jvm-0.5.20.3-rc.160.jar",
          "url": "composeblocks-jvm-0.5.20.3-rc.160.jar",
          "size": 349788,
          "sha512": "d5a699503221711d77d5042bd38cb3c23e75f7a327fda2af98d1b7690ade3eb356eaf93b2842ac93d2b957da46eb072890360f05aad2f2e45fb9526416c26d37",
          "sha256": "7aaececa8074ee77ff517f188cb5628e58b97db15fc0b7c923c8126749efae2c",
          "sha1": "2950974f8bd8e1e21837d8b3dc499c410e6dbab5",
          "md5": "441539041d4c8713852086a0626a8424"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20.3-rc.160"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20.3-rc.160"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-jvm-0.5.20.3-rc.160.jar",
          "url": "composeblocks-jvm-0.5.20.3-rc.160.jar",
          "size": 349788,
          "sha512": "d5a699503221711d77d5042bd38cb3c23e75f7a327fda2af98d1b7690ade3eb356eaf93b2842ac93d2b957da46eb072890360f05aad2f2e45fb9526416c26d37",
          "sha256": "7aaececa8074ee77ff517f188cb5628e58b97db15fc0b7c923c8126749efae2c",
          "sha1": "2950974f8bd8e1e21837d8b3dc499c410e6dbab5",
          "md5": "441539041d4c8713852086a0626a8424"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "composeblocks-jvm-0.5.20.3-rc.160-sources.jar",
          "url": "composeblocks-jvm-0.5.20.3-rc.160-sources.jar",
          "size": 62929,
          "sha512": "a1b6fc6d924260f33998241e03ec24748d5c5dfd0113774ba6737d13cf12976f05d7730d8a31102924f3f379dc14469fbbbc54a33812c1b3466749ccc47684d1",
          "sha256": "c060c74601af62602de4fce2f88037ef006540f40ab0fc07a70a191070214b78",
          "sha1": "16aca03e0bca1374655d6244d13d0ebffcd27f34",
          "md5": "18983dc3d325a95705ebeb14c1ac28aa"
        }
      ]
    }
  ]
}
