{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.3/flow-wrapper-kmp-0.5.3.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosArm64Main-0.5.3.klib",
          "url": "flow-wrapper-kmp-iosarm64-0.5.3.klib",
          "size": 78821,
          "sha512": "3814a3b095be4fede7e462e13898a79f5384040c330fa9d6976827c729f9c4ecb6effd0871dc51093015e140674e231e1f12e3472d18b68a8943985669cbc718",
          "sha256": "aac8c190ade968bd8a886a6b2885eee9eb50bfda1d1a6b200697bc65b576c0f5",
          "sha1": "8f7cec98c58115fbfc521cebc837837405b44a1f",
          "md5": "0ccfc8ff9f34d1ff20229f77649725c9"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosarm64-0.5.3-sources.jar",
          "url": "flow-wrapper-kmp-iosarm64-0.5.3-sources.jar",
          "size": 13360,
          "sha512": "1674d8adea7b591c5f64cff8371b3859f5259cf50845fd9b073f8a6e3060e88be3f7fa0e0b4970afc0c764d40449f644ce54995541c4c95e5a79ba9ecf04ce5e",
          "sha256": "b4d41ffcaa9d4832c31b3192e27e5aa0943494fbfb1ca5e2ddbbaea5942c2230",
          "sha1": "b7635d1d6b47a36b957306a82510957891933232",
          "md5": "49767b8d93f46a7c1d7723e49d9e8825"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.3.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosarm64-0.5.3-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "351a2e8cdf4d603a0f0783ab8291ce56a253740d1d3aba808cc3a58a6df5c003f2fba7a0748beec3ee8d191999f06b0a1c595dbd4f75ef8f0fe3c01db03cf3d5",
          "sha256": "fb9dca50a85df1e0e946d92e5ebfcb1e4866e759bccb7234caba0686a95a8997",
          "sha1": "ecb8598eded5b3cdff8067bd433d7244b8083374",
          "md5": "f05eeeaa3b6b8945c2c86f060100f61f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosarm64-0.5.3-metadata.jar",
          "url": "flow-wrapper-kmp-iosarm64-0.5.3-metadata.jar",
          "size": 3010,
          "sha512": "554ae7447c1d4298bf1d870011a4f5b05c456f79b12a24ba9f6d159a377f1c91794b8d86d3cd1c16e0ff51edff85132351fa6406c04540c06364c2efba2ef3f7",
          "sha256": "e0c5e56e73407d38f47d8bdbf72d8eb49d1f20e2384cf248a7820758285e4498",
          "sha1": "ece4aa7bdfb2ed1df8832285a612ef01ebcb3a93",
          "md5": "2c57115b09f378bf96dddb7c392bc661"
        }
      ]
    }
  ]
}
