{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.5.16-rc.94/runtime-0.5.16-rc.94.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.5.16-rc.94",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16-rc.94"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosSimulatorArm64Main-0.5.16-rc.94.klib",
          "url": "runtime-iossimulatorarm64-0.5.16-rc.94.klib",
          "size": 640409,
          "sha512": "67c66f7f82857bc1a4413cf54367635cd26e96dafc55efed67a63377a2d68c49850b14d3bd3ea5c96e38f64958b97923de70817bc0aeb9c4e50f22fe190a7819",
          "sha256": "56c7a160150da47b635d01359a19cd72d765389f750b977b34bfc922780be194",
          "sha1": "f7001dd413a45aa2751b2eebe9b4658b05f72b98",
          "md5": "805731fecce70432c6705a683febfd75"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.5.16-rc.94-sources.jar",
          "url": "runtime-iossimulatorarm64-0.5.16-rc.94-sources.jar",
          "size": 50432,
          "sha512": "963e702e635d69f3f30b2eec29532cd072ae1656c985a3b66942b99934b0bfebbaf51c9615d942146b537ab3398746881a7e14285a73773e84fa09b9e6ee85d5",
          "sha256": "abf8aff6002dc43e767fdd5a9359a51dcd7cf45cb634b5c32a3bff8695d9f7a7",
          "sha1": "6beffa84d84efad812de920582dac6e1657ee6ac",
          "md5": "a8a2686a4d636d22ae565704e2824741"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16-rc.94"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.5.16-rc.94-metadata.jar",
          "url": "runtime-iossimulatorarm64-0.5.16-rc.94-metadata.jar",
          "size": 2428,
          "sha512": "97091610531ef75368d6d0247984c4684fa58e7051dfd7a3f1ba131828c443d3fe6ca0939def2a5397bc142f6e35cf878af1307ad8b9541b7a9390cadbc9299f",
          "sha256": "1f15fe52288521da4cb390918bdf3641c5a6769e3ffffb9488fa90a4c0c696bb",
          "sha1": "27afdfdc00f1b7c9dd3e81005304bb564034b323",
          "md5": "5bd3029ac5967c249d92cd3dc6216785"
        }
      ]
    }
  ]
}
