{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.6.0-SNAPSHOT.12/core-0.6.0-SNAPSHOT.12.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.6.0-SNAPSHOT.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosX64Main-0.6.0-SNAPSHOT.12.klib",
          "url": "core-iosx64-0.6.0-SNAPSHOT.12.klib",
          "size": 92573,
          "sha512": "552bb80ed0037d97882b32bfe6f92b638881834313d6073cb178cb7054b31e7e429706e9bc824d2bd8120d3de6036018947762391af1b9776bd01763efb3d0b5",
          "sha256": "d1cba00f8fbaa8c1f5fd5dbca7631c29ceaae974a682b4675489691c6a23358a",
          "sha1": "7e4393eef1a3231c55c8f46f264c82b5567a36b9",
          "md5": "9a96c7c8c68f9ab147922b71fdbbb632"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iosx64-0.6.0-SNAPSHOT.12-sources.jar",
          "url": "core-iosx64-0.6.0-SNAPSHOT.12-sources.jar",
          "size": 11577,
          "sha512": "9fb033cd2b42a176992197e20e2309dca4129da19a7d04197c877f14559bb8f1e0534e536672b6e6125fd5b704e75c9f87dfe7c2b432a3412614d1afb8e61edc",
          "sha256": "4145609f6c1de9f6a3b58c3c87e47936cc12bce1f587bf216f9896f8cc547b89",
          "sha1": "c4393dccb01819dff29b6e8fac8ffcd616103ac8",
          "md5": "ab48b1eec5b4f4f838421003a0575982"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.6.0-SNAPSHOT.12-metadata.jar",
          "url": "core-iosx64-0.6.0-SNAPSHOT.12-metadata.jar",
          "size": 261,
          "sha512": "86ff31b7c81771b0e5dff485b281b017220c08b7b3de95110285dd484111e4d1c526965587ff6c30167c734b64a16e02e79ec113af8a9b77df5e9ff7275d0241",
          "sha256": "fb8a04bd36490d3a1889afafa1e50152025b38838cc683fc7e28cc562b3f60cf",
          "sha1": "a3ae0e68983b4d3c1f17d7f51e20786507e279c9",
          "md5": "dbdda9836302230ca6e4d9fe43d6b708"
        }
      ]
    }
  ]
}
