{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.20-SNAPSHOT/composeblocks-0.5.20-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-jvm-0.5.20-SNAPSHOT.jar",
          "url": "composeblocks-jvm-0.5.20-SNAPSHOT.jar",
          "size": 347970,
          "sha512": "805f5ab1597dcd9e3b1ace372390cfaa8a47f5e5bd878dccdca21b89c83c9066fe363c6fbbb3aa3447cbe65e22a178c2b3e7914e4466db5c28769c4b43e288d4",
          "sha256": "aeb26e6681a390b4096395a9024a7baae384aca2b5e8681406d7fe1e878a023b",
          "sha1": "0e04f64c090c934c0b767f161e259b7683c259a3",
          "md5": "333177337dc553fe8fa0649c38ae1935"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-jvm-0.5.20-SNAPSHOT.jar",
          "url": "composeblocks-jvm-0.5.20-SNAPSHOT.jar",
          "size": 347970,
          "sha512": "805f5ab1597dcd9e3b1ace372390cfaa8a47f5e5bd878dccdca21b89c83c9066fe363c6fbbb3aa3447cbe65e22a178c2b3e7914e4466db5c28769c4b43e288d4",
          "sha256": "aeb26e6681a390b4096395a9024a7baae384aca2b5e8681406d7fe1e878a023b",
          "sha1": "0e04f64c090c934c0b767f161e259b7683c259a3",
          "md5": "333177337dc553fe8fa0649c38ae1935"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "composeblocks-jvm-0.5.20-SNAPSHOT-sources.jar",
          "url": "composeblocks-jvm-0.5.20-SNAPSHOT-sources.jar",
          "size": 62439,
          "sha512": "d298077bddd9dd1a8a5e1872887446c920abb210d1dfdeed88e9d970fc0ffb1e3621620a71bec1c9125f09f9bda5cd9b2e16857511ee4a9746979231889089b3",
          "sha256": "fc541b5ec39cc4f025d6450782fa4ce92a66871b0ea12e2143e7d3907c97f61a",
          "sha1": "6bd12f366865d460c6c3a6906d1cf84d301959cf",
          "md5": "50b8a091984e6b08e0ed8c5465ada2e2"
        }
      ]
    }
  ]
}
