{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.19/composeblocks-0.5.19.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosSimulatorArm64Main-0.5.19.klib",
          "url": "composeblocks-iossimulatorarm64-0.5.19.klib",
          "size": 346702,
          "sha512": "aecadd25a6f04c0372c0ef5da3bce3f3e1946ec4ddd8ef3102286132bd6608de73274abfaa33239315539da79a4a2b280d55aad6315bd397261906e8855ab338",
          "sha256": "fc7f8d486db3ff014208f505831d7516dd29c9b0fa3a229be55b0cba51f7ea31",
          "sha1": "3165d4f09a555dfe573ab972e28efdc0814590c1",
          "md5": "61666d6a5f6444c786fd246b491a1ab4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.19-sources.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.19-sources.jar",
          "size": 62439,
          "sha512": "d298077bddd9dd1a8a5e1872887446c920abb210d1dfdeed88e9d970fc0ffb1e3621620a71bec1c9125f09f9bda5cd9b2e16857511ee4a9746979231889089b3",
          "sha256": "fc541b5ec39cc4f025d6450782fa4ce92a66871b0ea12e2143e7d3907c97f61a",
          "sha1": "6bd12f366865d460c6c3a6906d1cf84d301959cf",
          "md5": "50b8a091984e6b08e0ed8c5465ada2e2"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.19.kotlin_resources.zip",
          "url": "composeblocks-iossimulatorarm64-0.5.19-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "f7570c401458fc6df826a443ccaee1297c259fb55bc1f93f30cec8e2ab67606fd455861bdcb4d39989733f70c1d5c3c6b571cef7bdec444fd760dd6cac88a331",
          "sha256": "3adff217d78d21506dcd388cc823847fac4c3e384e6223f8ab8cd81fe437f62d",
          "sha1": "1806a654413c37ff0ba5258b35a7b0b5fa3debc7",
          "md5": "2f6aba6ed04b2faee6b8db4881804a79"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.19-metadata.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.19-metadata.jar",
          "size": 261,
          "sha512": "90326ea7d344a6e19066700ee04144f09967a98e5924b9c3be8e5b4ad10857910e5d0e9bfc6e778ab33b61b3c9d1f9a7fa3a8244d0cfa12bab1697affa3d926c",
          "sha256": "e0f26680d918a1259491deab79389fee97ac9b0fa03f8d75eb5a585c92885ace",
          "sha1": "f5276f48a57ea78d7819620516cf05a9e3c5ccf4",
          "md5": "728d8dfdef5b3071902ae05f56a3b309"
        }
      ]
    }
  ]
}
