{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "viewblocks",
    "version": "0.7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewblocks-0.7.0.1.aar",
          "url": "viewblocks-0.7.0.1.aar",
          "size": 98865,
          "sha512": "ff17f64eecbd6008e00cb02933caccbd2972624a2846e18ce366fda1577e25675f80bb3dc60806d6f4613316639b4f8dbde6ad50e5650c0c202fe5ce95e48d76",
          "sha256": "a80ffc667db7a0f1379c9c9df7b30fa4d1fe24dc140f0016e10791b8e5d862fb",
          "sha1": "32e4f89cddbf00667882a530d40b8fc5955caa86",
          "md5": "eff5ee6e42e3a693ddc7d09168a40cb4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.0.1",
            "requires": "0.7.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewblocks-0.7.0.1.aar",
          "url": "viewblocks-0.7.0.1.aar",
          "size": 98865,
          "sha512": "ff17f64eecbd6008e00cb02933caccbd2972624a2846e18ce366fda1577e25675f80bb3dc60806d6f4613316639b4f8dbde6ad50e5650c0c202fe5ce95e48d76",
          "sha256": "a80ffc667db7a0f1379c9c9df7b30fa4d1fe24dc140f0016e10791b8e5d862fb",
          "sha1": "32e4f89cddbf00667882a530d40b8fc5955caa86",
          "md5": "eff5ee6e42e3a693ddc7d09168a40cb4"
        }
      ]
    }
  ]
}
