{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.20-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-metadata-0.5.20-SNAPSHOT.3.jar",
          "url": "flow-wrapper-kmp-0.5.20-SNAPSHOT.3.jar",
          "size": 29603,
          "sha512": "0a12ac3857cf833db724f8d4a98c37a7b7718f1f43a701a1403b84549fcb9367b5bf70ed1fcff5568039a31b616a5f9db7460ba35052b953684edf6b17548175",
          "sha256": "88c4a9120c2d7d2037c367f9220ae1424776d9a09533cac05c4dcf4bcc21d51d",
          "sha1": "197a5de6fb40ed71034b757d29df1c5bd8c667b4",
          "md5": "874f3873ed797222625fea99575c1422"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-kotlin-0.5.20-SNAPSHOT.3-sources.jar",
          "url": "flow-wrapper-kmp-0.5.20-SNAPSHOT.3-sources.jar",
          "size": 41082,
          "sha512": "d084dc36bb298b8c88da8d1133effb14b8702fd721be3c4effd2d49e43c559e77c85477666eb2a0e6fbb2c0f1512fdd233626ceb2799fe48a11ffb8cf508b884",
          "sha256": "c5eb3decee40eb28a97a9b65dc6f986c45175a933de0040d83f2fc97d6ca93d1",
          "sha1": "0fda4fb0965aa26c3762777cf2c684799e20bbaf",
          "md5": "ab0e66090fc2bdfb36a3603c66cb34bf"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-android/0.5.20-SNAPSHOT.3/flow-wrapper-kmp-android-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-android",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-android/0.5.20-SNAPSHOT.3/flow-wrapper-kmp-android-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-android",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-android/0.5.20-SNAPSHOT.3/flow-wrapper-kmp-android-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-android",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.20-SNAPSHOT.3/flow-wrapper-kmp-iosarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.20-SNAPSHOT.3/flow-wrapper-kmp-iosarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.20-SNAPSHOT.3/flow-wrapper-kmp-iosarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.20-SNAPSHOT.3/flow-wrapper-kmp-iosarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.20-SNAPSHOT.3/flow-wrapper-kmp-iossimulatorarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.20-SNAPSHOT.3/flow-wrapper-kmp-iossimulatorarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.20-SNAPSHOT.3/flow-wrapper-kmp-iossimulatorarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.20-SNAPSHOT.3/flow-wrapper-kmp-iossimulatorarm64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.20-SNAPSHOT.3/flow-wrapper-kmp-iosx64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.20-SNAPSHOT.3/flow-wrapper-kmp-iosx64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.20-SNAPSHOT.3/flow-wrapper-kmp-iosx64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.20-SNAPSHOT.3/flow-wrapper-kmp-iosx64-0.5.20-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.20-SNAPSHOT.3"
      }
    }
  ]
}
