{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.7.1-rc.240/runtime-0.7.1-rc.240.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.7.1-rc.240",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosArm64Main-0.7.1-rc.240.klib",
          "url": "runtime-iosarm64-0.7.1-rc.240.klib",
          "size": 858666,
          "sha512": "871073aaf9b4e8bfa614b15fa98b739bbf685a4cd00699b72aa8a9cf6cf307d209e7d115ae65950b8d4617dfa02487ce7c2e22362c33c5d9c7af3e75c3b294dc",
          "sha256": "489d02906a303c587a0bbaa78dae50b059a93c4a394c53ff184f39d592fa9450",
          "sha1": "74683701e0afd7393cc36fdd654641c85361f90c",
          "md5": "fd1891acccb143a845b894d3f7cc47d5"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosarm64-0.7.1-rc.240-metadata.jar",
          "url": "runtime-iosarm64-0.7.1-rc.240-metadata.jar",
          "size": 2428,
          "sha512": "41459a474fccec6ef9e58fd8716f34f849c68d2ad2885564ee78e3f09620c4e9d1429ef8eac17d7b2f77d77dac275dc2c522d538f3c5f9f138a26cd5d28364df",
          "sha256": "1fedccca2020d759bb8f4af3a4171a1f695287cf885e8b980d3a7b66fc615652",
          "sha1": "e245fe5a2007c14ddad3ff7cd940c45f09ec18f9",
          "md5": "c3149d0ae341f80cbb636c235216f0e0"
        }
      ]
    }
  ]
}
