{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.5.19-SNAPSHOT/core-0.5.19-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.5.19-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosSimulatorArm64Main-0.5.19-SNAPSHOT.klib",
          "url": "core-iossimulatorarm64-0.5.19-SNAPSHOT.klib",
          "size": 127682,
          "sha512": "a98a7128048ee203ddba83cd9bbac4ac342076389248a3b1d01224ea1d30e081c3bda9c96117a239f917106b614ed7a4e9a4bedb0fa096a972daba0517b7d35b",
          "sha256": "e0ddb583ce19ae7024a698f64d4ef3634e73c0ec89315071b6808ba068efa531",
          "sha1": "93ce093dec896ddaeb92bb93ec90b491ef3cc98b",
          "md5": "542a91c00bc4f5305aa30ca044df8736"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iossimulatorarm64-0.5.19-SNAPSHOT-sources.jar",
          "url": "core-iossimulatorarm64-0.5.19-SNAPSHOT-sources.jar",
          "size": 19241,
          "sha512": "9a5393b3bb0307aa6931eb24e76bb3cbd6385fb2e1dba4c14e1a6d1864435fb6fd9ffef6aaf0d386dfc1a3d497e459f26c09cdac9f556b235a16802af7ac8b75",
          "sha256": "1c7a9aa3464ab76183efb0ae36a0ca75a3cdd21378c8e962848aca7556096d4e",
          "sha1": "43eed877c7528a7ce139b1643e585998031a97b3",
          "md5": "f3b49f1808e86065dcb78b9e223f0537"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.5.19-SNAPSHOT-metadata.jar",
          "url": "core-iossimulatorarm64-0.5.19-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "15f6048cdc968c7441215b5285395f51806285bab7d1cc90c981a43341071682bb3d2e3867b7ac81691950f89f7b12c98db65d00dc5aec1aa3dd3be177e53e02",
          "sha256": "dd156807e698fafb738047b6d48399c03a575f75c4b30f0c146f3db1d49a4a6d",
          "sha1": "55c88b31517cba3acea4ebd26238a03412bfb5fe",
          "md5": "600fb78dee38cf7b82a56e231d0c744a"
        }
      ]
    }
  ]
}
