{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.14/flow-wrapper-kmp-0.5.14.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.14.aar",
          "size": 110110,
          "sha512": "8769578897adc4174672a37e167c6d938cb2d75f4cdb1f6dfc4ef8848d63e238993ef0120ad042ea29a84b409e5ccbe8f16bea100c0e9ba8319898c20450f67e",
          "sha256": "b6d5b74174f5749e02da323b6a5bbc64adefc3e9d085cf3a9ee3342de21634c5",
          "sha1": "d297d2d98d6f312535930bb69f0bc9cc30b2618b",
          "md5": "0a7132c0eb628c25fdf669ba25a2f7b5"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.14"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.14.aar",
          "size": 110110,
          "sha512": "8769578897adc4174672a37e167c6d938cb2d75f4cdb1f6dfc4ef8848d63e238993ef0120ad042ea29a84b409e5ccbe8f16bea100c0e9ba8319898c20450f67e",
          "sha256": "b6d5b74174f5749e02da323b6a5bbc64adefc3e9d085cf3a9ee3342de21634c5",
          "sha1": "d297d2d98d6f312535930bb69f0bc9cc30b2618b",
          "md5": "0a7132c0eb628c25fdf669ba25a2f7b5"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-android-0.5.14-sources.jar",
          "url": "flow-wrapper-kmp-android-0.5.14-sources.jar",
          "size": 25624,
          "sha512": "f0877e7cad6e09d554a10cac19d359861f71463f652cf2b788a1c65c23280872eff67a2cc52137e5ec7ec77f39fcdb1db8e3140a2c8ea6b496bb885b90dce771",
          "sha256": "11142fa60c28d30908e2cd57046038fae2d399899aa546691d5be5ac62490218",
          "sha1": "cb6665e199725f67d239e5921a0f01fdfd57fc79",
          "md5": "76b89a236b75792a35aa6aa6b519b752"
        }
      ]
    }
  ]
}
