{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.6.0-SNAPSHOT.14/core-0.6.0-SNAPSHOT.14.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.6.0-SNAPSHOT.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosX64Main-0.6.0-SNAPSHOT.14.klib",
          "url": "core-iosx64-0.6.0-SNAPSHOT.14.klib",
          "size": 101557,
          "sha512": "dd30cc5428330ca805dabccb224465779c22a913d7a7c83e2ab54f139762b39afd6462a926f604101567100120b9f3cb90ed2ed572e0274a8899c9f3207ffd3a",
          "sha256": "7f3d9cde978d7e1bc0affbe24ff8ca1b03eccf4ef5002cff687eb5a5bd649d98",
          "sha1": "dd862715eaf51db488cc5ca889a80ac3377c46ec",
          "md5": "913b0ac160a5f627f17d69ffb35c3a44"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iosx64-0.6.0-SNAPSHOT.14-sources.jar",
          "url": "core-iosx64-0.6.0-SNAPSHOT.14-sources.jar",
          "size": 12871,
          "sha512": "9384b55817f88f910ec57688f568f23c7334e431ee50978b193d247dc6dc8604297381b30757d73c8c22a3ea4f3da34334acfaf4bfa1121de726f0027e0f3235",
          "sha256": "cbafd42c100bb7358370dc203cd61d4041cd683b48d69db2eda1e6514b18e617",
          "sha1": "20061d10ddcd97c4bb4a9c49602da7d79000e539",
          "md5": "337280c1de2570f705980fc4fe7f6037"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.6.0-SNAPSHOT.14-metadata.jar",
          "url": "core-iosx64-0.6.0-SNAPSHOT.14-metadata.jar",
          "size": 261,
          "sha512": "7035c76c70fe8056586554ff824f6b227935b75043c6430f068da50e726e78d0ff51ff9e6dad06dd2c5cf481b67d437710a4fdc8ef7a7a6fc58be54cc87a1a5c",
          "sha256": "f9e636e1bd42256dd21ccb748ec51738531b8be9b6aa244f19570533e9e3ec16",
          "sha1": "bb31c328f4d3147a141427e6e2da7725363d846e",
          "md5": "e89caf446d1ffdebcb87e37707ce12f7"
        }
      ]
    }
  ]
}
