{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.20.3-rc.160/composeblocks-0.5.20.3-rc.160.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.20.3-rc.160",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20.3-rc.160"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20.3-rc.160"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosArm64Main-0.5.20.3-rc.160.klib",
          "url": "composeblocks-iosarm64-0.5.20.3-rc.160.klib",
          "size": 347008,
          "sha512": "521d2016e352fd5d4300256af33294babdc35bb78a110ca0bea4af22d16d35e1f818f2cc8201d56184c5c4239032a11547eba3485b4572257ce1906c9b12069f",
          "sha256": "e38d8d8b69c2fe312aebd4fba62b2bda11fc6cb94b7d03779ca36402be65f7bd",
          "sha1": "7d4c78b49f3d8d12217f420546ab2b1600f2c455",
          "md5": "f76e22f535f586e9454fdaba50f4b356"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.20.3-rc.160-sources.jar",
          "url": "composeblocks-iosarm64-0.5.20.3-rc.160-sources.jar",
          "size": 62929,
          "sha512": "a1b6fc6d924260f33998241e03ec24748d5c5dfd0113774ba6737d13cf12976f05d7730d8a31102924f3f379dc14469fbbbc54a33812c1b3466749ccc47684d1",
          "sha256": "c060c74601af62602de4fce2f88037ef006540f40ab0fc07a70a191070214b78",
          "sha1": "16aca03e0bca1374655d6244d13d0ebffcd27f34",
          "md5": "18983dc3d325a95705ebeb14c1ac28aa"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20.3-rc.160"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20.3-rc.160"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.20.3-rc.160.kotlin_resources.zip",
          "url": "composeblocks-iosarm64-0.5.20.3-rc.160-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "22ca3314389624fb84cdba104d2b10fcc370fee63bd2c202cb3b3da086249f0fa2b4432def3a0e59c6a497f2002a8849e5808aac50d30e4bf3060d6ea12b86fa",
          "sha256": "033e2e14511a4161e2d52ffe852a7a0d7c5ea2ce47d04ded72e6ef4d321f210b",
          "sha1": "0d80607957a1cb5f22dcf2c392873b1d44cbe517",
          "md5": "2ded0b81442e4f5d20a197858364ed72"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20.3-rc.160"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20.3-rc.160"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.20.3-rc.160-metadata.jar",
          "url": "composeblocks-iosarm64-0.5.20.3-rc.160-metadata.jar",
          "size": 261,
          "sha512": "8e6e1b30cb4d810aa9a3185e56b2152e95b59094c89de4448973f6af9b04c87bf711600efa8c07e60535a44530cc6056e14184bb208d99629060223e63e12d70",
          "sha256": "74ce3de0cd918012aa196cfce3d397bddc6eaf22c9420959c4aa45f51bcfa575",
          "sha1": "e031591f93b1257ec100ab4fa78d426b459331c1",
          "md5": "d254744d3399515abc7e21541da526b6"
        }
      ]
    }
  ]
}
