{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20.3"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.20.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-metadata-0.5.20.3.jar",
          "url": "flow-wrapper-kmp-0.5.20.3.jar",
          "size": 30021,
          "sha512": "6c7f2669121a0ca4725c515226f20d01861ed01a08867b8ca76d1be0fb9d7041edf84e9a429ff1a12ee1b42b7082b46fe49e622cd69da0e2c98988180a1c7be5",
          "sha256": "6bd5b603cd2e77679c6ceebb7de7e5f4887f3433e9783bdcba4cb02b577ad27f",
          "sha1": "07cf74b0f7057fd0739d96c283fee18b8738cef5",
          "md5": "359e3ac4f046110a1fbfebec417bbcd0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-kotlin-0.5.20.3-sources.jar",
          "url": "flow-wrapper-kmp-0.5.20.3-sources.jar",
          "size": 44417,
          "sha512": "cebc02d290d539fac206a7f7ffdf7cad82955ea2037defbb4f14f31598dc1ba481b83d7da33f03b62aa0a9eca0979f4d07f584b5de90633009e2595f590e0f59",
          "sha256": "051217b3a526ce469d7ae6c1002668870a27f4cd80a4d8d9cfa76b1e4a0a3696",
          "sha1": "9d321d5b562b12ccc04a3c6ef11942719b1611c1",
          "md5": "593332a3d07f5d12aa36cc082d959eb7"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-android/0.5.20.3/flow-wrapper-kmp-android-0.5.20.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-android",
        "version": "0.5.20.3"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-android/0.5.20.3/flow-wrapper-kmp-android-0.5.20.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-android",
        "version": "0.5.20.3"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-android/0.5.20.3/flow-wrapper-kmp-android-0.5.20.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-android",
        "version": "0.5.20.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.20.3/flow-wrapper-kmp-iosarm64-0.5.20.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.20.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.20.3/flow-wrapper-kmp-iosarm64-0.5.20.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.20.3"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.20.3/flow-wrapper-kmp-iosarm64-0.5.20.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.20.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.20.3/flow-wrapper-kmp-iosarm64-0.5.20.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.20.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.20.3/flow-wrapper-kmp-iossimulatorarm64-0.5.20.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.20.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.20.3/flow-wrapper-kmp-iossimulatorarm64-0.5.20.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.20.3"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.20.3/flow-wrapper-kmp-iossimulatorarm64-0.5.20.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.20.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.20.3/flow-wrapper-kmp-iossimulatorarm64-0.5.20.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.20.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.20.3/flow-wrapper-kmp-iosx64-0.5.20.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.20.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.20.3/flow-wrapper-kmp-iosx64-0.5.20.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.20.3"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.20.3/flow-wrapper-kmp-iosx64-0.5.20.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.20.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.20.3/flow-wrapper-kmp-iosx64-0.5.20.3.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.20.3"
      }
    }
  ]
}
