{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.17-SNAPSHOT/composeblocks-0.5.17-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.17-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-jvm-0.5.17-SNAPSHOT.jar",
          "url": "composeblocks-jvm-0.5.17-SNAPSHOT.jar",
          "size": 346003,
          "sha512": "a3b50b98594fdff51718b11f7cf36189b0f3bffaaf2c567d7ca21396e1c872df9bb3cfff9806537691448e43808e9fa4dab581a7d47b4a5b82c73736ce2b28ee",
          "sha256": "4795b0f60f1d800234f3b9a37b583afe62c70700752be377697ac82370562146",
          "sha1": "3adb4c10378404af0a1348b16714f8fe433bfcd5",
          "md5": "207d6437bf9eccccacc8a72842c77ab1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17-SNAPSHOT"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.17-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-jvm-0.5.17-SNAPSHOT.jar",
          "url": "composeblocks-jvm-0.5.17-SNAPSHOT.jar",
          "size": 346003,
          "sha512": "a3b50b98594fdff51718b11f7cf36189b0f3bffaaf2c567d7ca21396e1c872df9bb3cfff9806537691448e43808e9fa4dab581a7d47b4a5b82c73736ce2b28ee",
          "sha256": "4795b0f60f1d800234f3b9a37b583afe62c70700752be377697ac82370562146",
          "sha1": "3adb4c10378404af0a1348b16714f8fe433bfcd5",
          "md5": "207d6437bf9eccccacc8a72842c77ab1"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "composeblocks-jvm-0.5.17-SNAPSHOT-sources.jar",
          "url": "composeblocks-jvm-0.5.17-SNAPSHOT-sources.jar",
          "size": 60646,
          "sha512": "72b321fce90019e028ba8e489e7bbe0e4863e35ac4b443749bdd4821e8bc2429294f29b8ae79c0e52ca87f5a8b36bc2093ef61815f4c51b76e935d10c5deb0e7",
          "sha256": "766c3bd150fce2a922f56071959613846680561526d6cf900be495e726708482",
          "sha1": "8db9966a7c740c7b8752b16761d5e3a48bf33a93",
          "md5": "0ee548675101f621f6b753e4b9feb248"
        }
      ]
    }
  ]
}
