{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.5.14/core-0.5.14.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.5.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosSimulatorArm64Main-0.5.14.klib",
          "url": "core-iossimulatorarm64-0.5.14.klib",
          "size": 101634,
          "sha512": "9c400a1c7128bc02011d5d29d2e0bc097bc71c03989bbaca5a7af2d860d27c2e3e15b0d65c4094b27b67ad5f18121428e7ba1ffd56a4e02673b2baa105274ec9",
          "sha256": "023be5334a14dfd2da73a221dcb514a699a878e3d87e04c085f72fb500de0972",
          "sha1": "190100a606c72e9c95671160849e0af9f5f28772",
          "md5": "de39d466ebd26b6349e2784ba26980cc"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iossimulatorarm64-0.5.14-sources.jar",
          "url": "core-iossimulatorarm64-0.5.14-sources.jar",
          "size": 12871,
          "sha512": "9384b55817f88f910ec57688f568f23c7334e431ee50978b193d247dc6dc8604297381b30757d73c8c22a3ea4f3da34334acfaf4bfa1121de726f0027e0f3235",
          "sha256": "cbafd42c100bb7358370dc203cd61d4041cd683b48d69db2eda1e6514b18e617",
          "sha1": "20061d10ddcd97c4bb4a9c49602da7d79000e539",
          "md5": "337280c1de2570f705980fc4fe7f6037"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iossimulatorarm64-0.5.14-metadata.jar",
          "url": "core-iossimulatorarm64-0.5.14-metadata.jar",
          "size": 261,
          "sha512": "11b2491415ab8e080012f29fe7fd205c7748141ffddf104e73629689c894cd70bef80f144ff8411ce7c760bc0453b6bbe90e987ac92cdd5926e2dfc472e7c5e6",
          "sha256": "a17297f7a061606ec5ddd81c066aec70d57ec615e44e6d8f09346bfa1a7d2f39",
          "sha1": "958a56bb47a5ef8430a643b0da7e39169f7f7631",
          "md5": "6fe08674cf9bad77c930b861b494ddf9"
        }
      ]
    }
  ]
}
