{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.5.17/core-0.5.17.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.5.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosX64Main-0.5.17.klib",
          "url": "core-iosx64-0.5.17.klib",
          "size": 127393,
          "sha512": "3518417032e29e503d02e32b269104b8734b7c9af41a45cc3b57440d617ceae1be51532b98250468572b8710c5372bba5c2e6b55009dd202fe95a55439764113",
          "sha256": "63de0224c2596bd9693bc9ded423d6355ca1e0b6faafedd377ba2deb630a13e4",
          "sha1": "d159e9824c4b76774ebcea16f837257b60f827ef",
          "md5": "4123841ce41a3aa72d4666fa11c9153d"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iosx64-0.5.17-sources.jar",
          "url": "core-iosx64-0.5.17-sources.jar",
          "size": 19168,
          "sha512": "fd197d938de534a7e41f8395587df54772e10d2f8875d12969b2dd0d7425d4ed7377caf17a1fc04775d9de6b2c02837252e82757498d401437e0eba129c67251",
          "sha256": "101df60d3d5497a6ca9b4c4aceb098b2c32c45306d0f3efd03838bd093c7c1fa",
          "sha1": "d16fc10cfadec7e60926a0fba06accd218f78c66",
          "md5": "d0fa1b1c212201641c53528a18d6d2ea"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.5.17-metadata.jar",
          "url": "core-iosx64-0.5.17-metadata.jar",
          "size": 261,
          "sha512": "f64f94deb975d09ae8a6990c9758040cad681f4eebfe4f2f5dd4e6047f931fd242e452c080ce06f140687c6ac706c7078b982b743fca477d2a5d4e936aa6b2a8",
          "sha256": "2a5568eb62770e769f7dc5c942ed549674f82ace4f3deebeae327fd5a3370062",
          "sha1": "9d7ebcf9163817cdbd8977d1de203af00c0f748a",
          "md5": "72a7400c8eb2e9b100b4a40296577b42"
        }
      ]
    }
  ]
}
