{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.20-SNAPSHOT.3/composeblocks-0.5.20-SNAPSHOT.3.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.20-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks.aar",
          "url": "composeblocks-android-0.5.20-SNAPSHOT.3.aar",
          "size": 204672,
          "sha512": "28613c646c9fa632ae1b7668661b9ea9688dcf233ee650f1374cee8555c69560f22ef607710e817cf3adde9171545c097ae36dac83b52af924fa2634ca81bd80",
          "sha256": "7665b2eb984e64df819759199895bbf1f84fb571139423cfb853352d48b6e26c",
          "sha1": "9b68bb048b10abd16c9d5052ff27541dbf1c228e",
          "md5": "736e0d227fad1b952fad7968d7306e6f"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-SNAPSHOT.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks.aar",
          "url": "composeblocks-android-0.5.20-SNAPSHOT.3.aar",
          "size": 204672,
          "sha512": "28613c646c9fa632ae1b7668661b9ea9688dcf233ee650f1374cee8555c69560f22ef607710e817cf3adde9171545c097ae36dac83b52af924fa2634ca81bd80",
          "sha256": "7665b2eb984e64df819759199895bbf1f84fb571139423cfb853352d48b6e26c",
          "sha1": "9b68bb048b10abd16c9d5052ff27541dbf1c228e",
          "md5": "736e0d227fad1b952fad7968d7306e6f"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "composeblocks-android-0.5.20-SNAPSHOT.3-sources.jar",
          "url": "composeblocks-android-0.5.20-SNAPSHOT.3-sources.jar",
          "size": 62890,
          "sha512": "4a59e27f2a29435e1ef668a3f80f54b5579a027454fa3563ccbac9ebc4c20fea52d6a9c9b1073a4eea216c777bd6f08d9104dc1622d14a962c7a0f6555a52602",
          "sha256": "38494ba44d71f81e028eb09b8af0ae27a8b8ece1e6c8a7a7e9656f507a53fe71",
          "sha1": "e6e5c5547420fa3ae406d945fd6226ba56b60f9f",
          "md5": "e71bf7ca299e303fb36f875345bdde51"
        }
      ]
    }
  ]
}
