{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.16-SNAPSHOT/flow-wrapper-kmp-0.5.16-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.16-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.16-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosX64Main-0.5.16-SNAPSHOT.klib",
          "url": "flow-wrapper-kmp-iosx64-0.5.16-SNAPSHOT.klib",
          "size": 238133,
          "sha512": "26ddb209e39de87ba944094f0be9952feb7d0f50fe37404aa0ba68c9990b8ecbf24135bd9e3b8e2b292fd50ce06543d8397eeed1713ee10a3e3a7a508c33e8ea",
          "sha256": "bebc90737f9bdeb2e23cf199eeabaa4fa0f2c574dd8a20d6f917196852834f58",
          "sha1": "51ec4878b4e2d8be3f2dbc2035171c5d88c9fbf9",
          "md5": "caedd8f26b02a129f374cf3a8375addb"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.16-SNAPSHOT-sources.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.16-SNAPSHOT-sources.jar",
          "size": 41189,
          "sha512": "6a228ff80668b5c9be66985825c544c570d2b6e21bc8424d423cd054b8ed8103a8e020f3e710ba73840c93fe7d370b0a8f9a03b148a836b1d26954ec942bddf1",
          "sha256": "dd74828f496c41afe98d011c3c293fe685a3621285d49a1695ddd00deb1ae559",
          "sha1": "c02bf91db5b7a11f89341a3c70bed243ec80056d",
          "md5": "fbb2de15145d56b96cce320a8b6db679"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.16-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.16-SNAPSHOT.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosx64-0.5.16-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "5446c341d80dbfa4642f315ba38d0dc236e29d90ae1e5d0ffad4641054405918a530d65a29e8678caa8615664ff36e33dafdb26c6ab9488ae643d678de788179",
          "sha256": "f71a21decbe75350151529abcf3f549c52dc2e5a79cd43a894672c1fd5590682",
          "sha1": "411b0d3e8e0f1e2be07ce802808ef3ed9666eb9b",
          "md5": "cdf6487b718844112e0cf337a8fe6ce1"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.16-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.16-SNAPSHOT-metadata.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.16-SNAPSHOT-metadata.jar",
          "size": 3747,
          "sha512": "cad906e946c0e1dee8058b9a90dc5bf8e14bf52b2e1b7e158c1dfe6893b3311e4f212a76fead5246fd942f97315df0aac96c17fd05ea601457c7889194f03311",
          "sha256": "0741759bd2860829b2448bbf5143a3e658186743fe4c8fdc0f3fa8372f674b9a",
          "sha1": "f598bb952eedab50aebdbcdbec6c61bb02f7283e",
          "md5": "6b637f962d8f04b8a8202939a715df3f"
        }
      ]
    }
  ]
}
