{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.16/composeblocks-0.5.16.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosArm64Main-0.5.16.klib",
          "url": "composeblocks-iosarm64-0.5.16.klib",
          "size": 331697,
          "sha512": "c7bb41ed7b8ee87cbf20e151be14f7c2cf9c9bcbe48db8ede008ea625945ec6f73ecd8d7b96d1e9ac729ae07a1e66a09a3c432b76939d57c912cf052d75aded4",
          "sha256": "a14661d99dd2f60d83db63ddf7d36448a46de0a557673784fd5b56fb4a6546ca",
          "sha1": "c313a372311504106f652ce7c7e91a21f6eedc08",
          "md5": "39063757f72a5597ba74585cb69c40c8"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.16-sources.jar",
          "url": "composeblocks-iosarm64-0.5.16-sources.jar",
          "size": 59511,
          "sha512": "9b215b4340d859f9bc19bcf8130f1ac340b58131f7c69825b2e0ac4afeb42e631a4a7f37b2b3c0a72a5b01c6366385395df28c5b7fc3e628eb8214a2e63e021f",
          "sha256": "5766c9ff09d578df821c1208f6bcf99afcfb80442ad1fb07333e14f240719a0c",
          "sha1": "de739a9fd5fe49eded6be087c00f311a5d69622f",
          "md5": "31b882d9765633f46be7c5c7d77e8031"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.16.kotlin_resources.zip",
          "url": "composeblocks-iosarm64-0.5.16-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "fe3b2ea1871a4fbe93e5d2c986cb5a5ba5279c7ad9c8b1b2152641bfc66e3e012637346151c8085d93c275e2bf823ffdecbf2dbaf452b5e8e55bbd55e0ffa989",
          "sha256": "06629c8724eaf3b9e9fe19c8b6fda27f87fb8e45410b149ea94522fb64c17aee",
          "sha1": "f918ce24bd87070d259488cd32efdc10f4220c58",
          "md5": "b36ce8dfdea6a10a31f7d0528b252ea2"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.16-metadata.jar",
          "url": "composeblocks-iosarm64-0.5.16-metadata.jar",
          "size": 261,
          "sha512": "d4d22999bb49faffa87cccde1117726849f55e973470a0ea6e3d5f8319400014055f008250b718b3b2f5b534ab56d471bd25f1eaa70159b498f2e9f5d2922eb5",
          "sha256": "e4690e255a1b270a66c10551d16e4b30a90f58f1a910159ea1ca71071bf710fb",
          "sha1": "74fe841522fd7dc79d4c0a0c70e8504f71caadc4",
          "md5": "143e093532ddd82eb865d043c40660a0"
        }
      ]
    }
  ]
}
