{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.16-rc.94/composeblocks-0.5.16-rc.94.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.16-rc.94",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16-rc.94"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.16-rc.94"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.5.16-rc.94.klib",
          "url": "composeblocks-iosx64-0.5.16-rc.94.klib",
          "size": 331684,
          "sha512": "39efe432c2693f28c718a59292fc2f46efd49598fb198f54ad710ade265b6206a72b960ba9fc8142c505c2603da4a1c0f1ca72e938993e61e656dd6d484b9bb3",
          "sha256": "363e027e10e4cbd03c305b074ef486330a1f9e684cd0043b292d6dab82d6cd4e",
          "sha1": "ae5865597002e7e39c863a7474244edea466fd44",
          "md5": "1df948d79bf1ab79bfa882a6d24b929f"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosx64-0.5.16-rc.94-sources.jar",
          "url": "composeblocks-iosx64-0.5.16-rc.94-sources.jar",
          "size": 59511,
          "sha512": "9b215b4340d859f9bc19bcf8130f1ac340b58131f7c69825b2e0ac4afeb42e631a4a7f37b2b3c0a72a5b01c6366385395df28c5b7fc3e628eb8214a2e63e021f",
          "sha256": "5766c9ff09d578df821c1208f6bcf99afcfb80442ad1fb07333e14f240719a0c",
          "sha1": "de739a9fd5fe49eded6be087c00f311a5d69622f",
          "md5": "31b882d9765633f46be7c5c7d77e8031"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16-rc.94"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.16-rc.94"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.16-rc.94.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.5.16-rc.94-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "97dbd4c181a18d52d20c4bdde79f377b1f948888f804e779afbc3fdde95986c65df8167d671066b77a88316732bb054c82b98ff98e20e5cf3df06c21155c6eb1",
          "sha256": "65716b3ee804037835e34402cea146820b428ade0de9867f907b6636df5be4cc",
          "sha1": "a9ba14da30cbcf34dffd5e5c04069fb5c8131222",
          "md5": "3ab710095276ce704d94c0c7a51bc0c8"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16-rc.94"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.16-rc.94"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.5.16-rc.94-metadata.jar",
          "url": "composeblocks-iosx64-0.5.16-rc.94-metadata.jar",
          "size": 261,
          "sha512": "9ef1e82c6e08387f2a42e3db71c8d6e7ce115b935ed1a22aa335f6cc7b63b5e563de2374d66bdc92d2736092217c0ff1c020e9ae7eef300829736a3bdc7ee537",
          "sha256": "8876ee0a8bb5bc639df2ecfa39efdf08f2f551edd5411aed7c121807b2c62581",
          "sha1": "4bbf9066a394b3e5463f7fce1102b42a7424eb2b",
          "md5": "d55832971f93851c59bf5fc244692d7d"
        }
      ]
    }
  ]
}
