{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.5.16-SNAPSHOT/core-0.5.16-SNAPSHOT.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.5.16-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.5.16-SNAPSHOT.jar",
          "url": "core-jvm-0.5.16-SNAPSHOT.jar",
          "size": 155916,
          "sha512": "1ca2c190380d7d62d4706537f52d723f259229f25fd6a97836829405a98a162e42b3e0d506a23e12983fbea24dd4cbfcfa00da2068ad325cb1e1ee922168bc1a",
          "sha256": "3b24de543644fa7d2b0e2a7c6a18d17ddbf5f8541aa60d893093a3204edcbc94",
          "sha1": "66c73448c38480aeff1bccdab35b531f666fb16f",
          "md5": "c4c5cff6f8319df6a37f8798b395f944"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.5.16-SNAPSHOT.jar",
          "url": "core-jvm-0.5.16-SNAPSHOT.jar",
          "size": 155916,
          "sha512": "1ca2c190380d7d62d4706537f52d723f259229f25fd6a97836829405a98a162e42b3e0d506a23e12983fbea24dd4cbfcfa00da2068ad325cb1e1ee922168bc1a",
          "sha256": "3b24de543644fa7d2b0e2a7c6a18d17ddbf5f8541aa60d893093a3204edcbc94",
          "sha1": "66c73448c38480aeff1bccdab35b531f666fb16f",
          "md5": "c4c5cff6f8319df6a37f8798b395f944"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-0.5.16-SNAPSHOT-sources.jar",
          "url": "core-jvm-0.5.16-SNAPSHOT-sources.jar",
          "size": 18179,
          "sha512": "5a105865b78db4ee6708347b7c9167237fd5da82b63649eb3eea89c760fa3940e959bff8737129aca1188714f891de26d3497c370e228d44d9bfdf4142421863",
          "sha256": "b0c66cc2ff7629c5816a4365595367607ea6efd061c258ff97bbdcd344c8bda1",
          "sha1": "4650d2435b6c1a25e83737f9318c0a3daed1eba3",
          "md5": "8a096dee7448a196156f7f5fab2ea097"
        }
      ]
    }
  ]
}
