{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.7.1-rc.240/core-0.7.1-rc.240.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.7.1-rc.240",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "core-android-0.7.1-rc.240.aar",
          "size": 127748,
          "sha512": "8b1a9ab4e4397c20c580e3474f19ff47d40bc26bda1f8f3b85e3ae939ca2788ffd45e43777096f9f0229ffa9ce0f5cc2d1afed874477e91f8596267807f4e514",
          "sha256": "2916a55d6d266e6641bedad3a75280ad779a43c6d12ff887a05f63f4e16d1472",
          "sha1": "63febaf7e2cab0eddfc32b06762fbb9404ae4b92",
          "md5": "c839d48ff8104bf9109a9b5740b498f5"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.1-rc.240",
            "requires": "0.7.1-rc.240"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "core-android-0.7.1-rc.240.aar",
          "size": 127748,
          "sha512": "8b1a9ab4e4397c20c580e3474f19ff47d40bc26bda1f8f3b85e3ae939ca2788ffd45e43777096f9f0229ffa9ce0f5cc2d1afed874477e91f8596267807f4e514",
          "sha256": "2916a55d6d266e6641bedad3a75280ad779a43c6d12ff887a05f63f4e16d1472",
          "sha1": "63febaf7e2cab0eddfc32b06762fbb9404ae4b92",
          "md5": "c839d48ff8104bf9109a9b5740b498f5"
        }
      ]
    }
  ]
}
