{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.5.14/runtime-0.5.14.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.5.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosX64Main-0.5.14.klib",
          "url": "runtime-iosx64-0.5.14.klib",
          "size": 576205,
          "sha512": "b3113b9ae0671848b7ad029a1a1f8750dc3626756635a1496549335acd8ab87bdb7355a77a423a804949d41eb6b528aa43607ce11aa5b40e6ff0359d80bbf0e1",
          "sha256": "f135a5b02d2f4779f22db54e6ac871e365a44abbecb24f2320834491824ae790",
          "sha1": "33ff567e4213dbe4f9a9b470a49cebd8b0397310",
          "md5": "c70e43ac3b3e403109cd07d168adb095"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-iosx64-0.5.14-sources.jar",
          "url": "runtime-iosx64-0.5.14-sources.jar",
          "size": 43259,
          "sha512": "4c6217193fce4e119f33d0c332a5aaeb551465df3e736571e7518e1bd3278ab38947ce9390ec54a84e10e81f6035adf7fe6582e1b30355e30242f593d6b25703",
          "sha256": "23d3ada3d7096db18dd3f23883c5f48c65648bd17143ce36f0ea111712363a42",
          "sha1": "3fba39d1d1481017b8bb215fed9b51d735d3017b",
          "md5": "eeee6fe51480ee84a6122626d08bc9b6"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosx64-0.5.14-metadata.jar",
          "url": "runtime-iosx64-0.5.14-metadata.jar",
          "size": 2428,
          "sha512": "d8ead6fe0df6095e6b6c7e84431ccd59f077cc80a06a28adab9d4035f90104c625a1a659a6f1e3aaf8e4b492366bd34588b37c137d4d06a05769666dfed88640",
          "sha256": "fbe7cc77ae2ec1ecc268d147348aa0f5398e3e26e326b553f35808a28ca3ad27",
          "sha1": "a34b4ba7c81c1f4d9416355c8afd7de881c64900",
          "md5": "fd783ba2a45420ec7f8658c1f46777c4"
        }
      ]
    }
  ]
}
