{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.5.15-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-SNAPSHOT.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-metadata-0.5.15-SNAPSHOT.3.jar",
          "url": "runtime-0.5.15-SNAPSHOT.3.jar",
          "size": 45650,
          "sha512": "25889c03fd7ade03e8bbe21fea24d181fb4c8d50739b1a151e36ae201a0bac3b360e4ab0d29a4d50766f901bc052819d5a4de077b0dffc91fc395dcd53051fbf",
          "sha256": "62ee5ff7a6ade049af248307053ed6a8a0c4ad126e7d281035c70b1bc910f48e",
          "sha1": "d37f9884828b7b40f0a321fe466a74e56c49fbad",
          "md5": "ee7feb9f663b33cc756b527ea88a95f0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-kotlin-0.5.15-SNAPSHOT.3-sources.jar",
          "url": "runtime-0.5.15-SNAPSHOT.3-sources.jar",
          "size": 47799,
          "sha512": "3e74df26b45b48dc79ab802c9ed1714e52a3a5e4b6b7a2752ced5cba3f64eaf4e92c199bb624ce7a50aef8699615a9e0dae9b2c038d525a4d12b51c18a0a38a2",
          "sha256": "4daa7bd66ba20573f26fc6f79af5e09477fbe79085db2bdb1fe7408fb8366393",
          "sha1": "b3cca06e475dc7bf987a1c74a1c10ff2e11270b2",
          "md5": "171bb667af9e970a7dde6f59a4c5cb03"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-android/0.5.15-SNAPSHOT.3/runtime-android-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-android",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-android/0.5.15-SNAPSHOT.3/runtime-android-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-android",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-android/0.5.15-SNAPSHOT.3/runtime-android-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-android",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.5.15-SNAPSHOT.3/runtime-iosarm64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-iosarm64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.5.15-SNAPSHOT.3/runtime-iosarm64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-iosarm64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.5.15-SNAPSHOT.3/runtime-iosarm64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-iosarm64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.5.15-SNAPSHOT.3/runtime-iossimulatorarm64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-iossimulatorarm64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.5.15-SNAPSHOT.3/runtime-iossimulatorarm64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-iossimulatorarm64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.5.15-SNAPSHOT.3/runtime-iossimulatorarm64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-iossimulatorarm64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosx64/0.5.15-SNAPSHOT.3/runtime-iosx64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-iosx64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosx64/0.5.15-SNAPSHOT.3/runtime-iosx64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-iosx64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosx64/0.5.15-SNAPSHOT.3/runtime-iosx64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-iosx64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.5.15-SNAPSHOT.3/runtime-jvm-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-jvm",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.5.15-SNAPSHOT.3/runtime-jvm-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-jvm",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.5.15-SNAPSHOT.3/runtime-jvm-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-jvm",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-linuxx64/0.5.15-SNAPSHOT.3/runtime-linuxx64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-linuxx64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-linuxx64/0.5.15-SNAPSHOT.3/runtime-linuxx64-0.5.15-SNAPSHOT.3.module",
        "group": "br.com.wave",
        "module": "runtime-linuxx64",
        "version": "0.5.15-SNAPSHOT.3"
      }
    }
  ]
}
