{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.7.0/runtime-0.7.0.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosArm64Main-0.7.0.klib",
          "url": "runtime-iosarm64-0.7.0.klib",
          "size": 684884,
          "sha512": "669fecd7a0b648e6ea244e9453f554eb58c1fe8f73035d5133d2b40578559cd16bd6215410a99f04e2f983942efe29fab964941994edfec70d6a41ca6e60935a",
          "sha256": "97fbc356db41022781aab0a5adf7bf4b6a0341011c26c471df80949e9a2e6b8e",
          "sha1": "53299e1bac91ef577eb1812991b65c0e92c44006",
          "md5": "e785a5dc04030467ad8c698db477b9f6"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosarm64-0.7.0-metadata.jar",
          "url": "runtime-iosarm64-0.7.0-metadata.jar",
          "size": 2428,
          "sha512": "3fae6ef669f5d981ea0b9513f1385c4645383a893e96bf6ca7012752e91a63ecfe7697e2e206c06d1940f142bb1af7d70a7a7112006c6f0f1c9050ee1c983cee",
          "sha256": "7ddf438dfd8c5c081b6179c8685e50de5edfe69994bc688c30415e0b3f60184e",
          "sha1": "a250dd341ac4ec590e559db1282844fec387e1fa",
          "md5": "54446eb4a3987388aca8b08cd5b78b8d"
        }
      ]
    }
  ]
}
