{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.6.0-SNAPSHOT.24/composeblocks-0.6.0-SNAPSHOT.24.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.6.0-SNAPSHOT.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.24"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.24"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosArm64Main-0.6.0-SNAPSHOT.24.klib",
          "url": "composeblocks-iosarm64-0.6.0-SNAPSHOT.24.klib",
          "size": 224084,
          "sha512": "5a64178d33c79b5218fee204c468c4cf0665f6ccfee077abcd634c38c82877ee596c2ec430dd7c56fe7572ab39fc7fa3a094de3b7162c0a33b9ebf815520f05d",
          "sha256": "e8a3d8827863c7b1f63b2a43adeda123af9960995c082a5f094581e4cca8fad7",
          "sha1": "908e17f0662dd29b0433484e60319d0a3ec5881f",
          "md5": "7c83bfde240e3c7f759bcc7ebd68a3b0"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosarm64-0.6.0-SNAPSHOT.24-sources.jar",
          "url": "composeblocks-iosarm64-0.6.0-SNAPSHOT.24-sources.jar",
          "size": 36001,
          "sha512": "a06eae165039e1dbce80d1ab377809fb2ad27f0caf4672e34d468bdd4286a33897a422d7fc8bf7ebd0a52f42cc02d5a5c0c718918a6df9454c2982ec4b59c736",
          "sha256": "bca7eacd2963d7040e5e5b9373bbb3ff433d26fccadc3c9bb70bda49906b9493",
          "sha1": "27713da878c704a2da419c8ee1fbb57d345716e3",
          "md5": "bb9423db087a7fa0fad0bb98eeba094e"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.24"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.24"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.6.0-SNAPSHOT.24.kotlin_resources.zip",
          "url": "composeblocks-iosarm64-0.6.0-SNAPSHOT.24-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "825c7e141c0b1e50d9f452434d3f40a6e02c028f4f38e0c1b6b2c888550e57bebae8f96c3c8672d3bf99c16e24131ef1248d0db12d9102c596b9c23207e5ced3",
          "sha256": "7142fc9ce6b5290c112c88a2daf209af6989bbed98f0a678784d3b0b7b1a6690",
          "sha1": "b29b3629bb0b890655e14c65bffec119621b451f",
          "md5": "5d85bdb698c86d40dc4c57156af2409f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.24"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.24"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosarm64-0.6.0-SNAPSHOT.24-metadata.jar",
          "url": "composeblocks-iosarm64-0.6.0-SNAPSHOT.24-metadata.jar",
          "size": 261,
          "sha512": "75edf9b1eecbceb1eb6439b3f745e5d2aa513d1fd0c0dae02076e255336f7a6a5fe49112458f6867f85d693d11505ccc2e0addffe391df21ac7c2fa5fb4321fa",
          "sha256": "5219eeec0fe176e2949d381dc10828e581a8ac8a55ca2d5015a54c7674637fe7",
          "sha1": "2d2600c3ecd59e6584ea6b36a10891cd6010f8d2",
          "md5": "1b1ef247b5215f3459782318613f9d6b"
        }
      ]
    }
  ]
}
