{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.7.0.1/core-0.7.0.1.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosX64Main-0.7.0.1.klib",
          "url": "core-iosx64-0.7.0.1.klib",
          "size": 144136,
          "sha512": "508c8328649e5bcb82fe0c0afb454ea846dc0d672db7c4e962ea1196ccc6dc34916d6db376540b2215c68baa7941bd9c98138a63c3fc419a57a9c43788e7b724",
          "sha256": "e032e4eaaee6cab7d25f7ce2eb4d15a9dae8c3cdf8f3a76d126f7fcc8182a069",
          "sha1": "de95c473973d4ac57ab0e964593885a86a8cec73",
          "md5": "8137401dfaed4c5a27e66319542ab947"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosx64-0.7.0.1-metadata.jar",
          "url": "core-iosx64-0.7.0.1-metadata.jar",
          "size": 261,
          "sha512": "1ed8af34dd88ea93c5b161cfb657f7d935cd973be4e3b190f2d2f23effaae995a017d6f4a37b6e08b66d2033226e9a9dbfdbb8e9de7690a64610f67400d0502d",
          "sha256": "758a5ecbde959d677c41dc310be47d7ffa5a8d4f8c6934fd9f289cea69ae999a",
          "sha1": "6d3fee7778988937ac217b451d420fcaf21b56ae",
          "md5": "a991778b8ae7d20f35d71e943363151c"
        }
      ]
    }
  ]
}
