{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.7.0.2/runtime-0.7.0.2.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosX64Main-0.7.0.2.klib",
          "url": "runtime-iosx64-0.7.0.2.klib",
          "size": 684871,
          "sha512": "f9fbc9545036b5db412df1ffffe09eb861c52f9f29c58bdc287f8ecd9652e283abc950e975e3fa64ec410541ccb3f08db5c5ea51cf5e9033b733fa80dab337d3",
          "sha256": "6b16faea4b0b005a6ae5fc08254285a83300541adb7085a9aa0104c0cbde6926",
          "sha1": "c90de044f559d167653f60cf6d508427f1ba0f42",
          "md5": "02a165311448021c2e27dec994ec06e2"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosx64-0.7.0.2-metadata.jar",
          "url": "runtime-iosx64-0.7.0.2-metadata.jar",
          "size": 2428,
          "sha512": "c0c6eb49be03826f82f2858efb5b05b8e27f5e8d03abb69eeebf932404178a56d2bc1844a63f396666138ad42363f94430181723f26885a1b33076968f29e6b6",
          "sha256": "357a9b1ac9f2bdb92d8cf4bfbf072e9365e2311768b21ee48a8e8bc06ba08bbf",
          "sha1": "e6a375400da7c510aa26f36613d2a53735dd82d4",
          "md5": "ae2a18052aaf8d21a78e5e0ef4515189"
        }
      ]
    }
  ]
}
