{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.5.16/runtime-0.5.16.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.5.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosArm64Main-0.5.16.klib",
          "url": "runtime-iosarm64-0.5.16.klib",
          "size": 640344,
          "sha512": "c296aba9f85cc0efbf84d3398a15c4a427063d463cb1d740d9363632a6c6c48c71186eee4d192536ab12971b3c2402a896fd657054c6d1b19eade546abad9b46",
          "sha256": "721034ba10e25be5f67cc95c789bf028d5dae8ae95021abc435bc0ab3b604172",
          "sha1": "9a5453415edacab91969d290e0723135f48d5d65",
          "md5": "cb1a9b3a896b9b0232e364fa52d82d63"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-iosarm64-0.5.16-sources.jar",
          "url": "runtime-iosarm64-0.5.16-sources.jar",
          "size": 50432,
          "sha512": "963e702e635d69f3f30b2eec29532cd072ae1656c985a3b66942b99934b0bfebbaf51c9615d942146b537ab3398746881a7e14285a73773e84fa09b9e6ee85d5",
          "sha256": "abf8aff6002dc43e767fdd5a9359a51dcd7cf45cb634b5c32a3bff8695d9f7a7",
          "sha1": "6beffa84d84efad812de920582dac6e1657ee6ac",
          "md5": "a8a2686a4d636d22ae565704e2824741"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosarm64-0.5.16-metadata.jar",
          "url": "runtime-iosarm64-0.5.16-metadata.jar",
          "size": 2428,
          "sha512": "6de6ebed5b6ae0e132d2f15166bb733612a439f84842cf213c80c92797f107982617240e7790d6ca06beded811f187887b0b05a41c519ec1cff627fd561127fd",
          "sha256": "ae1982fac17a00f84135b379dd8b5181e1e47a17984e658cdafd7d1a0c04c568",
          "sha1": "5a9b663de2457f8dc93ec45e7760afd6a5d74840",
          "md5": "0fd7fef96d6d2a6f53ac7e5823e5d3a9"
        }
      ]
    }
  ]
}
