{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.17-rc.109/flow-wrapper-kmp-0.5.17-rc.109.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.17-rc.109",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.17-rc.109.aar",
          "size": 212387,
          "sha512": "df6f4a084a1eb78ee195063d9c6a218859a2c504f779f91dd924a48c1cbe58fb378f6306988ee759dfe296ee5cc4f4fc0600af945afaf6adb45cfa1ebb676405",
          "sha256": "8e1c032c0d0e245d69262fb1c9faca754c256cf626be991bee559bf2cc82c4b9",
          "sha1": "5eea376ee378d8e082aaecba480ba1f37546a9b5",
          "md5": "1371455387dfb06fd3332ccf9328381a"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17-rc.109"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.17-rc.109"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.17-rc.109.aar",
          "size": 212387,
          "sha512": "df6f4a084a1eb78ee195063d9c6a218859a2c504f779f91dd924a48c1cbe58fb378f6306988ee759dfe296ee5cc4f4fc0600af945afaf6adb45cfa1ebb676405",
          "sha256": "8e1c032c0d0e245d69262fb1c9faca754c256cf626be991bee559bf2cc82c4b9",
          "sha1": "5eea376ee378d8e082aaecba480ba1f37546a9b5",
          "md5": "1371455387dfb06fd3332ccf9328381a"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-android-0.5.17-rc.109-sources.jar",
          "url": "flow-wrapper-kmp-android-0.5.17-rc.109-sources.jar",
          "size": 41892,
          "sha512": "2bd677c9a4a5f4bfadafa9908d14952e4b70313347a032b55e635212415c816d21e58880c34202b82cae74e357221a8a4095c2295db792b5064df627798b3a17",
          "sha256": "9e39480a55d159e455c2957c2dad81d62f50f90d544beeb7f7d1575ccd3e213b",
          "sha1": "4b49411a40d4531456fbda3ffa1cea08a770946c",
          "md5": "1d269754351828ee14ec9479c7d4caac"
        }
      ]
    }
  ]
}
