{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.5.19/flows-sdk-0.5.19.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.19.aar",
          "size": 189728,
          "sha512": "43a4d7e8999e1bfb253bcf36dbd145b0856b56893d0383ecb73538b3036394e21483ab3cd98678e117606176ac06ba6b724ae65e9c6e8e50efad7ec0f26dbab6",
          "sha256": "b7a583e284849f8e5ff75da2912ed12e93c9399292f705913164ecb27f568c29",
          "sha1": "45c4318cbbfd438af152fe595155dc8762d22192",
          "md5": "1c932f5608b9f0f764282b2640011a71"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-jdk",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-optimal",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.19.aar",
          "size": 189728,
          "sha512": "43a4d7e8999e1bfb253bcf36dbd145b0856b56893d0383ecb73538b3036394e21483ab3cd98678e117606176ac06ba6b724ae65e9c6e8e50efad7ec0f26dbab6",
          "sha256": "b7a583e284849f8e5ff75da2912ed12e93c9399292f705913164ecb27f568c29",
          "sha1": "45c4318cbbfd438af152fe595155dc8762d22192",
          "md5": "1c932f5608b9f0f764282b2640011a71"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flows-sdk-android-0.5.19-sources.jar",
          "url": "flows-sdk-android-0.5.19-sources.jar",
          "size": 29063,
          "sha512": "815de8628a3b653a8697894b546a4fd971f6d8d875bb59637aaf766a285a606d77249791d1b9e62a048037de55bd465ef668839fbb6b11dc45f613a9638a711c",
          "sha256": "0f1967a704c98227fd05a32ca5f81a34ff0e464e72cb0fa51ea7f1f78afdab6c",
          "sha1": "41dd20d0acb44f9d950c169cff7a02dde70fe1c1",
          "md5": "d626fe23eedb17b7b0528ce312b61d20"
        }
      ]
    }
  ]
}
