{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.7.0-rc.186/runtime-0.7.0-rc.186.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.7.0-rc.186",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosX64Main-0.7.0-rc.186.klib",
          "url": "runtime-iosx64-0.7.0-rc.186.klib",
          "size": 684871,
          "sha512": "f9fbc9545036b5db412df1ffffe09eb861c52f9f29c58bdc287f8ecd9652e283abc950e975e3fa64ec410541ccb3f08db5c5ea51cf5e9033b733fa80dab337d3",
          "sha256": "6b16faea4b0b005a6ae5fc08254285a83300541adb7085a9aa0104c0cbde6926",
          "sha1": "c90de044f559d167653f60cf6d508427f1ba0f42",
          "md5": "02a165311448021c2e27dec994ec06e2"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.0-rc.186"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosx64-0.7.0-rc.186-metadata.jar",
          "url": "runtime-iosx64-0.7.0-rc.186-metadata.jar",
          "size": 2428,
          "sha512": "3c623704169ed3653d9b6b7f3a20d63e45397ca47c6d7525a68e790b3b143f97dd1d248e8e04092fd1a9d5d2e0e59f6b7e538a20f2a0371a06dde0b011eb0d13",
          "sha256": "b1c17c82e6ce9c9216768e2cbff1cad526314ada434fdb4dda47427b5cc3363e",
          "sha1": "4fddf7b6cc7f47b9252348e93735b36a853422ff",
          "md5": "49490eed813aa55683c6191fcd3f243b"
        }
      ]
    }
  ]
}
