{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.7.1-rc.237/flows-sdk-0.7.1-rc.237.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.7.1-rc.237",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.7.1-rc.237.aar",
          "size": 160509,
          "sha512": "62327ac16cc6c7a3aeab31d7c4c730e73ba4f19668d30aca277e1bd66a803bbfb686fc88fb906524689eb49de3fd0a98d68942b561a2dc836658c4cc6e647b95",
          "sha256": "b9b397eae8a227fc8c6380a69fc31d1e1415ccbed6d5529717ab2cc8a5376867",
          "sha1": "3c1b6ebfc68c80658188aae91889b1b4f4b5e4e5",
          "md5": "65f9f74c0ee047b2bae96ac32d4eb222"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "viewblocks",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.7.1-rc.237",
            "requires": "0.7.1-rc.237"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.7.1-rc.237.aar",
          "size": 160509,
          "sha512": "62327ac16cc6c7a3aeab31d7c4c730e73ba4f19668d30aca277e1bd66a803bbfb686fc88fb906524689eb49de3fd0a98d68942b561a2dc836658c4cc6e647b95",
          "sha256": "b9b397eae8a227fc8c6380a69fc31d1e1415ccbed6d5529717ab2cc8a5376867",
          "sha1": "3c1b6ebfc68c80658188aae91889b1b4f4b5e4e5",
          "md5": "65f9f74c0ee047b2bae96ac32d4eb222"
        }
      ]
    }
  ]
}
