{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.3/flow-wrapper-kmp-0.5.3.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosX64Main-0.5.3.klib",
          "url": "flow-wrapper-kmp-iosx64-0.5.3.klib",
          "size": 78386,
          "sha512": "406943603f474a2252fc44f5aea317bf06ba3b8492171ab3f2066166b44ca1acf8707fb2f5297b2829cd40fd6c4461882a67415970c510fbef5314f33dd50d6a",
          "sha256": "91b1e46147d269990abf3ec2cbd128733d7600fdb0a064a7c9b370ca4e7a068a",
          "sha1": "1ca02b8f2487a452ba514fff4eab6120966a3d0c",
          "md5": "72a24eb11caa383b201cfd3c3b87345c"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.3-sources.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.3-sources.jar",
          "size": 13239,
          "sha512": "cd1e2814379139cb91120076ddf440be4e08a1387895792c8b791ef3ab94bd0227f8cfda690be36cc0278903f153856186105a153e53df88d396cbae4c0094ae",
          "sha256": "dfff33fecf7b1643d0a139b7aaba1b0a41c4c74f6320a9143b1d0a775ccad942",
          "sha1": "8b461853038dad10c3f6ef2535cfc92452a178e9",
          "md5": "00c8d5f168f1b2045c83a7a3e9fd96a8"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.3.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosx64-0.5.3-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "a1f3798d467036c6a2e6bd608862800477690755b203bb16a4a41c4733387dfcff732300ba718ed5d6f7fff7066db153e20309de10dacc1c4d76bf7e03172f20",
          "sha256": "0f306c71140ca14c872e09da4d7903e912e0330fcb98bf660a41beeb373bc764",
          "sha1": "aab6b3079a24f8e85e5392851f63f1de610dacdd",
          "md5": "30518ea1e616a344e396739b612156eb"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.3-metadata.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.3-metadata.jar",
          "size": 3010,
          "sha512": "0cd177daf796dc1c60cab9d589849832b2de04d799f711942c16cdf1f5f9f3086effc248fef36038c0e85ed865a15685bbb0f40721e16faa5c5d130a35646c9d",
          "sha256": "3840b45431fd686b3ecdb120fabc6e51f4ec7beb8abe2e845b6b5d0977802358",
          "sha1": "04d2e94639e0d9db438560286cb35adad555069f",
          "md5": "f36e911961946043864a268af01717f3"
        }
      ]
    }
  ]
}
