{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.12-SNAPSHOT.2/flow-wrapper-kmp-0.5.12-SNAPSHOT.2.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.12-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.12-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosX64Main-0.5.12-SNAPSHOT.2.klib",
          "url": "flow-wrapper-kmp-iosx64-0.5.12-SNAPSHOT.2.klib",
          "size": 144393,
          "sha512": "16a2828428b682fdae618e9bc7dd42e89174c0b9ecaf4f021ed89c8e82b4ddc89e3b53b89358fbf42916974e17a09c47f873ea75271a8efa11ed067938e1fe56",
          "sha256": "73787bdd84845fac09907b94f4640e6b1d43976ebbd88793bb21042cc011530e",
          "sha1": "8a35e85269895cd2e99f739b53e3d655aa68bf0f",
          "md5": "b00ccd43a33d9b0891cccc23491efe3c"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.12-SNAPSHOT.2-sources.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.12-SNAPSHOT.2-sources.jar",
          "size": 25733,
          "sha512": "e69aaa8014388360dec0dfa21d5eab283bf314ede6f48e8f3c2ef3315861156a922e2bb4217740bf65c7afc9caa69985182642325a338db014ee1d9818c12d30",
          "sha256": "7bf8817dbe523ce96e9ba5a5e89ddfcc419c89377933ef652e55e5ef0591555f",
          "sha1": "6c9572de3f98ef75f5b2dea1dfe9b4e1e637e155",
          "md5": "63460b706b7e1a1ea4dc505443525d58"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.12-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.12-SNAPSHOT.2.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosx64-0.5.12-SNAPSHOT.2-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "908396fa1184efdd2370a51e9bf6f4842b6e8fb08686311010ccdab96b203ef83b50c2416e52fe300a4a403538db9543a91ad79dbb1bbd09fafb0dd9e14ddf92",
          "sha256": "f687f02075652ee95362e7509f5df4f5249d234906e1f6917867dca8259ad040",
          "sha1": "cd2ba981e980f9620fa7d94f80ccba57cb793924",
          "md5": "43a19f6ae957b975f021d4506cb9ff4a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.12-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosx64-0.5.12-SNAPSHOT.2-metadata.jar",
          "url": "flow-wrapper-kmp-iosx64-0.5.12-SNAPSHOT.2-metadata.jar",
          "size": 3747,
          "sha512": "ff3506ac339361d149fb817c3a06cfa6df61c87a351f3ca8f8320475bbdda9145c014302de43dbcddc26a402daee8888a40e19350d2ba7953879d5b6346d2dd4",
          "sha256": "7052dfc4861118775d1cb6d9fa5af1e2aee76f2cf581eef045ca512706502078",
          "sha1": "4ac147aacec9c5cd1f233caf66e4d3cd32dd9aeb",
          "md5": "ec592c9da27f7e0f5471cb873d5d34d8"
        }
      ]
    }
  ]
}
