{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.10/flow-wrapper-kmp-0.5.10.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosArm64Main-0.5.10.klib",
          "url": "flow-wrapper-kmp-iosarm64-0.5.10.klib",
          "size": 104023,
          "sha512": "f4d902c32e2089392351db2a45892ebde226b122b9c85aa2f287b70f39aa7220bc404d8c845ba06608686336de98297aad144530f3bee83cdcf73ca3c79e6c27",
          "sha256": "7560c0d5e5939ce15e8aa291f90bdd775d98f6db52231aae5292c0ebf7c050ba",
          "sha1": "630a8219ccd2e5487dac23d41e4d23568316b4f2",
          "md5": "3bfc01d1dd06fa2efc36fba4343f03b3"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-iosarm64-0.5.10-sources.jar",
          "url": "flow-wrapper-kmp-iosarm64-0.5.10-sources.jar",
          "size": 16714,
          "sha512": "6dd09d51fa88a8a40cbb60eba8a789f9cc37fbde35464d7174318340dcbfe791fb2f63f5ec3e82608aade866b1b7bc4fe38dd7656ea66ff2f7e12ee724317846",
          "sha256": "93f4149b566caf7027eae5fc0e608d2fa4155920f535b46a33d1e8ff275a240f",
          "sha1": "cfff4a30654b14baaa9bf8a0657472e4fad72b47",
          "md5": "82d21e248875799ce307d9f1b850f24e"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-0.5.10.kotlin_resources.zip",
          "url": "flow-wrapper-kmp-iosarm64-0.5.10-kotlin_resources.kotlin_resources.zip",
          "size": 1193,
          "sha512": "dd961090ea72cf90fc5071b376c0dad7379140665fa0872f2ad673161da14ab99aa64c92a34173b25c4688f7f36a96924952fa24e7cc617a4916fa6e5c7e0448",
          "sha256": "9455f430a9505511ba1a48061b0b9c518c7027f2f20d5f1ef8ce50d2017cabc0",
          "sha1": "cc503ef981c20d8b47ee258f695c00cd07160407",
          "md5": "eecaaa6e43ab64b784159a37e58fe06d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-iosarm64-0.5.10-metadata.jar",
          "url": "flow-wrapper-kmp-iosarm64-0.5.10-metadata.jar",
          "size": 3469,
          "sha512": "2daa43daad042400412851266808e04882bc67e75ee98eb9090b1fb2369ebf6136c532f50848d0d37336cdbacd7da9e9e0e1229789a145a104861e0e3d151775",
          "sha256": "57b995af1daf83eb14fdcd6073e537727ab6f31addfe25383a2ece5179a57d62",
          "sha1": "2c01dc5f531b85452f8cd8de9d8ba4ebf972c448",
          "md5": "462bdfb6d622e8efcdcb83e0451437ad"
        }
      ]
    }
  ]
}
