{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.17-noscroll-SNAPSHOT.1/composeblocks-0.5.17-noscroll-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.17-noscroll-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17-noscroll-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.17-noscroll-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosSimulatorArm64Main-0.5.17-noscroll-SNAPSHOT.1.klib",
          "url": "composeblocks-iossimulatorarm64-0.5.17-noscroll-SNAPSHOT.1.klib",
          "size": 345043,
          "sha512": "acb8e8209a5169947301fe8b0caa9bda018cdbac1e209e66f3caf92ecd6bd227ccfeb123882e8cf87a89a1a1be6dc976dc1208e53ccbf8b53513ec1a903aa810",
          "sha256": "7e4efa78d5988abb0e4867a93b9bb29970ec915eeffcfafd80b19d3cfbf3f0ba",
          "sha1": "151983fac2fe8a028dc4618f5227706876ce4f70",
          "md5": "9d866d3e61f4429df4fb443f20a8a791"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.17-noscroll-SNAPSHOT.1-sources.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.17-noscroll-SNAPSHOT.1-sources.jar",
          "size": 61930,
          "sha512": "6436b50935d253f749332f483f2f93e5310e8a9751226f0c4c35789c353bd86326f039c4709b9efe78ecf4d93870683a5c65e8c15027a1ccd10b667d3055f10a",
          "sha256": "ea0097955daf4b0db86327abb5bb9139f0e5fb4b10894f87bba051bbb9905431",
          "sha1": "bc45d5d5af58025af70df24b2694b873b0a2b1d2",
          "md5": "38526fc5ffdd906ed72e12621a45f37a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17-noscroll-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.17-noscroll-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.17-noscroll-SNAPSHOT.1.kotlin_resources.zip",
          "url": "composeblocks-iossimulatorarm64-0.5.17-noscroll-SNAPSHOT.1-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "8688199decd9f45d6a12f57c0ca1b8fdd6fe05c5c2733f1a76c2ddd93f42ee9ab36753c4479c016dab9b47132245e45b0d9e8efd06f787998cb406f161e115d2",
          "sha256": "d38573c2c0973d65ba51994f7bfb53b58a70127cba7db37ea942f4a7f9460bdd",
          "sha1": "9309daadb60be04bc4c80490f93564e12694c82b",
          "md5": "dc9907545e50173a645a78a8dad8374b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.17-noscroll-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.17-noscroll-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.17-noscroll-SNAPSHOT.1-metadata.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.17-noscroll-SNAPSHOT.1-metadata.jar",
          "size": 261,
          "sha512": "066b0b0f8b3886e33f11d6d44e1b55fec9cca12e240c0e82710beb6e7b4b785594575b01917e110267959e6d2e3eb161f97d09b61c2b752637c87b17bf596899",
          "sha256": "3811afea0b77e3711b5edeac717d97dcb3ca78f5b453b636e3140637d271e358",
          "sha1": "c18cdb4edbb3c4978dc52f424dbfe5cc88147f4d",
          "md5": "f3a333b922b8fe09ada511c9574c8d08"
        }
      ]
    }
  ]
}
