{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flow-wrapper-kmp/0.5.20.3-rc.160/flow-wrapper-kmp-0.5.20.3-rc.160.module",
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.20.3-rc.160",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.20.3-rc.160.aar",
          "size": 221742,
          "sha512": "d0f8c1bb035cd78456f4a0960ec8eb55f503601c34f72ab300481ccca2407d517f9a5e4c71b9ce2ce9db9512609494d2d512543561b029c060cebf47581e4958",
          "sha256": "7d7dd6e47247e369ec7ae11c4ae46da406ec2207b84b7f3f2a8e88b0e3dbb607",
          "sha1": "11c947c06ed413dfd54a38fbb50265bd9fa4554a",
          "md5": "11388ce7a991240e38b753616a51d929"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20.3-rc.160"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.20.3-rc.160"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp.aar",
          "url": "flow-wrapper-kmp-android-0.5.20.3-rc.160.aar",
          "size": 221742,
          "sha512": "d0f8c1bb035cd78456f4a0960ec8eb55f503601c34f72ab300481ccca2407d517f9a5e4c71b9ce2ce9db9512609494d2d512543561b029c060cebf47581e4958",
          "sha256": "7d7dd6e47247e369ec7ae11c4ae46da406ec2207b84b7f3f2a8e88b0e3dbb607",
          "sha1": "11c947c06ed413dfd54a38fbb50265bd9fa4554a",
          "md5": "11388ce7a991240e38b753616a51d929"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-android-0.5.20.3-rc.160-sources.jar",
          "url": "flow-wrapper-kmp-android-0.5.20.3-rc.160-sources.jar",
          "size": 46542,
          "sha512": "ccc951d5fd82ea54999a9cf7086394f7360ff98ceada0dd76955f4675c1a2c0471731e1f66ac9dfedb93e43c415e5e1a20c670e3202d9fdf3133514bea2b2d27",
          "sha256": "ad157a5c428f20ee7eda2ff1e6344ed5f6c8c35876f17dbacb9979d539ffaec7",
          "sha1": "20b28254b3c2ae3883a2e3e11bddca4b31d44bfc",
          "md5": "dddcd03eb60788b0e36d52b0f2b637cc"
        }
      ]
    }
  ]
}
