{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.5.15-rc.67/runtime-0.5.15-rc.67.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.5.15-rc.67",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosSimulatorArm64Main-0.5.15-rc.67.klib",
          "url": "runtime-iossimulatorarm64-0.5.15-rc.67.klib",
          "size": 611943,
          "sha512": "f509d914acd812c08980cd26d72efb68620fa0e9062fad0ce9a532a93d3945441a87e03827aaaefedff36ace8719612992a5b9045093c65c9a4c30f2a82b4df2",
          "sha256": "f7ee742fd4abee79d26ff306de128b3d2f6c6e551b10d76a5b440bf141499a6b",
          "sha1": "7a74bb56ffcf186d803c41bf65f741fb41b91af3",
          "md5": "64e8448fa1ec07093fcaa01390ffc45b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.5.15-rc.67-sources.jar",
          "url": "runtime-iossimulatorarm64-0.5.15-rc.67-sources.jar",
          "size": 47799,
          "sha512": "cb100860d8ec6bc80257bdae06c133361d687cb8063858d313fe74c88688f8358c8519ad7342281f6e94629a9d8c126260e51153e2655f85daea22a7057d7e80",
          "sha256": "f7411582376d70363b1bb45cc4831b4f145bea73283b3793ef0ae3a05e059a0b",
          "sha1": "3aa30f288162f368895810cba40d5d6853e42ea8",
          "md5": "39c253acf971bd770df12e104511d2b2"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.15-rc.67"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.5.15-rc.67-metadata.jar",
          "url": "runtime-iossimulatorarm64-0.5.15-rc.67-metadata.jar",
          "size": 2428,
          "sha512": "89458af8f163ff95f0564a62a360baa9b3458d8dfd6e6f9d358d7c5f36f2bdd4373562e02606bff1cf874fbe771b30933afd8f0f42b858c4f93bdc8be8630d61",
          "sha256": "9a3035c478450e9b2d60a942e19b17707cc81f6731dac126fef8ef45f50c7a1b",
          "sha1": "47e8a84c2539ac99f1087ceecc3ed7f8e75f94d8",
          "md5": "edddcf1df0a801f4123387431c2d8943"
        }
      ]
    }
  ]
}
