{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.20-rc.139/composeblocks-0.5.20-rc.139.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.20-rc.139",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-rc.139"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-rc.139"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosArm64Main-0.5.20-rc.139.klib",
          "url": "composeblocks-iosarm64-0.5.20-rc.139.klib",
          "size": 347008,
          "sha512": "521d2016e352fd5d4300256af33294babdc35bb78a110ca0bea4af22d16d35e1f818f2cc8201d56184c5c4239032a11547eba3485b4572257ce1906c9b12069f",
          "sha256": "e38d8d8b69c2fe312aebd4fba62b2bda11fc6cb94b7d03779ca36402be65f7bd",
          "sha1": "7d4c78b49f3d8d12217f420546ab2b1600f2c455",
          "md5": "f76e22f535f586e9454fdaba50f4b356"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.20-rc.139-sources.jar",
          "url": "composeblocks-iosarm64-0.5.20-rc.139-sources.jar",
          "size": 62929,
          "sha512": "a1b6fc6d924260f33998241e03ec24748d5c5dfd0113774ba6737d13cf12976f05d7730d8a31102924f3f379dc14469fbbbc54a33812c1b3466749ccc47684d1",
          "sha256": "c060c74601af62602de4fce2f88037ef006540f40ab0fc07a70a191070214b78",
          "sha1": "16aca03e0bca1374655d6244d13d0ebffcd27f34",
          "md5": "18983dc3d325a95705ebeb14c1ac28aa"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-rc.139"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-rc.139"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.20-rc.139.kotlin_resources.zip",
          "url": "composeblocks-iosarm64-0.5.20-rc.139-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "cc563aaf2be466b121f63a38fc35f7191ca433fb26f622b033c71786c869320bcef3cccd9a6eb6bf763cf4608ff09dfb5d11f26a3afb4c595042241a9201d01b",
          "sha256": "1dde1ff124490545cad02d9d1c8b8b2efa39fb742e50c639e1773482ffd03bdf",
          "sha1": "7fd48664372054510cd923cac3793d0c34e02ef9",
          "md5": "ce43dc0f07a1ba9f3e7fbe259509f04a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-rc.139"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-rc.139"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosarm64-0.5.20-rc.139-metadata.jar",
          "url": "composeblocks-iosarm64-0.5.20-rc.139-metadata.jar",
          "size": 261,
          "sha512": "d4a7cdf4de22884c871f0760bab0129496ae7693603d5e44a45570c8cd933d9fda69eadda4e8883575a7adf95777d07845c8616ec0912d3cc477e5da19d03d18",
          "sha256": "d641178502782f7cae372452d68ba41c7a432afe25b7223109cbdd5c66f38699",
          "sha1": "2756141b402da62fae66d34f20ee05ad18de09ae",
          "md5": "9e273155d75340f5347ef716f1659832"
        }
      ]
    }
  ]
}
