{
  "formatVersion": "1.1",
  "component": {
    "url": "../../flows-sdk/0.5.13/flows-sdk-0.5.13.module",
    "group": "br.com.wave",
    "module": "flows-sdk",
    "version": "0.5.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.13.aar",
          "size": 125933,
          "sha512": "252610a1456af0a3d97f373b1365d3560052c8b9b5835c905cdbff1a55e5940cb0fa31a479d69b304ec5f79eeb9f916a6140c17f48a2da83dcee5750cc245f7b",
          "sha256": "328a5efcfe5107f538be63ccfac8c18e1f5ac6097048be9d0401a47ea4e69ade",
          "sha1": "f7346ea9a237b94e6782afbae7e7d23fe2582c6d",
          "md5": "9c410c1138ebf2ef83a76c627783345d"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flows-sdk.aar",
          "url": "flows-sdk-android-0.5.13.aar",
          "size": 125933,
          "sha512": "252610a1456af0a3d97f373b1365d3560052c8b9b5835c905cdbff1a55e5940cb0fa31a479d69b304ec5f79eeb9f916a6140c17f48a2da83dcee5750cc245f7b",
          "sha256": "328a5efcfe5107f538be63ccfac8c18e1f5ac6097048be9d0401a47ea4e69ade",
          "sha1": "f7346ea9a237b94e6782afbae7e7d23fe2582c6d",
          "md5": "9c410c1138ebf2ef83a76c627783345d"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flows-sdk-android-0.5.13-sources.jar",
          "url": "flows-sdk-android-0.5.13-sources.jar",
          "size": 14374,
          "sha512": "8457d3fb203d13518b4cd2399c956ba7e369040a0da9aaf86f0e0d1b22482e8e16a573e8ba523bc330bc2a04ff6b7ce046eec740e72f0f1880eec46a60e0555d",
          "sha256": "9fe9cb09559a07237dfa69d44be1d6a7ed13b64ebdb406d981d6d3bfa6291e96",
          "sha1": "eaf955ffd382603b2632294390d6babb93e6f216",
          "md5": "901cc1ff2bf981d438c39cc34c7f7d68"
        }
      ]
    }
  ]
}
