{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.20-SNAPSHOT.2/composeblocks-0.5.20-SNAPSHOT.2.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.20-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosSimulatorArm64Main-0.5.20-SNAPSHOT.2.klib",
          "url": "composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.2.klib",
          "size": 347378,
          "sha512": "b190379ac5292049c9beed1a6b92725503ccb1e617cdfdaae5e73b245e87cde71ece16a7e363350f24c76d2a08da84293309ac459b1687f664321c3d5bf12dc4",
          "sha256": "417de732e4125841d1e012f05fb19bf8da290ff858581151fc41c1e10cbf1ec3",
          "sha1": "a42ef959f2fc219a6c12b974f620428f3b1e8f07",
          "md5": "a580b1ec968e6068ea5c140062ce6bd9"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.2-sources.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.2-sources.jar",
          "size": 62694,
          "sha512": "055d1853c8b0201db9b6d2bd8e327ba42d258514d75cc0689baa5c7594f364558874aa8c5b7ceec8de264156b920e689154ef065efedfec512bc78b1b61bcdef",
          "sha256": "2a970da0365a2c67211ff98f8e5a5ab325786d4b88ef00de15c506b3c77a30f7",
          "sha1": "1f218d04534eebf4440f2406fee80c8fd5ec703a",
          "md5": "da74fe21b60a2502d8fed55cecb46fe5"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.20-SNAPSHOT.2.kotlin_resources.zip",
          "url": "composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.2-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "10d5026dc95999990967c255d0b09ccbef5554f9a95806250514ffdd7569467d795a45905f333dff39202ef47dfe2b6c328443a1001e84eba89e8131ca4a5d95",
          "sha256": "d031c65ee74d780f9f00919327fc12acebaa265cfe15f896405d7e8018d45f58",
          "sha1": "4621c2f84173f821db1ce8fb9e31f19f01e069b3",
          "md5": "604c82d2dcafc746796e8857004babf1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20-SNAPSHOT.2"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.20-SNAPSHOT.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.2-metadata.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.20-SNAPSHOT.2-metadata.jar",
          "size": 261,
          "sha512": "7e4bc2c1e9418c14b31ba0197982dc880b4d55e8738cf3085ea4b2310a43695ab29f3b591920cac7c224712b43bde73601f115ec96742985177f5e4e56541b0e",
          "sha256": "f8bfc877fa513204444df6896e75afcf663af9bdb65301b343054d0d78d9716e",
          "sha1": "96986f94f9937c95c07d135867de0ce80c5b9b1a",
          "md5": "1caeb5ed4d28d08f51b235ecae0d73d4"
        }
      ]
    }
  ]
}
