{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.6.0-SNAPSHOT.12/composeblocks-0.6.0-SNAPSHOT.12.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.6.0-SNAPSHOT.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.12"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.12"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosSimulatorArm64Main-0.6.0-SNAPSHOT.12.klib",
          "url": "composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.12.klib",
          "size": 217959,
          "sha512": "12376c50ddb6ffcc292ebdd5485da45ad4842f8cedb3f3627a67e6ec86c612761192c145c74c9a5ccedbb8d90dfbeab46535720eb21d33b2cbd776da47c8f64b",
          "sha256": "dacee254c8d5b943f904673c4f2811cd1f9a843f7534266521d8699c85d54d67",
          "sha1": "e8412f56788e7bd1630182aa442b170e09687a68",
          "md5": "4d96cc0badf20ad2293dbf56b6f81057"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.12-sources.jar",
          "url": "composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.12-sources.jar",
          "size": 32844,
          "sha512": "6446f73c8b2623d591733941de12c5d2e07bd3cce3bb604d469bba8858210a0bce9c57fd67ec0e2e207f0686cb5263a0f68cd5f1d5e37cf49cacbc997e12c2a0",
          "sha256": "c20b7158463464107b52aeaaa94fe2bb8be5135a9f362f82525e2f63baf906c0",
          "sha1": "fc59a3d0479125ba7edddae851100af7e8ca0318",
          "md5": "2f02c0f75055bd6abcb2f0e5abd61b86"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.12"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.12"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.6.0-SNAPSHOT.12.kotlin_resources.zip",
          "url": "composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.12-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "33e43a821e02476cc5a45ffd8444cbf9957dc45be13a2d672e11bca9943503e5d97e6c3cb8eb36e69e81582952dbcb677428f0c403a5e7f5283f1f182bc7d100",
          "sha256": "0316b21e2c7ddff33cc467b251b157ae8b29df8db20d1766e1b5311c7c1c46a2",
          "sha1": "bf2318686ddc7cbde97d54487689eebeb1eca0e4",
          "md5": "237f3697a93e9d123b5bfb3d6d9956f4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.12"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.12"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.12-metadata.jar",
          "url": "composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.12-metadata.jar",
          "size": 261,
          "sha512": "e27b37de3d57da39869e41b3077cd5eac9c0a8b5ad5961d12c19ebd05a568bf5d515aa668188eac48f37c8ea0e188e344a8308a2b5a51922fed22b1d013d6907",
          "sha256": "ab4e990ebfdb8863ee593635be20d1be7bb83794ee73f5db7df5346ed145b8f1",
          "sha1": "51208ee3a72dd36ba760f1f1f4468717e4c6df52",
          "md5": "e5a3ef939eb8fa2789a9651585a92056"
        }
      ]
    }
  ]
}
