{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.6.0-SNAPSHOT.25/composeblocks-0.6.0-SNAPSHOT.25.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.6.0-SNAPSHOT.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.25"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.25"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.6.0-SNAPSHOT.25.klib",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.25.klib",
          "size": 224071,
          "sha512": "948afd36c2e3ee6b738d78a0207b05e5dfdc1ebbeaa30882f1f2368907f882ed5e548529b087566d5442cc6422e3439a0c60bbbb1ba8de669261dddfcc48a879",
          "sha256": "bea0e5b50621e69bc4578122d65ac862d822355ec4c345de033a7e9c5c2251ac",
          "sha1": "ee7d328345a6cb216806bd0d67de43faacc23535",
          "md5": "49392f03c6e84ca0e4521694bcf0c6be"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosx64-0.6.0-SNAPSHOT.25-sources.jar",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.25-sources.jar",
          "size": 36001,
          "sha512": "a06eae165039e1dbce80d1ab377809fb2ad27f0caf4672e34d468bdd4286a33897a422d7fc8bf7ebd0a52f42cc02d5a5c0c718918a6df9454c2982ec4b59c736",
          "sha256": "bca7eacd2963d7040e5e5b9373bbb3ff433d26fccadc3c9bb70bda49906b9493",
          "sha1": "27713da878c704a2da419c8ee1fbb57d345716e3",
          "md5": "bb9423db087a7fa0fad0bb98eeba094e"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.25"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.25"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.6.0-SNAPSHOT.25.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.25-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "a35e2cc1630706be13c92e5f186532c45d0e1b61101696fda06b76569051c808b1a40492b60211a3291a11c006ad3f1e1cff4537b3a415eb1ffdf700fd38f613",
          "sha256": "6166b454ce3df1ced651c45184acd8dbcfacf9cf6704a231a8d4c58aae0c7c1f",
          "sha1": "f14efe10b318ffd7897dc718ab41d98ec5c1f353",
          "md5": "829b56add069dc6fd4d9c8d6de33a84b"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.25"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.25"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.6.0-SNAPSHOT.25-metadata.jar",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.25-metadata.jar",
          "size": 261,
          "sha512": "f1ca24d780c4c2fd89c33d70a8c41fe79ceb9f89a06a8fb486b617ae4aa7972c7f176e0ef25daf891424b46e66c685c13802254f09bc29d13c6ee4b48bfb1d21",
          "sha256": "f5bda71786d5e854fc86685b7128b1ee54ec3cdb36c2a04d0804e152e6c447f3",
          "sha1": "ae439f6f92290c2315c245ed52a869cf91d2a3da",
          "md5": "4abb8fb827efcad6d2b22181d4aaab66"
        }
      ]
    }
  ]
}
