{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.6.1-SNAPSHOT.1/composeblocks-0.6.1-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.6.1-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosSimulatorArm64Main-0.6.1-SNAPSHOT.1.klib",
          "url": "composeblocks-iossimulatorarm64-0.6.1-SNAPSHOT.1.klib",
          "size": 382208,
          "sha512": "50e620e9e6c533335f5f8e984c7db90ed41dde17346b9de3c52aecff988f5d8094898082d53c34d4eee70c12c4e9cc80a7208838ec96577278a648dd9a4cfdb7",
          "sha256": "ee869cdb58ddf1004f0e8e0dc9b8dec108a7515890bda496497bd433b1e08268",
          "sha1": "1519cf41317c3c8c7a08a146dc3e34054d3f99b2",
          "md5": "90fc13bb133f70ec95d7b12c64aafb53"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.6.1-SNAPSHOT.1-sources.jar",
          "url": "composeblocks-iossimulatorarm64-0.6.1-SNAPSHOT.1-sources.jar",
          "size": 72079,
          "sha512": "283c8bf185bb3fb08a7a10c39263e177e68dcc4a6dec480b72a2e90b7f40ad33708f4a1f228a9dada854d0ffcef630bd9433d23ad83e3b01e922120cca22ff44",
          "sha256": "7f0efb93ed5e5ac093c13a78289c5c665858c83aa9f26aa6284765c2a105a713",
          "sha1": "3b413c4dba9d61a966597f0b2c5fc61baedfeb5b",
          "md5": "43b60d69962c649ab93691e209be7b5b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.6.1-SNAPSHOT.1.kotlin_resources.zip",
          "url": "composeblocks-iossimulatorarm64-0.6.1-SNAPSHOT.1-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "62871bad75ad4edd09715c195a2fe9dea6919815e574dccd3b8f5150dbe47a314952bc58b19c516075b32940188f76296c41100691972524292b4d9f08e96371",
          "sha256": "05734dbfa98bb8d021cf79d728a5788ad46ed619bc6bf16019e164751dacb67f",
          "sha1": "2a92d79380171b37fde5f3dab091bf275cca6497",
          "md5": "91d899e01c92c9fe8a0cc6ce146bc2f0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.1-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.6.1-SNAPSHOT.1-metadata.jar",
          "url": "composeblocks-iossimulatorarm64-0.6.1-SNAPSHOT.1-metadata.jar",
          "size": 261,
          "sha512": "29e392d18ba0f69f5a80ff14b5605e814cd180ae49740021ab926a62c717f6be951b0e0a834409fa5d64fd916d6f8f67cd63ff4ded69f6050aa0bdfc8563e1cc",
          "sha256": "1d82036fbb10648a60b89965cd8f77c0537489e0c6cc82b9aded70116f60740e",
          "sha1": "3426d4f78be7729429a71084d3ba51b472dacac8",
          "md5": "623c0e40750ccfbb65c88e3e7993da43"
        }
      ]
    }
  ]
}
