{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.6.0-SNAPSHOT.24/composeblocks-0.6.0-SNAPSHOT.24.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.6.0-SNAPSHOT.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.24"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.24"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosX64Main-0.6.0-SNAPSHOT.24.klib",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.24.klib",
          "size": 224071,
          "sha512": "948afd36c2e3ee6b738d78a0207b05e5dfdc1ebbeaa30882f1f2368907f882ed5e548529b087566d5442cc6422e3439a0c60bbbb1ba8de669261dddfcc48a879",
          "sha256": "bea0e5b50621e69bc4578122d65ac862d822355ec4c345de033a7e9c5c2251ac",
          "sha1": "ee7d328345a6cb216806bd0d67de43faacc23535",
          "md5": "49392f03c6e84ca0e4521694bcf0c6be"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iosx64-0.6.0-SNAPSHOT.24-sources.jar",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.24-sources.jar",
          "size": 36001,
          "sha512": "a06eae165039e1dbce80d1ab377809fb2ad27f0caf4672e34d468bdd4286a33897a422d7fc8bf7ebd0a52f42cc02d5a5c0c718918a6df9454c2982ec4b59c736",
          "sha256": "bca7eacd2963d7040e5e5b9373bbb3ff433d26fccadc3c9bb70bda49906b9493",
          "sha1": "27713da878c704a2da419c8ee1fbb57d345716e3",
          "md5": "bb9423db087a7fa0fad0bb98eeba094e"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.24"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.24"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.6.0-SNAPSHOT.24.kotlin_resources.zip",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.24-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "996dd0d433a53fbad8ed9a5e96b196029a97e87078ae5595db2068ddab859e078a495a360658865b3bd2689133e07a5e665899800069dfc1092eb1e810680074",
          "sha256": "52a1306d62e87dd90bd9ea4a20ff1725c8ac06cda6d77fa8535b1b31f38696a0",
          "sha1": "27b9c1189c721a68b9af0a1d5cfc46723fb07467",
          "md5": "893f22be0c4dfb5747e2583b17f660b3"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.24"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.24"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosx64-0.6.0-SNAPSHOT.24-metadata.jar",
          "url": "composeblocks-iosx64-0.6.0-SNAPSHOT.24-metadata.jar",
          "size": 261,
          "sha512": "4d253d26647b98d337cd22347d721781bc45627ba375bf77f67bfc65128bc4363edfd7ec464cfc7c92219faeceb756b391bc412749517fe056eb03f13c36c652",
          "sha256": "1b033b77e0b7ac5c43d806bb3256beb8462a09c032a392d02cec93ea3ee4959a",
          "sha1": "7933cb009311bfbf9f0c9f7b02c0590f49744aff",
          "md5": "0fe807c0213f5e58a640c5845e907bec"
        }
      ]
    }
  ]
}
