{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.5.20/runtime-0.5.20.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.5.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosSimulatorArm64Main-0.5.20.klib",
          "url": "runtime-iossimulatorarm64-0.5.20.klib",
          "size": 642024,
          "sha512": "11a73cc73606466238b60fbd803b5ef420d523ef25e6f8513233edac2c20d63c3083211ab437486fd3db76ad38e421afface881c9aea61c1106ff003246701e8",
          "sha256": "c77c58686286fbafec0878d536e1e2b23541e8d54829c7e5fdf596381692001b",
          "sha1": "de786b605cc41532919df141d3dfda4179560a3c",
          "md5": "d34c99abe47782f370a732b72ed989a5"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.5.20-sources.jar",
          "url": "runtime-iossimulatorarm64-0.5.20-sources.jar",
          "size": 50636,
          "sha512": "680dc503a2597eddaa02aeca679f2d8750374a7c8cddf1ffb859b577709636c421107b158207948de36a14a52d9efeee60f42f2dab621065d5911b07d4f4f721",
          "sha256": "7cd096291514797aeb10f3c4e3ab62768042e0264a5bda13ed5299628aea8798",
          "sha1": "85e1818594f5b7b503432a280d7c6846ef16edfc",
          "md5": "d5790663b14e27fe01ce3aa4118b821b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.5.20-metadata.jar",
          "url": "runtime-iossimulatorarm64-0.5.20-metadata.jar",
          "size": 2428,
          "sha512": "4388d29534b5a4d0f3bcaf3196f3d65e00c9d6900d9c5c9d1f8a3f2aaeedf950afa6061cfbffc562d6a12187eedc505ea18c487a0b7a71c56e47d7098dee0ee3",
          "sha256": "0af04361f03d5c766feda43bf0d862840419b69aeef25aa49cad0eceb0455b3f",
          "sha1": "9fe3d71ac21e24ec1cea2ffe306047f97110bd5d",
          "md5": "b628352fbb02b61ad8a3080f43ff26e5"
        }
      ]
    }
  ]
}
