{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.6.0-SNAPSHOT.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.6.0-SNAPSHOT.15"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.6.0-SNAPSHOT.15"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-metadata-0.6.0-SNAPSHOT.15.jar",
          "url": "composeblocks-0.6.0-SNAPSHOT.15.jar",
          "size": 22080,
          "sha512": "7ef229a706fe5c2703f54c8f305d1035aefcf9a661f31bf384140c893b45b949625c337b1e47a3e47bbc95cf1e9c84c374f09195fc9aac068626db80a3ec1fa4",
          "sha256": "7faf6591524e1653a0fe3ff1490b4724b33f8564fcce6b1c4891716c4da1b226",
          "sha1": "c4e2071a5206d4b5a23e05db06b3ac50119030c1",
          "md5": "8191a5ced9c4f2b3ad60dd3420e584a5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "composeblocks-kotlin-0.6.0-SNAPSHOT.15-sources.jar",
          "url": "composeblocks-0.6.0-SNAPSHOT.15-sources.jar",
          "size": 36198,
          "sha512": "1efb00bb7841cb013d49d59bc98b77483cc32f0cb699782934cbfa66309fa9857f33cff027a27a49233a7f06202677900cfcc84d05a3e58930a000ef58c09475",
          "sha256": "c143fa3e329bf3ee8084e33434d670c3d11e1419dede1b439ce189859a6b72f4",
          "sha1": "cbbed2cf4f7acbc10d8b06ef143d15d551f6bfb3",
          "md5": "3588824e4914a64fa247866a0242de9b"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.6.0-SNAPSHOT.15/composeblocks-android-0.6.0-SNAPSHOT.15.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.6.0-SNAPSHOT.15"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.6.0-SNAPSHOT.15/composeblocks-android-0.6.0-SNAPSHOT.15.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.6.0-SNAPSHOT.15"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeblocks-android/0.6.0-SNAPSHOT.15/composeblocks-android-0.6.0-SNAPSHOT.15.module",
        "group": "br.com.wave",
        "module": "composeblocks-android",
        "version": "0.6.0-SNAPSHOT.15"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.6.0-SNAPSHOT.15/composeblocks-iosarm64-0.6.0-SNAPSHOT.15.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.6.0-SNAPSHOT.15"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.6.0-SNAPSHOT.15/composeblocks-iosarm64-0.6.0-SNAPSHOT.15.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.6.0-SNAPSHOT.15"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.6.0-SNAPSHOT.15/composeblocks-iosarm64-0.6.0-SNAPSHOT.15.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.6.0-SNAPSHOT.15"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosarm64/0.6.0-SNAPSHOT.15/composeblocks-iosarm64-0.6.0-SNAPSHOT.15.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosarm64",
        "version": "0.6.0-SNAPSHOT.15"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.6.0-SNAPSHOT.15/composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.15.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.6.0-SNAPSHOT.15"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.6.0-SNAPSHOT.15/composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.15.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.6.0-SNAPSHOT.15"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.6.0-SNAPSHOT.15/composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.15.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.6.0-SNAPSHOT.15"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iossimulatorarm64/0.6.0-SNAPSHOT.15/composeblocks-iossimulatorarm64-0.6.0-SNAPSHOT.15.module",
        "group": "br.com.wave",
        "module": "composeblocks-iossimulatorarm64",
        "version": "0.6.0-SNAPSHOT.15"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.6.0-SNAPSHOT.15/composeblocks-iosx64-0.6.0-SNAPSHOT.15.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.6.0-SNAPSHOT.15"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.6.0-SNAPSHOT.15/composeblocks-iosx64-0.6.0-SNAPSHOT.15.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.6.0-SNAPSHOT.15"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.6.0-SNAPSHOT.15/composeblocks-iosx64-0.6.0-SNAPSHOT.15.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.6.0-SNAPSHOT.15"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeblocks-iosx64/0.6.0-SNAPSHOT.15/composeblocks-iosx64-0.6.0-SNAPSHOT.15.module",
        "group": "br.com.wave",
        "module": "composeblocks-iosx64",
        "version": "0.6.0-SNAPSHOT.15"
      }
    }
  ]
}
