{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.7.2-SNAPSHOT.1/runtime-0.7.2-SNAPSHOT.1.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.7.2-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosArm64Main-0.7.2-SNAPSHOT.1.klib",
          "url": "runtime-iosarm64-0.7.2-SNAPSHOT.1.klib",
          "size": 858666,
          "sha512": "871073aaf9b4e8bfa614b15fa98b739bbf685a4cd00699b72aa8a9cf6cf307d209e7d115ae65950b8d4617dfa02487ce7c2e22362c33c5d9c7af3e75c3b294dc",
          "sha256": "489d02906a303c587a0bbaa78dae50b059a93c4a394c53ff184f39d592fa9450",
          "sha1": "74683701e0afd7393cc36fdd654641c85361f90c",
          "md5": "fd1891acccb143a845b894d3f7cc47d5"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.2-SNAPSHOT.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosarm64-0.7.2-SNAPSHOT.1-metadata.jar",
          "url": "runtime-iosarm64-0.7.2-SNAPSHOT.1-metadata.jar",
          "size": 2428,
          "sha512": "a877d4124ba526677f6e72721d8a8571d25ff5358faea2f98ce15633455201a7e5ec04b4e087546dee4b859c11d4f0f0a7b6a17b39d43239fc266e47d4ce3ee0",
          "sha256": "98a0f0ccc984034437003853c163d1199f8ab91e53c6bba99e30068595cb8515",
          "sha1": "330b2b6db6b41ac6ba103a25edb0051afb32267c",
          "md5": "51ad6a5e166ba703a09105ee53a49edd"
        }
      ]
    }
  ]
}
