{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.6.0-SNAPSHOT.12/core-0.6.0-SNAPSHOT.12.module",
    "group": "br.com.wave",
    "module": "core",
    "version": "0.6.0-SNAPSHOT.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosArm64Main-0.6.0-SNAPSHOT.12.klib",
          "url": "core-iosarm64-0.6.0-SNAPSHOT.12.klib",
          "size": 92586,
          "sha512": "75a6f7c6c7402326fb038e42e1f6cc972cb28ef284fb25a4f44b5c94f217859f175c4a8c60a8ed5f101525a957d3808224b54ab148e0fb2ea223f1b35e942d9f",
          "sha256": "dd4506a2950dfb819c1f546d4e0c5bd445e35b8d5b97130827f19ff75d24f3fc",
          "sha1": "7335467001750d9c8e56e0a658b07311c68e8643",
          "md5": "8a0b444d75247ce8fecc53163a52fd56"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iosarm64-0.6.0-SNAPSHOT.12-sources.jar",
          "url": "core-iosarm64-0.6.0-SNAPSHOT.12-sources.jar",
          "size": 11577,
          "sha512": "9fb033cd2b42a176992197e20e2309dca4129da19a7d04197c877f14559bb8f1e0534e536672b6e6125fd5b704e75c9f87dfe7c2b432a3412614d1afb8e61edc",
          "sha256": "4145609f6c1de9f6a3b58c3c87e47936cc12bce1f587bf216f9896f8cc547b89",
          "sha1": "c4393dccb01819dff29b6e8fac8ffcd616103ac8",
          "md5": "ab48b1eec5b4f4f838421003a0575982"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-0.6.0-SNAPSHOT.12-metadata.jar",
          "url": "core-iosarm64-0.6.0-SNAPSHOT.12-metadata.jar",
          "size": 261,
          "sha512": "86ff31b7c81771b0e5dff485b281b017220c08b7b3de95110285dd484111e4d1c526965587ff6c30167c734b64a16e02e79ec113af8a9b77df5e9ff7275d0241",
          "sha256": "fb8a04bd36490d3a1889afafa1e50152025b38838cc683fc7e28cc562b3f60cf",
          "sha1": "a3ae0e68983b4d3c1f17d7f51e20786507e279c9",
          "md5": "dbdda9836302230ca6e4d9fe43d6b708"
        }
      ]
    }
  ]
}
