{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "viewblocks",
    "version": "0.8.0-rc.261",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        }
      ],
      "files": [
        {
          "name": "viewblocks-0.8.0-rc.261.aar",
          "url": "viewblocks-0.8.0-rc.261.aar",
          "size": 108671,
          "sha512": "1c945f229a60183a74d828f726892b1ce72cd57df5e4d2b3ff7379c2339920131f0c3948be0ca8263382d505c857659f10f80a870fd42404997b88f052f6323d",
          "sha256": "f62faa585e33c29fbe7a9f688577b70051026d6e03b6af89c707496818f0f7c3",
          "sha1": "7866fecb00a875770d3547310387f7fa507cf8bc",
          "md5": "00c51ab23c5b41e99720e6277ed3202f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "composeblocks",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "webblocks",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flow-wrapper-kmp",
          "version": {
            "strictly": "0.8.0-rc.261",
            "requires": "0.8.0-rc.261"
          }
        }
      ],
      "files": [
        {
          "name": "viewblocks-0.8.0-rc.261.aar",
          "url": "viewblocks-0.8.0-rc.261.aar",
          "size": 108671,
          "sha512": "1c945f229a60183a74d828f726892b1ce72cd57df5e4d2b3ff7379c2339920131f0c3948be0ca8263382d505c857659f10f80a870fd42404997b88f052f6323d",
          "sha256": "f62faa585e33c29fbe7a9f688577b70051026d6e03b6af89c707496818f0f7c3",
          "sha1": "7866fecb00a875770d3547310387f7fa507cf8bc",
          "md5": "00c51ab23c5b41e99720e6277ed3202f"
        }
      ]
    }
  ]
}
