{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.wave",
    "module": "flow-wrapper-kmp",
    "version": "0.5.20.3-rc.160",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.20.3-rc.160"
          }
        },
        {
          "group": "br.com.wave",
          "module": "flows-sdk",
          "version": {
            "requires": "0.5.20.3-rc.160"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.kevinnzou",
          "module": "compose-webview-multiplatform",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "flow-wrapper-kmp-metadata-0.5.20.3-rc.160.jar",
          "url": "flow-wrapper-kmp-0.5.20.3-rc.160.jar",
          "size": 30031,
          "sha512": "b43fe382a9c621a000a4c1a4e080fb7424000eb9b62473575a9fb8d6ecd60d3f5a2817457917e9680bc6229320b02580f134806ff10c4317475010e26a9ca4f5",
          "sha256": "2b4cc2ff0862d46e263c851193702fb4cdc5eb2906476deaf17fcfbebea12078",
          "sha1": "46386a1390fbb13417cecf99f0108340f420e781",
          "md5": "f11aa7f5a7adfde3367b4beabef48f71"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "flow-wrapper-kmp-kotlin-0.5.20.3-rc.160-sources.jar",
          "url": "flow-wrapper-kmp-0.5.20.3-rc.160-sources.jar",
          "size": 44426,
          "sha512": "d03e497745f93f88e4375e780e6744829accac15bb5f6f21f589157d9ebae6bd42ac81b79ec363a263b33654ca2bd4b34f514d37531913c43c977b27e658bf5f",
          "sha256": "db1c70839597a4b97597e1511413f46fde4aa26a1393c919adf557b77731c163",
          "sha1": "a05029431aeb916ab92076ba48614100664be794",
          "md5": "3dd11e57118e8fb1987b65a301058e5e"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-android/0.5.20.3-rc.160/flow-wrapper-kmp-android-0.5.20.3-rc.160.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-android",
        "version": "0.5.20.3-rc.160"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-android/0.5.20.3-rc.160/flow-wrapper-kmp-android-0.5.20.3-rc.160.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-android",
        "version": "0.5.20.3-rc.160"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-android/0.5.20.3-rc.160/flow-wrapper-kmp-android-0.5.20.3-rc.160.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-android",
        "version": "0.5.20.3-rc.160"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.20.3-rc.160/flow-wrapper-kmp-iosarm64-0.5.20.3-rc.160.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.20.3-rc.160"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.20.3-rc.160/flow-wrapper-kmp-iosarm64-0.5.20.3-rc.160.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.20.3-rc.160"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.20.3-rc.160/flow-wrapper-kmp-iosarm64-0.5.20.3-rc.160.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.20.3-rc.160"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosarm64/0.5.20.3-rc.160/flow-wrapper-kmp-iosarm64-0.5.20.3-rc.160.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosarm64",
        "version": "0.5.20.3-rc.160"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.20.3-rc.160/flow-wrapper-kmp-iossimulatorarm64-0.5.20.3-rc.160.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.20.3-rc.160"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.20.3-rc.160/flow-wrapper-kmp-iossimulatorarm64-0.5.20.3-rc.160.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.20.3-rc.160"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.20.3-rc.160/flow-wrapper-kmp-iossimulatorarm64-0.5.20.3-rc.160.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.20.3-rc.160"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iossimulatorarm64/0.5.20.3-rc.160/flow-wrapper-kmp-iossimulatorarm64-0.5.20.3-rc.160.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iossimulatorarm64",
        "version": "0.5.20.3-rc.160"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.20.3-rc.160/flow-wrapper-kmp-iosx64-0.5.20.3-rc.160.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.20.3-rc.160"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.20.3-rc.160/flow-wrapper-kmp-iosx64-0.5.20.3-rc.160.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.20.3-rc.160"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.20.3-rc.160/flow-wrapper-kmp-iosx64-0.5.20.3-rc.160.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.20.3-rc.160"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../flow-wrapper-kmp-iosx64/0.5.20.3-rc.160/flow-wrapper-kmp-iosx64-0.5.20.3-rc.160.module",
        "group": "br.com.wave",
        "module": "flow-wrapper-kmp-iosx64",
        "version": "0.5.20.3-rc.160"
      }
    }
  ]
}
