{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.7.1-rc.240/runtime-0.7.1-rc.240.module",
    "group": "br.com.wave",
    "module": "runtime",
    "version": "0.7.1-rc.240",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosSimulatorArm64Main-0.7.1-rc.240.klib",
          "url": "runtime-iossimulatorarm64-0.7.1-rc.240.klib",
          "size": 858731,
          "sha512": "8fc2a6b0bb5c02dea8668fb354f7c9a98799c9279b64eb1be9cb72af7eb887607827d1bb9ec37df00580b010eb708a446befb100952e048eba19fbcd5a911ae8",
          "sha256": "8d4bde55f8fae58ec4a538695e9ebed81ae59d3bc04d780fdf7910d9e926bc3a",
          "sha1": "efe3d6b8714eed6b77fdbb95d06c749f45b84102",
          "md5": "6325d5c8d2821d19072a4ce38a25def0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.7.1-rc.240"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.7.1-rc.240-metadata.jar",
          "url": "runtime-iossimulatorarm64-0.7.1-rc.240-metadata.jar",
          "size": 2428,
          "sha512": "41459a474fccec6ef9e58fd8716f34f849c68d2ad2885564ee78e3f09620c4e9d1429ef8eac17d7b2f77d77dac275dc2c522d538f3c5f9f138a26cd5d28364df",
          "sha256": "1fedccca2020d759bb8f4af3a4171a1f695287cf885e8b980d3a7b66fc615652",
          "sha1": "e245fe5a2007c14ddad3ff7cd940c45f09ec18f9",
          "md5": "c3149d0ae341f80cbb636c235216f0e0"
        }
      ]
    }
  ]
}
