{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeblocks/0.5.12/composeblocks-0.5.12.module",
    "group": "br.com.wave",
    "module": "composeblocks",
    "version": "0.5.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.12"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iosSimulatorArm64Main-0.5.12.klib",
          "url": "composeblocks-iossimulatorarm64-0.5.12.klib",
          "size": 224363,
          "sha512": "56882b901f156ebf4a67bcfa3bc44a2ca796196feb125023b53cde29d5ae134fb57a8911cb4da27c6f3289e949c2d359b9da007f42c00044d10fef21da1bf549",
          "sha256": "54d0fdfee8959177283c6d62934da72be3f828e58dc77e4cc5bd472ef41f7a94",
          "sha1": "f2fc8b0271efa28c544834e08ebc89eb6e1f4431",
          "md5": "1e8a81d31f400592a786a9ca4ec5df43"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.12-sources.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.12-sources.jar",
          "size": 36171,
          "sha512": "23c4853c4c5ee3e6ac70f0d156f7edca210d60c462afc04368f907794a7dd2bb486270d34bbf5a74f3b285ae3096689a8043dbeac4e6731b501f0447b4c97010",
          "sha256": "27d5e6dbc67211882f5e0804adf3872f8687745226d6a4874e42cce92a4b2e3f",
          "sha1": "5993f83f60b0d937068cf7414394a0621ef03b5d",
          "md5": "f7e8a769e83320cad5d567a321b1c829"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.12"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-0.5.12.kotlin_resources.zip",
          "url": "composeblocks-iossimulatorarm64-0.5.12-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "0445473a6d321c6440ef04d0a767803a4814658c0181929b1769c12a490aa73863fbacba8d6ea40793be2afbf2c528b03920f884940823526b46af25925e662d",
          "sha256": "f299ea370446fc6e794692ddba579698f41611d4f8abadd03f5225af88d90d10",
          "sha1": "9c639f519958421fb34f8fe6cdf1fa2ed1b350d3",
          "md5": "5217a7d8d2df322b05bac735ec3297dc"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "br.com.wave",
          "module": "core",
          "version": {
            "requires": "0.5.12"
          }
        },
        {
          "group": "br.com.wave",
          "module": "runtime",
          "version": {
            "requires": "0.5.12"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "composeblocks-iossimulatorarm64-0.5.12-metadata.jar",
          "url": "composeblocks-iossimulatorarm64-0.5.12-metadata.jar",
          "size": 261,
          "sha512": "30c2590f68929f8196b94f6d1d62838897cdf4e01ccacf7b1851088903f684c6eba22c4848a1ae195ffb18be078d28858047faa23db177eb962413fa996692d6",
          "sha256": "bcb92edd6a56a3334bb9158d34a34200ab31340473176ac456b925b6754591a1",
          "sha1": "4b5f2ec6bf61b171d6495e43e098adc0533b52cf",
          "md5": "821aa588095e1e3167b116d7f6a0a063"
        }
      ]
    }
  ]
}
